### PR TITLE
[1.21.1] Fix blur effect rendered at high z with depth test breaking subsequent rendering of screen elements

### LINKED ISSUE #1504: [1.21] Rendering both darkening background and blur effect in a screen causes it to not render its contents when many HUD layers are present
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.31

**Steps to Reproduce:**
 1. Add a lot of HUD layers (in my test I used over 90, the real-world case in ATM10 ends up at 88 layers)
 2. Add a screen that renders both the darkening background (usually used by container screens) and the blur effect (usually used by out-of-world screens like the pause menu, title screen and settings)
 3. Open the screen while in a world and observe only the blur effect and dark translucent background being rendered

**Description of issue:**
When enough HUD layers are present and a screen renders both the darkening background (which enables the depth test) and the blur effect in that order, then any contents of the screen such as background texture, items, widgets, etc. vanish. Replacing the darkening background rendering with just `RenderSystem.enableDepthTest()` produces the same behaviour. Disabling the blur effect in the accessibility settings fixes the issue. It is not yet clear why the different depth causes this to happen.

### PR DESCRIPTION
**Pull request by XFactHD**
This PR fixes the blur effect breaking screen rendering when a lot of HUD layers are present and the blur effect is applied after drawing the dark half-transparent background.

Fixes #1504

### CODE REVIEW

**Review by embeddedt — DISMISSED** [review]

File: patches/net/minecraft/client/gui/screens/Screen.java.patch [hunk 1]
```diff
@@ -50,14 +50,19 @@
...
+@@ -354,9 +_,12 @@
  
          this.renderBlurredBackground(p_294317_);
          this.renderMenuBackground(p_283688_);
 +        net.neoforged.neoforge.common.NeoForge.EVENT_BUS.post(new net.neoforged.neoforge.client.event.ScreenEvent.BackgroundRendered(this, p_283688_));
      }
  
      protected void renderBlurredBackground(float p_330683_) {
++        // Neo: fix blur effect rendered at high z with depth test breaking subsequent rendering of screen elements
++        RenderSystem.disableDepthTest();
```
Comment (shartte) [inline patches/net/minecraft/client/gui/screens/Screen.java.patch]: should this comment link to the issue or are we going to find this later after several rounds of porting?

**Review by shartte — APPROVED** [review]

**Review by embeddedt — APPROVED** [review]
