### PR TITLE
[1.21.x] Fix the bug that some blocks do not catch fire from lava when they should

### LINKED ISSUE #2625: [1.21.1] Fletching Table does not catch fire from lava
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.206

**Logs:** https://gist.github.com/MineCake147E/84b8b00627bbfd40ae8834766701fd1a

**Steps to Reproduce:**
 1. Create a new world in Creative mode
 2. Put lava
 3. Put a `Fletching Table` (`minecraft:fletching_table`) nearby
 4. Execute the command `/gamerule randomTickSpeed 300` if you want to accelerate the test.
 5. See what happens

**Description of issue:**

According to Minecraft Wiki article on [Fire](https://minecraft.wiki/w/Fire#Non-flammable_blocks), there are many blocks that can catch fire from Lava while not being burnt away.  
Fletching Table is one of them.  
But in NeoForge 21.1.206, such blocks do not catch fire from lava when they should.

NeoForge 21.1.206 (`randomTickSpeed` is set to `300`) :
NeoForge 21.1.206

Vanilla (`randomTickSpeed` is set to `300`) :

Vanilla

The cause of this issue would likely be:

https://github.com/neoforged/NeoForge/blob/d9d43c802ba283301505f6b708528ce0f0204095/patches/net/minecraft/world/level/material/LavaFluid.java.patch#L49

The `&& state.isFlammable(level, pos, face)` should not be there, I guess.  
After removing that condition in my local environment, I get this (with `randomTickSpeed` is set to `300`) :

Modified NeoForge

### PR DESCRIPTION
**Pull request by MineCake147E**
## Summary

Resolves #2625 .

* Introduces new methods:
  * `IBlockExtension.ignitedByLava(BlockState, BlockGetter, BlockPos, Direction)`
  * `IBlockStateExtension.ignitedByLava(BlockGetter, BlockPos, Direction)`
* Patches the `LavaFluid.isFlammable(LevelReader, BlockPos, Direction)` to use the `IBlockStateExtension.ignitedByLava(BlockGetter, BlockPos, Direction)`

All images below are taken with `randomTickSpeed` set to `700`.
Vanilla:
Vanilla

Before patches (NeoForge 21.8.45):
Before

After patches (this PR):
After

### CODE REVIEW

File: patches/net/minecraft/world/level/material/LavaFluid.java.patch [hunk 1]
```diff
@@ -44,7 +44,7 @@
 +            return false;
 +        }
 +        BlockState state = level.getBlockState(pos);
-+        return state.ignitedByLava() && state.isFlammable(level, pos, face);
++        return state.ignitedByLava();
 +    }
 +
```
Comment (ChampionAsh5357) [inline patches/net/minecraft/world/level/material/LavaFluid.java.patch]: Is there any point to this patch existing if we are no longer checking fire flammability? Honestly, it seems weird that the block would catch fire by lava but won't actually burn. Seems to be a reported bug as well: https://bugs.mojang.com/browse/MC/issues/MC-3263

Comment (MineCake147E) [reply patches/net/minecraft/world/level/material/LavaFluid.java.patch]: > Honestly, it seems weird that the block would catch fire by lava but won't actually burn.

I don't think so.  
Mojang added many blocks after the [MC-3263](https://bugs.mojang.com/browse/MC/issues/MC-3263) has been reported (in Java Edition 1.4.4) and confirmed, including `minecraft:bamboo_sapling` and `minecraft:chiseled_bookshelf`.  
They said that Chiseled Bookshelf catching fire from lava and not burning away is an intended feature ([MC-262459](https://bugs.mojang.com/browse/MC/issues/MC-262459) has been resolved as "Works As Intended").  

Vanilla 1.21.8:
Chiseled Bookshelves catching fire and not burning away in Vanilla 1.21.8

NeoForge 21.8.45:
Chiseled Bookshelves not even catching fire in NeoForge 21.8.45

NeoForge 21.8.47-1.21.x-ignited-by-lava-fix:
Chiseled Bookshelves catching fire and not burning away in NeoForge 21.8.47-1.21.x-ignited-by-lava-fix

Comment (ChampionAsh5357) [reply patches/net/minecraft/world/level/material/LavaFluid.java.patch]: Hmm, that issue seems to stem from preventing the inventory being burned, which the fletching table does not have. Though, crafting table also seem to be in the same situation, so I will concede the point.

My first comment still stands though. The patch was added specifically for the flammability check, so if we are no longer doing it, we should either remove the patched method altogether (or I guess a deprecation in this case), or there should be an equivalent replacement for the block extension for ignited by lava.

Comment (MineCake147E) [reply patches/net/minecraft/world/level/material/LavaFluid.java.patch]: > there should be an equivalent replacement for the block extension for ignited by lava.

I will go for this approach.

Comment (MineCake147E) [reply patches/net/minecraft/world/level/material/LavaFluid.java.patch]: I added `IBlockExtension.ignitedByLava(BlockState, BlockGetter, BlockPos, Direction)` and `IBlockStateExtension.ignitedByLava(BlockGetter, BlockPos, Direction)`, and `LavaFluid.isFlammable` now uses `IBlockStateExtension.ignitedByLava(BlockGetter, BlockPos, Direction)` instead of `BlockStateBase.ignitedByLava()`.

**Review by ChampionAsh5357 — APPROVED** [review]

**Review by XFactHD — APPROVED** [review]
