### PR TITLE
[1.21] Add IItemExtension#supportsEnchantment

### LINKED ISSUE #1397: "isPrimaryItemFor" is never called during Anvil operations
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.145

**Logs:** Not relevant.

**Steps to Reproduce:**
1. Create and register an item whose class `extends Item`, and overrides `isPrimaryItemFor`;
2. Write a custom enchanting rule inside `isPrimaryItemFor`. Example: _If the enchantment fits a Diamond Sword, return true_;
3. Launch the game;
4. Place and use an Anvil, then attempt to apply a valid enchantment to the item using an Enchanted Book.

**Description of issue:**

NeoForge introduces an override called `isPrimaryItemFor` to Item classes, which allows modders to customize enchantment compatibility beyond the usage of tags. This is very versatile, because it lets us include/exclude in a way that some tags won't allow, such as `enchantable/sword` being tied to many broad enchantments.

However, this method is not called at any time when using the Anvil, only within the Enchanting Table. This causes both workstations to apply enchantments inconsistently, with the Anvil only consulting tags. What can be applied in one cannot be applied in the other.

This felt like a bug/oversight to me, so I thought of reporting it just in case.

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
This PR adds the hook `IItemExtension#supportsEnchantment`, which is an analogue to the old `IForgeItem#canApplyAtEnchantingTable` from before the changes.  Currently, we only have `IItemExtension#isPrimaryItemFor`, which handles a portion of that functionality, but not enough to satisfy many use cases.

Closes #1397

### CODE REVIEW

**Comment by Matyrobbrt** [comment]
I'm not so sure on this method name. It doesn't exactly convey *what* it is supported for. What about `canEnchantWith` or `supportsEnchantment`?

File: src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java [hunk 1]
```diff
@@ -422,17 +425,43 @@ default int getEnchantmentValue(ItemStack stack) {
...
+     * @see #isSupportedItemFor(ItemStack, Holder)
      */
     @ApiStatus.OverrideOnly
     default boolean isPrimaryItemFor(ItemStack stack, Holder<Enchantment> enchantment) {
-        return stack.getItem() == Items.BOOK || enchantment.value().isPrimaryItem(stack);
+        if (stack.getItem() == Items.BOOK) {
+            return true;
+        }
+        Optional<HolderSet<Item>> primaryItems = enchantment.value().definition().primaryItems();
+        return this.isSupportedItemFor(stack, enchantment) && (primaryItems.isEmpty() || stack.is(primaryItems.get()));
```
Comment (TelepathicGrunt) [inline src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java]: Is primaryItems.isEmpty() needed here? An empty holderSet should cause the contains to return false i thought

Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java]: `primaryItems` is an Optional - if not present, any supported item is accepted as primary

**Comment by Shadows-of-Fire** [comment]
I can get behind renaming the method to `supportsEnchantment` - I selected this name to match the other hook, but "supported items" isn't exactly an enchantment specific term like primary items are.

**Comment by Shadows-of-Fire** [comment]
Updated to change the method name from `isSupportedItemFor` to `supportsEnchantment`

File: patches/net/minecraft/world/item/enchantment/Enchantment.java.patch [hunk 2]
```diff
@@ -1,16 +1,48 @@
...
+     public boolean isSupportedItem(ItemStack p_344865_) {
+         return p_344865_.is(this.definition.supportedItems);
+     }
+@@ -188,6 +_,10 @@
+         return mutablecomponent;
+     }
+ 
++    /**
++     * @deprecated Neo: Use {@link ItemStack#isSupportedItemFor(Holder)}
++     */
```
Comment (Matyrobbrt) [inline patches/net/minecraft/world/item/enchantment/Enchantment.java.patch]: These links are invalid now.

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

File: patches/net/minecraft/world/item/enchantment/Enchantment.java.patch (hunk 2 above)
Comment (Shadows-of-Fire) [reply patches/net/minecraft/world/item/enchantment/Enchantment.java.patch]: Fixed, guess eclipse missed those in the refactor

**Review by Matyrobbrt — APPROVED** [review]
