### PR TITLE
[1.21.3] Add NF's needs_netherite_tool block tag to vanilla's incorrect_for_*_tool block tags

### LINKED ISSUE #1571: Tagging a block with NEEDS_NETHERITE_TOOL allows any tool to mine that block
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.62

**Logs:** N/A

**Steps to Reproduce:**
 1. Add a block to a mod, with `requiresCorrectToolForDrops`
 2. Tag that block with `Tags.Blocks.NEEDS_NETHERITE_TOOL` and `BlockTags.MINEABLE_WITH_PICKAXE` (though any tool type tag should do for the latter)
 3. Open Minecraft
 4. Observe that any tier of pickaxe can mine the block, see screenshot

image

**Description of issue:**
Tagging a block with `NEEDS_NETHERITE_TOOL` does not actually force the use of Netherite to mine the block. This appears to be because none of the `INCORRECT_FOR_x_TOOL` tags include `NEEDS_NETHERITE_TOOL`.

In my own test environment, I was able to get the expected behavior (only Netherite can mine NEEDS_NETHERITE_TOOL blocks) by adding the following to my block tags provider:
```kotlin
tag(BlockTags.INCORRECT_FOR_WOODEN_TOOL).addTag(Tags.Blocks.NEEDS_NETHERITE_TOOL)
tag(BlockTags.INCORRECT_FOR_STONE_TOOL).addTag(Tags.Blocks.NEEDS_NETHERITE_TOOL)
tag(BlockTags.INCORRECT_FOR_IRON_TOOL).addTag(Tags.Blocks.NEEDS_NETHERITE_TOOL)
tag(BlockTags.INCORRECT_FOR_GOLD_TOOL).addTag(Tags.Blocks.NEEDS_NETHERITE_TOOL)
tag(BlockTags.INCORRECT_FOR_DIAMOND_TOOL).addTag(Tags.Blocks.NEEDS_NETHERITE_TOOL)
```

Though, this assumes that Neoforge wants to treat Netherite's mining ability as being superior to Diamond.

Edit: added screenshot
Edit 2: added incorrect for stone, oops

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Added Javadoc to all the neoforge needs block tags to make it clear what they are for. And makes it so that Needs Netherite actually cause the block to not be mineable by diamond or below

closes https://github.com/neoforged/NeoForge/issues/1571

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
Same thing for this one about the double "by default"

File: src/main/java/net/neoforged/neoforge/common/Tags.java [hunk 1]
```diff
@@ -35,8 +35,28 @@ public static class Blocks {
          * This is patched into the following method: {@link net.minecraft.world.entity.monster.EnderMan.EndermanLeaveBlockGoal#canPlaceBlock(Level, BlockPos, BlockState, BlockState, BlockState, BlockPos)}
          */
         public static final TagKey<Block> ENDERMAN_PLACE_ON_BLACKLIST = neoforgeTag("enderman_place_on_blacklist");
+
+        /**
+         * For denoting blocks that need tools that are Wood or higher to mine.
+         * By default, this is not added to any Minecraft tag since by default, Wood is in the lowest "tier".
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/common/Tags.java]: Per @Shadows-of-Fire:
```suggestion
         * By default, this is not added to any Minecraft tag since Wood is in the lowest "tier".
```

File: src/main/java/net/neoforged/neoforge/common/Tags.java [hunk 2]
```diff
@@ -35,8 +35,28 @@ public static class Blocks {
...
+         */
         public static final TagKey<Block> NEEDS_WOOD_TOOL = neoforgeTag("needs_wood_tool");
+
+        /**
+         * For denoting blocks that need tools that are Gold or higher to mine.
+         * By default, this is not added to any Minecraft tag since by default, Gold is in the lowest "tier".
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/common/Tags.java]:
```suggestion
         * By default, this is not added to any Minecraft tag since Gold is in the lowest "tier".
```

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

**Review by sciwhiz12 — APPROVED** [review]
