### PR TITLE
Attempt to write saved data in a resilient manner

### LINKED ISSUE #775: Add more protections to SavedData for data corruption
Currently, `SavedData` tends to lose persisted data in the event of a crash, power loss, etc.

### PR DESCRIPTION
**Pull request by FiniteReality**
I'm implementing a naive solution for saving NBT data in a resilient manner here to prevent data corruption when a server/game crashes during saving. This should prevent data attachments (especially large ones) from corrupting, as any unfinished writes will get directed to a temp file instead. These temp files are automatically cleaned on load, if detected, using a naive algorithm which likely has terrible performance characteristics.

This should resolve #775, at least partially. It would be better if we could guarantee the write goes through, but if the JVM hard crashes (e.g. access violation, power loss) I don't see a way around needing something like this.

### CODE REVIEW

**Comment by FiniteReality** [comment]
I'm not 100% sure if putting the patch in NbtIo is the best place, as there are certain SavedData implementations which themselves do this kind of resilient saving - the player's saved data is one example. It may be worth moving the implementation into SavedData directly, rather than NbtIo. Thoughts?

**Comment by Technici4n** [comment]
I wanted to look into how vanilla handles this for its main level data file. There is some convoluted logic to make it work in many corner cases.

**Comment by FiniteReality** [comment]
> I wanted to look into how vanilla handles this for its main level data file. There is some convoluted logic to make it work in many corner cases.

Looking at it, it seems that it uses the same trick (`RegionFile#writeToExternalFile` creates a temp file, writes to it, and then moves it into place) for oversize chunks, but the main region file is simply a FileChannel created with `StandardOpenOption.DSYNC` which forces synchronous writes, and according to the NIO docs:
> The [SYNC](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/StandardOpenOption.html#SYNC) and [DSYNC](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/StandardOpenOption.html#DSYNC) options are used when opening a file to require that updates to the file are written synchronously to the underlying storage device. In the case of the default provider, and the file resides on a local storage device, and the [seekable](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/channels/SeekableByteChannel.html) channel is connected to a file that was opened with one of these options, then an invocation of the [write](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/channels/WritableByteChannel.html#write(java.nio.ByteBuffer)) method is only guaranteed to return when all changes made to the file by that invocation have been written to the device. These options are useful for ensuring that critical information is not lost in the event of a system crash. If the file does not reside on a local device then no such guarantee is made. Whether this guarantee is possible with other [provider](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/spi/FileSystemProvider.html) implementations is provider specific.

My guess is that internally this acts as a write-through for any caches and buffers for the region file that's open. Everything else on top of this is just shuffling I/O around so that it doesn't happen on the main thread, as they become blocking writes.

Since we're writing to a temporary file and moving that into place, all buffers should be appropriately flushed before the move completes anyway. We could consider moving to an I/O pool but I don't think this is necessary, and would be a rather invasive patch in comparison.

**Comment by Technici4n** [comment]
Doesn't MC also have some recovery system where it attempts to read files that are updated but haven't been moved yet? If it's just falling back to `LevelDirectory#oldDataFile` it's not as fancy as I remember...

The atomic move should be good enough.

**Comment by FiniteReality** [comment]
> Doesn't MC also have some recovery system where it attempts to read files that are updated but haven't been moved yet?

I couldn't find anything fancy like that. I assume they couldn't do that anyway, because it would risk data loss; a partially completed save could still have partially valid data and load successfully, even though the older file is more likely to be correct.

File: patches/net/minecraft/nbt/NbtIo.java.patch [hunk 1]
```diff
@@ -1,5 +1,48 @@
...
+-            OutputStream outputstream = Files.newOutputStream(p_309549_, SYNC_OUTPUT_OPTIONS);
++            OutputStream outputstream = Files.newOutputStream(tempFile, SYNC_OUTPUT_OPTIONS);
+             OutputStream outputstream1 = new BufferedOutputStream(outputstream);
+             DataOutputStream dataoutputstream = new DataOutputStream(outputstream1);
+         ) {
+             write(p_128956_, dataoutputstream);
+         }
++        try {
++            Files.move(tempFile, p_309549_, java.nio.file.StandardCopyOption.ATOMIC_MOVE);
++        } catch(java.nio.file.AtomicMoveNotSupportedException e) {
```
Comment (Technici4n) [inline patches/net/minecraft/nbt/NbtIo.java.patch]: Missing space after `catch`.

File: patches/net/minecraft/world/level/storage/DimensionDataStorage.java.patch [hunk 2]
```diff
@@ -42,6 +42,19 @@
 +                compoundtag1 = p_295038_.update(this.fixerUpper, compoundtag, i, p_78160_);
 +            } else {
 +                compoundtag1 = compoundtag;
++            }
++        }
++
++        // Neo: delete any temporary files so that we don't inflate disk space unnecessarily.
```
Comment (Technici4n) [inline patches/net/minecraft/world/level/storage/DimensionDataStorage.java.patch:48]: This is a bit ugly, maybe we should at least move it to a NeoForge class.

File: patches/net/minecraft/world/level/storage/DimensionDataStorage.java.patch [hunk 3]
```diff
@@ -42,6 +42,19 @@
...
++        try (var filesToDelete = java.nio.file.Files.find(
++            file1.toPath().getParent(), 1,
++            (file, attributes) ->
++                file.getFileName().toString().startsWith(file1.getName())
++                && file.getFileName().toString().endsWith("write-tmp"))) {
++
++            for (var file : filesToDelete.toList())
++            {
```
Comment (Technici4n) [inline patches/net/minecraft/world/level/storage/DimensionDataStorage.java.patch]: `{` should be on the same line.

File: patches/net/minecraft/nbt/NbtIo.java.patch [hunk 4]
```diff
@@ -1,5 +1,48 @@
 --- a/net/minecraft/nbt/NbtIo.java
 +++ b/net/minecraft/nbt/NbtIo.java
+@@ -72,12 +_,19 @@
+     }
+ 
+     public static void writeCompressed(CompoundTag p_128945_, Path p_309705_) throws IOException {
++        // Neo: write to a temporary file and move it to the correct location instead
```
Comment (Technici4n) [inline patches/net/minecraft/nbt/NbtIo.java.patch]: Should we maybe create a helper for atomic moves. Something like `CommonHooks.atomicWrite(Path, Consumer<Path>)`?

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+import org.jetbrains.annotations.Nullable;
+
+/**
+ * Declares a class containing helpers for performing file I/O in a resillient
+ * manner.
+ */
+public final class IOUtilities {
+    private static final String TEMP_FILE_SUFFIX = ".neoforge-tmp";
+    private static final OpenOption[] OPEN_OPTIONS = {
+            StandardOpenOption.DSYNC, // TODO: DSYNC or SYNC here?
```
Comment (FiniteReality) [inline src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: This is the one main question I have here: should we use DSYNC or SYNC? DSYNC only requires the content be written synchronously, while SYNC also waits for the metadata to finish.

Comment (FiniteReality) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: Oh, oops - I misclicked and resolved before posting. In any case, we discussed this in the NeoForge server and while it would be better if we could change this to use `FileChannel` to give us access to `FileChannel.force(false)`, it would be harder to implement due to needing to expose streams to consumers. Because of this, I'm going to leave it as `DSYNC` and leave changing the backend to FileChannel to somebody in the future, if performance becomes an issue.

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java [hunk 6]
```diff
@@ -0,0 +1,160 @@
...
+import java.util.function.Consumer;
+import net.minecraft.nbt.CompoundTag;
+import net.minecraft.nbt.NbtIo;
+import org.jetbrains.annotations.Nullable;
+
+/**
+ * Declares a class containing helpers for performing file I/O in a resillient
+ * manner.
+ */
+public final class IOUtilities {
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/common/IOUtilities.java:30]: Should this be marked `@ApiStatus.Internal`?

Should we also rename this to something like `ResilientIOUtilities`, to distinguish it from normal IO utilities and keeping in line with the javadocs?

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java [hunk 7]
```diff
@@ -0,0 +1,160 @@
...
+import java.nio.file.attribute.BasicFileAttributes;
+import java.util.function.BiPredicate;
+import java.util.function.Consumer;
+import net.minecraft.nbt.CompoundTag;
+import net.minecraft.nbt.NbtIo;
+import org.jetbrains.annotations.Nullable;
+
+/**
+ * Declares a class containing helpers for performing file I/O in a resillient
+ * manner.
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: Remove the "Declares a class containing", and substitute with "Contains".
```suggestion
 * Contains helpers for performing file I/O in a resillient manner.
```

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 5 above)
Comment (sciwhiz12) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: I think you may have forgotten to remove the comment, or at least replace it with this explanation.

**Review by sciwhiz12 — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 6 above)
Comment (FiniteReality) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java:30]: My thought was that it would be a convenient utility for other modders too, hence why it was made public.

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 7 above)
Comment (FiniteReality) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: :thinking: I don't even know why I wrote it this way in the first place, you're right.

Comment (Technici4n) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: Isn't the standard spelling `resilient`?

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 5 above)
Comment (Technici4n) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: Unresolving since you forgot to fix it:

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java [hunk 8]
```diff
@@ -0,0 +1,160 @@
...
+            } catch (Exception second) {
+                // But if we can't, we suppress the exception.
+                first.addSuppressed(second);
+            }
+
+            throw first;
+        }
+    }
+
+    private static void writeImpl(Path tempFile, Path destination, WriteCallback callback) throws IOException {
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: Why another function?

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java [hunk 9]
```diff
@@ -0,0 +1,160 @@
...
+            Files.move(tempFile, destination, StandardCopyOption.ATOMIC_MOVE);
+        } catch (java.nio.file.AtomicMoveNotSupportedException e) {
+            Files.move(tempFile, destination, StandardCopyOption.REPLACE_EXISTING);
+        }
+    }
+
+    /***
+     * Declares an interface which is functionally equivalent to {@link Consumer},
+     * except supports the ability to throw IOExceptions that may occur.
+     */
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: This is not particularly useful information.

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java [hunk 10]
```diff
@@ -0,0 +1,160 @@
...
+     * and it is the handler's responsibility to implement any buffering on top
+     * of this method.
+     *
+     * @param targetPath    The desired path to write to.
+     * @param writeCallback A callback which receives the opened stream to write
+     *                      data to.
+     *
+     * @throws IOException if an I/O error occurs during writing.
+     */
+    public static void atomicWrite(Path targetPath, WriteCallback writeCallback) throws IOException {
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/common/IOUtilities.java:120]: An alternative pattern is to make a custom `OutputStream`. See https://github.com/neoforged/ModDevGradle/blob/912978861241d87483713f3ced664f6316f0d005/src/main/java/net/neoforged/moddevgradle/internal/utils/FileUtils.java#L42. As you prefer, I don't mind either solution.

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 6 above)
Comment (Technici4n) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java:30]: I think it's fine to have public.

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 9 above)
Comment (FiniteReality) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: I'm not entirely sure what else could be said here.

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 10 above)
Comment (FiniteReality) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java:120]: I'm not a huge fan of the custom OutputStream approach, since part of me worries about poorly-implemented inner/outer streams, as well as consumers which don't properly call close

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 8 above)
Comment (FiniteReality) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: Personally, I dislike nested try/catch statements; I removed it though since it's technically unnecessary.

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 7 above)
Comment (FiniteReality) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: Yes; this was a typo.

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 9 above)
Comment (Technici4n) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: Maybe *gasps* no comment at all? More of a nitpick than anything else though.

**Review by Technici4n — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java [hunk 11]
```diff
@@ -122,8 +124,13 @@ public static void atomicWrite(Path targetPath, WriteCallback writeCallback) thr
                 TEMP_FILE_SUFFIX);
 
         try {
-            try (OutputStream writeStream = Files.newOutputStream(tempPath, OPEN_OPTIONS)) {
-                writeCallback.write(writeStream);
+            try (var channel = FileChannel.open(tempPath, OPEN_OPTIONS)) {
+                // We need to prevent the callback from closing the channel, since that
+                // would prevent us from flushing it.
+                var stream = CloseShieldOutputStream.wrap((Channels.newOutputStream(channel)));
```
Comment (FiniteReality) [inline src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: We don't need the extra parentheses here; everything else looks fine though :smile:

**Review by Technici4n — COMMENTED** [review]
Does closing the channel not flush it already?

**Comment by shartte** [comment]
> Does closing the channel not flush it already?

No. Not that we know of. You are thinking of java flush. We need OS-level fsync.

**Comment by Technici4n** [comment]
Ok. Just the extra parentheses and we're good then.

File: src/main/java/net/neoforged/neoforge/common/IOUtilities.java (hunk 11 above)
Comment (shartte) [reply src/main/java/net/neoforged/neoforge/common/IOUtilities.java]: Done

**Review by shartte — APPROVED** [review]

**Review by Technici4n — APPROVED** [review]
