### PR TITLE
[1.20.4] Rework how effects determine what they can be cured by

### LINKED ISSUE #322: Uncontrolled list type for mob effect curative items
**Minecraft Version:** 1.20.2

**NeoForge Version:** 20.2.86

**Steps to Reproduce:**
 1a. Make a custom mob effect that overrides `getCurativeItems()` and returns an unmodifiable list, and create a mob effect instance from it. OR:
 1b. Obtain any mob effect instance and call `mobEffectInstance.setCurativeItems(List<ItemStack>)` with an unmodifiable list.
 2. On the same mob effect instance, use `mobEffectInstance.addCurativeItem(ItemStack)` with a different item.

**Description of issue:**
Following the steps above, an `UnsupportedOperationException` should be thrown. The problem with this is that `addCurativeItem()` assumes that the list is mutable, and it is easy for a mod that overrides the curative item list to accidentally use an immutable list.

**Solution discussion:**
The simplest solution would be to change how the item list in the instance is handled, initializing it as a mutable copy of the list returned from `mobEffect.getCurativeItems()`, and in `mobEffectInstance.setCurativeItems(List<ItemStack>)`. There's also an opportunity to reshape this api in a different way, such as by changing `mobEffect.getCurativeItems()` from returning a list to modifying a list argument.

Note: This is not a problem I have experienced myself, but rather one that I identified from the perspective of overriding `mobEffect.getCurativeItems()`.

### PR DESCRIPTION
**Pull request by XFactHD**
This PR reworks the way `MobEffectInstance`s determine how the `MobEffect` they are holding can be cured. Instead of the effect instance holding a (hopefully) mutable list of stacks, it instead holds a non-replaceable, mutable set of `EffectCure`s to specify what an effect can be cured by. This has the benefit of allowing curing of effects without requiring an `ItemStack`

Fixes #322

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/common/EffectCures.java [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+ * Copyright (c) NeoForged and contributors
+ * SPDX-License-Identifier: LGPL-2.1-only
+ */
+
+package net.neoforged.neoforge.common;
+
+import java.util.Set;
+
+public class EffectCures {
+    public static final EffectCure MILK = EffectCure.get("milk");
```
Comment (KnightMiner) [inline src/main/java/net/neoforged/neoforge/common/EffectCures.java:14]: These could use some javadocs briefly describing how they work. Mostly modders might wonder whether they should use milk,  protected by totem, or a custom effect cure for their effect that cures something, and might not be aware that honey cures poison.

A mention to the potion added event as a way to add a custom cure event to a vanilla effect would be good somewhere as well, not sure where that best fits, perhaps `EffectCure`

File: src/main/java/net/neoforged/neoforge/common/extensions/IMobEffectInstanceExtension.java [hunk 2]
```diff
@@ -1,56 +0,0 @@
...
-     * Adds the given stack to the list of curative items for this PotionEffect
-     * 
-     * @param stack The ItemStack being added to the curative item list
-     */
-    default void addCurativeItem(ItemStack stack) {
-        if (!this.isCurativeItem(stack))
-            this.getCurativeItems().add(stack);
-    }
-
-    default void writeCurativeItems(CompoundTag nbt) {
```
Comment (KnightMiner) [inline src/main/java/net/neoforged/neoforge/common/extensions/IMobEffectInstanceExtension.java:51]: I do wonder if its worth still using this for `readCures` and `writeCures`, we can still clear/add to the set via `getCures()` as its not an immutable wrapper. Its a small patch either way, but guess its a patch into fewer places without the extension interface.

**Review by KnightMiner — APPROVED** [review]
Looks pretty much like I was thinking, just missing some javadocs on `EffectCures` and a stylistic question from me.

File: patches/net/minecraft/world/effect/MobEffectInstance.java.patch [hunk 3]
```diff
@@ -25,64 +25,72 @@
...
-+        return this.curativeItems;
-+    }
-+    @Override
-+    public void setCurativeItems(java.util.List<net.minecraft.world.item.ItemStack> curativeItems) {
-+        this.curativeItems = curativeItems;
++    private final java.util.Set<net.neoforged.neoforge.common.EffectCure> cures = com.google.common.collect.Sets.newIdentityHashSet();
++
++    /**
++     * Get the set of cures
++     * @return the {@link net.neoforged.neoforge.common.EffectCure}s which can cure the {@link MobEffect} held by this {@link MobEffectInstance}
```
Comment (Matyrobbrt) [inline patches/net/minecraft/world/effect/MobEffectInstance.java.patch]: Can be an inline return

File: patches/net/minecraft/world/entity/LivingEntity.java.patch [hunk 4]
```diff
@@ -669,17 +676,17 @@
  
 +    /* ==== FORGE START ==== */
 +    /***
-+     * Removes all potion effects that have curativeItem as a curative item for its effect
-+     * @param curativeItem The itemstack we are using to cure potion effects
++     * Removes all potion effects that have the given {@link net.neoforged.neoforge.common.EffectCure} in their set of cures
++     * @param cure The EffectCure being used
```
Comment (Matyrobbrt) [inline patches/net/minecraft/world/entity/LivingEntity.java.patch]:
```suggestion
+     * @param cure the EffectCure being used
```

File: src/main/java/net/neoforged/neoforge/common/EffectCure.java [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+
+    /**
+     * Gets or creates a new EffectCure for the given name.
+     */
+    public static EffectCure get(String name) {
+        return CURES.computeIfAbsent(name, EffectCure::new);
+    }
+
+    /**
+     * Returns the name of this cure
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/common/EffectCure.java]: Inline return

File: src/main/java/net/neoforged/neoforge/common/EffectCure.java [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+import java.util.Map;
+import java.util.concurrent.ConcurrentHashMap;
+
+public final class EffectCure {
+    private static final Map<String, EffectCure> CURES = new ConcurrentHashMap<>();
+
+    public static Codec<EffectCure> CODEC = Codec.STRING.xmap(EffectCure::get, EffectCure::name);
+
+    /**
+     * Returns all registered cures.
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/common/EffectCure.java]: Inline return

File: src/main/java/net/neoforged/neoforge/common/extensions/IMobEffectExtension.java [hunk 7]
```diff
@@ -5,37 +5,34 @@
...
 
     /**
-     * Used for determining {@code PotionEffect} sort order in GUIs.
-     * Defaults to the {@code PotionEffect}'s liquid color.
+     * Used for determining {@link MobEffect} sort order in GUIs.
+     * Defaults to the {@link MobEffect}'s liquid color.
      * 
-     * @param effectInstance the {@code PotionEffect} instance containing the potion
-     * @return a value used to sort {@code PotionEffect}s in GUIs
+     * @param effectInstance The {@link MobEffectInstance} containing this {@link MobEffect}
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/common/extensions/IMobEffectExtension.java]:
```suggestion
     * @param effectInstance the {@link MobEffectInstance} containing this {@link MobEffect}
```

File: src/main/java/net/neoforged/neoforge/event/entity/living/MobEffectEvent.java [hunk 8]
```diff
@@ -40,24 +41,36 @@ public MobEffectInstance getEffectInstance() {
...
         /**
-         * @return the {@link MobEffectEvent} which is being removed from the entity
+         * @return the {@link MobEffect} which is being removed from the entity
          */
         public MobEffect getEffect() {
             return this.effect;
         }
 
+        /**
+         * @return the {@link EffectCure} the effect is being cured by. Null if the effect is not removed due to being cured
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/event/entity/living/MobEffectEvent.java]: Inline return

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/common/EffectCures.java (hunk 1 above)
Comment (XFactHD) [reply src/main/java/net/neoforged/neoforge/common/EffectCures.java:14]: I added some simple docs, I currently can't think of anything better, so I'm open to suggestions

File: src/main/java/net/neoforged/neoforge/common/extensions/IMobEffectInstanceExtension.java (hunk 2 above)
Comment (XFactHD) [reply src/main/java/net/neoforged/neoforge/common/extensions/IMobEffectInstanceExtension.java:51]: I don't see much point in keeping the extension interface in this case because the patch is so small anyway.

File: src/main/java/net/neoforged/neoforge/common/EffectCures.java [hunk 9]
```diff
@@ -0,0 +1,25 @@
...
+    /**
+     * Cure used when a honey bottle is consumed. Only cures poison by default.
+     */
+    public static final EffectCure HONEY = EffectCure.get("honey");
+    /**
+     * Cure used when a totem of undying protects the player from death. Cures any effect by default.
+     */
+    public static final EffectCure PROTECTED_BY_TOTEM = EffectCure.get("protected_by_totem");
+
+    public static final Set<EffectCure> STANDARD_CURES = Set.of(MILK, PROTECTED_BY_TOTEM);
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/common/EffectCures.java]: Standard sounds a bit weird, I'd say default.

File: tests/src/main/java/net/neoforged/neoforge/debug/effect/MobEffectTests.java [hunk 10]
```diff
@@ -0,0 +1,91 @@
...
+            MobEffectInstance destInst = MobEffectInstance.load(srcInst.save(new CompoundTag()));
+            helper.assertTrue(srcInst.getCures().equals(destInst.getCures()), "'MobEffectInstance serialization roundtrip (standard cures)'");
+
+            srcInst.getCures().add(testCure);
+            destInst = MobEffectInstance.load(srcInst.save(new CompoundTag()));
+            helper.assertTrue(srcInst.getCures().equals(destInst.getCures()), "'MobEffectInstance serialization roundtrip (custom additional cure)'");
+
+            srcInst.getCures().clear();
+            destInst = MobEffectInstance.load(srcInst.save(new CompoundTag()));
+            helper.assertTrue(srcInst.getCures().equals(destInst.getCures()), "'MobEffectInstance serialization roundtrip (no cures)'");
```
Comment (Matyrobbrt) [inline tests/src/main/java/net/neoforged/neoforge/debug/effect/MobEffectTests.java:86]: Why are you surrounding every message in quotes?

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

File: tests/src/main/java/net/neoforged/neoforge/debug/effect/MobEffectTests.java (hunk 10 above)
Comment (XFactHD) [reply tests/src/main/java/net/neoforged/neoforge/debug/effect/MobEffectTests.java:86]: To me `Entity Pig[...] failed 'do the thing' test` reads better than `Entity Pig[...] failed do the thing test`. I'm not gonna die on that hill though

**Review by Matyrobbrt — DISMISSED** [review]

**Review by Matyrobbrt — APPROVED** [review]
