### PR TITLE
Respect `needsWorldRestart` and add `needsGameRestart`

### LINKED ISSUE #5: ForgeConfigSpec worldRestart is unused
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.8

**Steps to Reproduce:**
 1. View uses of `ForgeConfigSpec.ValueSpec#needsWorldRestart`
 2. See that there are none and that the value isn't even passed/accessible via `ConfigValue`

**Description of issue:**

The concept of certain config values needing a world restart in order for the config value changes to be updated/synced never got hooked back up again post 1.12. Given the fact that at some point support for config value caching got added it would make sense to only invalidate the cached values for entries that need a world restart when the config unloads (server is closed aka world restarts).

### PR DESCRIPTION
**Pull request by Matyrobbrt**
Config values marked as `needsWorldRestart` will only have their caches reset when the config is unloaded. Config values marked as `needsGameRestart` will never reset their caches.

Config UIs should now use `ConfigValue#getRaw` to get the actual config value.

Needs https://github.com/neoforged/FancyModLoader/pull/184

Fixes #5

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java [hunk 1]
```diff
@@ -1021,7 +1051,7 @@ public static class LongValue extends ConfigValue<Long> implements LongSupplier
         }
 
         @Override
-        protected Long getRaw(Config config, List<String> path, Supplier<Long> defaultSupplier) {
+        public Long getRaw(Config config, List<String> path, Supplier<Long> defaultSupplier) {
```
Comment (marchermans) [inline src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java:1318]: I don't like that this is made public, it opens modders up to a lot of shooting in the foot moments, by calling the wrong method.

What alternatives have you considered?

**Review by marchermans — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java (hunk 1 above)
Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java:1318]: Any other alternatives would expose getters that are even more accessible than the getRaw. This method has 3 more parameters which require much more work to get, no one will use it instead of get.

Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java:1318]: What are the other alternatives?
Have we considered creating some encapsulation mechanism that can be supplied to config UIs?

Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java:1318]: Encapsulation such as? The config ui needs the value "on disk" available, and getRaw is quite precisely what provides you with that. There is no footgun exposed here, the method requires a config instance which cannot be accessed directly from the config value and is only exposed by the spec, the path can be got from the config value, and the default supplier has to be provided as a lambda since there's only a getter that already calls it.

And besides, `getRaw` does exactly what it says. Gets the raw value a config holds. It's used for the cached getter, why wouldn't config uis, server dashboards, whatever use it when the `get` is cached and is no longer usable for that use case as it respects the restart flags.

Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java:1318]: Thinking this through again, I don't think Config UIs need getRaw().

The return type of get() and getRaw() is the same, so there is no difference there. The only difference is that get() is cached. While getRaw() is not. That on the other hand should be no hinderance to any config UI, because the value return by getRaw() is always the same as the value returned by get(). Or am I missing something here?

Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java:1318]: Hmm these flags are of an issue.
There are two aspects to consider:

Reload from disk, and UI.
- In UIs it does not matter.
- But when reloading from disk, it might matter.
  - Have we considered filtering the reload from disk to values that can be updated while the game is running?

Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java:1318]: > The only difference is that get() is cached.
> That on the other hand should be no hinderance to any config UI, because the value return by getRaw() is always the same as the value returned by get()

That's precisely the difference that matters in the context of this PR, as explained above and in the description... With this PR `get` does no longer represent the actual value of the config, as the caches will not be updated until the game or the world is restarted.

Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java:1318]: Okey understood. Still don't think you need the FML change.

**Review by marchermans — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java [hunk 2]
```diff
@@ -1071,4 +1101,28 @@ protected T getRaw(Config config, List<String> path, Supplier<T> defaultSupplier
...
+         * Require a world restart.
+         */
+        WORLD,
+        /**
+         * Require a game restart.
+         */
+        GAME;
+
+        private boolean canClearCache(boolean configUnloaded) {
+            if (this == GAME) return false;
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java]: This can be a fancy switch if you want. :P

**Review by Technici4n — DISMISSED** [review]

**Comment by HenryLoenwind** [comment]
If you rebase this (or merge main), I can PR the matching UI changes into this PR's branch.

**Review by TelepathicGrunt — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java [hunk 3]
```diff
@@ -136,11 +152,29 @@ public void afterReload() {
...
-                this.resetCaches(innerConfig.valueMap().values());
+                forEachValue(innerConfig.valueMap().values(), consumer);
+            }
+        });
+    }
+
+    @ApiStatus.Internal
+    public void resetWorldCaches() {
+        forEachValue(getValues().valueMap().values(), configValue -> {
+            if (configValue.getSpec().restartType == RestartType.GAME) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java]: Shouldn't this check for world?

**Review by XFactHD — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java (hunk 3 above)
Comment (TelepathicGrunt) [reply src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java]: I am very good at missing bugs lol

**Review by TelepathicGrunt — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java [hunk 4]
```diff
@@ -136,11 +152,29 @@ public void afterReload() {
...
+    }
+
+    @ApiStatus.Internal
+    public void resetWorldCaches() {
+        forEachValue(getValues().valueMap().values(), configValue -> {
+            if (configValue.getSpec().restartType == RestartType.WORLD) {
+                configValue.clearCache();
             }
         });
     }
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java]: This whole thing can be implemented using a single `resetCaches(Iterable<Object> configValues, RestartType restartType)` function.

**Review by Technici4n — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java (hunk 4 above)
Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java]: `forEachValue` is used by the validator, the best I can do is merge the 2 resetCache methods.

**Review by Technici4n — DISMISSED** [review]
Good but the build is failing.

**Review by Technici4n — DISMISSED** [review]

**Comment by HenryLoenwind** [comment]
The lines at https://github.com/neoforged/NeoForge/blob/c336f6c692bc4b5434b72d576ef99f41787417f9/src/main/java/net/neoforged/neoforge/client/gui/ConfigurationScreen.java#L610 need the same treatment as those starting at 602.

I missed those when checking the PR³. The RawSupplier handled that automatically before...

**Comment by TelepathicGrunt** [comment]
@HenryLoenwind 
gordon-ramsay-raw

File: src/main/java/net/neoforged/neoforge/client/gui/ConfigurationScreen.java [hunk 5]
```diff
@@ -106,6 +108,30 @@
  * 
  */
 public final class ConfigurationScreen extends OptionsSubScreen {
+    private static final class TooltipConfirmScreen extends ConfirmScreen {
+        boolean seenYes = false;
+
+        private TooltipConfirmScreen(BooleanConsumer p_95658_, Component p_95659_, Component p_95660_, Component p_95661_, Component p_95662_) {
+            super(p_95658_, p_95659_, p_95660_, p_95661_, p_95662_);
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/gui/ConfigurationScreen.java]:
```suggestion
        private TooltipConfirmScreen(BooleanConsumer callback, Component title, Component message, Component yesButton, Component noButton) {
            super(callback, title, message, yesButton, noButton);
```

**Review by XFactHD — CHANGES_REQUESTED** [review]
One nitpick, otherwise looks good to me

**Review by XFactHD — APPROVED** [review]
