### PR TITLE
[1.20.x] Actually post PlayerSpawnPhantomsEvent

### LINKED ISSUE #71: `PlayerSpawnPhantomsEvent` is just instantiated and not run on the event bus
**Minecraft Version:** 1.20.1

**NeoForge Version:** 47.1.56

**Logs:** Not really needed

**Steps to Reproduce:**
 1. Subscribe a PlayerSpawnPhantomsEvent
 2. Run the game and check that the event is never run

**Example code**
This makes Phantoms spawn in The End instead of the Overworld
```java
@SubscribeEvent
public void onPhantomsSpawn(PlayerSpawnPhantomsEvent event) {
    if (event.getEntity().level().dimension() == Level.OVERWORLD)
        event.setResult(Event.Result.DENY);
    else if (event.getEntity().level().dimension() == Level.END)
        event.setResult(Event.Result.ALLOW);
}
```

**Description of issue:**
This happens because the event is never posted, only instantiated:
https://github.com/neoforged/NeoForge/blob/3323a2f37989bea3171273292f5a355ef445a9f3/patches/minecraft/net/minecraft/world/level/levelgen/PhantomSpawner.java.patch#L10

### PR DESCRIPTION
**Pull request by AterAnimAvis**
The initial PR https://github.com/MinecraftForge/MinecraftForge/pull/9644, never actually fires the Event.

Fixes #71

### CODE REVIEW

**Comment by AterAnimAvis** [comment]
Updated for Formatting Issues + added simple Test Mod

Note that the provided example in #71 will still not fully work.
This event is fired from `PhantomSpawner`, a `CustomSpawner`, these are passed in via the constructor to the `Level`, and only the Overworld's `ServerLevel` gets constructed with a non empty list of these by default.
As such the spawning in the End won't actually occur, considering this out of scope for this PR.

File: src/test/java/net/minecraftforge/debug/entity/player/PlayerSpawnPhantomsEventTest.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+package net.minecraftforge.debug.entity.player;
+
+import net.minecraftforge.event.entity.player.PlayerSpawnPhantomsEvent;
+import net.minecraftforge.eventbus.api.Event;
+import net.minecraftforge.eventbus.api.SubscribeEvent;
+import net.minecraftforge.fml.common.Mod;
+
+@Mod("player_spawn_phantoms_event_test")
+@Mod.EventBusSubscriber()
+public class PlayerSpawnPhantomsEventTest
```
Comment (sciwhiz12) [inline src/test/java/net/minecraftforge/debug/entity/player/PlayerSpawnPhantomsEventTest.java:21]: Please provide a javadoc for this class which explains what feature this tests, how to test it, and what the expected results are from said test.

Also, we should probably make the test mod result more obvious, like setting the phantoms spawned to a unnaturally large amount, instead of preventing spawns (which may be attributed to luck).

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

**Review by sciwhiz12 — APPROVED** [review]
The test mod confirms the event posting works.

**Comment by Insane96** [comment]
>  and only the Overworld's `ServerLevel` gets constructed with a non empty list of these by default. As such the spawning in the End won't actually occur, considering this out of scope for this PR.

Good to know, thanks
