### PR TITLE
Unhook mayFly field from controlling flight

### LINKED ISSUE #3015: fly error
**Minecraft Version:** {Minecraft version}

**NeoForge Version:**21.1.215 /21.1.221

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 

**Description of issue:**
NeoForge breaks the Mayfly attribute in vanilla Minecraft

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Since we had `Abilities#mayFly` field deprecated for a significant number of Minecraft versions, it is time to kill it off once and for all in favor of the NeoForge attribute `net.neoforged.neoforge.common.NeoForgeMod#CREATIVE_FLIGHT`

Anyone using the old field will now find it does not control flight at all. Forcing the usage of the attribute. The `Abilities#mayFly` field already has a javadoc pointing to the attribute so no issue there.

Closes https://github.com/neoforged/NeoForge/issues/3015

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/common/extensions/IPlayerExtension.java [hunk 1]
```diff
@@ -79,14 +79,14 @@ default OptionalInt openMenu(MenuProvider menuProvider, Consumer<RegistryFriendl
      * Determine whether a player is allowed creative flight via game mode or attribute.
      * <p>
      * Modders are discouraged from setting {@link Abilities#mayfly} directly.
+     * That {@link Abilities#mayfly} field will no longer control flight due to {@link NeoForgeMod#CREATIVE_FLIGHT} replacing it.
```
Comment (KnightMiner) [inline src/main/java/net/neoforged/neoforge/common/extensions/IPlayerExtension.java]: The above javadoc says modders are discouraged from setting may fly, but this PR makes it no longer do anything instead of simply discouraging, so would be worth an update.

Comment (TelepathicGrunt) [reply src/main/java/net/neoforged/neoforge/common/extensions/IPlayerExtension.java]: Adjusted the wording. I use forbidden to really hammer to the reader to not use mayFly

**Review by pupnewfster — APPROVED** [review]
