### PR TITLE
Fix non-compostables being insertable through null side

### LINKED ISSUE #2572: IItemHandler for null side of Composter allows items without compost value to be inserted
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.164

**Steps to Reproduce:**
 1. Call `net.neoforged.neoforge.items.IItemHandler#insertItem` with an `IItemHandler` (obtained through `net.neoforged.neoforge.common.extensions.ILevelExtension#getCapability(net.neoforged.neoforge.capabilities.BlockCapability<T,C>, net.minecraft.core.BlockPos, C)` with `net.neoforged.neoforge.capabilities.Capabilities.ItemHandler#BLOCK` for `cap`, the position of a `ComposterBlock` for `pos`, and `null` for `context`) with `0` for `slot`, an `ItemStack` that has no compost value for `stack`, and anything for `simulate`.
 2. Observe that the `ItemStack` is inserted despite not having any compost value

**Description of issue:**
Composters return a `net.neoforged.neoforge.items.wrapper.ForwardingItemHandler` that forwards a `net.neoforged.neoforge.items.wrapper.InvWrapper` when queried with a `null` context.

The insertion logic checks for the wrapped `Container`'s `Container#canPlaceItem` which is not overriden by `net.minecraft.world.level.block.ComposterBlock.InputContainer`.

This means that we accept all items **with and without compost value** when trying to deposit into the null face, leading to unintended item voiding behaviour when trying to insert items without compost value.

The two choices that make sense to me are
1. Reject all items deposited because items are only meant to be accepted from above and `net.minecraft.world.Container#canPlaceItem` does not get passed enough information to decide
2. Accept only items **with compost value** because null face is generally used for full access

For clarification, this is technically a Mojang bug - but I believe it should be fixed in Neo as Neo exposes this behaviour through the `IItemHandler` registered in `net.neoforged.neoforge.capabilities.CapabilityHooks#registerVanillaProviders`.

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #2572 by changing the capability registration for `ComposterBlock` to always use `SidedInvWrapper`.

`InvWrapper` does not do an on-insertion check using `WorldlyContainer`'s `canPlaceItemThroughFace`, which composters use to restrict inserted stacks to compostable ones. `SidedInvWrapper` does this check, and it accepts `null` sides, so it's simpler to always use it.

This PR also adds a corresponding game test for this behavior. Without the fix, it errors as expected.

---

I'm unsure what our current policy is on mentioning the issue number in game tests for that issue, so I've left it out. If it's wanted, I can insert it quickly in. (Perhaps as a comment within the game test body?)

The game test assumes that the barrier item is always non-compostable, with a corresponding check to fail the game test if that assumption is wrong just in case.

The game test could be expanded to cover also ensuring that the appropriate sides will accept compostable items, but I think that's a bit too out-of-scope for the fix I'm implementing.

### CODE REVIEW

**Comment by sciwhiz12** [comment]
@Technici4n per your comment on the issue, https://github.com/neoforged/NeoForge/issues/2572#issuecomment-3223690348, I've added a comment about the `null` side being tested.

File: tests/src/main/java/net/neoforged/neoforge/debug/capabilities/VanillaHandlersTests.java [hunk 1]
```diff
@@ -78,6 +80,36 @@ public static void testComposterInvalidation(ExtendedGameTestHelper helper) {
...
+        // Of particular note to be tested here is the 'null' side; see #2572
+        // "IItemHandler for null side of Composter allows items without compost value to be inserted"
+        var sides = new Direction[] { null, Direction.UP, Direction.DOWN, Direction.NORTH, Direction.EAST, Direction.SOUTH, Direction.WEST };
+
+        for (Direction side : sides) {
+            var capability = helper.getLevel().getCapability(Capabilities.ItemHandler.BLOCK, helper.absolutePos(composterPos), side);
+            if (capability == null)
+                helper.fail("Expected composter to have a block item handler capability for side " + side);
+
+            assert capability != null; // The helper#fail call above ensures this is not null
```
Comment (Technici4n) [inline tests/src/main/java/net/neoforged/neoforge/debug/capabilities/VanillaHandlersTests.java]: This is weird. We have a `helper.requireCapability` method which will make this unnecessary I believe.

Comment (sciwhiz12) [reply tests/src/main/java/net/neoforged/neoforge/debug/capabilities/VanillaHandlersTests.java]: Ah, I was unaware that method existed. The rest of the class doesn't mention it, and I didn't look at other classes.

**Review by Technici4n — APPROVED** [review]
