### PR TITLE
Network refactoring

### LINKED ISSUE #348: `minecraft:register` is formatted incorrectly
**Minecraft Version:** 1.20.2

**NeoForge Version:** Tested on 20.2.84 and 20.2.86

**Steps to Reproduce:**
 1. Join a CraftBukkit server (which is overly strict) with NeoForge

**Description of issue:**
NeoForge prefixes the `minecraft:register` packet with an extra null character. Doing a code dig, I found that this is because NeoForge uses its `SimplePayload` class to send the `minecraft:register`. However, `SimplePayload` has a `packetIndex` field, which gets prefixed to the packet data. The `minecraft:register` code hardcodes the `SimplePayload` `packetIndex` to `0`, which causes the prefixed null character I saw in Wireshark.

### PR DESCRIPTION
**Pull request by marchermans**
# TLDR.
- Reworked networking, now completely based of of `CustomPacketPayload` and native to Minecraft
- Created events to register custom network payload types
- Implemented new negotiation mechanic for network payload types
- Fixed several bugs with the negotiation mechanic (aka there being for example a 0 in the minecraft:register payload type)
- Create an event to handle custom configuration tasks

# Introduction
## Reworked networking
Welcome to the reworked networking pull request for NeoForged.
The changes in this pull request implement the configuration network protocol designed by @modmuss50 with some minor modifications. I'm sharing more on those below.
> [!TIP]
> The NeoForge @neoforged/maintainers did perform an analysis of the networking protocol. It is a bit rough, but the resulting packet flows, and analysis comments can be found [here](https://hackmd.io/@neoforged/SkL_ikSXa)

## Consequences of the split packet type introduced in 1.20.2
During the introduction of 1.20.2, Mojang created in practice two distinct packet systems, one set known as the login packets and one set known as the play packets. Within those play packets, a unique phase was created; during this phase, the client configuration is supposed to happen. 

During the port to 1.20.2, we needed more time to address these unique structures within the packet layout that Mojang introduced, create APIs that allow modders to use these new packet systems to their fullest, and give access to this unique configuration phase. This PR achieves this.

## SimpleChannel and EventChannel
Original Forge contained two different ways of implementing a custom network channel. A simple registration-based approach is known as SimpleChannel, and a system that fires events for each packet received is known as EventChannel.
To simplify using networking and make interacting with new packet layouts easier, it was decided to rework both implementations into a single system, combining the best of both worlds.

# Implementation
## New network payload handling
The system is based on the `CustomPacketPayload` definition that Mojang uses to represent the content of custom packets. Internally, they register their custom payloads, used mainly for debugging, to a map. We need to extend this map so that a modder can send and receive a custom implementation of this `CustomPacketPayload`. This is what a significant part of this PR achieves. Modders can introduce new CustomPacketPayload implementations by registering them during the `RegisterPacketHandlerEvent`. 

### The registrar
Any modder can request a registrar for any namespace he or she desires; however, it is recommended that a modder only request a registrar for his or her namespace. Once a registrar is retrieved from the event, the modder can then configure the registrar with two different options: `versioned(String version)` to configure a version for all payloads registered after the call and `optional()` to mark all payloads registered after that call as not requiring a receiving side. An example of the registrar configuration can be found here:
```java
@SubscribeEvent
public static void register(final RegisterPacketHandlerEvent event) {
    final IPayloadRegistrar registrar = event.registrar(NeoForgeVersion.MOD_ID)
            .versioned(NeoForgeVersion.getSpec())
            .optional();
}
```
> [!NOTE]
> The registrar is an immutable object; calling `versioned(String version)` or `optional()` on an instance of the registrar will cause a new instance with the desired configuration to be created.

> [!CAUTION]
> The registrar loses its validity the moment the scope of the event has been left. Registering payload handlers outside of the event handling scope will result in those payloads not being known to the system and not being sent over the connection.

The registrar offers six different endpoints, three pairs of 2, to register new payloads. A pair exists for the play phase, one pair for the special configuration subphase, and one pair of methods for both.

> [!IMPORTANT]
> It is impossible to register custom payloads that should be sent during the login phase of the connection. And this PR offers, as such, no infrastructure to achieve this.

Within each pair of registration methods for a phase, two variants (as such, six methods) are available. One that registers the same handler for both sides of the connection and one that takes a consumer, allowing for the configuration of single-sided or differentially handled payloads. 

An example of the signature of the methods for the configuration phase is as follows:
```java
<T extends CustomPacketPayload> IPayloadRegistrar configuration(ResourceLocation id, FriendlyByteBuf.Reader<T> reader, IConfigurationPayloadHandler<T> handler);

<T extends CustomPacketPayload> IPayloadRegistrar configuration(ResourceLocation id, FriendlyByteBuf.Reader<T> reader, Consumer<IDirectionAwarePayloadHandlerBuilder<T, IConfigurationPayloadHandler<T>>> handler);
```
For the play phase, similar methods exist.
For payloads that are supposed to be sent during both the play phase as well as the configuration phase, there also exists a pair, however here, the handler is a common supertype of the handling callbacks, and the handler only has a reduced common superset of the information available to both phase handlers to it available.

### Payload discrimination
When considering this system, you might, right-fully so, ask how the system keeps the different payload types apart from each other. This is achieved by the system it-self. It writes a discriminator ID to the connection before invoking the actualy writing mechanic for a payload. Conversely on the client side, the discrimininator is read first, before a reader is looked up so that the rest of the payload can be read.

> [!NOTE]
> The system handles reading and writing the discriminator it-self, as a modder you do not need to take care of this yourself.

The value of the discriminator during writing is retrieved from the `CustomPacketPayload#id()` method, and is not allowed to be null.
The value against which the id, read from the connection, is compared to find a reader, is the one that is given to the registrar as the first argument.
It is as such of the upmost importance that you return the same value, as in the same resource location, from both the `id()` method on the payload instance, as well as given the same value to the registrar when registering your payload. 

> [!TIP]
> We recommond that you store your ID in a `public static final ResourceLocation ID = new ResourceLocation("mod_id", "payload_id")` field, and reference that in both places.

> [!WARNING]
> Given that the id is used as a discriminator, it is important that you use a unique value, especially for the ResourceLocations path section for each payload type. If you try to register the same id twice, the registrar will throw an exception. If you try to register an id with a namespace other then the one the registrar is for, the registrar will throw an exception. You are free to request registrars for other namespaces then your own.

### Payload reading
Payload reading happens via the vanilla method, implementing the `FriendlyByteBuf.Reader<T>` functional interface. During the registration of the payload type, as can be seen above, you need to pass an implementation of this interface so that a new instance of the payload can be created by the system when a custom payload packet with it as payload arrives on the receiving end.

> [!TIP]
> As we recommend that your payload implementations are `record`s in java, instead of classes, we also recommend that you create a custom constructor with the record, to read the records fields from the buffer. This constructor can then be passed as a method reference for the reader implementation. So if `SimplePayload(String somethign) {}` is your normal record, then adding `SimplePayload(FriendlyByteBuf buf) { this(buf.readUtf()); }` as a constructor to the `SimplePayload` record will allow you to pass it as a method reference `SimplePayload::new` to the registar when it asks for an implmentation of `FriendlyByteBuf.Reader<SimplePayload>`

> [!WARNING]
> There is no guarantee with respect to which thread the reading callback is invoked upon. It is as such important to note that the method can be called on many threads in parallel if the same packet is received on many connections simultaniously.

### Payload writing
The `CustomPacketPayload` interface contains a method: `write(FriendlyByteBuf)` method. This method is invoked when it is time to write your payload to the network connection. There is no guarantee on the thread this is invoked from.

> [!WARNING]
> There is no guarantee concerning which thread the writing method is invoked upon. It is as such important to note that the method can be called on many threads in parallel if it is being send over several connections at once.

> [!CAUTION]
> Payloads are only read and written if sent over a connection. This means that the host of a single-player world (even if exposed to LAN) has packets and, as such, payloads transferred in memory. This means that for those payloads, no write method is invoked, and no reader is called. Only the handler is invoked!

### Payload handling
Once a payload has been written, transmitted and read, the payload handler is invoked. This handler is again looked up with the id of the payload, and then invoked with the context of the receiving end. In practice each payload handler takes two arguments:
- The payload instance
- The context

> [!WARNING]
> Processing of the payload, as in the invocation of the handler callback, happens on the network thread, and can as such happen in parallel with other payloads of the same type being handled. If you need to ensure that the payload is processed on the main thread, serially, see the `ISynchronizedWorkHandler` available in the context under the `workHandler()` method.

#### The context
The context contains information, callbacks and entry points, to access the surrounding network system, the main thread, as well as handling processing other packets, or completing configuration tasks.

##### ReplyHandler
The reply handler can be used to quickly send a payload back to the sender. It is for example usefull to send and answer to a query packet, or simply send an acknowledge that you received and processed the payload. You still need to register the return payload.

##### PacketHandler
In case you implement a packet splitting mechanism, whether that splits on full vanilla packets, or custom packet payloads, the `IPacketHandler` interface gives you access the the start of the processing pipeline, allowing you to process other payloads immediatly. 

> [!NOTE]
> This does not transmit payloads, it purely allows for the receiving end to process additional packets or payloads constructed in memory during the processing of your payload

The packet handler also gives you access to a `disconnect(Component)` method allowing you to terminate the connection at will, showing the given component as reason to the user.

##### WorkHandler
The work handler allows you to schedule work on the main thread of the receiving side. This might be the `Minecraft` class instance if the logical receiving side is the client, or the `MinecraftServer` instance if the receiving side is the server.

The system uses `CompleteableFuture` instances so you can schedule different follow up tasks, if need be.

##### PacketFlow
The context will indicate via the packet flow, what the receiving side currently is. If it is a server bound flow, then handler is currently being invoked in the context of the server. Is it a client bound flow, then the handler is currently being invoked in the context of the client.

##### ConnectionProtocol
The current active connection protocol. Usefull if you have raw bytes of a packet wrapped in your payload, allowing your handler to decode the inner packet or payload, before passing it to the `IPacketHandler` for processing.

##### ChannelHandlerContext
The netty channel handling context that is currently processing the network connection on which the payload was received.
This context can be used to retrieve the raw underlying connection via `ConnectionUtils` or again be used to process raw bytes of inner packets and payloads.

##### Sender
This is an `Optional` containing a player, if and only if the handler is being invoked on the server side, but not during the configuration phase (there is simply no player instance yet, as such there is no way to get the information)

##### TaskCompletedHandler
This is a special contextual value only available to payloads for the configuration, which are specifically registered as such, to indicate that a specific configuration task has been completed, and that the next one can be started.

##### Future additions to the contexts
We are fully aware that these entry points might not be all information you as a modder need to process a packet. In general it is pretty easy to extend the interfaces and records. **They were specifically designed to allow for simple PRs in the future to add to them**, so please do not hesitate to create a quick PR to add your needed data to the context.

### Packet Sending
In tandem with the refactoring of the channel registration mechanic we added new tools and systems to allow you to easier send a custom payload to different targets.

#### PacketDistributor
This wrapper class now has the ability to process custom payloads solely. Its instances and targets can be passed around since they are immutable. Several methods on extension classes will accept these, to facilitate easy transfer of payloads.

#### Extension objects
We extended several vanilla types allowing for them to accept payloads as well, not just packets. Examples are chunk sections, listeners, entities and players.

### Netty information
In contrast with the past, we now store a lot of information related to the connection, for example the negotiated payload types, on the connection object itself. To this accord we added several attributes to store this information in. Allthough the attributes are considered part of the internal API, if somebody wants to dig through the internal guts, they should feel free to do so, however there is no guarantee that we would change them around in future releases, even outside the BC window.

### Tasks
Vanilla now provides a centralized way to perform tasks and jobs that need to be performed when a player joins. The player won't be instantiated or added to a world untill these tasks are completed.

Under normal circumstances these tasks are implementations of the `ConfigurationTask` interface, with a single method: `start(Consumer<Packet<?>>)`. However, this is subpar in our situation. Modders should never really have to touch raw Packets to perform their duties, only payloads. And as such it was decided to have modders implement the `ICustomConfigurationTask` interface from neoforge itself. This provides a wrapper around the `ConfigurationTask` signature and allows for sending payloads instead of packets, by implementing `run(Consumer<CustomPacketPayload>)` instead. The given consumer will then automatically convert the payload to a packet and send it to the client that is being configured.

> [!NOTE]
> In practice an instance of `ICustomConfigurationTask` is also an instance of `ConfigurationTask` as one extends the other. But to provide the ability for this to be a functional interface, the method `Start` is implemented as a default implementation. It is not recommended to also override that.

### OnGameConfigurationEvent
This event is fired to collect all tasks that should be run, and allows for the registration of `ICustomConfigurationTask` instances to the listener. It is not possible to register the vanilla `ConfigurationTask` instances.

> [!TIP]
> This event is fired on the mod bus, to preserve dependency order. Given that configuration tasks can only be ran in order of registration, you can safely assume that configuration tasks of your dependencies have been ran before yours.

### Forge changes:
Moved configuration sync, registry sync, and tier registry sync to configuration phase tasks.

## Bundle packet processing
In 1.20.2 Mojang introduced the bundling system for packets, which is a core component that allows for packets to be processed together. And started using sparsely. We anticipate modders want to use this system, so we adapted it to accept custom payloads. You will find a `sendBundled(CustomPacketPayload[] payloads)` method on the `ServerGamePacketListener`

> [!WARNING]
> Packet bundling is only supported during the play phase of the network protocol. It can not be used during the configuration phase of the protocol.

## Opening menus with custom data
In the past Forge supported opening UIs from the server side with additional data, via `NetworkHooks.openScreen(...)`. this system has been moved and is now part of the server `ServerPlayer` extension. You can call the method `openMenu` with the same parameters.

## Spawning entities with custom data
The previous networking implementation allowed for the spawning of custom entities via an overridden method on the `Entity` class: `getAddEntityPacket.` Modders that wanted to support custom additional data to be processed on the client side when the entity spawned, could override this method and return a packet from the method: `NetworkHooks.getEntitySpawningPacket(...)`

This system has now been refactored (as Mojang spawns and processes the entity packets with a bundle). The core of this new framework is the method `sendPairingData(ServerPlayer, Consumer<CustomPacketPayload>)` on the `Entity` class. There are now two methods to configure this.

### Using a custom payload
By overriding the method and invoking the consumer with a custom payload, you are guaranteed that your payload will be processed immediately after the spawning packet. You are free to do whatever you want, however, we recommend you at least transfer the entity id, as vanilla does, to retrieve the entity instance when your packet arrives. 

### Using the `IEntityWithComplexSpawn` interface
Implementing this interface on your entity forces you to implement two methods: `writeSpawnData` and `readSpawnData`. These methods, respectively, are invoked when an entity spawn bundle is generated and when the entity has been spawned.

### Removal of custom entity creation code in `EntityType`
It is no longer possible to use the entity spawn packet code mentioned above to create a different entity class on the client side. This was due to the refactoring of the payload mechanics. And the reliance on the vanilla spawning bundle.

## Forge Packetsplitter
This PR reimplements the vanilla packet splitter forge, previously contained in Forge, and expands its usage to any packet (other than the packet sent when stuff is split).

Due to the new mechanics, a packet or payload is now roughly split into 8MB chunks, as per the vanilla protocol limitations.

## Modlist transfer
Currently, the new protocol does not support sending the mod list across and only works on a channel and registry content basis. However, we do intend to work with the Fabric team on expanding the protocol in such a way that the server is made aware of what kind of mods the client has installed. 
We deem this necessary to allow server owners to block mods that would allow cheating, for example, an XRay mod, etc.
This will be added in another PR after further reviewing our stance and implementation possibilities.

---

## Todo:
- [x] Implement registry sync failure disconnecting and messaging
- [x] Discuss futher contextual components to the ServerConfigurationPacketListener, as this is the only piece of information given to the OnGameConfigurationEvent. We already exposed on that listener type if the connection is vanilla or not. Maybe the players UUID should be exposed as well? Please discuss this in the comments.
- [x] Test further scenarios where mismatches can occur
- [x] Is modlist mismatch testing even needed? Should we not more think about this in the form of content, aka network payload types, registries and their contents, tier sorting etc?
- [x] Improve support for bundle packets
- [x] Introduce endpoints to detect the payload state

---

## Follow up PRs
- Introduce a debugging tool
- Expand configuration protocol to communicate the client mods

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/network/DualStackUtils.java [hunk 1]
```diff
@@ -82,7 +82,7 @@ public static boolean checkIPv6(final InetAddress inetAddress) {
         } else {
             if (shouldLogDebug) {
                 final String addr = inetAddress == null ? "null" : "\"" + inetAddress.getHostAddress() + "\"";
-                LOGGER.debug("Unable to determine IP version of address: " + addr);
+                LOGGER.debug("Unable to determine IP preferredVersion of address: " + addr);
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/DualStackUtils.java]: This should be reverted.

File: patches/net/minecraft/client/multiplayer/ServerStatusPinger.java.patch
Comment (AterAnimAvis) [inline patches/net/minecraft/client/multiplayer/ServerStatusPinger.java.patch:1]: Whitespace only patch

File: patches/net/minecraft/server/MinecraftServer.java.patch [hunk 2]
```diff
@@ -125,7 +125,7 @@
              Optional.ofNullable(this.statusIcon),
 -            this.enforceSecureProfile()
 +            this.enforceSecureProfile(),
-+            Optional.of(new net.neoforged.neoforge.network.ServerStatusPing())
++            true //TODO: Possible build a system which indicates what the status of the modded server is.
```
Comment (AterAnimAvis) [inline patches/net/minecraft/server/MinecraftServer.java.patch]: `// Neo TODO:`?

File: src/main/java/net/neoforged/neoforge/client/gui/ModMismatchDisconnectedScreen.java [hunk 3]
```diff
@@ -208,17 +182,16 @@ protected int getContentHeight() {
         protected void drawPanel(GuiGraphics guiGraphics, int entryRight, int relativeY, Tesselator tess, int mouseX, int mouseY) {
             int i = 0;
 
-            for (Pair<FormattedCharSequence, Pair<FormattedCharSequence, FormattedCharSequence>> line : lineTable) {
+            for (Pair<FormattedCharSequence, FormattedCharSequence> line : lineTable) {
                 FormattedCharSequence name = line.getLeft();
-                Pair<FormattedCharSequence, FormattedCharSequence> versions = line.getRight();
+                FormattedCharSequence reaons = line.getRight();
```
Comment (AterAnimAvis) [inline src/main/java/net/neoforged/neoforge/client/gui/ModMismatchDisconnectedScreen.java]: `reasons`

File: patches/net/minecraft/client/multiplayer/ServerStatusPinger.java.patch [hunk 4]
```diff
@@ -1,10 +1,10 @@
...
-                         });
-+                        net.neoforged.neoforge.client.ClientHooks.processForgeListPingData(serverstatus, p_105460_);
-                         this.pingStart = Util.getMillis();
-                         connection.send(new ServerboundPingRequestPacket(this.pingStart));
-                         this.success = true;
+@@ -55,6 +_,7 @@
+             p_105460_.ping = -1L;
+             p_105460_.playerList = Collections.emptyList();
+             ClientStatusPacketListener clientstatuspacketlistener = new ClientStatusPacketListener() {
++
```
Comment (Matyrobbrt) [inline patches/net/minecraft/client/multiplayer/ServerStatusPinger.java.patch]: Whitespace patch

File: patches/net/minecraft/network/ConnectionProtocol.java.patch [hunk 5]
```diff
@@ -0,0 +1,185 @@
...
+             return this.packetSet.createPacket(p_294972_, p_296217_);
+         }
++        
++        /**
++         * Creates a new packet from the discriminator and the buffer.
++         *
++         * @param p_294972_ The discriminator
++         * @param p_296217_ The buffer
++         * @param p_130535_ The channel context
++         * @return The packet
```
Comment (Matyrobbrt) [inline patches/net/minecraft/network/ConnectionProtocol.java.patch]: Documentation of vanilla methods shall be left to parchment, you should only add the deprecated annotation

File: patches/net/minecraft/network/ConnectionProtocol.java.patch [hunk 6]
```diff
@@ -0,0 +1,185 @@
...
++         * Creates a new packet from the given discriminator and buffer.
++         *
++         * @param p_178328_ The discriminator
++         * @param p_178329_ The buffer
++         * @param p_130535_ The channel context
++         * @return The packet, or null if none can be read.
++         */
++        @Nullable
++        public Packet<?> createPacket(int p_178328_, FriendlyByteBuf p_178329_, io.netty.channel.ChannelHandlerContext p_130535_) {
++            java.util.function.BiFunction<FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, ? extends net.minecraft.network.protocol.Packet<? super T>> function = this.contextualIdToDeserializer.get(p_178328_);
```
Comment (Matyrobbrt) [inline patches/net/minecraft/network/ConnectionProtocol.java.patch]: See above

File: src/main/java/net/neoforged/neoforge/client/gui/ModMismatchDisconnectedScreen.java [hunk 7]
```diff
@@ -35,53 +35,35 @@
...
-        this.mismatchedModData = modMismatchData.mismatchedModData().entrySet().stream().filter(e -> !e.getValue().equals(NetworkRegistry.ABSENT.version())).collect(Collectors.toMap(Entry::getKey, Entry::getValue));
-        this.allModIds = presentModData.keySet().stream().map(ResourceLocation::getNamespace).distinct().collect(Collectors.toList());
-        this.presentModUrls = ModList.get().getMods().stream().filter(info -> allModIds.contains(info.getModId())).map(info -> Pair.of(info.getModId(), (String) info.getConfig().getConfigElement("displayURL").orElse(""))).collect(Collectors.toMap(Pair::getLeft, Pair::getRight));
+        this.mismatchedChannelData = mismatchedChannelData;
     }
 
     @Override
     protected void init() {
-        this.message = MultiLineLabel.create(this.font, this.reason, this.width - 50);
+        //this.message = MultiLineLabel.create(this.font, this.reason, this.width - 50);
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/client/gui/ModMismatchDisconnectedScreen.java]: If the message is unused, remove it

File: src/main/java/net/neoforged/neoforge/common/extensions/IPacketFlowExtension.java [hunk 8]
```diff
@@ -0,0 +1,43 @@
...
+package net.neoforged.neoforge.common.extensions;
+
+import net.minecraft.network.protocol.PacketFlow;
+import net.neoforged.fml.LogicalSide;
+
+/**
+ * Extension for {@link PacketFlow} to add some utility methods.
+ */
+public interface IPacketFlowExtension {
+
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/common/extensions/IPacketFlowExtension.java:15]: This is an useless extension for enum checks.

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

**Comment by Commoble** [comment]
Is it still possible to e.g. have the server check whether a channel exists on the client, and only attempt to send a packet if the client has that channel?

**Comment by marchermans** [comment]
> Is it still possible to e.g. have the server check whether a channel exists on the client, and only attempt to send a packet if the client has that channel?

Not at the moment, no.
It is also optional for that particular kind of check. The system already does this internally for you.

However, after discussing it, we should at least expose the information somewhere in such a way that if people need functionality that needs to be enabled on paired-only connections, they can do so.

File: src/main/java/net/neoforged/neoforge/common/extensions/IPacketFlowExtension.java (hunk 8 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/common/extensions/IPacketFlowExtension.java:15]: I would argue that this is a useful extension, especially when people work with streams or functional programming.

Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/common/extensions/IPacketFlowExtension.java:15]: `Predicate.isEqual` exists and does not require patches

Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/common/extensions/IPacketFlowExtension.java:15]: After internal discussion, there seems to be little consensus within the maintainer team; as the PR author, I decided to keep this in, as it matches my programming style better.

The isXXXX methods do not expand the patch size or the maintenance overhead.

Comment (sciwhiz12) [reply src/main/java/net/neoforged/neoforge/common/extensions/IPacketFlowExtension.java:15]: I would like to note my protest over this change, as I feel the principle of keeping an API small takes precedence over following the personal programming preferences of a maintainer-author and adding unnecessary methods to our public API surface.

There is no functional difference between `isClientbound()` and the equivalent check `== PacketFlow.CLIENTBOUND` (with the same for `SERVERBOUND`), and functional uses can be replaced with `Predicate.isEqual(PacketFlow.CLIENTBOUND)`.

The only substantial precedents for these kinds of methods exist in classes _outside_ of NeoForge: the `Dist` class (provided by [the MergeTool API](https://github.com/neoforged/MergeTool/blob/main/src/forgeAPI/java/net/neoforged/api/distmarker/Dist.java)) and the `LogicalSide` class (provided by [FancyModLoader](https://github.com/neoforged/FancyModLoader/blob/29b9b43185269582e8596ab68ecba362f988ef04/core/src/main/java/net/neoforged/fml/LogicalSide.java#L41-L55)).[^1] In both cases, these methods exist moreso by way of having existed long before many of us started developing NeoForge (or its predecessor, Minecraft Forge A.K.A. LexForge).

I would extremely hesitate to make precedent the pattern of including such 'helpers' in our API surface, particular for _very simple_ enums whose values are unlikely to ever change and where straight `==` comparisons are ideal. Insofar as this pattern goes, I will make it a point to bring up this discussion anytime this pattern appears in any contribution (by any author) in the future.

(For the record, the 'internal' discussion [was held in the public "Networking Protocol" thread](https://discord.com/channels/313125603924639766/1170668658813575230/1188068046292668437) of the `#brainstorming` forum in the Discord server.)

[^1]: Outside of these two cases, the only other uses of this design pattern -- having equivalent `boolean is<Value>()` methods for enum values which do `this == <VALUE>` -- are in NeoForge's `ConnectionType` and `IFluidHandler.FluidAction`; in the former case, only `isVanilla()` exists without an `isModded()` counterpart, and in the latter case, the `is` prefix is not present for `execute()` and `simulate()`.

File: patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch [hunk 9]
```diff
@@ -1,29 +1,87 @@
...
++        if (this.isModdedConnection) {
++            net.neoforged.neoforge.network.registration.NetworkRegistry.getInstance().onModdedPacketAtClient(this, p_295727_);
++            return;
++        }
++        
 +        this.handleUnknownCustomPayload(p_295727_, p_295411_);
      }
  
 -    private void handleUnknownCustomPayload(CustomPacketPayload p_296412_) {
 +    private void handleUnknownCustomPayload(net.minecraft.network.protocol.common.ClientboundCustomPayloadPacket p_295727_, CustomPacketPayload p_296412_) {
```
Comment (XFactHD) [inline patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch]: This patch is unnecessary now

File: patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch [hunk 10]
```diff
@@ -1,29 +1,87 @@
...
-         this.connection.send(new ServerboundFinishConfigurationPacket());
-+        net.neoforged.neoforge.network.NetworkHooks.handleClientLoginSuccess(this.connection);
+@@ -69,6 +_,13 @@
+     @Override
+     public void handleEnabledFeatures(ClientboundUpdateEnabledFeaturesPacket p_294410_) {
+         this.enabledFeatures = FeatureFlags.REGISTRY.fromNames(p_294410_.features());
++        //Fallback detection layer for vanilla servers
++        if (!this.isModdedConnection) {
++            this.isVanillaConnection = true;
++            if (!net.neoforged.neoforge.network.registration.NetworkRegistry.getInstance().onVanillaNetworkConnectionEstablished(this)) {
```
Comment (XFactHD) [inline patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch]: Unnecessary if and return statements

File: patches/net/minecraft/client/multiplayer/ClientPacketListener.java.patch [hunk 11]
```diff
@@ -65,33 +81,118 @@
...
++                );
++                return;
++            }
++            
 +            this.handleUnknownCustomPayload(p_295727_, p_295851_);
          }
      }
  
 -    private void handleUnknownCustomPayload(CustomPacketPayload p_294389_) {
 +    private void handleUnknownCustomPayload(net.minecraft.network.protocol.common.ClientboundCustomPayloadPacket p_295727_, CustomPacketPayload p_294389_) {
```
Comment (XFactHD) [inline patches/net/minecraft/client/multiplayer/ClientPacketListener.java.patch]: This patch is unnecessary now

File: patches/net/minecraft/client/multiplayer/CommonListenerCookie.java.patch [hunk 12]
```diff
@@ -0,0 +1,16 @@
...
+     WorldSessionTelemetryManager telemetryManager,
+     RegistryAccess.Frozen receivedRegistries,
+     FeatureFlagSet enabledFeatures,
++    boolean isModdedConnection,
+     @Nullable String serverBrand,
+     @Nullable ServerData serverData,
+     @Nullable Screen postDisconnectScreen
+ ) {
++    
++    public CommonListenerCookie(GameProfile localGameProfile, WorldSessionTelemetryManager telemetryManager, RegistryAccess.Frozen receivedRegistries, FeatureFlagSet enabledFeatures, @Nullable String serverBrand, @Nullable ServerData serverData, @Nullable Screen postDisconnectScreen) {
```
Comment (XFactHD) [inline patches/net/minecraft/client/multiplayer/CommonListenerCookie.java.patch:16]: This should probably be deprecated similar to other cases where the original signature is retained for compatibility

File: patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch [hunk 13]
```diff
@@ -1,21 +1,69 @@
 --- a/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java
 +++ b/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java
-@@ -59,14 +_,13 @@
+@@ -29,7 +_,7 @@
  
+ public record ClientboundCustomPayloadPacket(CustomPacketPayload payload) implements Packet<ClientCommonPacketListener> {
+     private static final int MAX_PAYLOAD_SIZE = 1048576;
+-    private static final Map<ResourceLocation, FriendlyByteBuf.Reader<? extends CustomPacketPayload>> KNOWN_TYPES = ImmutableMap.<ResourceLocation, FriendlyByteBuf.Reader<? extends CustomPacketPayload>>builder(
```
Comment (XFactHD) [inline patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch]: This should be an AT instead

File: patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch
Comment (XFactHD) [inline patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch:1]: This entire patch shouldn't be needed anymore, it's existence makes no difference with respect to the compatibility with older versions and the added data is unused in the new implementation.

File: patches/net/minecraft/server/level/ServerEntity.java.patch [hunk 14]
```diff
@@ -12,19 +12,33 @@
...
+-        this.sendPairingData(p_8542_, list::add);
++        List<Packet<? super ClientGamePacketListener>> list = new ArrayList<>();
++        this.sendPairingData(p_8542_, new net.neoforged.neoforge.network.bundle.PacketAndPayloadAcceptor<>(list::add));
          p_8542_.connection.send(new ClientboundBundlePacket(list));
          this.entity.startSeenByPlayer(p_8542_);
 +        net.neoforged.neoforge.event.EventHooks.onStartEntityTracking(this.entity, p_8542_);
      }
  
-     public void sendPairingData(ServerPlayer p_289562_, Consumer<Packet<ClientGamePacketListener>> p_289563_) {
+-    public void sendPairingData(ServerPlayer p_289562_, Consumer<Packet<ClientGamePacketListener>> p_289563_) {
```
Comment (XFactHD) [inline patches/net/minecraft/server/level/ServerEntity.java.patch:32]: Since this is a public method, it may make sense to keep the old signature around and forward it to the new one

File: patches/net/minecraft/server/network/ServerConfigurationPacketListenerImpl.java.patch [hunk 15]
```diff
@@ -0,0 +1,108 @@
...
+             LOGGER.error("Couldn't place player in world", (Throwable)exception);
+@@ -146,8 +_,9 @@
+             }
+         }
+     }
+-
+-    private void finishCurrentTask(ConfigurationTask.Type p_294853_) {
++    
++    @Override
++    public void finishCurrentTask(ConfigurationTask.Type p_294853_) {
```
Comment (XFactHD) [inline patches/net/minecraft/server/network/ServerConfigurationPacketListenerImpl.java.patch]: This should be an AT instead

File: src/main/java/net/neoforged/neoforge/common/TierSortingRegistry.java [hunk 16]
```diff
@@ -256,7 +246,7 @@ protected JsonObject prepare(@NotNull ResourceManager resourceManager, ProfilerF
             @Override
             protected void apply(@NotNull JsonObject data, @NotNull ResourceManager resourceManager, ProfilerFiller p) {
                 try {
-                    if (data.size() > 0) {
+                    if (!data.isEmpty()) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/common/TierSortingRegistry.java]: This should be reverted until we know why it causes recompile to fail in userdev for some people

File: patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch [hunk 17]
```diff
@@ -1,14 +1,86 @@
...
+         this.connection.flushChannel();
+     }
+ 
++    @Override
+     public void send(Packet<?> p_294278_) {
+         this.send(p_294278_, null);
+     }
++    
++    @Override
++    public void send(net.minecraft.network.protocol.common.custom.CustomPacketPayload packetPayload) {
```
Comment (XFactHD) [inline patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch]: This should be a default-implemented method on the extension interface

File: patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch [hunk 18]
```diff
@@ -1,14 +1,86 @@
...
+         boolean flag = !this.suspendFlushingOnServerThread || !this.server.isSameThread();
+ 
+         try {
+@@ -121,6 +_,11 @@
+             throw new ReportedException(crashreport);
+         }
      }
++    
++    @Override
++    public void send(net.minecraft.network.protocol.common.custom.CustomPacketPayload packetPayload, @Nullable PacketSendListener listener) {
```
Comment (XFactHD) [inline patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch]: This should be a default-implemented method on the extension interface

File: patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch [hunk 19]
```diff
@@ -15,3 +21,54 @@
...
+ 
+     public void send(Packet<?> p_295097_) {
++        if (!net.neoforged.neoforge.network.registration.NetworkRegistry.getInstance().canSendPacket(p_295097_, this)) {
++            return;
++        }
++        
+         this.connection.send(p_295097_);
+     }
+ 
++    public void send(CustomPacketPayload payload) {
```
Comment (XFactHD) [inline patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch]: This is already default-implemented on the extension interface

File: patches/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java.patch [hunk 20]
```diff
@@ -1,21 +1,68 @@
 --- a/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java
 +++ b/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java
-@@ -23,14 +_,13 @@
+@@ -11,21 +_,60 @@
  
+ public record ServerboundCustomPayloadPacket(CustomPacketPayload payload) implements Packet<ServerCommonPacketListener> {
+     private static final int MAX_PAYLOAD_SIZE = 32767;
+-    private static final Map<ResourceLocation, FriendlyByteBuf.Reader<? extends CustomPacketPayload>> KNOWN_TYPES = ImmutableMap.<ResourceLocation, FriendlyByteBuf.Reader<? extends CustomPacketPayload>>builder(
```
Comment (XFactHD) [inline patches/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java.patch]: This should be an AT instead

File: src/main/java/net/neoforged/neoforge/common/extensions/IServerConfigurationPacketListenerExtension.java [hunk 21]
```diff
@@ -0,0 +1,23 @@
...
+package net.neoforged.neoforge.common.extensions;
+
+import net.minecraft.network.protocol.configuration.ServerConfigurationPacketListener;
+import net.minecraft.server.network.ConfigurationTask;
+import net.minecraft.server.network.ServerConfigurationPacketListenerImpl;
+
+/**
+ * Extension class for {@link ServerConfigurationPacketListener}
+ */
+public interface IServerConfigurationPacketListenerExtension extends IServerCommonPacketListenerExtension {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/common/extensions/IServerConfigurationPacketListenerExtension.java:15]: This extension is unnecessary. The only method it contains can be exposed with just an AT instead.

File: src/main/java/net/neoforged/neoforge/entity/IEntityWithComplexSpawn.java [hunk 22]
```diff
@@ -8,10 +8,10 @@
 import net.minecraft.network.FriendlyByteBuf;
 
 /**
- * A interface for Entities that need extra information to be communicated
+ * An interface for Entities that need extra information to be communicated
  * between the server and client when they are spawned.
  */
-public interface IEntityAdditionalSpawnData {
+public interface IEntityWithComplexSpawn {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/entity/IEntityWithComplexSpawn.java:14]: I would prefer to keep the original name, I see little to no point in renaming it.

File: src/main/java/net/neoforged/neoforge/network/PacketDistributor.java
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/PacketDistributor.java:1]: Is there any reason for any of these to take the context parameter (i.e. player, dimension, chunk, etc.) as a supplier which is going to be resolved immediately anyway instead of just passing in the resolved values directly? If not, then it would be nice to remove the wrapping in suppliers to make the API a bit cleaner.

File: src/main/java/net/neoforged/neoforge/network/configuration/ICustomConfigurationTask.java [hunk 23]
```diff
@@ -0,0 +1,47 @@
...
+
+    /**
+     * Invoked when it is time for this configuration to run.
+     * 
+     * @param p_294184_ A consumer that accepts a {@link Packet} to send to the client.
+     * @implNote Please do not override this method, it is implemented to wrap the {@link CustomPacketPayload} in a {@link ClientboundCustomPayloadPacket}.
+     */
+    @Override
+    @ApiStatus.Internal
+    default void start(@NotNull Consumer<Packet<?>> p_294184_) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/configuration/ICustomConfigurationTask.java]: Please use a proper parameter name.

File: src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java [hunk 24]
```diff
@@ -0,0 +1,125 @@
...
+
+    public void handle(FrozenRegistrySyncCompletedPayload payload, ConfigurationPayloadContext context) {
+        if (!this.toSynchronize.isEmpty()) {
+            context.packetHandler().disconnect(Component.translatable("neoforge.registries.sync.failed", this.toSynchronize.stream().map(Object::toString).collect(Collectors.joining(", "))));
+            return;
+        }
+
+        context.workHandler().submitAsync(() -> {
+            //This method normally returns missing entries, but we just accept what the server send us and ignore the rest.
+            RegistryManager.applySnapshot(synchronizedRegistries, false, false);
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java]: The missing entries returned by this method are ones which the server knows about but the client doesn't. These must not be ignored and instead should cause a disconnect. Ignoring these will lead to desync scenarios like ghost blocks.

File: src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java [hunk 25]
```diff
@@ -0,0 +1,54 @@
...
+import net.minecraft.world.entity.player.Player;
+
+/**
+ * Defines a phase-less payload context that is passed to a handler for a payload that arrives during the connection.
+ */
+public interface IPayloadContext {
+    /**
+     * {@return a handler that can be used to reply to the payload.}
+     */
+    IReplyHandler handler();
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java]: This should be called `replyHandler` as `handler` does not bring across what this actually is

File: src/main/java/net/neoforged/neoforge/network/payload/FrozenRegistrySyncCompletedPayload.java [hunk 26]
```diff
@@ -0,0 +1,32 @@
...
+@ApiStatus.Internal
+public record FrozenRegistrySyncCompletedPayload() implements CustomPacketPayload {
+    public static final ResourceLocation ID = new ResourceLocation(NeoForgeVersion.MOD_ID, "frozen_registry_sync_completed");
+
+    public FrozenRegistrySyncCompletedPayload(FriendlyByteBuf buf) {
+        this();
+    }
+
+    @Override
+    public void write(FriendlyByteBuf p_294947_) {}
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/payload/FrozenRegistrySyncCompletedPayload.java]: Use a proper parameter name

File: src/main/java/net/neoforged/neoforge/network/payload/ModdedNetworkPayload.java [hunk 27]
```diff
@@ -0,0 +1,42 @@
...
+
+    public static final ResourceLocation ID = new ResourceLocation("network");
+    public static final FriendlyByteBuf.Reader<? extends CustomPacketPayload> READER = ModdedNetworkPayload::new;
+
+    public ModdedNetworkPayload(FriendlyByteBuf buf) {
+        this(buf.readCollection(HashSet::new, ModdedNetworkComponent::new), buf.readCollection(HashSet::new, ModdedNetworkComponent::new));
+    }
+
+    @Override
+    public void write(FriendlyByteBuf p_294947_) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/payload/ModdedNetworkPayload.java]: Use a proper parameter name

File: src/main/java/net/neoforged/neoforge/network/payload/ModdedNetworkQueryPayload.java [hunk 28]
```diff
@@ -0,0 +1,46 @@
...
+    public ModdedNetworkQueryPayload() {
+        this(Set.of(), Set.of());
+    }
+
+    public ModdedNetworkQueryPayload(FriendlyByteBuf byteBuf) {
+        this(byteBuf.readCollection(HashSet::new, ModdedNetworkQueryComponent::new), byteBuf.readCollection(HashSet::new, ModdedNetworkQueryComponent::new));
+    }
+
+    @Override
+    public void write(FriendlyByteBuf p_294947_) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/payload/ModdedNetworkQueryPayload.java]: Use a proper parameter name

File: src/main/java/net/neoforged/neoforge/network/payload/ModdedNetworkSetupFailedPayload.java [hunk 29]
```diff
@@ -0,0 +1,39 @@
...
+public record ModdedNetworkSetupFailedPayload(Map<ResourceLocation, Component> failureReasons) implements CustomPacketPayload {
+    public static final ResourceLocation ID = new ResourceLocation(NeoForgeVersion.MOD_ID, "modded_network_setup_failed");
+    public static final FriendlyByteBuf.Reader<? extends CustomPacketPayload> READER = ModdedNetworkSetupFailedPayload::new;
+
+    public ModdedNetworkSetupFailedPayload(FriendlyByteBuf buf) {
+        this(buf.readMap(FriendlyByteBuf::readResourceLocation, FriendlyByteBuf::readComponent));
+    }
+
+    @Override
+    public void write(FriendlyByteBuf p_294947_) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/payload/ModdedNetworkSetupFailedPayload.java]: Use a proper parameter name

File: src/main/java/net/neoforged/neoforge/network/payload/SplitPacketPayload.java [hunk 30]
```diff
@@ -0,0 +1,40 @@
...
+@ApiStatus.Internal
+public record SplitPacketPayload(byte[] payload) implements CustomPacketPayload {
+    public static final ResourceLocation ID = new ResourceLocation(NeoForgeVersion.MOD_ID, "split");
+
+    public SplitPacketPayload(FriendlyByteBuf buf) {
+        this(buf.readBytes(buf.readVarInt()).array());
+    }
+
+    @Override
+    public void write(FriendlyByteBuf p_294947_) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/payload/SplitPacketPayload.java]: Use a proper parameter name

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java [hunk 31]
```diff
@@ -0,0 +1,189 @@
...
+     * Registers a new payload type for the play phase.
+     *
+     * @param <T>     The type of the payload.
+     * @param id      The id of the payload.
+     * @param reader  The reader for the payload.
+     * @param handler The handler for the payload.
+     * @return The registrar.
+     * @implNote This method will capture all internal errors and wrap them in a {@link RegistrationFailedException}.
+     */
+    <T extends CustomPacketPayload> IPayloadRegistrar play(ResourceLocation id, FriendlyByteBuf.Reader<T> reader, IPlayPayloadHandler<T> handler);
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java:92]: I am still not convinced that the registration of a single handler for both sides is a good idea. Neo itself currently has a single use case for this, that being the packet splitter which is a very special case, and everything else that receives the packet on both sides has a dedicated handler per side. It might be better to remove this way of registration and just force the very few use cases of identical handlers to specify them twice.

**Review by XFactHD — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java [hunk 32]
```diff
@@ -0,0 +1,125 @@
...
+                            buf.release();
+                        }
+                    }
+                });
+    }
+
+    public void handle(AdvancedOpenScreenPayload msg, PlayPayloadContext context) {
+        final FriendlyByteBuf buf = new FriendlyByteBuf(Unpooled.wrappedBuffer(msg.additionalData()));
+        try {
+            createMenuScreen(msg.name(), msg.menuType(), msg.windowId(), buf);
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java]: Screen initialization must be enqueued on the main thread

File: src/main/java/net/neoforged/neoforge/network/PacketDistributor.java [hunk 33]
```diff
@@ -167,18 +157,26 @@ public void send(Packet<?> packet) {
             packetConsumer.accept(packet);
         }
 
-        public PlayNetworkDirection getDirection() {
-            return distributor.direction;
+        public void send(CustomPacketPayload payload) {
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/PacketDistributor.java]: Is it possible to make this vararg and if there is one element just send the packet and otherwise behave as if it was `IServerGamePacketListenerExtension#sendBundled`? That way the packet distributors don't have to be reimplemented for sending a bundled packet.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 34]
```diff
@@ -0,0 +1,955 @@
...
+
+            registration.handle(
+                    packet.payload(),
+                    new PlayPayloadContext(
+                            playPacketListener::send,
+                            new ClientPacketHandler(playPacketListener),
+                            new EventLoopSynchronizedWorkHandler<>(playPacketListener.getMainThreadEventLoop(), packet.payload()),
+                            PacketFlow.CLIENTBOUND,
+                            listener.getConnection().channel().pipeline().lastContext(),
+                            Optional.empty()));
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: Could we add an extension to `ClientGamePacketListener` that adds a `@Nullable Player getPlayer()` and implement that in `ClientCommonPacketListenerImpl` to return `this.minecraft.player` as it has a minecraft context?

**Review by pupnewfster — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/common/extensions/IPlayerExtension.java [hunk 35]
```diff
@@ -92,4 +98,33 @@ default boolean isCloseEnough(Entity entity, double dist) {
...
+     * Refer to {@link MenuType#create(IContainerFactory)} for how to provide a function to consume
+     * these GUI requests on the client.
+     * <p>
+     * The maximum size for #extraDataWriter is 32600 bytes.
+     *
+     * @param menuProvider    A supplier of container properties including the registry name of the container
+     * @param extraDataWriter Consumer to write any additional data the GUI needs
+     * @return The window ID of the opened GUI, or empty if the GUI could not be opened
+     */
+    default OptionalInt openMenu(MenuProvider menuProvider, Consumer<FriendlyByteBuf> extraDataWriter) {
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/common/extensions/IPlayerExtension.java:127]: This and the other `openMenu` overload should have the `@Nullable` annotation on the `MenuProvider` as the only implementation has it so we may as well make it more explicitly clear that modders can pass a null provider to it.

File: patches/net/minecraft/network/protocol/status/ServerStatus.java.patch [hunk 36]
```diff
@@ -16,7 +16,7 @@
                      ServerStatus.Favicon.CODEC.optionalFieldOf("favicon").forGetter(ServerStatus::favicon),
 -                    Codec.BOOL.optionalFieldOf("enforcesSecureChat", Boolean.valueOf(false)).forGetter(ServerStatus::enforcesSecureChat)
 +                    Codec.BOOL.optionalFieldOf("enforcesSecureChat", Boolean.valueOf(false)).forGetter(ServerStatus::enforcesSecureChat),
-+                    net.neoforged.neoforge.network.ServerStatusPing.CODEC.optionalFieldOf("neoForgeData").forGetter(ServerStatus::neoForgeData)
++                    Codec.BOOL.optionalFieldOf("isModded", Boolean.valueOf(false)).forGetter(ServerStatus::isModded)
```
Comment (pupnewfster) [inline patches/net/minecraft/network/protocol/status/ServerStatus.java.patch]: Why doesn't this just use `Boolean.FALSE` given we know it is always false rather than using the one that is more for use when unsure which is needed?

File: tests/src/main/java/net/neoforged/neoforge/oldtest/misc/ContainerTypeTest.java [hunk 37]
```diff
@@ -93,7 +92,9 @@ private void onRightClick(PlayerInteractEvent.RightClickBlock event) {
         if (!event.getLevel().isClientSide && event.getHand() == InteractionHand.MAIN_HAND) {
             if (event.getLevel().getBlockState(event.getPos()).getBlock() == Blocks.SPONGE) {
                 String text = "Hello World!";
-                NetworkHooks.openScreen((ServerPlayer) event.getEntity(), new MenuProvider() {
+
+                final ServerPlayer player = (ServerPlayer) event.getEntity();
```
Comment (pupnewfster) [inline tests/src/main/java/net/neoforged/neoforge/oldtest/misc/ContainerTypeTest.java]: This cast to `ServerPlayer` is unnecessary as the method exists on `Player`, and then will actually function when the player is a `ServerPlayer`

File: tests/src/main/java/net/neoforged/neoforge/oldtest/recipebook/RecipeBookExtensionTest.java [hunk 38]
```diff
@@ -61,8 +60,10 @@ public RecipeBookExtensionTest(IEventBus modBus) {
     private void onRightClick(PlayerInteractEvent.RightClickBlock event) {
         if (event.getLevel().isClientSide)
             return;
-        if (event.getLevel().getBlockState(event.getPos()).getBlock() == Blocks.GRASS_BLOCK)
-            NetworkHooks.openScreen((ServerPlayer) event.getEntity(), new SimpleMenuProvider((id, inv, p) -> new RecipeBookTestMenu(id, inv, ContainerLevelAccess.create(event.getLevel(), event.getPos())), Component.literal("Test")));
+        if (event.getLevel().getBlockState(event.getPos()).getBlock() == Blocks.GRASS_BLOCK) {
+            final ServerPlayer player = (ServerPlayer) event.getEntity();
```
Comment (pupnewfster) [inline tests/src/main/java/net/neoforged/neoforge/oldtest/recipebook/RecipeBookExtensionTest.java]: This cast to `ServerPlayer` is unnecessary as the method exists on `Player`, and then will actually function when the player is a `ServerPlayer`

File: testframework/src/main/java/net/neoforged/testframework/gametest/GameTestPlayer.java [hunk 39]
```diff
@@ -34,6 +39,14 @@ public GameTestPlayer(MinecraftServer server, ServerLevel level, GameProfile pro
         this.helper = helper;
     }
 
+    @Override
+    public void moveTo(double p_9171_, double p_9172_, double p_9173_) {
+        super.moveTo(p_9171_, p_9172_, p_9173_);
```
Comment (pupnewfster) [inline testframework/src/main/java/net/neoforged/testframework/gametest/GameTestPlayer.java]: Non-srg names please to make it easier to read, given even if we get parchment setup at some point I doubt it will affect non-mc code

File: src/main/java/net/neoforged/neoforge/network/bundle/BundlePacketUtils.java [hunk 40]
```diff
@@ -0,0 +1,37 @@
...
+
+    private BundlePacketUtils() {
+        throw new IllegalStateException("Tried to create utility class!");
+    }
+
+    public static <T extends PacketListener> Iterable<Packet<? super T>> flatten(Iterable<Packet<? super T>> packets) {
+        final List<Packet<? super T>> result = new ArrayList<>();
+        packets.forEach(packet -> {
+            if (packet instanceof BundlePacket<? super T> innerBundle) {
+                result.addAll(Lists.newArrayList(flatten(innerBundle.subPackets())));
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/bundle/BundlePacketUtils.java]: The intermediary ArrayList creation feels kind of weird to be honest (especially when implementation detail wise it is already a list). Can we maybe just make the flatten method return a List instead?

File: patches/net/minecraft/server/level/ServerEntity.java.patch (hunk 14 above)
Comment (marchermans) [reply patches/net/minecraft/server/level/ServerEntity.java.patch:32]: Is not possible due to generic coercion.

File: src/main/java/net/neoforged/neoforge/common/extensions/IServerConfigurationPacketListenerExtension.java (hunk 21 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/common/extensions/IServerConfigurationPacketListenerExtension.java:15]: Needs to be part of the extended interface signature.

File: src/main/java/net/neoforged/neoforge/entity/IEntityWithComplexSpawn.java (hunk 22 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/entity/IEntityWithComplexSpawn.java:14]: This was renamed to make people aware of the new mechanics.

File: src/main/java/net/neoforged/neoforge/network/payload/AdvancedOpenScreenPayload.java [hunk 41]
```diff
@@ -0,0 +1,67 @@
...
+
+    private static byte[] writeCustomData(Consumer<FriendlyByteBuf> dataWriter) {
+        final FriendlyByteBuf buf = new FriendlyByteBuf(Unpooled.buffer());
+        try {
+            dataWriter.accept(buf);
+            return buf.array();
+        } finally {
+            buf.release();
+        }
+    }
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/payload/AdvancedOpenScreenPayload.java]: This helper is mostly duplicated between here and the `AdvancedAddEntityPayload`; can we extract it to a util method so we don't need it in so many of them? If we want to not expose it to modders we could just have it be package private as both of those payloads of ours are in the same package. It would remove the need for it here, and allow using it instead of duplicating the logic as part of the entity payload's `writeCustomData` method

File: patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch [hunk 42]
```diff
@@ -15,3 +21,54 @@
...
++        return connection;
++    }
++    
++    @Override
++    public net.minecraft.util.thread.ReentrantBlockableEventLoop<?> getMainThreadEventLoop() {
++        return minecraft;
++    }
++    
++    @Override
++    public boolean isVanillaConnection() {
```
Comment (pupnewfster) [inline patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch]: Can this method (and maybe the `isConnected` method be moved to being defaulted methods in the extension interface?

File: patches/net/minecraft/server/level/ServerPlayer.java.patch [hunk 43]
```diff
@@ -91,8 +91,31 @@
...
+         } else {
+@@ -999,10 +_,16 @@
+ 
+                 return OptionalInt.empty();
+             } else {
+-                this.connection
+-                    .send(new ClientboundOpenScreenPacket(abstractcontainermenu.containerId, abstractcontainermenu.getType(), p_9033_.getDisplayName()));
++                if (extraDataWriter == null) {
++                    this.connection
++                        .send(new ClientboundOpenScreenPacket(abstractcontainermenu.containerId, abstractcontainermenu.getType(), p_9033_.getDisplayName()));
```
Comment (pupnewfster) [inline patches/net/minecraft/server/level/ServerPlayer.java.patch]: Remove the added indentation of these two lines so that the hunk is only addition rather than also removal which will make the patch itself easier to read

File: patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch [hunk 44]
```diff
@@ -1,14 +1,86 @@
...
++    public Connection getConnection() {
++        return connection;
++    }
++    @Override
++    public net.minecraft.util.thread.ReentrantBlockableEventLoop<?> getMainThreadEventLoop() {
++        return server;
++    }
++    
++    @Override
++    public boolean isVanillaConnection() {
```
Comment (pupnewfster) [inline patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch]: Can this method (and maybe the `isConnected` method be moved to being defaulted methods in the extension interface?

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java (hunk 31 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java:92]: Like we talked about in discord voice chat. Both of our existing solutions offer this as an option.

File: patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch [hunk 45]
```diff
@@ -122,3 +138,29 @@
                          }
      
                          @Override
+@@ -1745,7 +_,7 @@
+             throw new IllegalStateException("Client acknowledged config, but none was requested");
+         } else {
+             this.connection
+-                .setListener(new ServerConfigurationPacketListenerImpl(this.server, this.connection, this.createCookie(this.player.clientInformation())));
++                    .setListener(new ServerConfigurationPacketListenerImpl(this.server, this.connection, this.createCookie(this.player.clientInformation(), this.isModdedConnection)));
```
Comment (pupnewfster) [inline patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: Indentation change should be removed so it is easier to compare the lines of the patch visually and see what changed

File: patches/net/minecraft/network/protocol/BundlerInfo.java.patch [hunk 46]
```diff
@@ -0,0 +1,66 @@
...
+@@ -38,11 +_,31 @@
+                 }
+             }
+ 
++            @Override
++            public void unbundlePacket(io.netty.channel.ChannelHandlerContext context, Packet<?> bundlePacket, Consumer<Packet<?>> packetSender) {
++                if (bundlePacket.getClass() == p_265438_) {
++                    P p = (P)bundlePacket;
++                    java.util.List<Packet<?>> packets = net.neoforged.neoforge.network.registration.NetworkRegistry.getInstance().filterGameBundlePackets(context, p.subPackets());
++                    if (packets.size() == 0) {
```
Comment (pupnewfster) [inline patches/net/minecraft/network/protocol/BundlerInfo.java.patch]: Is the reason this uses `packets.size() == 0` to better mirror the `size == 1` check below? If not this might as well just use `isEmpty()`

File: patches/net/minecraft/network/protocol/BundlerInfo.java.patch [hunk 47]
```diff
@@ -0,0 +1,66 @@
...
++
++    /**
++     * Writes a bundle packet to the network connection.
++     *
++     * @param context The network context.
++     * @param bundlePacket The bundle packet to write.
++     * @param packetSender The packet sender.
++     * @implNote This implementation should filter out packets which are not sendable on the current context, however to preserve compatibility the default implementation does not do this.
++     */
++    default void unbundlePacket(io.netty.channel.ChannelHandlerContext context, Packet<?> bundlePacket, Consumer<Packet<?>> packetSender) { unbundlePacket(bundlePacket, packetSender); }
```
Comment (pupnewfster) [inline patches/net/minecraft/network/protocol/BundlerInfo.java.patch]: Given it is still a single hunk can this have the `unbundlePacket` redirect call happen on a new line so it is a bit easier to read the impl of this defaulted method that is being added?

Also and I don't feel strongly one way or the other about if we do it, but in general method overloads have the extra parameters be at the end rather than added in the middle or in front of the other parameters, so should we add the `ChannelHandlerContext` as the final parameter instead of as the first?

File: src/main/java/net/neoforged/neoforge/network/PacketDistributor.java (hunk 33 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/PacketDistributor.java]: Sadly no, due to the way PacketDistributor is currently structured this is not easy. It is simply only intended to send one payload/packet at a time.

Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/PacketDistributor.java]: Statement was mistaken :dagger: 

I implemented it now as follows:
- If client bound and with more then 1 packet, create bundle.
- If client bound and one packet, send one packet
- If server bound send packets individually without bundle.

File: patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch [hunk 48]
```diff
@@ -37,13 +37,17 @@
...
      public ConnectionProtocol nextProtocol() {
          return this.intention.protocol();
 +    }
 +
 +    public String getFMLVersion() {
 +        return this.fmlVersion;
++    }
++    
++    private static String getFMLVersion(final String ip) {
++        return ip.contains("\0") ? java.util.Objects.equals(ip.split("\0")[1], net.neoforged.neoforge.internal.versions.neoforge.NeoForgeVersion.getSpec()) ? net.neoforged.neoforge.internal.versions.neoforge.NeoForgeVersion.getSpec() : ip.split("\0")[1] : "NONE";
```
Comment (pupnewfster) [inline patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch]: I feel like we had a discussion about this at some point... and there being some doubt as to whether it potentially uses object equality checks, but given I don't fully remember I am going to bring it up again...

if `ip.split("\0")[1]` is equal to `NeoForgeVersion.getSpec()` then two bits of the ternary are equal and this entire return statement could be simplified to `return ip.contains("\0") ? ip.split("\0")[1] : "NONE";`

File: src/main/java/net/neoforged/neoforge/network/negotiation/NetworkComponentNegotiator.java [hunk 49]
```diff
@@ -0,0 +1,182 @@
...
+    public static NegotiationResult negotiate(List<NegotiableNetworkComponent> server, List<NegotiableNetworkComponent> client) {
+        //Ensure the inputs are modifiable
+        server = new ArrayList<>(server);
+        client = new ArrayList<>(client);
+
+        List<NegotiableNetworkComponent> finalServer = server;
+        final List<NegotiableNetworkComponent> disabledOptionalOnClient = client.stream()
+                .filter(NegotiableNetworkComponent::optional)
+                .filter(c -> finalServer.stream().noneMatch(c2 -> c2.id().equals(c.id())))
+                .toList();
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/negotiation/NetworkComponentNegotiator.java]: Could this be moved into a private helper method to calculate the `disabledOptional`? That way there isn't the duplication between calculating the ones for the client and the ones for the server, and on top of that because the lists would be passed as parameters to the method they wouldn't be getting modified and then we don't need the `finalServer` and `finalClient` variables which should hopefully improve the overall readability of this method.

File: src/main/java/net/neoforged/neoforge/network/negotiation/NetworkComponentNegotiator.java [hunk 50]
```diff
@@ -0,0 +1,182 @@
...
+
+        if (!server.isEmpty()) {
+            final Map<ResourceLocation, Component> failureReasons = Maps.newHashMap();
+            server.forEach(c -> failureReasons.put(c.id(), Component.translatable("neoforge.network.negotiation.failure.missing.server.client")));
+            return new NegotiationResult(List.of(), false, failureReasons);
+        }
+
+        final List<NegotiatedNetworkComponent> result = Lists.newArrayList();
+        final Map<ResourceLocation, Component> failureReasons = Maps.newHashMap();
+        for (Table.Cell<ResourceLocation, NegotiableNetworkComponent, NegotiableNetworkComponent> resourceLocationNegotiableNetworkComponentNegotiableNetworkComponentCell : matches.cellSet()) {
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/negotiation/NetworkComponentNegotiator.java]: Can this variable have a cleaner/shorter name? For example `match`?

File: src/main/java/net/neoforged/neoforge/network/negotiation/NetworkComponentNegotiator.java [hunk 51]
```diff
@@ -0,0 +1,182 @@
...
+            }
+
+            //We can take the servers version here. Either both sides have the same version, or both sides have no version.
+            result.add(new NegotiatedNetworkComponent(serverComponent.id(), serverComponent.version()));
+        }
+
+        if (!failureReasons.isEmpty()) {
+            result.clear();
+        }
+        return new NegotiationResult(result, failureReasons.isEmpty(), failureReasons);
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/negotiation/NetworkComponentNegotiator.java]: Instead of explicitly clearing the result do we potentially want this to be something like:
```java
if (failureReasons.isEmpty()) {
    return new NegotiationResult(result, true, failureReasons);
}
return new NegotiationResult(List.of(), false, failureReasons);
```

File: src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java [hunk 52]
```diff
@@ -0,0 +1,125 @@
...
+    public void handle(ConfigFilePayload payload, ConfigurationPayloadContext context) {
+        ConfigSync.INSTANCE.receiveSyncedConfig(payload.contents(), payload.fileName());
+    }
+
+    public void handle(TierSortingRegistryPayload payload, ConfigurationPayloadContext context) {
+        TierSortingRegistry.handleSync(payload, context);
+    }
+
+    public void handle(AdvancedAddEntityPayload advancedAddEntityPayload, PlayPayloadContext context) {
+        context.workHandler().submitAsync(
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java:99]: Do we want this to be execute or add some other error message like we are doing for handling registry freezing rather than this kind of just swallowing it?

File: src/main/java/net/neoforged/neoforge/network/filters/VanillaPacketSplitter.java [hunk 53]
```diff
@@ -125,34 +122,26 @@ private static void onClientPacket(NetworkEvent.ServerCustomPayloadEvent event)
...
+            Packet<?> packet = protocol.codec(flow).createPacket(packetId, full, channelHandlerContext);
             if (packet == null) {
                 LOGGER.error("Received invalid packet ID {} in neoforge:split", packetId);
             } else {
                 receivedBuffers.clear();
                 full.release();
-                ctx.enqueueWork(() -> genericsFtw(packet, event.getSource().getNetworkManager().getPacketListener()));
+
+                context.workHandler()
+                        .submitAsync(() -> context.packetHandler().handle(packet));
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/filters/VanillaPacketSplitter.java]: Do we want this to be execute or add some other error message rather than this kind of just swallowing it?

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 54]
```diff
@@ -0,0 +1,955 @@
...
+
+    private static final NetworkRegistry INSTANCE = new NetworkRegistry();
+
+    public static NetworkRegistry getInstance() {
+        return INSTANCE;
+    }
+
+    private boolean setup = false;
+    private final Map<ResourceLocation, ConfigurationRegistration<?>> knownConfigurationRegistrations = Maps.newHashMap();
+    private final Map<ResourceLocation, PlayRegistration<?>> knownPlayRegistrations = Maps.newHashMap();
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:95]: Why do these use `Maps.newHashMap()` and other parts of this class use `new HashMap<>()`?

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 55]
```diff
@@ -0,0 +1,955 @@
...
+                    } else if (listener instanceof ClientGamePacketListener clientListener) {
+                        clientListener.getConnection().disconnect(Component.translatable("neoforge.network.invalid_flow"));
+                    } else {
+                        LOGGER.error("Received a modded custom payload packet {} that is not supposed to be send to the server. Disconnecting client, but the listener is not a game listener. This should not happen.", channel.id());
+                        throw new IllegalStateException("A client send a packet with an unknown or not accepted channel, while negotiation succeeded. Somebody changed the channels known to NeoForge!");
+                    }
+                }
+            }
+
+            return registration;
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: Can this block of duplicate code that is the say for if it is play or is configuration be merged somehow? Basically the unique parts of these two branches of the if statement are getting the:
- `NetworkChannel channel`
- `registration`

Granted we would need another internal interface to handle some of the hierarchy stuff between the two (such as for returning flow etc), but I think it might be worth it.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 56]
```diff
@@ -0,0 +1,955 @@
...
+        if (payloadSetup == null) {
+            LOGGER.warn("Received a modded custom payload packet from a client that has not negotiated with the server. Disconnecting client.");
+            listener.disconnect(Component.translatable("multiplayer.disconnect.incompatible", "NeoForge %s".formatted(NeoForgeVersion.getVersion())));
+            return;
+        }
+
+        if (listener instanceof ServerConfigurationPacketListener configurationPacketListener) {
+            //Get the configuration channel for the packet.
+            final NetworkChannel channel = payloadSetup.configuration().get(packet.payload().id());
+            ;
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: Remove this random semicolon

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 57]
```diff
@@ -0,0 +1,955 @@
...
+                            new ServerPacketHandler(configurationPacketListener),
+                            configurationPacketListener::finishCurrentTask,
+                            new EventLoopSynchronizedWorkHandler<>(configurationPacketListener.getMainThreadEventLoop(), packet.payload()),
+                            PacketFlow.SERVERBOUND,
+                            listener.getConnection().channel().pipeline().lastContext(),
+                            Optional.empty()));
+        } else if (listener instanceof ServerGamePacketListener playPacketListener) {
+            //Get the configuration channel for the packet.
+            final NetworkChannel channel = payloadSetup.play().get(packet.payload().id());
+            ;
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: Remove this random semicolon

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 58]
```diff
@@ -0,0 +1,955 @@
...
+        if (payloadSetup == null) {
+            LOGGER.warn("Received a modded custom payload packet from a server that has not negotiated with the client. Disconnecting server.");
+            listener.getConnection().disconnect(Component.translatable("multiplayer.disconnect.incompatible", "NeoForge %s".formatted(NeoForgeVersion.getVersion())));
+            return;
+        }
+
+        if (listener instanceof ClientConfigurationPacketListener configurationPacketListener) {
+            //Get the configuration channel for the packet.
+            final NetworkChannel channel = payloadSetup.configuration().get(packet.payload().id());
+            ;
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: Remove this random semicolon

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 59]
```diff
@@ -0,0 +1,955 @@
...
+     * @param play          The play channels that the client has available.
+     */
+    public void onModdedConnectionDetectedAtServer(ServerConfigurationPacketListener sender, Set<ModdedNetworkQueryComponent> configuration, Set<ModdedNetworkQueryComponent> play) {
+        final NegotiationResult configurationNegotiationResult = NetworkComponentNegotiator.negotiate(
+                knownConfigurationRegistrations.entrySet().stream()
+                        .map(entry -> new NegotiableNetworkComponent(entry.getKey(), entry.getValue().version(), entry.getValue().flow(), entry.getValue().optional()))
+                        .toList(),
+                configuration.stream()
+                        .map(entry -> new NegotiableNetworkComponent(entry.id(), entry.version(), entry.flow(), entry.optional()))
+                        .toList());
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:452]: Similar to the code deduplication in my other comment can we deduplicate the code between this and the play negotiation result? As the main thing would be adding a helper to call `NetworkComponentNegotiator#negotiate` with knownRegistrations and then the set of modded components

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 60]
```diff
@@ -0,0 +1,959 @@
...
+        sender.getConnection().channel().attr(ATTRIBUTE_FLOW).set(PacketFlow.SERVERBOUND);
+        sender.getConnection().channel().attr(ATTRIBUTE_PAYLOAD_SETUP).set(NetworkPayloadSetup.emptyModded());
+
+        //Negotiation failed. Disconnect the client.
+        if (!configurationNegotiationResult.success()) {
+            if (!configurationNegotiationResult.failureReasons().isEmpty()) {
+                sender.send(new ModdedNetworkSetupFailedPayload(configurationNegotiationResult.failureReasons()));
+            }
+
+            sender.disconnect(Component.translatable("multiplayer.disconnect.incompatible", "NeoForge %s".formatted(NeoForgeVersion.getVersion())));
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:464]: Is there meant to be a return statement after this line so that it doesn't check the negotiation of play? Or is it meant to potentially have multiple `sender.disconnect` calls?

File: src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java [hunk 61]
```diff
@@ -0,0 +1,65 @@
...
+     */
+    Optional<Player> player();
+
+    /**
+     * {@return the level acts within this context.}
+     *
+     * @return This {@link Optional} will be filled with the current client side level if the payload was sent by the server, the server will only populate this field if it is not configuring the client.
+     */
+    default Optional<Level> level() {
+        return player().map(Entity::level);
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java:63]: Is there any cases where client side we may have no player but have a level set on Minecraft? If so we may want to override this for those, otherwise it doesn't matter. (I am not sure offhand if there are any cases where that is the case)

File: src/main/java/net/neoforged/neoforge/network/PacketDistributor.java [hunk 62]
```diff
@@ -5,85 +5,84 @@
...
 /**
  * Means to distribute packets in various ways
- *
- * @see SimpleChannel#send(PacketTarget, Object)
- *
- * @param <T>
  */
 public class PacketDistributor<T> {
     /**
      * Send to the player specified in the Supplier
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/PacketDistributor.java]: This javadoc needs to be updated as it no longer is in a supplier (as well as the javadocs for the other distributors)

**Review by pupnewfster — CHANGES_REQUESTED** [review]

File: patches/net/minecraft/network/protocol/status/ServerStatus.java.patch (hunk 36 above)
Comment (marchermans) [reply patches/net/minecraft/network/protocol/status/ServerStatus.java.patch]: Partially because the line above it does the same.
But I applied the suggestion.

File: patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch (hunk 42 above)
Comment (marchermans) [reply patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch]: Done

File: patches/net/minecraft/server/level/ServerPlayer.java.patch (hunk 43 above)
Comment (marchermans) [reply patches/net/minecraft/server/level/ServerPlayer.java.patch]: I personally feel like that the patch is easier to read in the current state.

Do you insist on shrinking it 2 lines.

Comment (pupnewfster) [reply patches/net/minecraft/server/level/ServerPlayer.java.patch]: I feel like it makes it easier to tell what is still the same as vanilla in case vanilla makes changes. You can leave it as is for now and leave this unresolved and see what other maintainers think on this comment, and then we can decide what to do and resolve it from there.

File: patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch (hunk 48 above)
Comment (marchermans) [reply patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch]: After @XFactHD checked: This can be removed entirely

File: patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch [hunk 63]
```diff
@@ -1,6 +1,12 @@
 --- a/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java
 +++ b/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java
-@@ -101,12 +_,12 @@
+@@ -96,17 +_,17 @@
+     public void handleCustomPayload(ClientboundCustomPayloadPacket p_295727_) {
+         CustomPacketPayload custompacketpayload = p_295727_.payload();
+         if (!(custompacketpayload instanceof DiscardedPayload)) {
+-            PacketUtils.ensureRunningOnSameThread(p_295727_, this, this.minecraft);
+             if (custompacketpayload instanceof BrandPayload brandpayload) {
++                PacketUtils.ensureRunningOnSameThread(p_295727_, this, this.minecraft); //Neo: We move this here to ensure that only vanilla packets are handled on the main thread.
```
Comment (Shadows-of-Fire) [inline patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch:9]: Why bother with this?  Is it desirable to handle things off-thread?  It would be better to just undo this patch and maintain Mojang's enforcement that all custom payloads are on-thread.

File: src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java (hunk 52 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java:99]: Add a disconnect on failure to process.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 54 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:95]: Personal preference.
I tend to do that over calling a constructor because it is better unit-testable in the end.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 55 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: Probably in some way, but it would become pretty ugly pretty quickly.
Unless somebody has a proposal, I suggest leaving it like this.

File: patches/net/minecraft/server/level/ServerPlayer.java.patch (hunk 43 above)
Comment (Shadows-of-Fire) [reply patches/net/minecraft/server/level/ServerPlayer.java.patch]: I think realistically it depends how good the fuzzy patcher will be about figuring out if this indent-only hunk has changed.

If it may cause issues there, we should probably remove the indentation change, because we don't want to introduce subtle errors caused by vanilla changing and this patch reverting the change.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 54 above)
Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:95]: We should be consistent, not splice between the guava helper and the ctor.

**Review by Shadows-of-Fire — CHANGES_REQUESTED** [review]
Didn't get through everything but I probably won't have time to do further review until mid-jan and I honestly don't anticipate this is still open by then

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 54 above)
Comment (Technici4n) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:95]: Note that the guava method is effectively deprecated, and should not be used in new code:
image

File: patches/net/minecraft/server/level/ServerPlayer.java.patch [hunk 64]
```diff
@@ -91,8 +91,31 @@
...
-                     .send(new ClientboundOpenScreenPacket(abstractcontainermenu.containerId, abstractcontainermenu.getType(), p_9033_.getDisplayName()));
+@@ -983,6 +_,11 @@
+ 
+     @Override
+     public OptionalInt openMenu(@Nullable MenuProvider p_9033_) {
++        return openMenu(p_9033_, (java.util.function.Consumer<net.minecraft.network.FriendlyByteBuf>) null);
++    }
++
++    @Override
++    public OptionalInt openMenu(@Nullable MenuProvider p_9033_, @Nullable java.util.function.Consumer<net.minecraft.network.FriendlyByteBuf> extraDataWriter) {
```
Comment (Technici4n) [inline patches/net/minecraft/server/level/ServerPlayer.java.patch:102]: The vanilla logic will call `closeContainer`. Previously, the NetworkHooks method called `doCloseContainer` directly. There should be an option for modders to skip sending the `ClientboundContainerClosePacket` packet, else menu transitions in GUIs will needlessly re-center the cursor.

**Review by Technici4n — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 59 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:452]: Same as above, I tried merging them, but the code really got ugly and hard to read.

The duplication is annoying but not worse then the merged variant so I will leave it.

File: src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java (hunk 61 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java:63]: No

File: patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch (hunk 63 above)
Comment (marchermans) [reply patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch:9]: Yes, it is desirable to do complex computations off-thread during handling.

Additionally this is something we always had, and I see no functional reason to remove it.

**Review by covers1624 — DISMISSED** [review]

File: patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch [hunk 65]
```diff
@@ -15,3 +21,54 @@
...
++        return connection;
++    }
++    
++    @Override
++    public net.minecraft.util.thread.ReentrantBlockableEventLoop<?> getMainThreadEventLoop() {
++        return minecraft;
++    }
++    
++    @Override
++    public ClientCommonPacketListener self() {
```
Comment (pupnewfster) [inline patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch]: Why is this done here rather than how we do other extension interfaces of having the `self` method be private and just cast to the expected type?

File: patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch [hunk 66]
```diff
@@ -1,14 +1,80 @@
...
++        return connection;
++    }
++
++    @Override
++    public net.minecraft.util.thread.ReentrantBlockableEventLoop<?> getMainThreadEventLoop() {
++        return server;
++    }
++
++    @Override
++    public ServerCommonPacketListener self() {
```
Comment (pupnewfster) [inline patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch]: Why is this done here rather than how we do other extension interfaces of having the `self` method be private and just cast to the expected type?

File: patches/net/minecraft/client/renderer/block/model/ItemModelGenerator.java.patch [hunk 67]
```diff
@@ -1,16 +1,6 @@
 --- a/net/minecraft/client/renderer/block/model/ItemModelGenerator.java
 +++ b/net/minecraft/client/renderer/block/model/ItemModelGenerator.java
-@@ -32,13 +_,16 @@
- 
-             Material material = p_111672_.getMaterial(s);
-             map.put(s, Either.left(material));
--            SpriteContents spritecontents = p_111671_.apply(material).contents();
```
Comment (pupnewfster) [inline patches/net/minecraft/client/renderer/block/model/ItemModelGenerator.java.patch]: Maybe this is just github being weird but why is this patch being changed? It feels like potentially a messed up merge as it doesn't look like it has anything to do with networking.

File: patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch [hunk 68]
```diff
@@ -122,3 +138,33 @@
...
++        if (!this.isModdedConnection) {
++            super.handleCustomPayload(p_294276_);
++        }
++        
++        net.neoforged.neoforge.network.registration.NetworkRegistry.getInstance().onModdedPacketAtServer(
++                this, p_294276_
++        );
++    }
++
++    public ServerGamePacketListener self() {
```
Comment (pupnewfster) [inline patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: Why is this done here rather than how we do other extension interfaces of having the `self` method be private and just cast to the expected type?

File: src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java [hunk 69]
```diff
@@ -0,0 +1,140 @@
...
+            try {
+                createMenuScreen(msg.name(), msg.menuType(), msg.windowId(), buf);
+            } finally {
+                buf.release();
+            }
+        })
+                .exceptionally(e -> {
+                    context.packetHandler().disconnect(Component.translatable("neoforge.advanced_open_screen.failed", e.getMessage()));
+                    return null;
+                });
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java]: Weird indentation going on here

**Review by pupnewfster — CHANGES_REQUESTED** [review]

File: patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch (hunk 65 above)
Comment (marchermans) [reply patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch]: Because the self with cast in interfaces causes a massive overhead because the compiler injects multiple instance of checks which can not be inlined or improved.

File: patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch (hunk 66 above)
Comment (marchermans) [reply patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch]: See other

File: patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch (hunk 68 above)
Comment (marchermans) [reply patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch]: Because here ther eis a method conflict and its needs to be overriden.

File: patches/net/minecraft/client/multiplayer/CommonListenerCookie.java.patch [hunk 70]
```diff
@@ -0,0 +1,20 @@
+--- a/net/minecraft/client/multiplayer/CommonListenerCookie.java
++++ b/net/minecraft/client/multiplayer/CommonListenerCookie.java
+@@ -15,8 +_,17 @@
+     WorldSessionTelemetryManager telemetryManager,
+     RegistryAccess.Frozen receivedRegistries,
+     FeatureFlagSet enabledFeatures,
++    boolean isModdedConnection,
```
Comment (Matyrobbrt) [inline patches/net/minecraft/client/multiplayer/CommonListenerCookie.java.patch]: Why was this put here in the middle? That increases the chances of it being misplaced/rejected when updating since it needs more context. It also means that the patches will add random parameters to constructions in the middle of them which can become very confusing.

File: patches/net/minecraft/network/ConnectionProtocol.java.patch [hunk 71]
```diff
@@ -0,0 +1,182 @@
...
+             return function != null ? function.apply(p_178329_) : null;
++        }
++        
++        /**
++         * Creates a new packet from the given discriminator and buffer.
++         *
++         * @param p_178328_ The discriminator
++         * @param p_178329_ The buffer
++         * @param p_130535_ The channel context
++         * @return The packet, or null if none can be read.
```
Comment (Matyrobbrt) [inline patches/net/minecraft/network/ConnectionProtocol.java.patch]: What does `none` mean? This doc should be more descriptive otherwise it's a "javadoc for the sake of it" which isn't really necessary nor appropriate.

File: patches/net/minecraft/network/protocol/BundlerInfo.java.patch [hunk 72]
```diff
@@ -0,0 +1,68 @@
...
++            @Override
++            public void unbundlePacket(Packet<?> bundlePacket, Consumer<Packet<?>> packetSender, io.netty.channel.ChannelHandlerContext context) {
++                if (bundlePacket.getClass() == p_265438_) {
++                    P p = (P)bundlePacket;
++                    java.util.List<Packet<?>> packets = net.neoforged.neoforge.network.registration.NetworkRegistry.getInstance().filterGameBundlePackets(context, p.subPackets());
++                    if (packets.isEmpty()) {
++                        return;
++                    }
++                    if (packets.size() == 1) {
++                        packetSender.accept(packets.get(0));
```
Comment (Matyrobbrt) [inline patches/net/minecraft/network/protocol/BundlerInfo.java.patch:25]: Why is the delimiter not being accepted when there's only one packet? Also, `packets` is ignored down the line and the packets inside `p.subPackets()` are processed.

File: patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch [hunk 73]
```diff
@@ -1,21 +1,54 @@
 --- a/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java
 +++ b/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java
-@@ -59,14 +_,13 @@
+@@ -53,13 +_,50 @@
+         .put(WorldGenAttemptDebugPayload.ID, WorldGenAttemptDebugPayload::new)
+         .build();
  
++    /**
++     * @deprecated Use {@link #ClientboundCustomPayloadPacket(FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, net.minecraft.network.ConnectionProtocol)} instead, this variant can only read vanilla payloads.
```
Comment (Matyrobbrt) [inline patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch]:
```suggestion
+     * @deprecated Use {@link #ClientboundCustomPayloadPacket(FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, net.minecraft.network.ConnectionProtocol)} instead, as this variant can only read vanilla payloads.
```

File: patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch [hunk 74]
```diff
@@ -1,21 +1,54 @@
...
++     * @param protocol The protocol of the connection
++     * @return The payload
++     */
++    private static CustomPacketPayload readPayload(ResourceLocation p_294367_, FriendlyByteBuf p_294321_, io.netty.channel.ChannelHandlerContext context, net.minecraft.network.ConnectionProtocol protocol) {
++        FriendlyByteBuf.Reader<? extends CustomPacketPayload> reader = net.neoforged.neoforge.network.registration.NetworkRegistry.getInstance().getReader(p_294367_, context, protocol, KNOWN_TYPES);
++        return (CustomPacketPayload)(reader != null ? reader.apply(p_294321_) : readUnknownPayload(p_294367_, p_294321_));
++    }
++
++    /**
++     * @deprecated Use {@link #readPayload(ResourceLocation, FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, net.minecraft.network.ConnectionProtocol)} instead, this variant can only read vanilla payloads.
```
Comment (Matyrobbrt) [inline patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch]:
```suggestion
+     * @deprecated Use {@link #readPayload(ResourceLocation, FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, net.minecraft.network.ConnectionProtocol)} instead, as this variant can only read vanilla payloads.
```

File: patches/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java.patch [hunk 75]
```diff
@@ -1,21 +1,56 @@
...
++        FriendlyByteBuf.Reader<? extends CustomPacketPayload> reader = net.neoforged.neoforge.network.registration.NetworkRegistry.getInstance().getReader(p_294367_, context, protocol, KNOWN_TYPES);
++        return (CustomPacketPayload)(reader != null ? reader.apply(p_294321_) : readUnknownPayload(p_294367_, p_294321_));
++    }
++
++    /**
++     * Reads the payload from the given buffer.
++     * @param p_294367_ The id of the payload
++     * @param p_294321_ The buffer to read from
++     * @return The payload
++     * @deprecated Use {@link #readPayload(ResourceLocation, FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, net.minecraft.network.ConnectionProtocol)} instead, this variant can only read vanilla payloads.
```
Comment (Matyrobbrt) [inline patches/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java.patch]:
```suggestion
+     * @deprecated Use {@link #readPayload(ResourceLocation, FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, net.minecraft.network.ConnectionProtocol)} instead, as this variant can only read vanilla payloads.
```

File: patches/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java.patch [hunk 76]
```diff
@@ -1,21 +1,56 @@
...
 +++ b/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java
-@@ -23,14 +_,13 @@
+@@ -17,13 +_,52 @@
+         .put(BrandPayload.ID, BrandPayload::new)
+         .build();
  
++    /**
++     * Creates a new packet with a custom payload from the network.
++     * @param p_296108_ The buffer to read the packet from.
++     * @deprecated Use {@link #ServerboundCustomPayloadPacket(FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, net.minecraft.network.ConnectionProtocol)} instead, this variant can only read vanilla payloads.
```
Comment (Matyrobbrt) [inline patches/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java.patch]:
```suggestion
+     * @deprecated Use {@link #ServerboundCustomPayloadPacket(FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, net.minecraft.network.ConnectionProtocol)} instead, as this variant can only read vanilla payloads.
```

File: src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java (hunk 69 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java]: Problem with spotless

File: src/main/resources/assets/neoforge/lang/en_us.json [hunk 77]
```diff
@@ -50,7 +50,7 @@
   "fml.modmismatchscreen.missingmods.client": "Your client is missing the following mods, install these mods to join this server:",
   "fml.modmismatchscreen.missingmods.server": "The server is missing the following mods, remove these mods from your client to join this server:",
   "fml.modmismatchscreen.mismatchedmods": "The following mod versions do not match, install the same version of these mods that the server has to join this server:",
-  "fml.modmismatchscreen.table.modname": "Mod name",
+  "fml.modmismatchscreen.table.channelname": "Channel name",
```
Comment (pupnewfster) [inline src/main/resources/assets/neoforge/lang/en_us.json:53]: This file is missing all the new translation keys used by this PR

File: src/main/java/net/neoforged/neoforge/common/extensions/IFriendlyByteBufExtension.java [hunk 78]
```diff
@@ -37,4 +43,57 @@ default void writeFluidStack(FluidStack stack) {
...
+        } else {
+            self().writeBoolean(true);
+            Item item = stack.getItem();
+            self().writeId(BuiltInRegistries.ITEM, item);
+            self().writeVarInt(stack.getCount());
+            CompoundTag compoundtag = new CompoundTag();
+            if (item.isDamageable(stack) || item.shouldOverrideMultiplayerNbt()) {
+                compoundtag = stack.getTag();
+            }
+            compoundtag = net.neoforged.neoforge.attachment.AttachmentInternals.addAttachmentsToTag(compoundtag, stack, false);
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/common/extensions/IFriendlyByteBufExtension.java]: Switch this to using an import instead of the FQN

File: src/main/java/net/neoforged/neoforge/common/extensions/IFriendlyByteBufExtension.java [hunk 79]
```diff
@@ -37,4 +43,57 @@ default void writeFluidStack(FluidStack stack) {
...
+     *
+     * @return The read stack
+     */
+    default ItemStack readItemWithLargeCount() {
+        if (!self().readBoolean()) {
+            return ItemStack.EMPTY;
+        } else {
+            Item item = self().readById(BuiltInRegistries.ITEM);
+            int i = self().readVarInt();
+            return net.neoforged.neoforge.attachment.AttachmentInternals.reconstructItemStack(item, i, self().readNbt());
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/common/extensions/IFriendlyByteBufExtension.java]: Switch this to using an import instead of the FQN

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/common/extensions/IFriendlyByteBufExtension.java [hunk 80]
```diff
@@ -37,4 +43,57 @@ default void writeFluidStack(FluidStack stack) {
...
+    default <T> void writeObjectCollection(Collection<T> set, BiConsumer<T, FriendlyByteBuf> writer) {
+        self().writeCollection(set, (buf, t) -> writer.accept(t, buf));
+    }
+
+    /**
+     * Reads an {@link ItemStack} from the current buffer, but allows for a larger count than the vanilla method, using a variable length int instead of a byte.
+     *
+     * @return The read stack
+     */
+    default ItemStack readItemWithLargeCount() {
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/common/extensions/IFriendlyByteBufExtension.java:68]: If we are just adding a couple general use extensions that aren't actually used by this PR, one that would be of some use to me rather than having to have it in my own util method is similar to `writeCollection` is there was a `writeArray` and `readArray` (I was initially going to make one for those two in a PR after this networking refactor, but if you are including the large count item ones, might as well do the other two simple ones as well)

**Review by pupnewfster — CHANGES_REQUESTED** [review]

File: patches/net/minecraft/network/protocol/BundlerInfo.java.patch (hunk 72 above)
Comment (marchermans) [reply patches/net/minecraft/network/protocol/BundlerInfo.java.patch:25]: The delimiter is not accepted because the bundle is unpacked.
The purpose of a bundle is to process all packets within that bundle at the same time. If there is only one packet, having the bundle or not makes no difference to the result. As such, no delimiters are needed.

File: src/main/java/net/neoforged/neoforge/common/extensions/IFriendlyByteBufExtension.java (hunk 80 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/common/extensions/IFriendlyByteBufExtension.java:68]: Done

File: patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch (hunk 73 above)
Comment (XFactHD) [reply patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch]: This change appears to have been accidentally overwritten again

File: patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch (hunk 17 above)
Comment (XFactHD) [reply patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch]: Only one of the two methods was moved to a default impl in the extension interface, the commented one was not.

**Review by XFactHD — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/client/extensions/IMenuProviderExtension.java [hunk 81]
```diff
@@ -0,0 +1,21 @@
...
+
+/**
+ * Extension type for the {@link net.minecraft.world.MenuProvider} interface.
+ */
+public interface IMenuProviderExtension {
+
+    /**
+     * {@return true if the existing container should be closed on the client side when opening a new one, false otherwise}
+     * 
+     * @implNote Returning false, prevents the mouse from being (re-)centered when opening a new container.
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/client/extensions/IMenuProviderExtension.java]:
```suggestion
     * @implNote Returning false prevents the mouse from being (re-)centered when opening a new container.
```

File: src/main/java/net/neoforged/neoforge/client/extensions/IMenuProviderExtension.java [hunk 82]
```diff
@@ -0,0 +1,21 @@
...
+
+package net.neoforged.neoforge.client.extensions;
+
+/**
+ * Extension type for the {@link net.minecraft.world.MenuProvider} interface.
+ */
+public interface IMenuProviderExtension {
+
+    /**
+     * {@return true if the existing container should be closed on the client side when opening a new one, false otherwise}
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/client/extensions/IMenuProviderExtension.java]:
```suggestion
     * {@return {@code true} if the existing container should be closed on the client side when opening a new one, {@code false} otherwise}
```

File: src/main/java/net/neoforged/neoforge/common/extensions/IClientCommonPacketListenerExtension.java [hunk 83]
```diff
@@ -0,0 +1,90 @@
...
+/**
+ * This interface is used to extend the {@link ClientCommonPacketListener} interface.
+ * <p>
+ * Its primary purpose is to expose sending logic, for transmitting packets to the server.
+ * </p>
+ */
+public interface IClientCommonPacketListenerExtension {
+
+    /**
+     * {@return the ClientCommonPacketListener} this extension is attached to
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/common/extensions/IClientCommonPacketListenerExtension.java]: The inline-return is closed too early.

File: src/main/java/net/neoforged/neoforge/common/extensions/IPacketFlowExtension.java [hunk 84]
```diff
@@ -0,0 +1,43 @@
...
+    default boolean isServerbound() {
+        return self() == PacketFlow.SERVERBOUND;
+    }
+
+    /**
+     * {@return the {@link LogicalSide} that is receiving packets in this {@link PacketFlow}}
+     */
+    default LogicalSide getReceptionSide() {
+        return isServerbound() ? LogicalSide.SERVER : LogicalSide.CLIENT;
+    };
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/common/extensions/IPacketFlowExtension.java]: Useless semicolon

File: src/main/java/net/neoforged/neoforge/common/util/DebuggingHelper.java
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/common/util/DebuggingHelper.java:1]: If this file is kept it should be in a client package and marked internal.

File: src/main/java/net/neoforged/neoforge/network/ConfigurationInitialization.java [hunk 85]
```diff
@@ -0,0 +1,27 @@
...
+
+import net.neoforged.bus.api.SubscribeEvent;
+import net.neoforged.fml.common.Mod;
+import net.neoforged.neoforge.network.configuration.SyncConfig;
+import net.neoforged.neoforge.network.configuration.SyncRegistries;
+import net.neoforged.neoforge.network.configuration.SyncTierSortingRegistry;
+import net.neoforged.neoforge.network.event.OnGameConfigurationEvent;
+
+@Mod.EventBusSubscriber(modid = "neoforge", bus = Mod.EventBusSubscriber.Bus.MOD)
+public class ConfigurationInitialization {
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/ConfigurationInitialization.java:18]: Should be marked as internal.

File: src/main/java/net/neoforged/neoforge/network/ConfigurationInitialization.java [hunk 86]
```diff
@@ -0,0 +1,27 @@
...
+
+    @SubscribeEvent
+    public static void configureModdedClient(OnGameConfigurationEvent event) {
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/ConfigurationInitialization.java]: Make this method package-private to avoid it being called from the 'outside'.

File: src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java [hunk 87]
```diff
@@ -5,50 +5,65 @@
...
+import net.neoforged.neoforge.network.payload.TierSortingRegistrySyncCompletePayload;
+import net.neoforged.neoforge.network.registration.IPayloadRegistrar;
+import org.jetbrains.annotations.ApiStatus;
+
+@Mod.EventBusSubscriber(modid = NeoForgeVersion.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
+@ApiStatus.Internal
+public class NetworkInitialization {
+
+    @SubscribeEvent
+    public static void register(final RegisterPayloadHandlerEvent event) {
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java]: Make this method package-private.

File: src/main/java/net/neoforged/neoforge/network/configuration/ICustomConfigurationTask.java [hunk 88]
```diff
@@ -0,0 +1,47 @@
...
+    void run(Consumer<CustomPacketPayload> sender);
+
+    /**
+     * Invoked when it is time for this configuration to run.
+     * 
+     * @param sender A consumer that accepts a {@link Packet} to send to the client.
+     * @implNote Please do not override this method, it is implemented to wrap the {@link CustomPacketPayload} in a {@link ClientboundCustomPayloadPacket}.
+     */
+    @Override
+    @ApiStatus.Internal
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/configuration/ICustomConfigurationTask.java:43]: Is this internal so that it's not overriden or is it internal so that it's not used by mods? If the former, use `@ApiStatus.NonExtendable` instead.

File: src/main/java/net/neoforged/neoforge/network/event/OnGameConfigurationEvent.java [hunk 89]
```diff
@@ -0,0 +1,58 @@
...
+import net.neoforged.bus.api.Event;
+import net.neoforged.fml.event.IModBusEvent;
+import net.neoforged.neoforge.network.configuration.ICustomConfigurationTask;
+import org.jetbrains.annotations.ApiStatus;
+
+/**
+ * Fired when the server configuration packet listener collects all the configuration tasks
+ * that should be run on the server to configure the client.
+ */
+public class OnGameConfigurationEvent extends Event implements IModBusEvent {
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/event/OnGameConfigurationEvent.java:20]: Document that the event is fired on the mod event bus in the javadoc.

File: src/main/java/net/neoforged/neoforge/network/event/RegisterPayloadHandlerEvent.java [hunk 90]
```diff
@@ -0,0 +1,36 @@
...
+import net.neoforged.neoforge.network.registration.NetworkRegistry;
+import org.jetbrains.annotations.ApiStatus;
+
+/**
+ * Event fired when the {@link NetworkRegistry} is being set up.
+ * <p>
+ * This event is used to collect all the payload types and their handlers that should be used on the network.
+ * </p>
+ */
+public class RegisterPayloadHandlerEvent extends Event implements IModBusEvent {
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/event/RegisterPayloadHandlerEvent.java:21]: Document the fact that this event is fired on the mod event bus in the javadoc.

File: src/main/java/net/neoforged/neoforge/network/filters/NetworkFilters.java [hunk 91]
```diff
@@ -35,6 +40,21 @@ public static void injectIfNecessary(Connection manager) {
...
+            return; // Realistically this can only ever be null if the connection was prematurely closed due to an error. We return early here to reduce further log spam.
+
+        final List<VanillaPacketFilter> toRemove = pipeline.names()
+                .stream()
+                .map(name -> pipeline.get(name))
+                .filter(VanillaPacketFilter.class::isInstance)
+                .map(VanillaPacketFilter.class::cast)
+                .toList();
+
+        toRemove.forEach(pipeline::remove);
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/filters/NetworkFilters.java:56]: There should be a comment noting that the list is created to avoid concurrent modification.

File: src/main/java/net/neoforged/neoforge/network/filters/VanillaPacketSplitter.java [hunk 92]
```diff
@@ -49,69 +45,70 @@ public class VanillaPacketSplitter {
     private static final byte STATE_FIRST = 1;
     private static final byte STATE_LAST = 2;
 
-    public static void register() {
-        Predicate<String> versionCheck = NetworkRegistry.acceptMissingOr(VERSION);
-        EventNetworkChannel channel = NetworkRegistry.newEventChannel(CHANNEL, () -> VERSION, versionCheck, versionCheck);
-        channel.addListener(VanillaPacketSplitter::onClientPacket);
+    @SubscribeEvent
+    public static void register(final RegisterPayloadHandlerEvent event) {
+        event.registrar(NeoForgeVersion.MOD_ID)
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/filters/VanillaPacketSplitter.java]: Why is this registered here and not alongside all other packets we add?

File: src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java [hunk 93]
```diff
@@ -0,0 +1,65 @@
...
+ * Defines a phase-less payload context that is passed to a handler for a payload that arrives during the connection.
+ */
+public interface IPayloadContext {
+    /**
+     * {@return a handler that can be used to reply to the payload.}
+     */
+    IReplyHandler replyHandler();
+
+    /**
+     * {@return a handler that can be used to have the current listener which received the payload handle another packet immediately.}
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java]:
```suggestion
     * {@return a handler that can be used to have the current listener which received the payload handle another packet immediately}
```

File: src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java [hunk 94]
```diff
@@ -0,0 +1,65 @@
...
+     */
+    IPacketHandler packetHandler();
+
+    /**
+     * {@return a handler that can execute tasks on the main thread.}
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java]: Inline returns have no dots at the end, same with all of them in this class.

File: src/main/java/net/neoforged/neoforge/network/handling/ISynchronizedWorkHandler.java [hunk 95]
```diff
@@ -0,0 +1,53 @@
...
+     * @param task The task to run.
+     */
+    void execute(Runnable task);
+
+    /**
+     * Submits the given work to be run synchronously on the main thread of the game.
+     * <p>
+     * This method will <bold>not</bold> be guarded against exceptions.
+     * <br>
+     * If you need to guard against exceptions, call {@link CompletableFuture#exceptionally(Function)},
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/handling/ISynchronizedWorkHandler.java:32]: `exceptionally` is the wrong method to use when you want to handle an exception, and if the CF is Void. For that you should use `whenComplete` and check if the exception is not `null`.

File: src/main/java/net/neoforged/neoforge/network/handling/ISynchronizedWorkHandler.java [hunk 96]
```diff
@@ -0,0 +1,53 @@
...
+     * @param task The task to run.
+     */
+    CompletableFuture<Void> submitAsync(Runnable task);
+
+    /**
+     * Submits the given work to be run synchronously on the main thread of the game.
+     * <p>
+     * This method will <bold>not</bold> be guarded against exceptions.
+     * <br>
+     * If you need to guard against exceptions, call {@link CompletableFuture#exceptionally(Function)},
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/handling/ISynchronizedWorkHandler.java:45]: `exceptionally` is the wrong method to use when you want to handle an exception, and if the CF is Void. For that you should use `whenComplete` and check if the exception is not `null`.

File: src/main/java/net/neoforged/neoforge/network/payload/SplitPacketPayload.java (hunk 30 above)
Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/network/payload/SplitPacketPayload.java]: The parameter name is still srg.

From Orion: I seem unable to comment or resolve this, so per edit: Resolved.

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java [hunk 97]
```diff
@@ -0,0 +1,194 @@
...
+ * <br>
+ * Ids can be reused between play and configuration payloads, but it is needed to use different ids for different payloads.
+ * <br>
+ * Under certain situations you are not able to register a payload:
+ * <ul>
+ * <li>If the id you are trying to register is already in use, meaning you used the same id twice for different packets of the same kind.</li>
+ * <li>If you are trying to register a payload to a namespace that is not your own.</li>
+ * </ul>
+ * In principal this means that the registration will fail if any of these cases occur.
+ * The exception thrown in these cases is a {@link RegistrationFailedException}.
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java]: `principle` not `principal`. Also, this implies that there are cases where the registration will *not* fail? What are those and why would it not fail?

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java [hunk 98]
```diff
@@ -0,0 +1,194 @@
...
+ * Although you are free to capture this exception and handle it, it is not recommended to do so, since it is a sign of a programming error.
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java]: Useless remark.

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java [hunk 99]
```diff
@@ -0,0 +1,194 @@
...
+ * <p>
+ * There are two kinds of payloads:
+ * <ul>
+ * <li>Play payloads: These are payloads that are sent from the client to the server, or from the server to the client, during normal gameplay.</li>
+ * <li>Configuration payloads: These are payloads that are sent from the server to the client, or from the client to the server, during the login process, before the player is spawned.</li>
+ * </ul>
+ * You can register a custom payload for either of these types of payloads using the {@link #play(ResourceLocation, FriendlyByteBuf.Reader, IPlayPayloadHandler)}
+ * and {@link #configuration(ResourceLocation, FriendlyByteBuf.Reader, IConfigurationPayloadHandler)} methods respectively.
+ * <br>
+ * The difference between the play and configuration phases, if you like to call them that, is that the configuration phase generally requires
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java:58]: Javadocs should not refer to the reader or use expressions such as `if you'd like to call them that`. Use proper names whose meaning is documented.

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java [hunk 100]
```diff
@@ -0,0 +1,194 @@
...
+ * a confirmation payload to be returned to the server to trigger the next phase. In the {@link ConfigurationPayloadContext context} passed into
+ * your {@link IConfigurationPayloadHandler} you will find a {@link ITaskCompletedHandler} which you can use, <span class="strong">on the server side</span>,
+ * to notify the connection management system that a given {@link ConfigurationTask.Type} has been completed. This will trigger the next phase of the
+ * login process. Invoking the {@link ITaskCompletedHandler#onTaskCompleted(ConfigurationTask.Type)} method on the client, will throw an exception.
+ * </p>
+ * <p>
+ * Note: the processing of payloads happens solely on the network thread. You are yourself responsible for ensuring that any data you access
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java]: `You are yourself` is a pleonasm

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java [hunk 101]
```diff
@@ -0,0 +1,194 @@
...
+ * {@link #play(ResourceLocation, FriendlyByteBuf.Reader, IPlayPayloadHandler)} or {@link #configuration(ResourceLocation, FriendlyByteBuf.Reader, IConfigurationPayloadHandler)}
+ * respectively, since those are also invoked on the network thread.
+ * <br>
+ * The {@link PlayPayloadContext} and {@link ConfigurationPayloadContext} given to each of these handlers contains a {@link ISynchronizedWorkHandler}
+ * which you can use to submit work to be run on the main thread of the game. This is the recommended way to handle any work that needs to be done
+ * on the main thread.
+ * <br>
+ * Note the reader passed to any of the registration methods in this interface is invoked only if the payload is actually transferred over a connection which
+ * is not marked as {@link Connection#isMemoryConnection()}. This is important for single-player of lan-opened worlds since there the writer and reader are
+ * not invoked. This is because the payload is not actually transferred over the network, but only passed around in memory.
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java]: Excessive use of `this`. Maybe use `that` in the second sentence.

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java [hunk 102]
```diff
@@ -0,0 +1,194 @@
...
+     * @return The registrar.
+     */
+    <T extends CustomPacketPayload> IPayloadRegistrar common(ResourceLocation id, FriendlyByteBuf.Reader<T> reader, Consumer<IDirectionAwarePayloadHandlerBuilder<T, IPayloadHandler<T>>> handler);
+
+    /**
+     * Defines that the payloads registered by this registrar have a specific version associated with them.
+     * Clients connecting to a server with these payloads, will only be able to connect if they have the same version.
+     *
+     * @param version The version to use.
+     * @return The registrar, ready to configure payloads with that version.
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java]: If the registration is immutable, it should be noted in this method that a new registrar is returned.

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java [hunk 103]
```diff
@@ -0,0 +1,194 @@
...
+    /**
+     * Defines that the payloads registered by this registrar are optional.
+     * Clients connecting to a server which do not have the payloads registered, will still be able to connect.
+     * <p>
+     * If clients have also a version set, and a version mismatch occurs (so both client and server have the payloads registered,
+     * yet have different versions), the connection attempt will fail.
+     * In other words, marking a payload as optional does not exempt it from versioning, if it has that configured.
+     * </p>
+     * 
+     * @return The registrar, ready to configure payloads as optional.
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java]: If the registration is immutable, it should be noted in this method that a new registrar is returned.

File: src/main/java/net/neoforged/neoforge/network/registration/ModdedPacketRegistrar.java [hunk 104]
```diff
@@ -0,0 +1,147 @@
...
+import net.neoforged.neoforge.network.handling.IConfigurationPayloadHandler;
+import net.neoforged.neoforge.network.handling.IPayloadHandler;
+import net.neoforged.neoforge.network.handling.IPlayPayloadHandler;
+import org.jetbrains.annotations.ApiStatus;
+
+/**
+ * The internal implementation of {@link IPayloadRegistrar} for modded packets.
+ */
+@SuppressWarnings("OptionalUsedAsFieldOrParameterType")
+@ApiStatus.Internal
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/ModdedPacketRegistrar.java]: Pointless internal annotation as the class is package-private.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 54 above)
Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:95]: This wasn't resolved. We should be consistent and use the new method that hasn't been effectively deprecated 10 years ago.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 105]
```diff
@@ -0,0 +1,959 @@
...
+
+            final ConfigurationRegistration<?> registration = knownConfigurationRegistrations.get(channel.id());
+            if (registration == null) {
+                LOGGER.error("Received a modded custom payload packet {} with an unknown or not accepted channel. Not parsing packet.", channel.id());
+                throw new IllegalStateException("A client send a packet with an unknown or not accepted channel, while negotiation succeeded. Somebody changed the channels known to NeoForge!");
+            }
+
+            if (registration.flow().isPresent()) {
+                if (registration.flow().get() != flow) {
+                    LOGGER.warn("Received a modded custom payload packet {} that is not supposed to be send to the server. Disconnecting client.", channel.id());
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: `sent` not `send`

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 106]
```diff
@@ -0,0 +1,959 @@
...
+                    final Connection connection = ConnectionUtils.getConnection(context);
+                    final PacketListener listener = connection.getPacketListener();
+                    if (listener instanceof ServerGamePacketListener serverListener) {
+                        serverListener.disconnect(Component.translatable("neoforge.network.invalid_flow", flow));
+                    } else if (listener instanceof ClientGamePacketListener clientListener) {
+                        clientListener.getConnection().disconnect(Component.translatable("neoforge.network.invalid_flow", flow));
+                    } else {
+                        LOGGER.error("Received a modded custom payload packet {} that is not supposed to be send to the server. Disconnecting client, but the listener is not a game listener. This should not happen.", channel.id());
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: `sent` not `send`

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 107]
```diff
@@ -0,0 +1,959 @@
...
+            //Also validate that everything is key and then return a reader.
+            if (channel == null) {
+                LOGGER.warn("Received a modded custom payload packet {} with an unknown or not accepted channel. Not parsing packet.", id);
+                return null;
+            }
+
+            final ConfigurationRegistration<?> registration = knownConfigurationRegistrations.get(channel.id());
+            if (registration == null) {
+                LOGGER.error("Received a modded custom payload packet {} with an unknown or not accepted channel. Not parsing packet.", channel.id());
+                throw new IllegalStateException("A client send a packet with an unknown or not accepted channel, while negotiation succeeded. Somebody changed the channels known to NeoForge!");
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: `sent` not `send`. Also, that assumption in the exception sounds.. wrong and should be removed as it jumps to conclusions.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 108]
```diff
@@ -0,0 +1,959 @@
...
+                    final Connection connection = ConnectionUtils.getConnection(context);
+                    final PacketListener listener = connection.getPacketListener();
+                    if (listener instanceof ServerGamePacketListener serverListener) {
+                        serverListener.disconnect(Component.translatable("neoforge.network.invalid_flow", flow));
+                    } else if (listener instanceof ClientGamePacketListener clientListener) {
+                        clientListener.getConnection().disconnect(Component.translatable("neoforge.network.invalid_flow", flow));
+                    } else {
+                        LOGGER.error("Received a modded custom payload packet {} that is not supposed to be send to the server. Disconnecting client, but the listener is not a game listener. This should not happen.", channel.id());
+                        throw new IllegalStateException("A client send a packet with an unknown or not accepted channel, while negotiation succeeded. Somebody changed the channels known to NeoForge!");
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: `sent` not `send`. Also, that assumption in the exception sounds.. wrong and should be removed as it jumps to conclusions.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 109]
```diff
@@ -0,0 +1,959 @@
...
+                    }
+                }
+            }
+
+            return registration;
+        } else {
+            //Error case, somebody is trying to send a custom packet during a phase that is not supported.
+            LOGGER.error("Received a modded custom payload packet from a client that is not in the configuration or play phase. Not parsing packet.");
+            throw new IllegalStateException("A client send a packet while not in the configuration or play phase. Somebody changed the phases known to NeoForge!");
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: `sent` not `send`. Also, that assumption in the exception sounds.. wrong and should be removed as it jumps to conclusions.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 110]
```diff
@@ -0,0 +1,959 @@
...
+                    final Connection connection = ConnectionUtils.getConnection(context);
+                    final PacketListener listener = connection.getPacketListener();
+                    if (listener instanceof ServerGamePacketListener serverListener) {
+                        serverListener.disconnect(Component.translatable("neoforge.network.invalid_flow", flow));
+                    } else if (listener instanceof ClientGamePacketListener clientListener) {
+                        clientListener.getConnection().disconnect(Component.translatable("neoforge.network.invalid_flow", flow));
+                    } else {
+                        LOGGER.error("Received a modded custom payload packet {} that is not supposed to be send to the server. Disconnecting client, but the listener is not a game listener. This should not happen.", channel.id());
+                        throw new IllegalStateException("A client send a packet with an unknown or not accepted channel, while negotiation succeeded. Somebody changed the channels known to NeoForge!");
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: `sent` not `send`. Also, that assumption in the exception sounds.. wrong and should be removed as it jumps to conclusions.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 111]
```diff
@@ -0,0 +1,959 @@
...
+                if (registration.flow().get() != flow) {
+                    LOGGER.warn("Received a modded custom payload packet {} that is not supposed to be send to the server. Disconnecting client.", channel.id());
+                    final Connection connection = ConnectionUtils.getConnection(context);
+                    final PacketListener listener = connection.getPacketListener();
+                    if (listener instanceof ServerGamePacketListener serverListener) {
+                        serverListener.disconnect(Component.translatable("neoforge.network.invalid_flow", flow));
+                    } else if (listener instanceof ClientGamePacketListener clientListener) {
+                        clientListener.getConnection().disconnect(Component.translatable("neoforge.network.invalid_flow", flow));
+                    } else {
+                        LOGGER.error("Received a modded custom payload packet {} that is not supposed to be send to the server. Disconnecting client, but the listener is not a game listener. This should not happen.", channel.id());
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: `sent` not `send`

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 112]
```diff
@@ -0,0 +1,959 @@
...
+
+            final PlayRegistration<?> registration = knownPlayRegistrations.get(channel.id());
+            if (registration == null) {
+                LOGGER.error("Received a modded custom payload packet {} with an unknown or not accepted channel. Not parsing packet.", channel.id());
+                throw new IllegalStateException("A client send a packet with an unknown or not accepted channel, while negotiation succeeded. Somebody changed the channels known to NeoForge!");
+            }
+
+            if (registration.flow().isPresent()) {
+                if (registration.flow().get() != flow) {
+                    LOGGER.warn("Received a modded custom payload packet {} that is not supposed to be send to the server. Disconnecting client.", channel.id());
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: `sent` not `send`

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 113]
```diff
@@ -0,0 +1,959 @@
...
+            //Validate that everything is okey and then return a reader.
+            if (channel == null) {
+                LOGGER.warn("Received a modded custom payload packet {} with an unknown or not accepted channel. Not parsing packet.", id);
+                return null;
+            }
+
+            final PlayRegistration<?> registration = knownPlayRegistrations.get(channel.id());
+            if (registration == null) {
+                LOGGER.error("Received a modded custom payload packet {} with an unknown or not accepted channel. Not parsing packet.", channel.id());
+                throw new IllegalStateException("A client send a packet with an unknown or not accepted channel, while negotiation succeeded. Somebody changed the channels known to NeoForge!");
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: `sent` not `send`. Also, that assumption in the exception sounds.. wrong and should be removed as it jumps to conclusions.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 114]
```diff
@@ -0,0 +1,959 @@
...
+        if (id.equals(ModdedNetworkSetupFailedPayload.ID)) {
+            return ModdedNetworkSetupFailedPayload.READER;
+        }
+
+        //Check the network setup.
+        final NetworkPayloadSetup payloadSetup = context.channel().attr(ATTRIBUTE_PAYLOAD_SETUP).get();
+        final PacketFlow flow = context.channel().attr(ATTRIBUTE_FLOW).get();
+        if (payloadSetup == null || flow == null) {
+            //Error: Bail.
+            LOGGER.warn("Received a modded custom payload packet {} that has not negotiated with the server. Not parsing packet.", id);
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: The packet has not negotiated with the server?... this doesn't make sense.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 115]
```diff
@@ -0,0 +1,959 @@
...
+     * The method will first validate that a proper modded connection is setup and that a {@link NetworkPayloadSetup} is present on the connection. If that is not the case a warning is logged, and the client is disconnected with a generic error message.
+     * </p>
+     * <p>
+     * If the connection is setup properly, the method will check if the packet is known to the connection, and if it is not, the client is disconnected. Then checks are executed against the stored known packet handlers to see if the packet is known to the server. Technically, this list is considered fixed, based on the fact that the registration event is only fired once during bootstrap, so in practice this is just a safe-guard against people messing with the registration map. Once that completes the registered replyHandler is invoked.
+     * </p>
+     *
+     * @param listener The listener which received the packet.
+     * @param packet   The packet that was received.
+     */
+    public void onModdedPacketAtServer(ServerCommonPacketListener listener, ServerboundCustomPayloadPacket packet) {
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:272]: Same comments as above

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 116]
```diff
@@ -0,0 +1,959 @@
...
+     * The method will first validate that a proper modded connection is setup and that a {@link NetworkPayloadSetup} is present on the connection. If that is not the case a warning is logged, and the client is disconnected with a generic error message.
+     * </p>
+     * <p>
+     * If the connection is setup properly, the method will check if the packet is known to the connection, and if it is not, the client is disconnected. Then checks are executed against the stored known packet handlers to see if the packet is known to the client. Technically, this list is considered fixed, based on the fact that the registration event is only fired once during bootstrap, so in practice this is just a safe-guard against people messing with the registration map. Once that completes the registered replyHandler is invoked.
+     * </p>
+     *
+     * @param listener The listener which received the packet.
+     * @param packet   The packet that was received.
+     */
+    public boolean onModdedPacketAtClient(ClientCommonPacketListener listener, ClientboundCustomPayloadPacket packet) {
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:354]: Same comments as above.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 117]
```diff
@@ -0,0 +1,959 @@
...
+
+            if (shouldSendPacketRaw(packet)) {
+                toSend.add(packet);
+                return;
+            }
+
+            final NetworkChannel channel = payloadSetup.play().get(customPayloadPacket.payload().id());
+
+            if (channel == null) {
+                LOGGER.trace("Somebody tried to send: {} to a client which can not accept it. Not sending packet.", customPayloadPacket.payload().id());
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: `cannot`

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 118]
```diff
@@ -0,0 +1,959 @@
...
+        @Override
+        public void disconnect(Component reason) {
+            listener().disconnect(reason);
+        }
+
+        private static <T extends PacketListener> void resolvePacketGenerics(Packet<T> packet, ServerCommonPacketListener listener) {
+            try {
+                packet.handle((T) listener);
+            } catch (ClassCastException exception) {
+                throw new IllegalStateException("Somebody tried to handle a packet to a listener that does not support it.", exception);
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: handle *to*?

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 119]
```diff
@@ -0,0 +1,959 @@
...
+        @Override
+        public void disconnect(Component reason) {
+            listener().getConnection().disconnect(reason);
+        }
+
+        private static <T extends PacketListener> void resolvePacketGenerics(Packet<T> packet, ClientCommonPacketListener listener) {
+            try {
+                packet.handle((T) listener);
+            } catch (ClassCastException exception) {
+                throw new IllegalStateException("Somebody tried to handle a packet to a listener that does not support it.", exception);
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: handle *to*?

File: src/main/java/net/neoforged/neoforge/network/registration/RegistrationFailedException.java [hunk 120]
```diff
@@ -0,0 +1,149 @@
...
+ * <ul>
+ * <li>The payload id is already registered.</li>
+ * <li>The payload id is registered in the wrong namespace.</li>
+ * <li>Some other unknown reason.</li>
+ * </ul>
+ * The reason for the exception can be determined by the {@link Reason} enum.
+ * <p>
+ * Note: this exception is a runtime exception, meaning that it does not need to be caught.
+ * It is not recommended that this exception is caught, since it is a sign of a programming error.
+ * However, if a modder wishes to do so, they can capture it and handle it appropriately.
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/network/registration/RegistrationFailedException.java]: Pointless comment, all of this is deducible from the fact that the exception inherits from `RuntimeException.`

File: tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityTests.java [hunk 121]
```diff
@@ -5,9 +5,178 @@
...
+                            "Advanced payload for custom spawn was send"))
+                    .thenExecute(player -> helper.assertTrue(
+                            player.getOutboundPayloads(CustomSyncPayload.class)
+                                    .findAny().isEmpty(),
+                            "Custom sync payload for custom spawn was send"))
+                    .thenSucceed();
+        });
+    }
+
+    public static final class CustomComplexSpawnEntity extends Entity implements IEntityWithComplexSpawn {
```
Comment (Matyrobbrt) [inline tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityTests.java:85]: Use proper non-srg names in this class.

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/network/event/OnGameConfigurationEvent.java (hunk 89 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/event/OnGameConfigurationEvent.java:20]: This is not done on any of the new events touched by NF, See RegisterCapabilitiesEvent.

File: src/main/java/net/neoforged/neoforge/network/event/RegisterPayloadHandlerEvent.java (hunk 90 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/event/RegisterPayloadHandlerEvent.java:21]: See other event.
This is not done anymore, and as such not done here.

File: src/main/java/net/neoforged/neoforge/network/filters/VanillaPacketSplitter.java (hunk 92 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/filters/VanillaPacketSplitter.java]: Because that is how it was.
This PR is not going to change the original core behaviour of other subsystems.
The VPS already worked like this using a SimpleChannel, so I just followed suit. It is not better or worse to register stuff together or split, as such I left it exactly as I found it, structurally.

File: src/main/java/net/neoforged/neoforge/network/handling/ISynchronizedWorkHandler.java (hunk 95 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/handling/ISynchronizedWorkHandler.java:32]: This is not true, any documentation I could find indicates that there is a massive difference in behaviour between `whenComplete` and `exceptionally`, namely that `whenComplete` does not clear the exceptional state from the CF chain, where `exceptionally` does.

In this case it is as such significantly better to use `exceptionally`. See the JDoc, as well as the following SO Article and question: https://stackoverflow.com/questions/31338514/functional-java-interaction-between-whencomplete-and-exceptionally, https://mincong.io/2020/05/30/exception-handling-in-completable-future/

File: src/main/java/net/neoforged/neoforge/network/handling/ISynchronizedWorkHandler.java (hunk 96 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/handling/ISynchronizedWorkHandler.java:45]: See above.

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java (hunk 98 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java]: For you, maybe. But given that this JDoc needs to be clear to even novice programmers and modders, I use my PR author's discretion to leave it in.

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java (hunk 99 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java:58]: Documentation on the styling of JDoc guidelines for Forge?
This JDoc is a verbatim description of the core registrar and is meant as documentation for novices and experts alike. I see no reason to change the wording.

File: src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java (hunk 98 above)
Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/network/registration/IPayloadRegistrar.java]: Our docs do not need to mention that you can catch exceptions, nor what counts as a "programming error" or not. Javadocs are not guides to a system, that's what blogs and documentation articles are for. Javadocs are for documenting the behavior of the member being documented.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 107 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: The assumption is correct. There is no other systems that makes these registration objects, and as such an external influence modified them.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 108 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: See above

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 109 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: See above

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 110 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: See above

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 113 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java]: See above

File: patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch [hunk 122]
```diff
@@ -15,3 +21,45 @@
...
+         }
++    }
++    
++    @Override
++    public Connection getConnection() {
++        return connection;
++    }
++    
++    @Override
++    public net.minecraft.util.thread.ReentrantBlockableEventLoop<?> getMainThreadEventLoop() {
```
Comment (pupnewfster) [inline patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch]: Given this just returns `minecraft` do we want to consider moving this default impl into the extension interface and have it just call the `getMinecraft` method the extension is adding?

File: patches/net/minecraft/client/multiplayer/ClientHandshakePacketListenerImpl.java.patch [hunk 123]
```diff
@@ -1,19 +1,12 @@
...
-         this.updateStatus.accept(Component.translatable("connect.negotiating"));
-         this.connection.send(new ServerboundCustomQueryAnswerPacket(p_104545_.transactionId(), null));
-     }
+@@ -168,7 +_,8 @@
+                         FeatureFlags.DEFAULT_FLAGS,
+                         null,
+                         this.serverData,
+-                        this.parent
++                        this.parent,
++                        false
```
Comment (pupnewfster) [inline patches/net/minecraft/client/multiplayer/ClientHandshakePacketListenerImpl.java.patch]: I believe this patch is unnecessary as the patched in deprecated constructor will default the `isModdedConnection` to false anyway?

File: patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch [hunk 124]
```diff
@@ -1,21 +1,50 @@
...
++    }
++
++    /**
++     * @deprecated Use {@link #readPayload(ResourceLocation, FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, net.minecraft.network.ConnectionProtocol)} instead, as this variant can only read vanilla payloads.
++     */
++    @Deprecated
      private static CustomPacketPayload readPayload(ResourceLocation p_294802_, FriendlyByteBuf p_294886_) {
          FriendlyByteBuf.Reader<? extends CustomPacketPayload> reader = KNOWN_TYPES.get(p_294802_);
 -        return (CustomPacketPayload)(reader != null ? reader.apply(p_294886_) : readUnknownPayload(p_294802_, p_294886_));
 +        return reader != null ? reader.apply(p_294886_) : readUnknownPayload(p_294802_, p_294886_);
```
Comment (pupnewfster) [inline patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch]: Is the removal of this cast actually necessary?

File: patches/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java.patch [hunk 125]
```diff
@@ -1,21 +1,56 @@
...
++     * @param p_294367_ The id of the payload
++     * @param p_294321_ The buffer to read from
++     * @return The payload
++     * @deprecated Use {@link #readPayload(ResourceLocation, FriendlyByteBuf, io.netty.channel.ChannelHandlerContext, net.minecraft.network.ConnectionProtocol)} instead, as this variant can only read vanilla payloads.
++     */
++    @Deprecated
      private static CustomPacketPayload readPayload(ResourceLocation p_294367_, FriendlyByteBuf p_294321_) {
          FriendlyByteBuf.Reader<? extends CustomPacketPayload> reader = KNOWN_TYPES.get(p_294367_);
 -        return (CustomPacketPayload)(reader != null ? reader.apply(p_294321_) : readUnknownPayload(p_294367_, p_294321_));
 +        return reader != null ? reader.apply(p_294321_) : readUnknownPayload(p_294367_, p_294321_);
```
Comment (pupnewfster) [inline patches/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java.patch]: Is the removal of this cast actually necessary?

File: src/main/java/net/neoforged/neoforge/network/filters/NetworkFilters.java [hunk 126]
```diff
@@ -35,6 +40,22 @@ public static void injectIfNecessary(Connection manager) {
...
 
+    public static void cleanIfNecessary(Connection manager) {
+        ChannelPipeline pipeline = manager.channel().pipeline();
+        if (pipeline.get("packet_handler") == null)
+            return; // Realistically this can only ever be null if the connection was prematurely closed due to an error. We return early here to reduce further log spam.
+
+        //Grab the pipeline filters to remove in a seperate list to avoid a ConcurrentModificationException
+        final List<VanillaPacketFilter> toRemove = pipeline.names()
+                .stream()
+                .map(name -> pipeline.get(name))
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/filters/NetworkFilters.java]: Instead of mapping it like this by looking it up from the pipeline for each name we got should we maybe make use of `pipeline.toMap`?

File: src/main/java/net/neoforged/neoforge/network/payload/SplitPacketPayload.java [hunk 127]
```diff
@@ -0,0 +1,40 @@
...
+ * </p>
+ * 
+ * @param payload The slice of the original packet.
+ */
+@ApiStatus.Internal
+public record SplitPacketPayload(byte[] payload) implements CustomPacketPayload {
+    public static final ResourceLocation ID = new ResourceLocation(NeoForgeVersion.MOD_ID, "split");
+
+    public SplitPacketPayload(FriendlyByteBuf buf) {
+        this(buf.readBytes(buf.readVarInt()).array());
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/payload/SplitPacketPayload.java]: Why does this not use `FriendlyByteBuf#readByteArray` and the write method use `FriendlyByteBuf#writeByteArray`?

**Review by pupnewfster — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/network/filters/NetworkFilters.java (hunk 126 above)
Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/network/filters/NetworkFilters.java]: We want to remove all elements of a specific type. Using `toMap` would not help here.

File: src/main/java/net/neoforged/neoforge/network/filters/GenericPacketSplitter.java [hunk 128]
```diff
@@ -0,0 +1,227 @@
...
+        //Now write a max int value for the maximum length of the byte[]
+        temporaryBuf.writeInt(Integer.MAX_VALUE);
+
+        //During normal write operations, this is the prefix content that is written before the actual payload.
+        //This is the same for both clientbound and serverbound packets.
+        final int prefixSize = temporaryBuf.readableBytes();
+        return CompressionDecoder.MAXIMUM_UNCOMPRESSED_LENGTH - prefixSize;
+    }
+
+    private static AttributeKey<ConnectionProtocol.CodecData<?>> getProtocolKey(PacketFlow p_294385_) {
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/filters/GenericPacketSplitter.java]: This should use a non-srg name

File: src/main/java/net/neoforged/neoforge/network/filters/GenericPacketSplitter.java [hunk 129]
```diff
@@ -0,0 +1,227 @@
...
+            MAX_PACKET_SIZE);
+
+    private static final byte STATE_FIRST = 1;
+    private static final byte STATE_LAST = 2;
+
+    private final AttributeKey<ConnectionProtocol.CodecData<?>> codecKey;
+
+    public GenericPacketSplitter(Connection connection) {
+        this(
+                getProtocolKey(connection.getDirection().getOpposite()));
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/filters/GenericPacketSplitter.java]: This being on the next line feels like a formatting error

**Review by pupnewfster — CHANGES_REQUESTED** [review]

**Review by pupnewfster — DISMISSED** [review]

**Comment by robotgryphon** [comment]
How are these `RegisterPacketHandler` events sorted? A concern is that if any listener can request any registrar, it becomes trivial to stomp on changes from other mods accidentally, ESPECIALLY if a mod wants to "add-on" to another mod's existing registrar, given the whole system is "immutable" --- can this be elaborated on?

File: src/main/java/net/neoforged/neoforge/network/filters/GenericPacketSplitter.java [hunk 130]
```diff
@@ -0,0 +1,237 @@
...
+                ConnectionProtocol.CodecData<?> codecdata = attribute.get();
+
+                final byte[] packetData = buf.array();
+                for (int part = 0; part < parts; part++) {
+                    final ByteBuf partPrefix;
+                    if (part == 0) {
+                        partPrefix = Unpooled.buffer(5);
+                        partPrefix.writeByte(STATE_FIRST);
+
+                        new FriendlyByteBuf(partPrefix).writeVarInt(codecdata.packetId(packet));
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/network/filters/GenericPacketSplitter.java]: Instead of instantiating a `FriendlyByteBuf` here just as a wrapper in order to access `writeVarInt` we should just directly use mojang's `VarInt` helper that the method calls (as it accepts a `ByteBuf`):
```java
VarInt.write(partPrefix, codecdata.packetId(packet));
```

File: src/main/java/net/neoforged/neoforge/registries/RegistrySnapshot.java [hunk 131]
```diff
@@ -66,6 +66,50 @@ public <T> RegistrySnapshot(Registry<T> registry, boolean full) {
...
+                pkt.writeVarInt(this.ids.size());
+                this.ids.forEach((k, v) -> {
+                    pkt.writeVarInt(k);
+                    pkt.writeResourceLocation(v);
+                });
+                pkt.writeVarInt(this.aliases.size());
+                this.aliases.forEach((k, v) -> {
+                    pkt.writeResourceLocation(k);
+                    pkt.writeResourceLocation(v);
+                });
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/registries/RegistrySnapshot.java]:
```java
pkt.writeMap(this.ids, FriendlyByteBuf::writeVarInt, FriendlyByteBuf::writeResourceLocation);
pkt.writeMap(this.aliases, FriendlyByteBuf::writeResourceLocation, FriendlyByteBuf::writeResourceLocation);
```

File: src/main/java/net/neoforged/neoforge/registries/RegistrySnapshot.java [hunk 132]
```diff
@@ -66,6 +66,50 @@ public <T> RegistrySnapshot(Registry<T> registry, boolean full) {
...
+     */
+    public RegistrySnapshot(FriendlyByteBuf buf) {
+        this();
+        int len = buf.readVarInt();
+        for (int x = 0; x < len; x++)
+            this.ids.put(buf.readVarInt(), buf.readResourceLocation());
+
+        len = buf.readVarInt();
+        for (int x = 0; x < len; x++)
+            this.aliases.put(buf.readResourceLocation(), buf.readResourceLocation());
```
Comment (pupnewfster) [inline src/main/java/net/neoforged/neoforge/registries/RegistrySnapshot.java]:
```java
buf.readMap(size -> this.ids, FriendlyByteBuf::readVarInt, FriendlyByteBuf::readResourceLocation);
buf.readMap(size -> this.aliases, FriendlyByteBuf::readResourceLocation, FriendlyByteBuf::readResourceLocation);
 ```

**Review by pupnewfster — CHANGES_REQUESTED** [review]

File: patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch [hunk 133]
```diff
@@ -1,14 +1,57 @@
 --- a/net/minecraft/server/network/ServerCommonPacketListenerImpl.java
 +++ b/net/minecraft/server/network/ServerCommonPacketListenerImpl.java
-@@ -68,6 +_,11 @@
+@@ -105,11 +_,17 @@
+         this.connection.flushChannel();
+     }
+ 
++    @Override
```
Comment (pupnewfster) [inline patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch]: Useless patch, unless this is meant to be `@Deprecated` instead of `@Override`

**Review by pupnewfster — DISMISSED** [review]

**Review by XFactHD — DISMISSED** [review]

**Review by pupnewfster — APPROVED** [review]
