### PR TITLE
[1.21.8] Fix AnimationLoader loading too late

### LINKED ISSUE #2566: [1.21.8]Animation Loader system is too late to load
Minecraft Version: 1.21.8

NeoForge Version: 21.8.25

Description of issue: after 1.21.6 (or above) mojang change animation system. It cannot use Model.getAnimation in EntityModel class and return to empty animation.
because AnimationLoader is load late after the Entity Model and EntityRenderer load
solusion is should be load before load Entity Model and EntityRenderer
like before in ClientNeoForgeMod.class:
```
    event.addListener(NeoForgeReloadListeners.ENTITY_ANIMATIONS, AnimationLoader.INSTANCE);
```

to this:
```
    event.addDependency(NeoForgeReloadListeners.ENTITY_ANIMATIONS, AnimationLoader.INSTANCE);
```

### PR DESCRIPTION
**Pull request by XFactHD**
In 1.21.6, the keyframe animation system was changed to bake the keyframe animations in the constructor of the entity model using said animation and these models are instantiated in the constructor of the entity renderer rendering said model.
This PR fixes the animation loader running after the entity renderer instantiation, causing the models to receive empty animations on the first resource reload and potentially outdated animations from the last reload on any subsequent reload.

Fixes #2566

### CODE REVIEW

**Review by Technici4n — APPROVED** [review]

File: src/client/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java [hunk 1]
```diff
@@ -157,7 +157,10 @@ static void onRegisterReloadListeners(AddClientReloadListenersEvent event) {
         event.addDependency(NeoForgeReloadListeners.BRANDING, VanillaClientListeners.FIRST);
 
         event.addListener(NeoForgeReloadListeners.OBJ_LOADER, ObjLoader.INSTANCE);
+
         event.addListener(NeoForgeReloadListeners.ENTITY_ANIMATIONS, AnimationLoader.INSTANCE);
+        // Animations need to be loaded before entity renderers are instantiated
+        event.addDependency(NeoForgeReloadListeners.ENTITY_ANIMATIONS, VanillaClientListeners.ENTITY_RENDERER);
```
Comment (ChampionAsh5357) [inline src/client/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java:163]: This should be fine given that models aren't actually baked until the entity renderer, but technically, the models themselves are loaded in the `ModelManager`, so it would be a bit safer to have this run before that.

Comment (XFactHD) [reply src/client/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java:163]: The `ModelManager` is irrelevant for entity models, it's only responsible for block and item models.

Comment (ChampionAsh5357) [reply src/client/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java:163]: They're loaded as part of the model manager since they are used in item special models.

Comment (XFactHD) [reply src/client/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java:163]: Right, I completely forgot that the item models have access to entity models. However, the item model baking happens entirely in the async prepare phase where the listener sorting has no effect (it only applies to the synchronous apply phase) and the animations wouldn't be accessible regardless, even if the animation loader's prepare phase is done early enough.
1.21.9 or whatever the next version will be is going to have a system in resource reloaders that may make it feasible to give item models access to animations but for now it's not feasible to do this.

Comment (ChampionAsh5357) [reply src/client/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java:163]: Hmm, we should probably make another issue to keep track of this then, since any model that uses the animation system cannot be used within an item model as the animations are baked in the mod constructor. Or, that animations should be stored in a lazy instance and that should be a docs issue.

Either makes sense to me until we revisit with the shared state in 21.9

**Review by ChampionAsh5357 — APPROVED** [review]

**Review by embeddedt — APPROVED** [review]
