### PR TITLE
Fix TagEmptyCondition working for loaded-but-empty tags

### LINKED ISSUE #3104: [26.1.2] TagEmptyCondition now behaves as "TagLoadedCondition"
**Minecraft Version:** 26.1.2

**NeoForge Version:**26.1.2.13-beta

**Logs:** N/A

**Steps to Reproduce:**
 1. Create a recipe with a Not Condition containing a Tag Empty Condition.
 2. Create a tag with optional content. Ensure that the optional content is not present (i.e. tag should be empty, condition should be true -> inverted -> recipe should not load)
 3. Recipe loads.

**Description of issue:**

```
public boolean test(ICondition.IContext context) {
        return !context.isTagLoaded(tag);
    }
```

This will cause empty tags to report as non-empty, because they are loaded. 
E.g. an empty example mod with this recipe condition setup: https://github.com/klikli-dev/occultism/blob/version/26.1.2/src/generated/resources/data/occultism/recipe/miner/ores/bone_fragments_ore.json will lead to the reicpe loading, despite bone_fragments not existing and bone_fragments tag being empty.

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
This PR forwards some additional information from the tag loaded stage to `ConditionContext`, which permits us to restore the behavior of `TagEmptyCondition`. Currently the condition returns `true` if we load a tag with no contents, which is incorrect.

Closes #3104

### CODE REVIEW

File: patches/net/minecraft/core/MappedRegistry.java.patch [hunk 1]
```diff
@@ -139,6 +139,19 @@
...
                      List<Identifier> unboundTags = this.frozenTags
                          .entrySet()
+@@ -452,6 +_,12 @@
+                     return patchedHolder;
+                 }
+ 
++                // Neo: Make the underlying staged tag contents accessible for loading condition evaluation.
++                @Override
++                public Map<TagKey<T>, List<Holder<T>>> contents() {
++                    return pendingContents;
```
Comment (XFactHD) [inline patches/net/minecraft/core/MappedRegistry.java.patch]: The returned map should be wrapped in `Collections.unmodifiableMap()` to prevent external mutation.

File: src/main/java/net/neoforged/neoforge/common/extensions/PendingTagsExtension.java
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/common/extensions/PendingTagsExtension.java:1]: This extension interface is pointless as the implementation of its only member needs to be patched into the target anyway. The docs provided by this interface should be moved to the implementation of the method.

**Review by XFactHD — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/common/extensions/PendingTagsExtension.java
Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/common/extensions/PendingTagsExtension.java:1]: The method isn't patched into the target, it's patched into an anonymous instantiation of the target. So I think we still keep the extension.

**Review by XFactHD — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/common/extensions/IPendingTagsExtension.java [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+import net.minecraft.core.HolderSet;
+import net.minecraft.core.Registry.PendingTags;
+import net.minecraft.tags.TagKey;
+
+/**
+ * Extension for {@link PendingTags} so that we can inspect tag contents before they are bound.
+ * The {@link HolderSet.Named} returned by {@link PendingTags#lookup()} is not safe to read from until {@link PendingTags#apply()}
+ * has been called. So to counteract that, we have to forward the underlying pending contents.
+ */
+public interface IPendingTagsExtension<T> {
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/common/extensions/IPendingTagsExtension.java]: Consider naming this `PendingTagsExtension`

Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/common/extensions/IPendingTagsExtension.java]: But then I have to get the PR re-approved, screm

**Review by XFactHD — APPROVED** [review]
