### PR TITLE
Annotation marker fixes, javadoc cleanup, and LivingChangeTargetEvent methods renamed

### LINKED ISSUE #655: LivingChangeTargetEvent has incorrect nullability markers
The vanilla method `Mob#setTarget` has the following signature: `public void setTarget(@Nullable LivingEntity p_21544_)`, and the `LivingChangeTargetEvent` is fired from within this method.  However, neither `CommonHooks.onLivingChangeTarget` nor the event itself have proper `@Nullable` annotations on the target fields.

Honestly this whole event looks erroneous, as it was renamed from `LivingSetAttackTargetEvent` to `LivingChangeTargetEvent`, which brings with it the implied notion that the "original" target would be the mob's _old_ target, when it is in fact the "about to be set" target.

### LINKED ISSUE #1249: Remove unnecessary code in the file named ElytraLayer.java.patch.
in
https://github.com/neoforged/NeoForge/blob/1.21.x/patches/net/minecraft/client/renderer/entity/layers/ElytraLayer.java.patch

https://github.com/neoforged/NeoForge/blob/1.21.x/patches/net/minecraft/client/renderer/entity/layers/ElytraLayer.java.patch#L6-L27

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Closes https://github.com/neoforged/NeoForge/issues/655

And will fix some Javadoc to make some people happier lol.

remember, it is `// Neo:`. Not `// NEO:`. And do not do `<p></p>`. Do just `<p>`. And no more `NEOFORGE START` `NEOFORGE END` markers.

LivingChangeTargetEvent has its methods renamed to be more clear of what they represent. Also noticed a missing null check in the patch for that which could cause issues later if null got saved to the brain

### CODE REVIEW

**Review by shartte — DISMISSED** [review]

File: patches/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch [hunk 1]
```diff
@@ -117,6 +127,9 @@
 +
 +    private static net.neoforged.neoforge.client.ChunkRenderTypeSet createSetFromPredicate(java.util.function.Predicate<RenderType> predicate) {
 +        return net.neoforged.neoforge.client.ChunkRenderTypeSet.of(RenderType.chunkBufferLayers().stream().filter(predicate).toArray(RenderType[]::new));
-     }
- 
++    }
++
++    // Neo: Disable cutout mode on FAST rendering
```
Comment (sciwhiz12) [inline patches/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch]: What is this comment referring to? There's no patched code after it.

File: patches/net/minecraft/world/item/Item.java.patch [hunk 2]
```diff
@@ -148,31 +148,31 @@
...
-+    // NEO START
++    // Neo: Client rendering for Items
 +    private Object renderProperties;
 +
-+    /*
-+        DO NOT CALL, IT WILL DISAPPEAR IN THE FUTURE
-+        Call RenderProperties.get instead
-+    */
++    /**
++     * Neo: DO NOT CALL, IT WILL DISAPPEAR IN THE FUTURE
```
Comment (sciwhiz12) [inline patches/net/minecraft/world/item/Item.java.patch:155]: Should we TODO this for removal?

File: src/main/java/net/neoforged/neoforge/event/entity/living/LivingChangeTargetEvent.java [hunk 3]
```diff
@@ -36,30 +37,33 @@
...
     /**
-     * {@return the new target of this entity.}
+     * {@return the new target that this entity will begin to track.}
      */
-    public LivingEntity getNewTarget() {
-        return newTarget;
+    @Nullable
+    public LivingEntity getNewAboutToBeSetTarget() {
+        return newAboutToBeSetTarget;
     }
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/event/entity/living/LivingChangeTargetEvent.java:58]: In the future, I'd prefer breaking changes like these be made into their own separate PR from a general cleanup PR, to keep changes logically separate where possible and practical.

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

File: patches/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch (hunk 1 above)
Comment (TelepathicGrunt) [reply patches/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch]: Oh man lol. Because this patch started with FORGE START but had no FORGE END, I thought setFancy was a patch we did lmao. More reason to yeet the start and end comments. Will fix shortly

File: patches/net/minecraft/world/item/Item.java.patch (hunk 2 above)
Comment (TelepathicGrunt) [reply patches/net/minecraft/world/item/Item.java.patch:155]: Added todo on all of these so we can track them in future easier

File: patches/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch (hunk 1 above)
Comment (TelepathicGrunt) [reply patches/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch]: Ok so I removed this comment and moved out patches in this file to be below setFancy. That way after a certain point, it's just neo additions which would be easier to understand

**Review by sciwhiz12 — DISMISSED** [review]
Merge when ready.

File: patches/net/minecraft/world/damagesource/DamageEffects.java.patch [hunk 4]
```diff
@@ -26,6 +26,20 @@
 +        this(p_270875_, () -> p_270383_);
 +    }
 +
++    /**
++     * Creates a new DamageEffects with the specified ID and sound. Store the created enum in a static final field.<br>
++     * Use an enumextender.json to link to your {@link net.neoforged.fml.common.asm.enumextension.EnumProxy} in order to create new entries for this enum.<br>
++     * Example usage:
```
Comment (sciwhiz12) [inline patches/net/minecraft/world/damagesource/DamageEffects.java.patch]: Use paragraph tags rather than line break tags.

Comment (TelepathicGrunt) [reply patches/net/minecraft/world/damagesource/DamageEffects.java.patch]: this aint no approval! : screm :

Fixed

**Review by sciwhiz12 — DISMISSED** [review]

**Review by sciwhiz12 — APPROVED** [review]
