### PR TITLE
[1.20.5] Record a BlockSnapshot for client break predictions and cleanup break pipeline

### LINKED ISSUE #808: Block Entity data is discarded when canceling BreakEvent
When breaking a block, the client will start a prediction about the break process via `MultiPlayerGameMode#startPrediction`, and immediately trigger the break on the client.

While the prediction is "active", changes to the block sent by the server via `ClientboundBlockUpdatePacket` will not be commited into the world, instead being delayed until a `ClientboundBlockChangedAckPacket` is sent (which will happen next tick). This process allows the client to reset the player's position if they moved into an illegally-broken block.

Since the block change is not committed into the world, other packets that rely on the block change being committed (such as `ClientboundBlockEntityDataPacket`) will be discarded, meaning that when a block is broken on the client but denied by the server, the BE data is lost from the client.

This is also a [vanilla bug](https://bugs.mojang.com/browse/MC-270804) - if you place a sign in a spawn chunk (while spawn protection is active, which requires at least one op) and break it, the sign text will go blank.

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
### Clientside Break Predictions
This PR fixes #808 by attaching a `BlockSnapshot` to the `ServerVerifiedState` stored by vanilla for recording staged client block break actions. If the client restores the same block that was previously broken (meaning the break action was denied by the server), the BE data is restored to the snapshot. This prevents desyncs from occuring.

It also removes the code that sends a BE update packet from `CommonHooks.onBlockBreakEvent`.  Due to the same issue, this packet is always discarded, as the client state is set to air.
### Block Break Cleanup
Unrelated to the above, this PR removes the method `IItemExtension#onBlockStartBreak`.  This method had an incorrect hook spot (meaning it is not usable and was not previously usable for its intended purpose), and provides no unique functionality that cannot be accomplished by using `BreakEvent` or other methods on Item.

Finally, it updates the javadocs and fixes some logic in `CommonHooks.fireBlockBreak` (renamed from `onBlockBreakEvent`).

## Future Work
We should consider firing `BlockEvent.BreakEvent` on the client to prevent the desync before it can possibly occur; this patch will still be necessary to support pure server-side operations, and prevent desyncs in cases where vanilla blocks the break action (until vanilla fixes the bug).

Additionally, we need to re-assess `IBlockExtension#onDestroyedByPlayer` to see if it still provides and unique functionality, since the maintenance cost for this method is fairly high due to how much logic it subverts.

In other break-event related changes, the XP modification code can finally be moved out of `BreakEvent` and into `BlockDropsEvent` when #788 is rebased to 1.20.5

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java [hunk 1]
```diff
@@ -120,18 +120,29 @@ public boolean restoreToLocation(LevelAccessor world, BlockPos pos, boolean forc
         if (world instanceof Level)
             ((Level) world).sendBlockUpdated(pos, current, replaced, flags);
 
+        restoreBlockEntity(world, pos);
+
+        if (DEBUG)
+            System.out.println("Restored " + this.toString());
```
Comment (FiniteReality) [inline src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java]: We should change this logic to use a slf4j logger. That way we can check `if (logger.isDebugEnabled())` or similar instead of using `System.out.println`.

File: src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java [hunk 2]
```diff
@@ -120,18 +120,29 @@ public boolean restoreToLocation(LevelAccessor world, BlockPos pos, boolean forc
...
+        return true;
+    }
+
+    /**
+     * Loads the stored {@link BlockEntity} data if one exists at the given position.
+     * 
+     * @return true if any data was loaded
+     */
+    public boolean restoreBlockEntity(LevelAccessor world, BlockPos pos) {
         BlockEntity te = null;
```
Comment (FiniteReality) [inline src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java]: Since we're here anyway, it may be worth changing these variable names to match the renaming of TileEntity to BlockEntity

**Comment by FiniteReality** [comment]
Is this still targeted at 1.20.5? My understanding was that we quickly dropped support for 1.20.5 as 1.20.6 arrived shortly afterwards.

File: src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java (hunk 1 above)
Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java]: We can change it to emit to the main neo logger instead of println, but it still needs to be guarded behind the compile-time flag instead of checking `logger.isDebugEnabled()`

File: patches/net/minecraft/client/multiplayer/ClientLevel.java.patch [hunk 3]
```diff
@@ -17,6 +17,21 @@
  
      public void handleBlockChangedAck(int p_233652_) {
          this.blockStatePredictionHandler.endPredictionsUpTo(p_233652_, this);
+@@ -157,10 +_,14 @@
+     @Override
+     public boolean setBlock(BlockPos p_233643_, BlockState p_233644_, int p_233645_, int p_233646_) {
+         if (this.blockStatePredictionHandler.isPredicting()) {
++            // Neo: Record and store a snapshot in the prediction so that BE data can be restored if the break is denied.
++            var snapshot = net.neoforged.neoforge.common.util.BlockSnapshot.create(this.dimension(), this, p_233643_);
```
Comment (FiniteReality) [inline patches/net/minecraft/client/multiplayer/ClientLevel.java.patch]: It may be a larger patch, but wouldn't it make more sense to implement this in `retainKnownServerState`?

File: patches/net/minecraft/client/multiplayer/prediction/BlockStatePredictionHandler.java.patch [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+             }
+         }
+     }
+@@ -72,8 +_,20 @@
+         return this.isPredicting;
+     }
+ 
++    /**
++     * Sets the stored BlockSnapshot on the ServerVerifiedState for the given position.
++     * This method is only called after {@link #retainKnownServerState}, so we are certain a map entry exists.
```
Comment (FiniteReality) [inline patches/net/minecraft/client/multiplayer/prediction/BlockStatePredictionHandler.java.patch:25]: (As an addon to https://github.com/neoforged/NeoForge/pull/809/files#r1602234435) - if we handled the entire patch in this class, we can ensure that this is the case. Currently, we cannot because this is marked as public API, and mods could do funny things with prediction that cause this assumed precondition to fail.

File: patches/net/minecraft/client/multiplayer/ClientLevel.java.patch (hunk 3 above)
Comment (Shadows-of-Fire) [reply patches/net/minecraft/client/multiplayer/ClientLevel.java.patch]: No, that would be impossible, since `setBlock` has already been called by the time control flow reaches `retainKnownServerState`.

File: patches/net/minecraft/server/level/ServerPlayerGameMode.java.patch [hunk 5]
```diff
@@ -82,11 +77,18 @@
...
-+        boolean removed = state.onDestroyedByPlayer(this.level, p_180235_1_, this.player, canHarvest, this.level.getFluidState(p_180235_1_));
++    /**
++     * Patched-in method that handles actual removal of blocks for {@link #destroyBlock(BlockPos)}.
++     *
++     * @param pos The block pos of the destroyed block
++     * @param state The state of the destroyed block
++     * @param canHarvest If the player breaking the block can harvest the drops of the block
++     * @return If the block was removed, as reported by {@link BlockState#onDestroyedByPlayer}.
++     */
++    private boolean removeBlock(BlockPos pos, BlockState state, boolean canHarvest) {
```
Comment (FiniteReality) [inline patches/net/minecraft/server/level/ServerPlayerGameMode.java.patch:88]: Should this method have an EXC entry for mapping `pos` back to `p_180235_1_`?

File: src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java (hunk 1 above)
Comment (FiniteReality) [reply src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java]: That works - I was thinking of being in a world where we have the logging refactor work done :sweat_smile:

File: patches/net/minecraft/server/level/ServerPlayerGameMode.java.patch (hunk 5 above)
Comment (Shadows-of-Fire) [reply patches/net/minecraft/server/level/ServerPlayerGameMode.java.patch:88]: No, the original method was a patch as well.  Not sure why the parameter name was obfuscated in that case.  Probably someone being lazy with copypaste.

File: src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java (hunk 2 above)
Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java]: Hornet's nest you've poked there :p

Did a full cleanup pass on that class

**Review by FiniteReality — APPROVED** [review]
I can't see anything wrong, hopefully this doesn't blow everything up :smile:

**Comment by Shadows-of-Fire** [comment]
Always the possibility, but I think this one is safe enough
