### PR TITLE
[1.21.x] Fix parameter ordering issue in ItemStackedOnOtherEvent

### LINKED ISSUE #1797: Switched arguments for `ItemStackedOnOtherEvent`?
See https://discord.com/channels/313125603924639766/1249305774987939900/1300732536225402890
and https://discord.com/channels/313125603924639766/1249305774987939900/1262353590710829167

Original text:

is it intentional that these arguments are switched?

```java
private boolean tryItemClickBehaviourOverride(Player player, ClickAction action, Slot slot, ItemStack clickedItem, ItemStack carriedItem) {
    // Neo: Fire the ItemStackedOnOtherEvent, and return true if it was cancelled (meaning the event was handled). Returning true will trigger the container to stop processing further logic.
    if (net.neoforged.neoforge.common.CommonHooks.onItemStackedOn(clickedItem, carriedItem, slot, action, player, createCarriedSlotAccess())) {
```

```java
public static boolean onItemStackedOn(ItemStack carriedItem, ItemStack stackedOnItem, Slot slot, ClickAction action, Player player, SlotAccess carriedSlotAccess) {
    return NeoForge.EVENT_BUS.post(new ItemStackedOnOtherEvent(carriedItem, stackedOnItem, slot, action, player, carriedSlotAccess)).isCanceled();
}
```

when i click an armor item into a slot the carrieditem in the event is empty and the stackedonitem has the item
i'd assume the container hasn't been set yet, so it should be the other way around

---

The current `1.21.x` still seems to have the problem

```java
ItemStack itemstack9 = slot7.getItem();
ItemStack itemstack10 = this.getCarried();
player.updateTutorialInventoryAction(itemstack10, slot7.getItem(), clickaction);
if (!this.tryItemClickBehaviourOverride(player, clickaction, slot7, itemstack9, itemstack10)) {
```

The carried item is the second argument in the `tryItemClickBehaviourOverride` method and gets set as the second argument for the event
But the second argument for the event is the stacked-on item

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
This PR fixes a parameter ordering issue when firing the `ItemStackedOnOtherEvent`. Since #1248, the parameters have been swapped, and the carried stack was mixed up with the "stacked-on" stack.

Closes #1797

### CODE REVIEW

**Comment by sciwhiz12** [comment]
Reran the game tests check because `livingDamageSequenceEvents`, a game test, is a bit flaky.

File: patches/net/minecraft/world/inventory/AbstractContainerMenu.java.patch [hunk 1]
```diff
@@ -1,11 +1,12 @@
...
 +++ b/net/minecraft/world/inventory/AbstractContainerMenu.java
-@@ -567,6 +_,11 @@
+@@ -567,6 +_,12 @@
      }
  
      private boolean tryItemClickBehaviourOverride(Player p_249615_, ClickAction p_250300_, Slot p_249384_, ItemStack p_251073_, ItemStack p_252026_) {
 +        // Neo: Fire the ItemStackedOnOtherEvent, and return true if it was cancelled (meaning the event was handled). Returning true will trigger the container to stop processing further logic.
-+        if (net.neoforged.neoforge.common.CommonHooks.onItemStackedOn(p_251073_, p_252026_, p_249384_, p_250300_, p_249615_, createCarriedSlotAccess())) {
++        // The first parameter to onItemStackedOn is the "carried" (under-mouse) item, which is the second ItemStack parameter to this method.
++        if (net.neoforged.neoforge.common.CommonHooks.onItemStackedOn(p_252026_, p_251073_, p_249384_, p_250300_, p_249615_, createCarriedSlotAccess())) {
```
Comment (sciwhiz12) [inline patches/net/minecraft/world/inventory/AbstractContainerMenu.java.patch:9]: Why did you remove the `Neo:` part of the comment?

Comment (Shadows-of-Fire) [reply patches/net/minecraft/world/inventory/AbstractContainerMenu.java.patch:9]: I didn't, this is a _new_ comment after the first comment line (which contains `Neo:`)

Comment (sciwhiz12) [reply patches/net/minecraft/world/inventory/AbstractContainerMenu.java.patch:9]: _sigh_ I'm blind.

**Review by sciwhiz12 — APPROVED** [review]

**Comment by Shadows-of-Fire** [comment]
@neoforged/bots backport 1.21.1
