### PR TITLE
Respect WorldlyContainer nullability contracts in SidedInvWrapper

### LINKED ISSUE #1840: Incorrect null contracts in SidedInvWrapper
SidedInvWrapper is a capability wrapper for `WorldlyContainer`, a vanilla interface with the following definition:

```java
public interface WorldlyContainer extends Container {
    int[] getSlotsForFace(Direction side);

    boolean canPlaceItemThroughFace(int index, ItemStack itemStack, @Nullable Direction direction);

    boolean canTakeItemThroughFace(int index, ItemStack stack, Direction direction);
}
```

As a capability wrapper for the `IItemHandler` capability, `SidedInvWrapper` directly accepts a null `Direction` and passes it through to these methods, which is illegal in two of three cases.

These erroneous calls are in `SidedInvWrapper.getSlot` and `SidedInvWrapper#extractItem`. In both cases, `SidedInvWrapper` needs to fallback to the equivalent behavior from `InvWrapper` when the direction is null.

This behavior has gone unnoticed for quite a while, simply because none of the vanilla implementation crash when passed null values. This does not change the fact that this is a bug in `SidedInvWrapper`.

### PR DESCRIPTION
**Pull request by Technici4n**
Untested but I think it's correct. Fixes #1840.

Previously, worldly containers would be wrapped using `InvWrapper` when queried with a `null` direction. This PR will now always use a `SidedInvWrapper` for them for the `null` direction too. This removes the need to special case the shulker box.

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/items/wrapper/SidedInvWrapper.java [hunk 1]
```diff
@@ -47,6 +47,9 @@ public SidedInvWrapper(WorldlyContainer inv, @Nullable Direction side) {
     }
 
     public static int getSlot(WorldlyContainer inv, int slot, @Nullable Direction side) {
```
Comment (Shadows-of-Fire) [inline src/main/java/net/neoforged/neoforge/items/wrapper/SidedInvWrapper.java:49]: This method should be made protected, the `@Nullable` removed, and the usages updated accordingly. `WorldlyContainer` doesn't have a concept of slots for a null side.

Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/items/wrapper/SidedInvWrapper.java:49]: This cannot be done on older versions as it would be a breaking change. I am retargeting this PR for 1.21.1 and will open a new one for latest with that change in mind.

Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/items/wrapper/SidedInvWrapper.java:49]: Never mind, I forgot that will attempt to bring in the rest of the branch.

Comment (Technici4n) [reply src/main/java/net/neoforged/neoforge/items/wrapper/SidedInvWrapper.java:49]: There is no point in doing this, it will just make the call sites of `getSlot` more annoying because the `null` side will need to be handled there explicitly.

**Review by Shadows-of-Fire — APPROVED** [review]

**Comment by KlemenDEV** [comment]
I think this PR introduced this issue: https://github.com/neoforged/NeoForge/issues/2307
