### PR TITLE
Fallback to magic damage on clientside when connecting to vanilla

### LINKED ISSUE #614: [20.1 & 20.4] Vanilla Server causes Neo Client crashes due to `ForgeMod.POISON_DAMAGE` usage
**Minecraft Version:** `1.20.1` and `1.20.4`

**NeoForge Version:** `47.1.86` and `20.4.102-beta`

**Logs:**
`20.1` <https://paste.gemwire.uk/view/raw/85178e32>
`20.4` <https://gist.github.com/AterAnimAvis/75965c965f715e10a9fcf6d656c40d46>

**Steps to Reproduce:**
 1. Connect to Vanilla Server
 2. Spawn Armor Stand
 3. Splash with Poison Potion

**Description of issue:**
`20.1` <https://github.com/neoforged/NeoForge/blob/360c02fe58629c045db468f2f4137146c3c80d51/patches/minecraft/net/minecraft/world/effect/MobEffect.java.patch#L26>
`20.4` <https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/effect/PoisonMobEffect.java.patch#L9>

We need to fallback to the Vanilla DamageType if `forge:poison` isn't present in the registry.

[Discord Discussion](https://discord.com/channels/313125603924639766/852298000042164244/1204482512726794282)

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
Closes #614 for 1.20.4

### CODE REVIEW

File: patches/net/minecraft/world/effect/PoisonMobEffect.java.patch [hunk 1]
```diff
@@ -1,12 +1,16 @@
...
          super.applyEffectTick(p_296276_, p_296233_);
          if (p_296276_.getHealth() > 1.0F) {
 -            p_296276_.hurt(p_296276_.damageSources().magic(), 1.0F);
 +            // Neo: Replace DamageSources#magic() with neoforge:poison to allow differentiating poison damage.
-+            p_296276_.hurt(p_296276_.damageSources().source(net.neoforged.neoforge.common.NeoForgeMod.POISON_DAMAGE), 1.0F);
++            // Fallback to minecraft:magic in client code when connecting to a vanilla server.
++            // LivingEntity#hurt(DamageSource) will no-op in client code immediately, but the holder is resolved before the no-op.
++            var dTypeReg = p_296276_.damageSources().damageTypes;
++            var dType = dTypeReg.getHolder(net.neoforged.neoforge.common.NeoForgeMod.POISON_DAMAGE).orElse(dTypeReg.getHolderOrThrow(net.minecraft.world.damagesource.DamageTypes.MAGIC));
++            p_296276_.hurt(new net.minecraft.world.damagesource.DamageSource(dType), 1.0F);
```
Comment (embeddedt) [inline patches/net/minecraft/world/effect/PoisonMobEffect.java.patch:13]: Would it be better to provide `p_296276_.damageSources().magic()` for the fallback case instead of constructing a new `DamageSource`? Don't know if it matters.

Comment (Shadows-of-Fire) [reply patches/net/minecraft/world/effect/PoisonMobEffect.java.patch:13]: I don't *think* it matters. DS objects are fairly cheap, vanilla just caches them because they can.

**Review by embeddedt — APPROVED** [review]
I'll assume you tested this, code seems correct
