### PR TITLE
Fix forced chunks data serialization error

### LINKED ISSUE #2115: [1.21.5] Crash when trying to save world with chunks forceloaded through NeoForge
**Minecraft Version:** 1.21.5

**NeoForge Version:**21.5.14-beta

**Logs:** Crash report https://pastebin.com/87ZLwbQ9

**Steps to Reproduce:**
 1. Create a new singleplayer world
 2. Through a custom mod/test mod, request any chunk using NeoForge's `TicketController` for a BlockPos owner or an Entity owner. I did this the following way: `SecurityCraft.CAMERA_TICKET_CONTROLLER.forceChunk(serverLevel, dummyEntity, x, z, true, false);` with `dummyEntity` being of type `SecurityCamera`.
 3. Allow your world to save, either by entering the pause menu or waiting until the world autosaves.
 4. Observe the game crashing

**Description of issue:**
As discussed in Discord, the issue is NeoForge's ForcedChunkManager trying to encode its chunks in vanilla's `TicketStorage` (see `TicketStorage#37`), and using a custom codec to do so. This codec effectively tries to save a `Map<UUID, TicketSet>` and a `Map<BlockPos, TicketSet>` to NBT, for storage within the world data file. However, for the Java maps to be properly convertible to a `CompoundTag` for storage, both key entries (BlockPos and UUID) need to be serialized to a `String`, which is not happening currently due to the wrong codecs being used (they're currently both converted to an `IntStream`, which `CompoundTag` cannot deal with). This leads the game to crash since the ForcedChunkManager data cannot be saved to NBT.

Relevant Discord conversation with potential suggestions: https://discord.com/channels/313125603924639766/852298000042164244/1357804883260084395

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #2115 by implementing a new extra codec which serializes an unbounded map as a list of objects, allowing for maps whose keys are not serializable to strings.

The `ForcedChunkManager.OwnedChunks` record has maps whose keys are not serialized to strings, which causes an error when serializing them on world save. The new extra codec allows for minimal changes to the codec and surrounding data structures, while providing a new convenient helper codec for those who need maps with non-string-serializable keys.

This only occured in 1.21.5 when the `SavedData` system, used by the forced chunks saved data system which vanilla uses and Neo extends, switched from manual NBT serialization to `Codec`-mediated serialization.

## Alternatives

The extra codec could be simplified by changing it to store a list of lists, where each nested list has two entries: the first entry for the key, and the second entry for the value/element. I chose the list-of-objects route in order to pack field names for self-documenting serialized data, and to provide an easier path of migration if a user of the extra codec moves to expanding beyond a map to a list of objects on their own.

Note that if a list-of-lists is implemented, then serializing to NBT would still function despite the possibility of a non-homogeneous list as 1.21.5 implemented special measures to deal with non-homogeneous lists: transparently converting non-compounds into compounds with a blank (`""`) key. (For example, `[1, {}]` would be serialized as `[{"": 1}, {}]`, but the serialized form would not be visible to code or users; NBT transparently converts the first entry when retrieved.)

The extra codec could also be eliminated altogether by changing the maps in `ForcedChunkManager.OwnedChunks` to be list of objects themselves, though that would incur more changes to `ForcedChunkManager`. However, a quick look-through shows none of the public API would be affected by those changes.

### CODE REVIEW

File: tests/src/junit/java/net/neoforged/neoforge/unittest/ExtraCodecsTests.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+                new BlockPos(0, 8, 0), "testB",
+                new BlockPos(0, 0, 8), "testC");
+        Codec<Map<BlockPos, String>> codec = NeoForgeExtraCodecs.unboundedMapAsList("position", BlockPos.CODEC, "value", Codec.STRING);
+
+        DataResult<JsonElement> resultJson = codec.encodeStart(JsonOps.INSTANCE, values);
+        assertTrue(resultJson.isSuccess(), "Encode to JSON should succeed");
+        System.out.println(resultJson.getOrThrow());
+
+        DataResult<Tag> resultTag = codec.encodeStart(NbtOps.INSTANCE, values);
+        assertTrue(resultTag.isSuccess(), "Encode to NBT should succeed");
```
Comment (Matyrobbrt) [inline tests/src/junit/java/net/neoforged/neoforge/unittest/ExtraCodecsTests.java]: Maybe do a round-trip too?

File: src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java [hunk 2]
```diff
@@ -315,4 +317,44 @@ public String toString() {
...
+     *
+     * @param keyCodec     codec for the key
+     * @param elementCodec codec for the element
+     * @param <K>          the key type
+     * @param <V>          the element type
+     * @return a codec for an unbounded map
+     * @see #unboundedMapAsList(String, Codec, String, Codec)
+     */
+    public static <K, V> Codec<Map<K, V>> unboundedMapAsList(Codec<K> keyCodec, Codec<V> elementCodec) {
+        return unboundedMapAsList("key", keyCodec, "element", elementCodec);
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java]: I would use `key` and `value`. Alternatively, I would simply not add this method and prefer if the names are always explicit.

File: src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java [hunk 3]
```diff
@@ -315,4 +317,44 @@ public String toString() {
...
+     * @param keyName      the name of the key in the encoded map for each key-element entry
+     * @param keyCodec     codec for the key
+     * @param elementName  the name of the element in the encoded map for each key-element entry
+     * @param elementCodec codec for the element
+     * @param <K>          the key type
+     * @param <V>          the element type
+     * @return a codec for an unbounded map
+     */
+    public static <K, V> Codec<Map<K, V>> unboundedMapAsList(String keyName, Codec<K> keyCodec, String elementName, Codec<V> elementCodec) {
+        Codec<Pair<K, V>> pairCodec = RecordCodecBuilder.create(
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java]: This is not blocking, but you could use `Map.Entry` directly and then `Map#ofEntries` to avoid the streams.

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java (hunk 2 above)
Comment (sciwhiz12) [reply src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java]: I used `"key"` and `"element"` because `Codec#unboundedMap` uses those names for its two parameter codecs: `keyCodec` and `elementCodec`.

As for the existence of this method, I added it for convenience. I can just remove it if that's wanted, since even in this PR I used explicit names.

Comment (Matyrobbrt) [reply src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java]: I would remove it to encourage the use of descriptive names.

**Review by Matyrobbrt — APPROVED** [review]
