### PR TITLE
Fix Vanilla clients crashing the server due to updated server config sync

### LINKED ISSUE #2221: [1.21.5] Server crash when trying to join NeoForge server with vanilla client
**Minecraft Version:** 1.21.5

**NeoForge Version:** Server has 21.5.55-beta, client is vanilla

**Logs:** Crash report: https://pastebin.com/2TTxWhHg

**Steps to Reproduce:**
 1. Start a NeoForge dedicated server with NF 21.5.55-beta and no additional mods
 2. Start a vanilla 1.21.5 client
 3. Try to join the server with your client
 4. Observe the server crashing, and the client being disconnected

**Description of issue:**
There's a non-zero chance I just have a messed-up vanilla client or something, because NF configs suddenly crashing on me is very unexpected, so if someone else could try to reproduce this, it'd be appreciated

### LINKED ISSUE #2223: [1.21.5] Console error when joining dedicated NeoForge server
**Minecraft Version:** 1.21.5

**NeoForge Version:** 21.5.55-beta, both client and server

**Logs:** Error message: https://pastebin.com/TftaRvNP

**Steps to Reproduce:**
 1. Start a NeoForge dedicated server with NF 21.5.55-beta and no additional mods
 2. Start a NeoForge 21.5.55-beta client, no additional mods
 3. Join the server with your client (joining works as usual)
 4. Observe a long error message/stacktrace being printed in the clientside log

**Description of issue:**
I'm not very well versed with NF configuration options, I don't know if this error has an actual effect on how the game behaves, I assume it doesn't.

### PR DESCRIPTION
**Pull request by shartte**
Also skips re-syncing configs that are in-memory which prevents logging pointless exceptions on a client receiving synchronized configs.

Fixes #2221
Fixes #2223

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/network/ConfigSync.java [hunk 1]
```diff
@@ -78,9 +78,14 @@ public static void registerEventListeners() {
                         return;
                     }
 
+                    var configFormat = loadedConfig.config().configFormat();
+                    if (configFormat.isInMemory()) {
+                        return; // An in-memory format indicates that we received this config from a server and shouldn't try to sync it
+                    }
+
                     // Write config bytes and queue for syncing to all connected players.
                     // This is harmless client-side, as the configsToSync map is either empty or full of stale connections.
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/network/ConfigSync.java]: This comment is now outdated.

**Review by Technici4n — DISMISSED** [review]

**Review by Technici4n — APPROVED** [review]
