### PR TITLE
[1.21.10] Add Method to get Raw Child from Value Input

### LINKED ISSUE #2728: Attachments on BlockEntities fail to deserialize when empty due to something like Optional.
**Minecraft Version:** `1.21.10` (Though this is likely true since the `ValueInput` system was introduced into the Attachment system)

**NeoForge Version:** `21.10.8-beta`

**Steps to Reproduce:**
 1. Create a Codec that has an optional field such that the object can be essentially resulting in an empty compoundtag `{}`
 2. Using an attachment with said codec, attach it to a block entity
 3. Deserialize (which usually is easiest by stopping world then loading world)
 4. The log will have a deserialization issue.

Easiest codec is roughly 
```java
    private static final MapCodec<Thing> MAP_CODEC = RecordCodecBuilder.mapCodec(builder -> builder.group(
            CODEC.optionalFieldOf("thing").forGetter(data -> Optional.ofNullable(data.thing)))
    ).apply(builder, Thing::new));
```

**Description of issue:**
It would seem that for block entities when they go to `loadAdditional`, Codecs that could have optional fields such that the object would effectively be empty on disk, will throw due to the empty child being returned in the input reads.

```java
protected final void deserializeAttachments(ValueInput input) {
    ...
    getAttachmentMap().put(type, type.serializer.read(getExposedHolder(), input.childOrEmpty(key))); // The input passed in here will result in an issue in the serializer's read.
    ....
```

### PR DESCRIPTION
**Pull request by ChampionAsh5357**
Closes #2728 

Internally, `TagValueInput` wraps most objects and lists returning a new input through `TagValueInput#wrapChild`, which checks whether the backing tag is empty. If so, it returns an empty context as for most use cases, it's considered to be 'nothing exists'. However, modders may provide a different meaning to nothing exists, most prominently for data attachments. As such, a new method: `rawChildOrEmpty` is added to get the raw output of the input rather than attempting to wrap and resolve to an existing input.

Technically, this is one solution to do so, and it only implements the one method for handling the attachment holder use case. There are technically other solutions and implementations that could be done to make this feature complete, but for simplicity, only the one method was added to fix the underlying bug as the other implementations are generally sufficient enough.

### CODE REVIEW

**Comment by Technici4n** [comment]
What are your thoughts on checking if the ValueInput is empty in the codec implementation of the attachment serializer?

**Review by Technici4n — CHANGES_REQUESTED** [review]
In any case please add a test (junit should hopefully do)

**Comment by ChampionAsh5357** [comment]
> What are your thoughts on checking if the ValueInput is empty in the codec implementation of the attachment serializer?

I've thought about that, but the problem is an empty input does not necessarily mean a default value. We could do something similar where we attempt to deserialize an empty compound tag, but I wanted to avoid having specific implementations in what's supposed to be an abstraction.

**Review by marchermans — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/common/extensions/ValueInputExtension.java [hunk 1]
```diff
@@ -37,4 +37,19 @@ default Set<String> keySet() {
     default void readChild(String key, ValueIOSerializable object) {
         self().child(key).ifPresent(object::deserialize);
     }
+
+    /**
+     * Reads the {@code child} object from the given {@code key},
+     * or provides an empty {@link ValueInput} if the child does not exist.
+     * Unlike {@link ValueInput#childOrEmpty(String)}, this will not attempt
+     * to use an empty context if no data exists in the backing object.
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/common/extensions/ValueInputExtension.java]: It will use an empty context if there is no such child. The difference is only if there exists a child (e.g. as reported by `keySet()`) that is empty. So I think the javadoc needs updating. You could also mention explicitly that this can be used when deserializing an empty but present tag with a codec.

File: tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java [hunk 2]
```diff
@@ -158,4 +167,73 @@ static void dynamicDataContentSerialization(DynamicTest test, RegistrationHelper
...
+    static void pseudoEmptyAttachmentSerialization(DynamicTest test, RegistrationHelper reg) {
+        class EmptyObject {
+            @Nullable
+            public Integer value;
+
+            public EmptyObject(Optional<Integer> value) {
+                this.value = value.orElse(null);
+            }
+
+            @Override
```
Comment (Technici4n) [inline tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java]: Why did you override equals? Better do an `Object.equals(a.value, b.value)` later in the test.

File: tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java [hunk 3]
```diff
@@ -158,4 +167,73 @@ static void dynamicDataContentSerialization(DynamicTest test, RegistrationHelper
             helper.succeed();
         });
     }
+
+    @TestHolder(description = "Tests serialization for an empty object", enabledByDefault = true)
```
Comment (Technici4n) [inline tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java]: You could link the corresponding github issue since this is a regression test for it.

File: tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java [hunk 4]
```diff
@@ -158,4 +167,73 @@ static void dynamicDataContentSerialization(DynamicTest test, RegistrationHelper
...
+            }
+
+            @Override
+            public boolean equals(Object obj) {
+                if (!(obj instanceof EmptyObject empty)) return false;
+                return Objects.equals(this.value, empty.value);
+            }
+        }
+
+        class HolderTest extends AttachmentHolder implements ValueIOSerializable {
```
Comment (Technici4n) [inline tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java]: This is a TestHolder, not a HolderTest

Comment (Technici4n) [inline tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java]: Why does it implement ValueIOSerializable?

File: tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java [hunk 5]
```diff
@@ -158,4 +167,73 @@ static void dynamicDataContentSerialization(DynamicTest test, RegistrationHelper
...
+            public void deserialize(ValueInput input) {
+                this.deserializeAttachments(input);
+            }
+        }
+
+        var nullableAttachment = reg.attachments()
+                .register("nullable_attachment", () -> AttachmentType.builder(() -> new EmptyObject(Optional.of(1)))
+                        .serialize(RecordCodecBuilder.mapCodec(
+                                instance -> instance.group(
+                                        Codec.INT.optionalFieldOf("value").forGetter(obj -> Optional.ofNullable(obj.value))).apply(instance, EmptyObject::new)))
```
Comment (Technici4n) [inline tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java]: I wonder if an optional that would default to 0 would spare you from all the Optional stuff, both here and in the class above.

File: tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java [hunk 6]
```diff
@@ -158,4 +167,73 @@ static void dynamicDataContentSerialization(DynamicTest test, RegistrationHelper
...
+            originalHolder.setData(nullableAttachment, new EmptyObject(Optional.empty()));
+
+            var output = TagValueOutput.createWithContext(ProblemReporter.DISCARDING, lookup);
+            originalHolder.serializeAttachments(output);
+
+            var anotherHolder = new HolderTest();
+            try {
+                // Try to deserialize
+                anotherHolder.deserialize(TagValueInput.create(ProblemReporter.DISCARDING, lookup, output.buildResult()));
+            } catch (Exception e) {
```
Comment (Technici4n) [inline tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java:201]: What's the point of this? The test will fail anyway if there is an exception.

**Review by Technici4n — COMMENTED** [review]
Nitpicky review, sorry not sorry 🙈

File: tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java (hunk 4 above)
Comment (sciwhiz12) [reply tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java]: I believe that would cause all the existing references to the `@TestHolder` annotation to require the fully-qualified name.

Comment (Technici4n) [reply tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java]: Ah yes. Maybe TestAttachmentHolder then

File: tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java (hunk 5 above)
Comment (ChampionAsh5357) [reply tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java]: Honestly, probably.

File: tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java (hunk 6 above)
Comment (ChampionAsh5357) [reply tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java:201]: The test doesn't fail, but it also doesn't succeed either, leaving it as an incomplete test. The point is to purposely mark the test as failed so that the error is caught as part of the failure message rather than searching for such a log.

Comment (Technici4n) [reply tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java:201]: I would remove the try/catch (it really should fail the test), but 🤷 this also works for me.

File: src/main/java/net/neoforged/neoforge/common/extensions/ValueInputExtension.java [hunk 7]
```diff
@@ -37,4 +37,20 @@ default Set<String> keySet() {
     default void readChild(String key, ValueIOSerializable object) {
         self().child(key).ifPresent(object::deserialize);
     }
+
+    /**
+     * Reads the {@code child} object from the given {@code key},
+     * or provides an empty {@link ValueInput} if the child does not exist.
+     * Unlike {@link ValueInput#childOrEmpty(String)}, this will not return
+     * an empty context if there are no keys (as reported by {@link #keySet()}),
+     * within the child.
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/common/extensions/ValueInputExtension.java]: Is this clearer?
```suggestion
     * This function behaves differently than {@link ValueInput#childOrEmpty(String)}
     * in the case where the child exists (as reported by {@link #keySet()}) but is empty.
     * While {@link ValueInput#childOrEmpty(String)} will return an empty {@code ValueInput}
     * from which nothing can ever be read with a codec, this function will instead return a
     * a wrapper around the empty child, allowing values to be read with a codec,
     * provided that the codec can deserialize empty map-like objects.
```

**Review by Technici4n — APPROVED** [review]
