### PR TITLE
[1.21.4] Expose vanilla model generators for modded usages

### LINKED ISSUE #1742: [1.21.4] Missing json files when generating Item Models
**Minecraft Version:** 1.21.4

**NeoForge Version:** 21.4.7-beta

**Logs:** no logs

**Steps to Reproduce:**
 1. Create a class that extends the ItemModelProvider
 2. use ``basicItem()`` to generate an Item Model

**Description of issue:**
The problem here is that it only generates the json file inside the ``assets/mod_id/models/item`` directory but not the ``ItemModelModifier`` json inside the ``assets/mod_id/items`` directory.
Also there is currently no way to alter the Modifier for items

### PR DESCRIPTION
**Pull request by ApexModder**
Updated version of #1696 for `1.21.4`.

While the vanilla providers have been exposed for modded usage, and can be used for more simpler model generation. This is still highly WIP and requires more patches to support our model extensions and generating a model from scratch.

### CODE REVIEW

**Comment by ApexModder** [comment]
Merged in @XFactHD [fork](https://github.com/ApexModder/NeoForge/pull/1), everything should be exposed and usable. Test mod datagen just needs rewriting to now use vanilla model providers.

**Comment by ApexModder** [comment]
This PR should now be ready for view but important note `ExtendedModelTemplate.Builder` may still get some major reworking to lessen the amount of nesting/`.end` calls.
Thinking of refactoring into lambda style rather than builder style.

Meaning that the following
`ExtendedModelTemplate.builder().element().end()`

would change to something like so
`ExtendedModelTemplate.builder().element(element -> { })`

File: patches/net/minecraft/client/data/models/ItemModelOutput.java.patch [hunk 1]
```diff
@@ -0,0 +1,10 @@
+--- a/net/minecraft/client/data/models/ItemModelOutput.java
++++ b/net/minecraft/client/data/models/ItemModelOutput.java
+@@ -10,4 +_,7 @@
+     void accept(Item p_387543_, ItemModel.Unbaked p_386880_);
+ 
+     void copy(Item p_387316_, Item p_387995_);
++
++    default void register(Item item, net.minecraft.client.renderer.item.ClientItem clientItem) {
```
Comment (XFactHD) [inline patches/net/minecraft/client/data/models/ItemModelOutput.java.patch:11]: This should have a comment mentioning that Neo pulls this up into the interface to allow mods to control the entire `ClientItem` for an item and not just the `ItemModel.Unbaked` it uses.

File: patches/net/minecraft/client/data/models/ModelProvider.java.patch [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+ 
+ @OnlyIn(Dist.CLIENT)
+-public class ModelProvider implements DataProvider {
++public class ModelProvider implements DataProvider, net.neoforged.neoforge.common.extensions.IModelProviderExtension {
+     private final PackOutput.PathProvider blockStatePathProvider;
+     private final PackOutput.PathProvider itemInfoPathProvider;
+     private final PackOutput.PathProvider modelPathProvider;
++    public final String modId;
+ 
++    // NeoForge: Use the above constructor passing in their mod id
```
Comment (XFactHD) [inline patches/net/minecraft/client/data/models/ModelProvider.java.patch]: The constructor is below now.

File: patches/net/minecraft/client/data/models/ModelProvider.java.patch [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+     @OnlyIn(Dist.CLIENT)
+     static class BlockStateGeneratorCollector implements Consumer<BlockStateGenerator> {
+         private final Map<Block, BlockStateGenerator> generators = new HashMap<>();
++        private final Supplier<Stream<? extends Holder<Block>>> knownBlocks;
++
++        public BlockStateGeneratorCollector(Supplier<Stream<? extends Holder<Block>>> knownBlocks) {
++            this.knownBlocks = knownBlocks;
++        }
++
++        public BlockStateGeneratorCollector() {
```
Comment (XFactHD) [inline patches/net/minecraft/client/data/models/ModelProvider.java.patch:84]: This constructor should be deprecated.

File: patches/net/minecraft/client/data/models/ModelProvider.java.patch [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+     static class ItemInfoCollector implements ItemModelOutput {
+         private final Map<Item, ClientItem> itemInfos = new HashMap<>();
+         private final Map<Item, Item> copies = new HashMap<>();
++        private final Supplier<Stream<? extends Holder<Item>>> knownItems;
++
++        public ItemInfoCollector(Supplier<Stream<? extends Holder<Item>>> knownItems) {
++            this.knownItems = knownItems;
++        }
++
++        public ItemInfoCollector() {
```
Comment (XFactHD) [inline patches/net/minecraft/client/data/models/ModelProvider.java.patch:113]: This constructor should be deprecated.

File: patches/net/minecraft/client/data/models/ModelProvider.java.patch [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
++        itemModels.run();
++    }
++
++    protected Stream<? extends Holder<Block>> getKnownBlocks() {
++        return BuiltInRegistries.BLOCK.listElements().filter(holder -> holder.getKey().location().getNamespace().equals(modId));
++    }
++
++    protected Stream<? extends Holder<Item>> getKnownItems() {
++        return BuiltInRegistries.ITEM.listElements().filter(holder -> holder.getKey().location().getNamespace().equals(modId));
+     }
```
Comment (XFactHD) [inline patches/net/minecraft/client/data/models/ModelProvider.java.patch]: These two methods should have a doc comment mentioning that they should return a stream of all blocks and items respectively for which this generator creates models and maybe also that either can return an empty stream if the generator is used to only generate either block or item models (i.e. if you use a separate provider for pure non-`BlockItem` items).

File: patches/net/minecraft/client/data/models/model/ModelTemplate.java.patch [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+@@ -52,6 +_,12 @@
+     public ResourceLocation create(ResourceLocation p_388380_, TextureMapping p_387099_, BiConsumer<ResourceLocation, ModelInstance> p_387748_) {
+         Map<TextureSlot, ResourceLocation> map = this.createMap(p_387099_);
+         p_387748_.accept(p_388380_, () -> {
++            return createBaseTemplate(p_388380_, map);
++        });
++        return p_388380_;
++    }
++
++    public JsonObject createBaseTemplate(ResourceLocation p_388380_, Map<TextureSlot, ResourceLocation> map) {
```
Comment (XFactHD) [inline patches/net/minecraft/client/data/models/model/ModelTemplate.java.patch:13]: This method should have a comment mentioning that it's intended to allow subclasses of `ModelTemplate` to customize serialization.

File: patches/net/minecraft/client/data/models/model/ModelTemplate.java.patch [hunk 7]
```diff
@@ -0,0 +1,31 @@
...
+             return jsonobject;
+-        });
+-        return p_388380_;
+     }
+ 
+     private Map<TextureSlot, ResourceLocation> createMap(TextureMapping p_387972_) {
+         return Streams.concat(this.requiredSlots.stream(), p_387972_.getForced()).collect(ImmutableMap.toImmutableMap(Function.identity(), p_387972_::get));
++    }
++
++    public net.neoforged.neoforge.client.model.generators.template.ExtendedModelTemplateBuilder extend() {
```
Comment (XFactHD) [inline patches/net/minecraft/client/data/models/model/ModelTemplate.java.patch:30]: I'm not quite happy with the name of this method, it was just the first thing I could think of when I implemented this. I currently can't think of any better name, maybe someone else has a better idea.
This method should ideally also have a short comment explaining what one can do with this.

File: patches/net/minecraft/client/data/models/model/TextureMapping.java.patch [hunk 8]
```diff
@@ -0,0 +1,14 @@
+--- a/net/minecraft/client/data/models/model/TextureMapping.java
++++ b/net/minecraft/client/data/models/model/TextureMapping.java
+@@ -412,4 +_,11 @@
+         ResourceLocation resourcelocation = BuiltInRegistries.ITEM.getKey(p_386842_);
+         return resourcelocation.withPath(p_387396_ -> "item/" + p_387396_ + p_386898_);
+     }
++
++    public TextureMapping copy() {
```
Comment (XFactHD) [inline patches/net/minecraft/client/data/models/model/TextureMapping.java.patch:9]: This method should have a comment to indicate that it's added by Neo.

File: src/main/java/net/neoforged/neoforge/client/extensions/IBlockModelGeneratorExtensions.java [hunk 9]
```diff
@@ -0,0 +1,117 @@
...
+
+import net.minecraft.client.data.models.BlockModelGenerators;
+import net.minecraft.client.data.models.blockstates.MultiVariantGenerator;
+import net.minecraft.client.data.models.model.ModelLocationUtils;
+import net.minecraft.client.data.models.model.ModelTemplates;
+import net.minecraft.client.data.models.model.TextureMapping;
+import net.minecraft.world.level.block.Block;
+import net.minecraft.world.level.block.state.properties.BlockStateProperties;
+
+public interface IBlockModelGeneratorExtensions {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/extensions/IBlockModelGeneratorExtensions.java]: All methods in this class should have a short doc comment mentioning that they are standalone versions of the respective methods in `BlockStateGenerators.BlockFamilyProvider`.
The interface's name should also match the target class's name exactly to avoid confusion.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/ExtendedModelTemplateBuilder.java [hunk 10]
```diff
@@ -0,0 +1,178 @@
...
+
+    public ExtendedModelTemplateBuilder suffix(String suffix) {
+        this.suffix = Optional.of(suffix);
+        return this;
+    }
+
+    public ExtendedModelTemplateBuilder requiredTextureSlot(TextureSlot slot) {
+        this.requiredSlots.add(slot);
+        return this;
+    }
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/ExtendedModelTemplateBuilder.java]: These methods need some short doc comments about what they are for, particularly the suffix and texture slot ones as they have a significant impact on the serialization behaviour of the template.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/ExtendedModelTemplateBuilder.java [hunk 11]
```diff
@@ -0,0 +1,178 @@
...
+    public ExtendedModelTemplateBuilder element(Consumer<ElementBuilder> action) {
+        Preconditions.checkState(
+                customLoader == null || customLoader.allowInlineElements,
+                "Custom model loader %s does not support inline elements",
+                customLoader != null ? customLoader.loaderId : null);
+        ElementBuilder ret = new ElementBuilder();
+        action.accept(ret);
+        elements.add(ret);
+        return this;
+    }
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/ExtendedModelTemplateBuilder.java]: These methods need some short doc comments and the `ao()` method should be renamed to `ambientOcclusion()` for clarity.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/ElementBuilder.java [hunk 12]
```diff
@@ -0,0 +1,257 @@
...
+
+    private static void validateCoordinate(float coord, char name) {
+        Preconditions.checkArgument(!(coord < -16.0F) && !(coord > 32.0F), "Position " + name + " out of range, must be within [-16, 32]. Found: %d", coord);
+    }
+
+    private static void validatePosition(Vector3f pos) {
+        validateCoordinate(pos.x(), 'x');
+        validateCoordinate(pos.y(), 'y');
+        validateCoordinate(pos.z(), 'z');
+    }
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/ElementBuilder.java]: It would be nice to move these methods to the bottom of the class as they are just noise to someone reading the class to grasp its API surface.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/ExtendedModelTemplateBuilder.java [hunk 13]
```diff
@@ -0,0 +1,178 @@
...
+
+    public ExtendedModelTemplateBuilder rootTransforms(Consumer<RootTransformsBuilder> action) {
+        action.accept(rootTransforms);
+        return this;
+    }
+
+    public ExtendedModelTemplate build() {
+        return new ExtendedModelTemplate(this);
+    }
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/ExtendedModelTemplateBuilder.java]: These methods need short doc comments, particularly the root transforms one to differentiate it from the other transforms method.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/FaceBuilder.java [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+    public FaceBuilder texture(TextureSlot texture) {
+        Preconditions.checkNotNull(texture, "Texture must not be null");
+        this.texture = texture;
+        return this;
+    }
+
+    public FaceBuilder uvs(float u1, float v1, float u2, float v2) {
+        this.uvs = new float[] { u1, v1, u2, v2 };
+        return this;
+    }
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/FaceBuilder.java]: The three methods missing docs need short doc comments.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/RotationBuilder.java [hunk 15]
```diff
@@ -0,0 +1,70 @@
...
+        return this;
+    }
+
+    BlockElementRotation build() {
+        Preconditions.checkNotNull(origin, "No origin specified");
+        Preconditions.checkNotNull(axis, "No axis specified");
+        return new BlockElementRotation(origin, axis, angle, rescale);
+    }
+
+    public RotationBuilder copy() {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/RotationBuilder.java]:
```suggestion
    RotationBuilder copy() {
```

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/TransformsBuilder.java [hunk 16]
```diff
@@ -0,0 +1,42 @@
...
+        return this;
+    }
+
+    Map<ItemDisplayContext, ItemTransform> build() {
+        return this.transforms.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> e.getValue().build(), (k1, k2) -> {
+            throw new IllegalArgumentException();
+        }, LinkedHashMap::new));
+    }
+
+    public void copyFrom(TransformsBuilder builder) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/TransformsBuilder.java]:
```suggestion
    void copyFrom(TransformsBuilder builder) {
```

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/ElementBuilder.java [hunk 17]
```diff
@@ -0,0 +1,257 @@
...
+            this.rotation = new RotationBuilder();
+        }
+        action.accept(rotation);
+        return this;
+    }
+
+    public ElementBuilder shade(boolean shade) {
+        this.shade = shade;
+        return this;
+    }
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/ElementBuilder.java]: These should have short doc comments, particularly shade as that seems to be something that regularly confuses people in relation to AO.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/RootTransformsBuilder.java [hunk 18]
```diff
@@ -0,0 +1,282 @@
...
+     * @throws NullPointerException     if {@code origin} is {@code null}
+     * @throws IllegalArgumentException if {@code origin} is not {@code center}, {@code corner} or {@code opposing-corner}
+     */
+    public RootTransformsBuilder origin(TransformationHelper.TransformOrigin origin) {
+        this.origin = Preconditions.checkNotNull(origin, "Origin must not be null");
+        this.originVec = null;
+        return this;
+    }
+
+    public JsonObject toJson() {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/RootTransformsBuilder.java]:
```suggestion
    JsonObject toJson() {
```

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/RootTransformsBuilder.java [hunk 19]
```diff
@@ -0,0 +1,282 @@
...
+    private static JsonArray writeQuaternion(Quaternionf quaternion) {
+        JsonArray array = new JsonArray();
+        array.add(quaternion.x());
+        array.add(quaternion.y());
+        array.add(quaternion.z());
+        array.add(quaternion.w());
+        return array;
+    }
+
+    public void copyFrom(RootTransformsBuilder other) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/RootTransformsBuilder.java]:
```suggestion
    void copyFrom(RootTransformsBuilder other) {
```

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/RotationBuilder.java [hunk 20]
```diff
@@ -0,0 +1,70 @@
...
+
+public final class RotationBuilder {
+    @Nullable
+    private Vector3f origin;
+    @Nullable
+    private Direction.Axis axis;
+    private float angle;
+    private boolean rescale;
+
+    public RotationBuilder origin(float x, float y, float z) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/RotationBuilder.java:26]: This method should have a doc comment explaining that this defines the point around which the element will be rotated.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/RotationBuilder.java [hunk 21]
```diff
@@ -0,0 +1,70 @@
...
+     * @throws IllegalArgumentException if {@code angle} is invalid (not one of 0, +/-22.5, +/-45)
+     */
+    public RotationBuilder angle(float angle) {
+        // Same logic from BlockPart.Deserializer#parseAngle
+        Preconditions.checkArgument(angle == 0.0F || Mth.abs(angle) == 22.5F || Mth.abs(angle) == 45.0F, "Invalid rotation %f found, only -45/-22.5/0/22.5/45 allowed", angle);
+        this.angle = angle;
+        return this;
+    }
+
+    public RotationBuilder rescale(boolean rescale) {
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/RotationBuilder.java:57]: This method should have a short doc comment explaining what rescaling means in context of the applied rotation.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/TransformVecBuilder.java [hunk 22]
```diff
@@ -0,0 +1,62 @@
...
+
+    public TransformVecBuilder scale(float x, float y, float z) {
+        this.scale = new Vector3f(x, y, z);
+        return this;
+    }
+
+    public TransformVecBuilder rightRotation(float x, float y, float z) {
+        this.rightRotation = new Vector3f(x, y, z);
+        return this;
+    }
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/TransformVecBuilder.java]: These methods should have short doc comments, particularly for `rotation()` and `rightRotation()`.
I think `leftRotation()` should also be removed as it provides no real benefit and `rotation()` being the left rotation can instead be clarified in its docs.

**Review by XFactHD — CHANGES_REQUESTED** [review]
A couple more comments, primarily about documentation.
When these are adressed, this PR is good to go from my end. The approval and merge has to be done by someone else as this PR adds code I wrote.

**Comment by ApexModder** [comment]
@XFactHD just pushed changes for all comments aside from `rootTransforms` and `rescale` javadocs as im unsure what these do myself.

Also left the `extend` method as is, as im unsure of a better name myself.

File: src/main/resources/META-INF/injected-interfaces.json [hunk 23]
```diff
@@ -270,5 +273,14 @@
   ],
   "net/minecraft/world/level/biome/BiomeSpecialEffects$GrassColorModifier": [
     "net/neoforged/fml/common/asm/enumextension/IExtensibleEnum"
+  ],
+  "net/minecraft/client/data/models/model/TexturedModel": [
```
Comment (Matyrobbrt) [inline src/main/resources/META-INF/injected-interfaces.json]: Please put all of these in the section above (preferably alphabetically). This section is for enum extension.

**Review by Matyrobbrt — DISMISSED** [review]

File: src/main/resources/META-INF/injected-interfaces.json (hunk 23 above)
Comment (ApexModder) [reply src/main/resources/META-INF/injected-interfaces.json]: Wasnt aware it was split into sections, moved my ifaces to above the first enum extension iface hopefully thats the correct spot.

File: patches/net/minecraft/client/data/models/ModelProvider.java.patch [hunk 24]
```diff
@@ -0,0 +1,163 @@
...
++        registerModels(new BlockModelGenerators(modelprovider$blockstategeneratorcollector, modelprovider$iteminfocollector, modelprovider$simplemodelcollector), new ItemModelGenerators(modelprovider$iteminfocollector, modelprovider$simplemodelcollector));
+         modelprovider$blockstategeneratorcollector.validate();
+         modelprovider$iteminfocollector.finalizeAndValidate();
+         return CompletableFuture.allOf(
+-            modelprovider$blockstategeneratorcollector.save(p_387857_, this.blockStatePathProvider),
+-            modelprovider$simplemodelcollector.save(p_387857_, this.modelPathProvider),
+-            modelprovider$iteminfocollector.save(p_387857_, this.itemInfoPathProvider)
++                modelprovider$blockstategeneratorcollector.save(p_387857_, this.blockStatePathProvider),
++                modelprovider$simplemodelcollector.save(p_387857_, this.modelPathProvider),
++                modelprovider$iteminfocollector.save(p_387857_, this.itemInfoPathProvider)
```
Comment (XFactHD) [inline patches/net/minecraft/client/data/models/ModelProvider.java.patch]: Please revert this, it's purely a formatting change.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/TransformVecBuilder.java [hunk 25]
```diff
@@ -0,0 +1,79 @@
...
+    private Vector3f rightRotation = new Vector3f(ItemTransform.Deserializer.DEFAULT_ROTATION);
+
+    TransformVecBuilder(ItemDisplayContext type) {
+        // param unused for functional match
+    }
+
+    /**
+     * Sets the rotation for this transformation.
+     * <p>
+     * This is rotation is considered the "left rotation" when also using {@linkplain #rightRotation(float, float, float)}.
```
Comment (XFactHD) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/TransformVecBuilder.java]:
```suggestion
     * This rotation is considered the "left rotation" when also using {@linkplain #rightRotation(float, float, float)}.
```

File: patches/net/minecraft/client/data/models/ItemModelOutput.java.patch [hunk 26]
```diff
@@ -0,0 +1,11 @@
+--- a/net/minecraft/client/data/models/ItemModelOutput.java
++++ b/net/minecraft/client/data/models/ItemModelOutput.java
+@@ -10,4 +_,8 @@
+     void accept(Item p_387543_, ItemModel.Unbaked p_386880_);
+ 
+     void copy(Item p_387316_, Item p_387995_);
++
++    // Neo: Pulled up from 'ModelProvider.ItemInfoCollector' to give modders full control over the 'ClientItem' over the 'ItemModel.Unbacked' in '#accept'
```
Comment (XFactHD) [inline patches/net/minecraft/client/data/models/ItemModelOutput.java.patch]:
```suggestion
+    // Neo: Pulled up from 'ModelProvider.ItemInfoCollector' to give modders full control over the 'ClientItem' instead of just the 'ItemModel.Unbacked' in '#accept'
```

**Review by XFactHD — DISMISSED** [review]

**Comment by ApexModder** [comment]
PR should be ready for review and merge, only unresolved comment should be xfacts one about `ModelTemplate#extend` but we are both unsure of a more fitting name.

File: patches/net/minecraft/client/data/models/model/ModelTemplate.java.patch (hunk 7 above)
Comment (embeddedt) [reply patches/net/minecraft/client/data/models/model/ModelTemplate.java.patch:30]: `createExtendedModelTemplateBuilder` is more descriptive but also ridiculously long.

File: patches/net/minecraft/client/data/models/ItemModelOutput.java.patch (hunk 1 above)
Comment (marchermans) [reply patches/net/minecraft/client/data/models/ItemModelOutput.java.patch:11]: Please provide JDoc on what this method does or is supposed to do after it now has been pulled up.

We can not expect tools like Parchment to provide this to modders so we should be libraral here with the explanation even if that increases the patch size.

File: src/main/java/net/neoforged/neoforge/client/extensions/IBlockModelGeneratorsExtension.java [hunk 27]
```diff
@@ -0,0 +1,151 @@
...
+import net.minecraft.client.data.models.BlockModelGenerators;
+import net.minecraft.client.data.models.blockstates.MultiVariantGenerator;
+import net.minecraft.client.data.models.model.ModelLocationUtils;
+import net.minecraft.client.data.models.model.ModelTemplates;
+import net.minecraft.client.data.models.model.TextureMapping;
+import net.minecraft.data.BlockFamily;
+import net.minecraft.world.level.block.Block;
+import net.minecraft.world.level.block.state.properties.BlockStateProperties;
+
+public interface IBlockModelGeneratorsExtension {
```
Comment (marchermans) [inline src/main/java/net/neoforged/neoforge/client/extensions/IBlockModelGeneratorsExtension.java]: This extension is not strictly necessary.
It is possible to create a custom BlockFamily that is incomplete and use it to perform these generations

Comment (marchermans) [reply src/main/java/net/neoforged/neoforge/client/extensions/IBlockModelGeneratorsExtension.java]: Please remove it.

File: src/main/java/net/neoforged/neoforge/common/data/ExistingFileHelper.java
Comment (marchermans) [inline src/main/java/net/neoforged/neoforge/common/data/ExistingFileHelper.java:1]: When this originally was discussed we realised that this class is a very large hack that does not work well anymore in modern data gen.

We ripped it out of model and blockstate generation now, and should remove it from the rest as well.

Please mark this as Deprecated without removal date, so we keep an eye on this.

**Review by marchermans — CHANGES_REQUESTED** [review]

File: patches/net/minecraft/client/data/models/ItemModelOutput.java.patch [hunk 28]
```diff
@@ -0,0 +1,11 @@
+--- a/net/minecraft/client/data/models/ItemModelOutput.java
++++ b/net/minecraft/client/data/models/ItemModelOutput.java
+@@ -10,4 +_,8 @@
+     void accept(Item p_387543_, ItemModel.Unbaked p_386880_);
+ 
+     void copy(Item p_387316_, Item p_387995_);
++
++    // Neo: Pulled up from 'ModelProvider.ItemInfoCollector' to give modders full control over the 'ClientItem' instead of just the 'ItemModel.Unbacked' in '#accept'
```
Comment (ChampionAsh5357) [inline patches/net/minecraft/client/data/models/ItemModelOutput.java.patch]:
```suggestion
+    // Neo: Pulled up from 'ModelProvider.ItemInfoCollector' to give modders full control over the 'ClientItem' instead of just the 'ItemModel.Unbaked' in '#accept'
```

File: src/main/java/net/neoforged/neoforge/client/extensions/ITexturedModelExtension.java [hunk 29]
```diff
@@ -0,0 +1,30 @@
...
+package net.neoforged.neoforge.client.extensions;
+
+import java.util.function.UnaryOperator;
+import net.minecraft.client.data.models.model.ModelTemplate;
+import net.minecraft.client.data.models.model.TexturedModel;
+
+public interface ITexturedModelExtension {
+    default TexturedModel updateTemplate(UnaryOperator<ModelTemplate> modifier) {
+        return new TexturedModel(self().getMapping(), modifier.apply(self().getTemplate()));
+    }
```
Comment (ChampionAsh5357) [inline src/main/java/net/neoforged/neoforge/client/extensions/ITexturedModelExtension.java:18]: I feel like this needs some documentation to explain why `updateTemplate` makes sense, since the additional data used by the custom loaders is set on the template itself rather than the textures slots.

File: src/main/java/net/neoforged/neoforge/client/model/generators/loaders/DynamicFluidContainerModelBuilder.java
Comment (ChampionAsh5357) [inline src/main/java/net/neoforged/neoforge/client/model/generators/loaders/DynamicFluidContainerModelBuilder.java:1]: I feel like this could be moved to an extension method on `ItemModelGenerators` rather than being outright removed as it still is a neoforge-added item model.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/CustomLoaderBuilder.java [hunk 30]
```diff
@@ -76,4 +81,8 @@ public JsonObject toJson(JsonObject json) {
 
         return json;
     }
+
+    protected static void serializeNestedTemplate(ModelTemplate template, TextureMapping textures, Consumer<JsonElement> consumer) {
+        template.create(DUMMY, textures, (id, jsonSup) -> consumer.accept(jsonSup.get()));
+    }
```
Comment (ChampionAsh5357) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/CustomLoaderBuilder.java:93]: Documentation? I don't know what this would be for.

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]
A few minor things excluding what Orion said. I also removed my comments about the `ExistingFileHelper` if we are planning to strip it out.

File: src/main/java/net/neoforged/neoforge/client/model/generators/loaders/DynamicFluidContainerModelBuilder.java
Comment (XFactHD) [reply src/main/java/net/neoforged/neoforge/client/model/generators/loaders/DynamicFluidContainerModelBuilder.java:1]: The only reason custom model loaders have builders is because they aren't reversible and therefore not serializable. The dynamic fluid container model is a custom `ItemModel` now though and the associated `ItemModel.Unbaked` can just be instantiated and passed to `ItemModelOutput#register()`.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/CustomLoaderBuilder.java (hunk 30 above)
Comment (ApexModder) [reply src/main/java/net/neoforged/neoforge/client/model/generators/template/CustomLoaderBuilder.java:93]: Method was unused and thus has been removed, was told its better practice to now reference external files rather than inlining models like we used to, which this was used for in the past.

File: src/main/java/net/neoforged/neoforge/client/model/generators/loaders/DynamicFluidContainerModelBuilder.java
Comment (ChampionAsh5357) [reply src/main/java/net/neoforged/neoforge/client/model/generators/loaders/DynamicFluidContainerModelBuilder.java:1]: I understand. I just figured it would probably be easier to have a convenience method to create them, similar to all the methods in the model generator.

**Review by marchermans — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/FaceBuilder.java [hunk 31]
```diff
@@ -0,0 +1,135 @@
...
+
+    BlockElementFace build() {
+        if (this.texture == null) {
+            throw new IllegalStateException("A model face must have a texture");
+        }
+        return new BlockElementFace(cullface, tintindex, texture.toString(), new BlockFaceUV(uvs, rotation.rotation), new ExtraFaceData(this.color, this.blockLight, this.skyLight, this.hasAmbientOcclusion), new MutableObject<>());
+    }
+
+    FaceBuilder copy() {
```
Comment (Soaryn) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/FaceBuilder.java:124]: Is this missing the textureslot copy? Seems like we'd need to make a new template with the textures manually otherwise

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/FaceBuilder.java [hunk 32]
```diff
@@ -0,0 +1,135 @@
...
+import net.minecraft.core.Direction;
+import net.neoforged.neoforge.client.model.ExtraFaceData;
+import org.apache.commons.lang3.mutable.MutableObject;
+import org.jetbrains.annotations.Nullable;
+
+public final class FaceBuilder {
+    @Nullable
+    private Direction cullface;
+    private int tintindex = -1;
+    @Nullable
```
Comment (Soaryn) [inline src/main/java/net/neoforged/neoforge/client/model/generators/template/FaceBuilder.java:22]: Can it really be classified as `Nullable` if it errors when it is null? 
`build()` calls `.toString()`

Comment (ApexModder) [reply src/main/java/net/neoforged/neoforge/client/model/generators/template/FaceBuilder.java:22]: I mean yeah, internally it is null cause it has no initial value (what texture slot would you default every face to?) but all attempts for users to set the texture are null checked and the final `build` call also null checks the texture, making it a required non null field.

this is also how face builder has always functioned in the legacy modelgen code iirc and no ones had issues with it before as far as im aware.

File: patches/net/minecraft/client/data/models/BlockModelGenerators.java.patch [hunk 33]
```diff
@@ -0,0 +1,19 @@
...
++     * block instead of creating a model and blockstate file for it. Intended for use cases where the full block is
++     * separately generated or otherwise exists such as when a dummy {@link BlockFamily} is used to create additional
++     * variants for existing vanilla block families
++     */
++    public BlockModelGenerators.BlockFamilyProvider familyWithExistingFullBlock(Block fullBlock) {
++        var provider = new BlockModelGenerators.BlockFamilyProvider(TextureMapping.cube(fullBlock));
++        provider.fullBlock = ModelLocationUtils.getModelLocation(fullBlock);
++        return provider;
++    }
+ }
```
Comment (ChampionAsh5357) [inline patches/net/minecraft/client/data/models/BlockModelGenerators.java.patch:19]: Is there a reason this has to be a patch rather than a extension method? Or are we not planning on adding any common usages to the base generators?

Comment (ChampionAsh5357) [inline patches/net/minecraft/client/data/models/BlockModelGenerators.java.patch:19]: Is there a reason this has to be a patch rather than a extension method? Or are we not planning on adding any common usages to the base generators?

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/CustomLoaderBuilder.java (hunk 30 above)
Comment (ChampionAsh5357) [reply src/main/java/net/neoforged/neoforge/client/model/generators/template/CustomLoaderBuilder.java:93]: Is this supposed to be removed? Basing this off your previous comment.

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]
Just some quick comments based on my previous ones.

File: patches/net/minecraft/client/data/models/BlockModelGenerators.java.patch (hunk 33 above)
Comment (XFactHD) [reply patches/net/minecraft/client/data/models/BlockModelGenerators.java.patch:19]: It would (at least for now) be the only extension and doing it as a patch is simpler as an extension method would require exposing the `BlockFamilyProvider#fullBlock` field.

File: src/main/java/net/neoforged/neoforge/client/model/generators/template/CustomLoaderBuilder.java (hunk 30 above)
Comment (XFactHD) [reply src/main/java/net/neoforged/neoforge/client/model/generators/template/CustomLoaderBuilder.java:93]: Apex did remove it at first but it turned out that we'll need it for a subsequent PR, so it was added back and documented.

**Review by ChampionAsh5357 — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/common/data/ExistingFileHelper.java [hunk 34]
```diff
@@ -46,6 +45,7 @@
  * extra resource packs passed in via the {@code --existing} argument,
  * or mod resources via the {@code --existing-mod} argument.
  */
+@Deprecated(forRemoval = true, since = "1.21.4")
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/common/data/ExistingFileHelper.java:50]: Why is this deprecated for removal? There should likely be a comment explaining why, and what alternatives (if any) should be used instead.

File: src/main/resources/META-INF/injected-interfaces.json [hunk 35]
```diff
@@ -271,4 +279,4 @@
   "net/minecraft/world/level/biome/BiomeSpecialEffects$GrassColorModifier": [
     "net/neoforged/fml/common/asm/enumextension/IExtensibleEnum"
   ]
-}
+}
```
Comment (sciwhiz12) [inline src/main/resources/META-INF/injected-interfaces.json]: Is this removal of the newline intentional?

File: patches/net/minecraft/client/data/models/ModelProvider.java.patch [hunk 36]
```diff
@@ -0,0 +1,140 @@
+--- a/net/minecraft/client/data/models/ModelProvider.java
++++ b/net/minecraft/client/data/models/ModelProvider.java
+@@ -34,20 +_,58 @@
+     private final PackOutput.PathProvider blockStatePathProvider;
+     private final PackOutput.PathProvider itemInfoPathProvider;
+     private final PackOutput.PathProvider modelPathProvider;
++    public final String modId;
+ 
++    // NeoForge: Use the below constructor passing in your mod id
```
Comment (sciwhiz12) [inline patches/net/minecraft/client/data/models/ModelProvider.java.patch]: Convention is for comments in patches to use `Neo:`. Also, reword the comment to avoid using position, and instead refer to the additional parameter.
```suggestion
+    // Neo: Use the constructor which accepts a mod ID.
```

File: patches/net/minecraft/client/data/models/ModelProvider.java.patch [hunk 37]
```diff
@@ -0,0 +1,140 @@
...
+     @OnlyIn(Dist.CLIENT)
+     static class BlockStateGeneratorCollector implements Consumer<BlockStateGenerator> {
+         private final Map<Block, BlockStateGenerator> generators = new HashMap<>();
++        private final Supplier<Stream<? extends Holder<Block>>> knownBlocks;
++
++        public BlockStateGeneratorCollector(Supplier<Stream<? extends Holder<Block>>> knownBlocks) {
++            this.knownBlocks = knownBlocks;
++        }
++
++        @Deprecated // Neo: Provided for vanilla/multi-loader compatibility, use above constructor
```
Comment (sciwhiz12) [inline patches/net/minecraft/client/data/models/ModelProvider.java.patch]: Reword the comment to avoid using position, and instead refer to the additional parameter.
```suggestion
+        @Deprecated // Neo: Provided for vanilla/multi-loader compatibility. Use constructor with Supplier parameter.
```

File: patches/net/minecraft/client/data/models/ModelProvider.java.patch [hunk 38]
```diff
@@ -0,0 +1,140 @@
...
+     static class ItemInfoCollector implements ItemModelOutput {
+         private final Map<Item, ClientItem> itemInfos = new HashMap<>();
+         private final Map<Item, Item> copies = new HashMap<>();
++        private final Supplier<Stream<? extends Holder<Item>>> knownItems;
++
++        public ItemInfoCollector(Supplier<Stream<? extends Holder<Item>>> knownItems) {
++            this.knownItems = knownItems;
++        }
++
++        @Deprecated // Neo: Provided for vanilla/multi-loader compatibility, use above constructor
```
Comment (sciwhiz12) [inline patches/net/minecraft/client/data/models/ModelProvider.java.patch]: Reword the comment to avoid using position, and instead refer to the additional parameter.
```suggestion
+        @Deprecated // Neo: Provided for vanilla/multi-loader compatibility. Use constructor with Supplier parameter.
```

File: patches/net/minecraft/client/data/models/model/ModelLocationUtils.java.patch [hunk 39]
```diff
@@ -0,0 +1,18 @@
+--- a/net/minecraft/client/data/models/model/ModelLocationUtils.java
++++ b/net/minecraft/client/data/models/model/ModelLocationUtils.java
+@@ -11,11 +_,13 @@
+ public class ModelLocationUtils {
+     @Deprecated
+     public static ResourceLocation decorateBlockModelLocation(String p_388520_) {
+-        return ResourceLocation.withDefaultNamespace("block/" + p_388520_);
++        // NeoForge: Use ResourceLocation.parse to support modded paths
```
Comment (sciwhiz12) [inline patches/net/minecraft/client/data/models/model/ModelLocationUtils.java.patch]: Convention is for comments in patches to use `Neo:`.
```suggestion
+        // Neo: Use ResourceLocation.parse to support modded paths
```

File: patches/net/minecraft/client/data/models/model/ModelLocationUtils.java.patch [hunk 40]
```diff
@@ -0,0 +1,18 @@
...
++        return ResourceLocation.parse(p_388520_).withPrefix("block/");
+     }
+ 
+     public static ResourceLocation decorateItemModelLocation(String p_387226_) {
+-        return ResourceLocation.withDefaultNamespace("item/" + p_387226_);
++        // NeoForge: Use ResourceLocation.parse to support modded paths
```
Comment (sciwhiz12) [inline patches/net/minecraft/client/data/models/model/ModelLocationUtils.java.patch]: Convention is for comments in patches to use `Neo:`.
```suggestion
+        // Neo: Use ResourceLocation.parse to support modded paths
```

File: tests/src/main/java/net/neoforged/neoforge/debug/VanillaDataGenTest.java [hunk 41]
```diff
@@ -0,0 +1,68 @@
...
+import net.minecraft.world.level.block.state.BlockBehaviour;
+import net.neoforged.api.distmarker.Dist;
+import net.neoforged.testframework.DynamicTest;
+import net.neoforged.testframework.annotation.ForEachTest;
+import net.neoforged.testframework.annotation.TestHolder;
+import net.neoforged.testframework.registration.RegistrationHelper;
+
+@ForEachTest(groups = "vanilla_data_gen", side = Dist.CLIENT)
+public interface VanillaDataGenTest {
+    @TestHolder(description = "Tests the the patched vanilla model generators work for modded usages")
```
Comment (sciwhiz12) [inline tests/src/main/java/net/neoforged/neoforge/debug/VanillaDataGenTest.java]: Typo: double "the".
```suggestion
    @TestHolder(description = "Tests the patched vanilla model generators work for modded usages")
```

File: src/main/java/net/neoforged/neoforge/common/data/ExistingFileHelper.java (hunk 34 above)
Comment (ApexModder) [reply src/main/java/net/neoforged/neoforge/common/data/ExistingFileHelper.java:50]: Existing file helper afaik is officially dead and marked for removals with no planned alternative to be implemented. There have been talks however about a follow up pr to go over to fully make EFH optional/nullable everywhere.

**Review by sciwhiz12 — APPROVED** [review]
