### PR TITLE
Fix a bug where cancelling AnvilUpdateEvent didn't make output empty

### LINKED ISSUE #2227: [1.21.1+] Cannot forbid combining armors on anvil with AnvilUpdateEvent
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.83

**Steps to Reproduce:**
 1. Write this event handler:
```
    @SubscribeEvent
    public static void bugEvent(AnvilUpdateEvent event) {
        if (event.getLeft().is(Items.DIAMOND_BOOTS) && event.getRight().is(Items.DIAMOND_BOOTS)) {
            event.setCanceled(true);
        }
    }
```
 2. Open anvil menu in game
 3. Put boots on the left
 4. Type new name
 5. Put another boots on the right
 6. Get the output, and see that both inputs are destroyed.
Image

**Description of issue:**
I want to forbid combining armors on anvil while allowing renaming without manipulating the bytecode.

### PR DESCRIPTION
**Pull request by Sleepy-Horse**
Fix #2227
Add tests for this event

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/event/AnvilUpdateEvent.java [hunk 1]
```diff
@@ -13,12 +13,12 @@
...
 
 /**
- *
- * AnvilUpdateEvent is fired whenever the input stacks (left or right) or the name in an anvil changed. <br>
- * It is called from {@link AnvilMenu#createResult()}. <br>
- * If the event is canceled, vanilla behavior will not run, and the output will be set to {@link ItemStack#EMPTY}. <br>
- * If the event is not canceled, but the output is not empty, it will set the output and not run vanilla behavior. <br>
- * if the output is empty, and the event is not canceled, vanilla behavior will execute. <br>
+ * Fired when the anvil recalculates its output due to changes in either input slot or the item name,
+ * and the left slot contains an item that can store enchantments via data components. <br>
```
Comment (Shadows-of-Fire) [inline src/main/java/net/neoforged/neoforge/event/AnvilUpdateEvent.java]: >  left slot contains an item that can store enchantments via data components.  

That... doesn't really make any sense. Seems like the firing point is probably wrong?

Comment (Sleepy-Horse) [reply src/main/java/net/neoforged/neoforge/event/AnvilUpdateEvent.java]: Alternatively, we could move the firing point at the start of the function. In that case the event will actually fire for every input update, and it will be possible to create recipes with empty left slot. This is the solution I proposed in discord earlier.

**Comment by Technici4n** [comment]
Finally I will be able to remove this code from my mod?

```java
                event.setCanceled(true);
                // According to the documentation setCanceled should be all we need, but unfortunately we have to manually override the output and
                // cost too??
                if (event.getPlayer().containerMenu instanceof AnvilMenu anvilMenu) {
                    anvilMenu.getSlot(2).set(ItemStack.EMPTY);
                    anvilMenu.setMaximumCost(0);
                }
```
:D

**Comment by Shadows-of-Fire** [comment]
Hey, that means you've known about it for _how long_ :p

**Review by Shadows-of-Fire — APPROVED** [review]
