### PR TITLE
Replace CRLF line endings in mod list's details

### LINKED ISSUE #1316: Mod list renders special line ending characters
**Minecraft Version:** 1.21.0

**NeoForge Version:** 21.0.82-beta and above (tested up to 21.0.95-beta, current latest)

**Logs:** [latest.log](https://files.lostluma.net/U5CfQN.txt)

**Steps to Reproduce:**
 1. Install a mod that has newlines in the credits section
    In my case I installed this exact [Dynamic FPS version](https://modrinth.com/mod/dynamic-fps/version/AhFXokhh)
 2. Launch the game
 3. Open the mods list
 4. Click on the mod you downloaded
 5. See erroneous line ending characters rendered that should be invisible: [screenshot](https://files.lostluma.net/oSQJbE.png)

**Description of issue:**

Since `21.0.82-beta` the mod list renders the `cr` line ending character when viewing a mod which has a field with newlines.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Closes https://github.com/neoforged/NeoForge/issues/1316

This is a temporary dirty workaround until Sci's entire rework of the mod list screen. Tested using the person's mods.toml setup with a neo test mod to verify the line endings are replaced

### CODE REVIEW

**Review by Matyrobbrt — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java [hunk 1]
```diff
@@ -404,19 +403,19 @@ public void upload() {
...
 
         if (vercheck.status() == VersionChecker.Status.OUTDATED || vercheck.status() == VersionChecker.Status.BETA_OUTDATED)
-            lines.add(FMLTranslations.parseMessage("fml.menu.mods.info.updateavailable", vercheck.url() == null ? "" : vercheck.url()));
-        lines.add(FMLTranslations.parseMessage("fml.menu.mods.info.license", ((ModFileInfo) selectedMod.getOwningFile()).getLicense()));
+            lines.add(FMLTranslations.parseMessage("fml.menu.mods.info.updateavailable", vercheck.url() == null ? "" : vercheck.url()).replace("\r\n", "\n"));
+        lines.add(FMLTranslations.parseMessage("fml.menu.mods.info.license", selectedMod.getOwningFile().getLicense()).replace("\r\n", "\n"));
         lines.add(null);
-        lines.add(FMLTranslations.parseMessageWithFallback("fml.menu.mods.info.description." + selectedMod.getModId(), selectedMod::getDescription));
+        lines.add(FMLTranslations.parseMessageWithFallback("fml.menu.mods.info.description." + selectedMod.getModId(), selectedMod::getDescription).replace("\r\n", "\n"));
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java]: It seems this is unnecessary since `ModInfo`'s constructor (in FML) already normalizes CRLF line endings to LF. Should we add a comment for this?

Comment (TelepathicGrunt) [reply src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java]: Well, your followup PR will kill this code right? So this code won't be here much longer. That does explain why descriptions don't have this line ending issue in testing. I just added this just to be safe but yeah.

Comment (sciwhiz12) [reply src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java]: I think, since it might be a small while before I get my rewrite of the mod list screen in fully working order, it would be a good idea to add a comment at the top of all these changes that says that we're explicitly normalizing CRLF to LF since that is not automatically handled.

**Review by sciwhiz12 — APPROVED** [review]
Tested by using multiline strings in fields other than the description (which is already normalized in FML), and it works.
