### PR TITLE
Fix FinalizeSpawnEvent for trial spawners

### LINKED ISSUE #783: MobSpawnEvent.FinalizeSpawn with MobSpawnType.TRIAL_SPAWNER is not working
**Minecraft Version:** 1.20.4

**NeoForge Version:** 2.4.200

**Logs:** not have

**Steps to Reproduce:**
 1. write code on MobSpawnEvent.FinalizeSpawn with MobSpawnType.TRIAL_SPAWNER
 2. make spawn on Trial Spawner
 3. nothing happen

**Description of issue:** I found this while my mod debugging when I add about Trial Spawner mob. There is a possibility that I overlooked the process of Trial Spawner somewhere or it may not have been written.

### LINKED ISSUE #939: [All 1.20.X] finalizeSpawn() is always passed null SpawnGroupData
**Minecraft Version:** 1.20.1

**NeoForge Version:** 1.20.1-47.1.105

**Steps to Reproduce:**
Base game effects - Create a new world and look for plains/savannah to find a horse herd. Seed 3040816188384926459 has one right near spawn. Observe that the group has mismatched color and markings, whereas in vanilla would have all been the same base color with different markings.

Modding effects - Create a mob that spawns in groups and attempt to add custom finalizeSpawn() functionality. Observe that the SpawnGroupData passed in is always null, even though it should only be null for the first member of the group and after that should be the data returned by the previous call.

**Description of issue:**
When a mob's finalizeSpawn() is called, the SpawnGroupData passed in is always null, causing vanilla horse herds to spawn with mismatched colors and patterns and limiting what mods can do.

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
This PR allows the finalize spawn event to be fired with the proper context for Trial Spawners.  This was a bit annoying since `BaseSpawner` and `TrialSpawner` are totally disjoint objects, so we're left with `Either<BlockEntity, Entity>` as the "spawner" object.

This also moves the event from an inner class to a full class (`MobSpawnEvent.FinalizeSpawn` -> `FinalizeSpawnEvent`) and updates the documentation on related areas since it had been remarked as confusing.

Closes #783
Closes #939

### CODE REVIEW

File: patches/net/minecraft/world/entity/Mob.java.patch [hunk 1]
```diff
@@ -84,15 +84,12 @@
...
      }
  
 +    /**
-+     * Forge: Override-Only, call via EventHooks.onFinalizeSpawn.<br>
-+     * Overrides are allowed. Do not wrap super calls within override (as that will cause stack overflows).<br>
-+     * Vanilla calls are replaced with a transformer, and are not visible in source.<br>
-+     * <p>
++     * @deprecated Override-Only. External callers should call via {@link net.neoforged.neoforge.event.EventHooks#finalizeMobSpawn}.
 +     */
 +    @Deprecated
```
Comment (Technici4n) [inline patches/net/minecraft/world/entity/Mob.java.patch:94]: This could use `@ApiStatus.OverrideOnly` or something like that

File: src/main/java/net/neoforged/neoforge/event/EventHooks.java [hunk 2]
```diff
@@ -302,17 +313,31 @@ public static SpawnGroupData onFinalizeSpawn(Mob mob, ServerLevelAccessor level,
     }
 
     /**
-     * Returns the FinalizeSpawn event instance, or null if it was canceled.<br>
-     * This is separate since mob spawners perform special finalizeSpawn handling when NBT data is present, but we still want to fire the event.<br>
-     * This overload is also the only way to pass through a {@link BaseSpawner} instance.
+     * Finalizes the spawn of a mob by firing the {@link FinalizeSpawnEvent} and calling {@link Mob#finalizeSpawn} with the result.
+     * <p>
+     * This method is separate since mob spawners perform special finalizeSpawn handling when NBT data is present, but we still want to fire the event.
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/event/EventHooks.java:318]: Isn't spawn NBT data gone?

File: src/main/java/net/neoforged/neoforge/event/entity/living/FinalizeSpawnEvent.java [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+import net.minecraft.world.level.block.entity.TrialSpawnerBlockEntity;
+import net.neoforged.bus.api.ICancellableEvent;
+import net.neoforged.neoforge.common.NeoForge;
+import net.neoforged.neoforge.common.NeoForgeEventHandler;
+import net.neoforged.neoforge.event.EventHooks;
+import org.jetbrains.annotations.ApiStatus;
+import org.jetbrains.annotations.Nullable;
+
+/**
+ * This event is fired before {@link Mob#finalizeSpawn} is called.<br>
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/event/entity/living/FinalizeSpawnEvent.java:28]: `<br>` is bad practice. Use paragraphs where it makes sense, let the renderer take care of line breaks within paragraphs.

File: patches/net/minecraft/world/entity/Mob.java.patch (hunk 1 above)
Comment (Shadows-of-Fire) [reply patches/net/minecraft/world/entity/Mob.java.patch:94]: It is `@OverrideOnly` (see the line below).  It's also deprecated because IDE's only weakly respect `@OverrideOnly`.  This is generally what we apply to force-override-only methods.

File: src/main/java/net/neoforged/neoforge/event/EventHooks.java (hunk 2 above)
Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/event/EventHooks.java:318]: The `CompoundTag` that was present in `finalizeSpawn` is gone, but this line isn't referring to that.

This is referring to the fact that spawners do not normally call `finalizeSpawn` if a `SpawnData` object is present that contains more information than just the `id` key.

File: src/main/java/net/neoforged/neoforge/event/entity/living/FinalizeSpawnEvent.java (hunk 3 above)
Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/event/entity/living/FinalizeSpawnEvent.java:28]: This is just what was already there; I can go update it, but the event is unchanged aside from the `spawner` field

**Review by embeddedt — DISMISSED** [review]
Seems okay to me. @Technici4n?

**Comment by Technici4n** [comment]
Sure, go ahead.

File: src/main/java/net/neoforged/neoforge/event/EventHooks.java [hunk 4]
```diff
@@ -303,13 +303,13 @@ public static boolean checkSpawnPositionSpawner(Mob mob, ServerLevelAccessor lev
...
+        NeoForge.EVENT_BUS.post(event);
 
-        if (!cancel) {
-            mob.finalizeSpawn(level, event.getDifficulty(), event.getSpawnType(), event.getSpawnData());
+        if (!event.isCanceled()) {
+            return mob.finalizeSpawn(level, event.getDifficulty(), event.getSpawnType(), event.getSpawnData());
         }
 
-        return cancel ? null : event.getSpawnData();
+        return null;
```
Comment (embeddedt) [inline src/main/java/net/neoforged/neoforge/event/EventHooks.java:312]: The new implementation no longer allows mods to force custom `SpawnGroupData` from their event handler to be used.

Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/event/EventHooks.java:312]: It gets used by the `Mob#finalizeSpawn` call, which is then responsible for propagating it forward.  Typically those implementations just return the passed spawn group data.

**Review by embeddedt — APPROVED** [review]

**Review by XFactHD — APPROVED** [review]
