### PR TITLE
[1.21.4] Add support for double modifier keybinds

### LINKED ISSUE #2012: Double modifier key binds are broken since 1.19.2
**Minecraft Version:** {was able to reproduce on 1.21.1, 1.21.4}

**NeoForge Version:** {21.1.132, 21.4.109}

**Steps to Reproduce:**
 1. Open Options -> Controls -> Key Binds
 2. Try to set LShift + LCtrl keybind for Sneak
 3. Only last key saves. For this keybind: LCtrl 

**Description of issue:**
On 1.19.2 all worked fine. On 1.20.1 and later we can't set this keybind. Only last key saves.

Seems like NeoForge captured this issue from MinecraftForge 1.20.1(moment of creation), so issues are same: https://github.com/MinecraftForge/MinecraftForge/issues/10494

### PR DESCRIPTION
**Pull request by ChampionAsh5357**
Closes #2012 

Modifies the key lookup code to handle key mappings that use double modifiers (e.g. Ctrl + Shift). Most of the logic just goes towards allowing the key mappings to be pressed in any order while being removed properly from the associated map on release of either modifier.

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/client/settings/KeyModifier.java [hunk 1]
```diff
@@ -129,4 +183,9 @@ public static KeyModifier valueFromString(String stringValue) {
     public abstract boolean isActive(@Nullable IKeyConflictContext conflictContext);
 
     public abstract Component getCombinedName(InputConstants.Key key, Supplier<Component> defaultLogic);
+
+    // Neo: Make abstract in 1.21.5
+    public InputConstants.Key[] codes() {
+        return null;
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/client/settings/KeyModifier.java:190]: Seeing a `null` in a non-nullable place gives me the 👀, but since there's no genuine way this `null` can be received (without some enum-extending shenaniganry), this should be fine.

File: src/main/java/net/neoforged/neoforge/client/settings/KeyModifier.java [hunk 2]
```diff
@@ -90,10 +128,16 @@ public boolean isActive(@Nullable IKeyConflictContext conflictContext) {
...
+
+        @Override
+        public InputConstants.Key[] codes() {
+            return KEYS;
+        }
     };
 
     public static final KeyModifier[] MODIFIER_VALUES = { SHIFT, CONTROL, ALT };
 
+    @Deprecated(forRemoval = true, since = "1.21.4")
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/client/settings/KeyModifier.java:141]: Ideally, this should have a `/** @deprecated */` comment pointing to the new method.

File: patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch [hunk 3]
```diff
@@ -27,7 +27,7 @@
          if (this.selectedKey != null) {
 -            if (p_345810_ == 256) {
 +            var key = InputConstants.getKey(p_345810_, p_345447_);
-+            if (net.neoforged.neoforge.client.settings.KeyModifier.isKeyCodeModifier(key)) {
++            if (lastPressedModifier == InputConstants.UNKNOWN && net.neoforged.neoforge.client.settings.KeyModifier.isKeyCodeModifier(key)) {
```
Comment (sciwhiz12) [inline patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch:30]: What does this change do? I'm not quite sure.

File: src/main/java/net/neoforged/neoforge/client/settings/KeyMappingLookup.java [hunk 4]
```diff
@@ -31,13 +32,60 @@ public class KeyMappingLookup {
...
+        for (var modifier : activeModifiers) {
+            // If modifier matches, add other modifiers
+            if (modifier.matches(keyCode)) {
+                // Check if binding matches with another modifier
+                for (var key : activeModifiers) {
+
+                    // Skip if modifier matches
+                    if (key.matches(keyCode)) {
+                        continue;
+                    }
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/client/settings/KeyMappingLookup.java]: Couldn't this be replaced with a `key == modifier` condition instead? That more strongly gives the first-glance impression of "loop on all modifiers except the originally matched one". Unless we anticipate that multiple `KeyModifier`s might match on the same key code in the future (as they are all exclusive to each other for now).

I ask this since this threw me for a loop (ha) trying to understand what this nested loop was doing. Only after a few rereads did I realize what it does (at least, what it seems to me).

File: src/main/java/net/neoforged/neoforge/client/settings/KeyMappingLookup.java [hunk 5]
```diff
@@ -31,13 +32,60 @@ public class KeyMappingLookup {
...
+
+                    // Loop through all modifier codes
+                    for (var modifierKey : key.codes()) {
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/client/settings/KeyMappingLookup.java]: Could probably be named differently to reduce the association between `modifierKey` (which is derived from the nested loop) and `modifier` (from the outer loop). Perhaps `otherModifierCode`, with the `key` loop variable renamed as `otherModifier`?

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Tested and it seems to work. I just have some questions and potential changes.

File: src/main/java/net/neoforged/neoforge/client/settings/KeyModifier.java (hunk 1 above)
Comment (ChampionAsh5357) [reply src/main/java/net/neoforged/neoforge/client/settings/KeyModifier.java:190]: The reason I did this was to avoid breaking changes, but yeah, it should generally be changed in 1.21.5 to avoid such a null case.

File: patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch (hunk 3 above)
Comment (ChampionAsh5357) [reply patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch:30]: Basically, this makes sure that the user is not currently holding a modifier key before assigning it to the last pressed key. Otherwise, if this was not checked, then the user would not be able to select two modifier keys at once.

File: src/main/java/net/neoforged/neoforge/client/settings/KeyMappingLookup.java (hunk 4 above)
Comment (ChampionAsh5357) [reply src/main/java/net/neoforged/neoforge/client/settings/KeyMappingLookup.java]: Sure, I just need to rearrange a bit of the code to get the modifier first.

**Review by sciwhiz12 — APPROVED** [review]

**Comment by sciwhiz12** [comment]
@neoforged/bots backport 1.21.1
