### PR TITLE
Capture final target position for EnderMan & item teleport hook

### LINKED ISSUE #3113: EntityTeleportEvent.EnderEntity doesn't provide the final target Position
**Minecraft Version:** 26.1

**NeoForge Version:** 26.1.2.15-beta

**Steps to Reproduce:**
 1. Register an event listening to EntityTeleportEvent.EnderEntity
 2. Observe the target position is not necessarily where it is warping to. Sometimes higher or lower by rather extreme values. I have seen 30 blocks off

**Description of issue:**
I was trying to prevent endermen from warping into a very specific zone, but found that the event doesn't give us the final warp position, but rather the estimation. After the event runs it does the finalization of the warp target. I would prefer either we have another FinalizedEvent or move the call of this to have the corrected values. Otherwise we don't have a solid way to respond correctly to the warp events.

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #3113 by moving the `EntityTeleportEvent.EnderEntity` and `EntityTeleportEvent.ItemConsumption` hooks to `LivingEntity#randomTeleport`, which captures the proper final Y level.

The original locations of the teleport hooks do not provide the final Y level of the target position; for example, `EnderMan#teleport` only had a potential target position that isn't occupied by blocks. It is `LivingEntity#randomTeleport` which finds the Y level the entity can stand on and occupy, so the hook is moved there.

To move the `EntityTeleportEvent.ItemConsumption` hook, a new overload of `LivingEntity#teleport` was added with an additional context of the consumed item stack. If that is supplied, the event fired is `ItemConsumption`; otherwise, if the entity is an `Enderman`, the event fired is `EnderEntity`.

Partially tested by spawning endermen in the rain and seeing them teleport while breakpointing at the event hook, and seeing them teleport and scatter like normal.

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
If we're moving this into `LivingEntity#randomTeleport`, is there a reason we can't genericize the event for all living entities?

**Comment by sciwhiz12** [comment]
There would be some design considerations to be made there, like should we distinguish teleports by item consumption versus raw calls of the method, or (as @pupnewfster raised in [Discord in a conversation](https://discord.com/channels/313125603924639766/852298000042164244/1497240721747611698)) should we communicate the 'reason' for the teleport if possible and how would that be represented.

On that latter point, `EntityTeleportEvent` is structured such that each sub-event is its own 'reason': an event for `/spreadplayers`, an event for `/tp`, an event for EnderMan and Shulker, an event for ender pearl, and an event for item consumption.

We'd either have to surface a `reason` field (whose type is up for discussion), or make a sub-event that means "a random teleport for a living entity" with its own sub-events (EnderMan, cats for morning gifts, item consumption effects, maybe mod-specific sub-events), or make a sub-event that means "a random teleport by anything not encompassed above" which is then extended by mods.

I think for now, we can leave the scope of this PR to fixing the issues of the event's final target position, and leave it to another PR to figure out how best to genericize this event. (Also, I don't want to do more mork. :smile:)

**Comment by sciwhiz12** [comment]
Updated to also move the hook for `EntityTeleportEvent.ItemConsumption`, since it suffers from the same problem.

**Comment by ChampionAsh5357** [comment]
Gotcha. The only other thing I noticed is that this change would affect the behavior of the event slightly, where since we are modifying the final resolved Y value instead of the estimated Y, the teleportation would fail if the block at that Y blocks the teleport. I think that should either be a comment or an announcement in dev-annoucements to indicate this change.

Lmk which you want to do and I'll approve afterward.

File: patches/net/minecraft/world/entity/LivingEntity.java.patch [hunk 1]
```diff
@@ -642,6 +642,60 @@
...
++    // Neo: Add overload with the consumed item causing the random teleport
++    public boolean randomTeleport(double xx, double yy, double zz, boolean showParticles, ItemStack consumedStack) {
+         double xo = this.getX();
+         double yo = this.getY();
+         double zo = this.getZ();
+@@ -3573,6 +_,8 @@
+         boolean ok = false;
+         BlockPos pos = BlockPos.containing(xx, yy, zz);
+         Level level = this.level();
++        // Neo: Store whether we actually did a teleport to the target, to know when not to teleport back to the same back
```
Comment (XFactHD) [inline patches/net/minecraft/world/entity/LivingEntity.java.patch]: The end of this sentence makes no sense

**Review by XFactHD — CHANGES_REQUESTED** [review]

**Comment by sciwhiz12** [comment]
> Gotcha. The only other thing I noticed is that this change would affect the behavior of the event slightly, where since we are modifying the final resolved Y value instead of the estimated Y, the teleportation would fail if the block at that Y blocks the teleport. I think that should either be a comment or an announcement in dev-annoucements to indicate this change.

I'll add it as a comment at the very least. Feel free to make a dev-announcement.

File: patches/net/minecraft/world/entity/LivingEntity.java.patch (hunk 1 above)
Comment (sciwhiz12) [reply patches/net/minecraft/world/entity/LivingEntity.java.patch]: Whoops. I must've got distracted while finishing that comment.

**Review by XFactHD — APPROVED** [review]
