### PR TITLE
Port to 1.21.5

### LINKED ISSUE #2044: port/1.21.5: The height of the blue line when the player enables hitbox rendering is too high when the player uses elytra.
**Minecraft Version:** 1.21.5-rc1

**NeoForge Version:** 21.5.0-alpha.1.21.5-rc1.20250322.080934

**Logs:** https://gist.github.com/Lolothepro/737499bc9b3e046e6c5810bf733c4031

**Steps to Reproduce:**
 1. Enable hitbox rendering
 2. Use an elytra

**Description of issue:**

Eye height not updated when player uses elytra

With 1.21.5:

NeoForge 1.21.5rc1:

Image

Vanilla 1.21.5rc1:

Image

Note that this does not happen with NeoForge 1.21.4:

Image

### PR DESCRIPTION
**Pull request by Technici4n**
It's finally here!

### CODE REVIEW

File: patches/com/mojang/blaze3d/systems/CommandEncoder.java.patch [hunk 1]
```diff
@@ -0,0 +1,11 @@
+--- a/com/mojang/blaze3d/systems/CommandEncoder.java
++++ b/com/mojang/blaze3d/systems/CommandEncoder.java
+@@ -25,6 +_,8 @@
+ 
+     void clearDepthTexture(GpuTexture p_410276_, double p_410184_);
+ 
++    void clearStencilTexture(GpuTexture texture, int value);
```
Comment (RogueLogix) [inline patches/com/mojang/blaze3d/systems/CommandEncoder.java.patch:7]: IMO much like mojang's combined clearColorAndDepthTextures, combined clearDepthStencilTexture and clearColorAndDepthStencilTextures calls should also exist

File: patches/com/mojang/blaze3d/resource/RenderTargetDescriptor.java.patch [hunk 2]
```diff
@@ -1,18 +1,36 @@
...
+-        return new TextureTarget(null, this.width, this.height, this.useDepth);
++        return new TextureTarget(null, this.width, this.height, this.useDepth, this.useStencil);
+     }
+ 
+     public void prepare(RenderTarget p_393765_) {
+@@ -20,6 +_,9 @@
+         } else {
+             RenderSystem.getDevice().createCommandEncoder().clearColorTexture(p_393765_.getColorTexture(), this.clearColor);
+         }
++        if (this.useStencil) {
```
Comment (RogueLogix) [inline patches/com/mojang/blaze3d/resource/RenderTargetDescriptor.java.patch:23]: as stencil requires depth, this should be inside the useDepth if statement (and IMO use a non-existent but mentioned in other comment clearColorAndDepthStencilTextures call)

File: patches/com/mojang/blaze3d/opengl/GlDevice.java.patch [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
++    }
++
++    /**
++     * Create a new GPU texture from an existing texture whose lifecycle is externally managed.
++     */
++    public GpuTexture createExternalTexture(@Nullable String label, TextureFormat format, int width, int height, int mipLevels, int nativeId) {
++        if (label == null) {
++            label = String.valueOf(nativeId);
++        }
++        GlTexture gltexture = new GlTexture(label, format, width, height, mipLevels, nativeId);
```
Comment (RogueLogix) [inline patches/com/mojang/blaze3d/opengl/GlDevice.java.patch]: the wrong GlTexture constructor is called here, texture id is deleted twice. note: this is not a violation of the GL spec. glDeleteTextures silently ignores non-texture ids, hence no error is generated.

File: src/main/java/net/neoforged/neoforge/client/NeoForgeRenderTypes.java [hunk 4]
```diff
@@ -154,180 +153,144 @@ public RenderType get() {
...
             var renderState = RenderType.CompositeState.builder()
-                    .setShaderState(RENDERTYPE_ENTITY_TRANSLUCENT_UNLIT_SHADER)
                     .setTextureState(new TextureStateShard(textureLocation, TriState.DEFAULT, false))
-                    .setTransparencyState(RenderType.TRANSLUCENT_TRANSPARENCY)
-                    .setCullState(RenderType.NO_CULL)
                     .setLightmapState(RenderType.LIGHTMAP)
                     .setOverlayState(RenderType.OVERLAY)
                     .createCompositeState(true);
-            return RenderType.create("neoforge_entity_unlit_translucent", DefaultVertexFormat.NEW_ENTITY, VertexFormat.Mode.QUADS, 256, true, sortingEnabled, renderState);
+            return RenderType.create("neoforge_entity_unlit_translucent", 256, true, sortingEnabled, NeoForgeRenderPipelines.ENTITY_UNLIT_TRANSLUCENT, renderState);
```
Comment (RogueLogix) [inline src/main/java/net/neoforged/neoforge/client/NeoForgeRenderTypes.java:178]: the now unused json for this rendertype wasn't deleted

File: patches/com/mojang/blaze3d/opengl/GlDevice.java.patch (hunk 3 above)
Comment (shartte) [reply patches/com/mojang/blaze3d/opengl/GlDevice.java.patch]: Addressed

File: src/main/java/net/neoforged/neoforge/client/NeoForgeRenderTypes.java (hunk 4 above)
Comment (shartte) [reply src/main/java/net/neoforged/neoforge/client/NeoForgeRenderTypes.java:178]: Addressed
