### PR TITLE
Fix enchantment attribute modifiers not being applied

### LINKED ISSUE #1120: 1.21: Efficiency enchantment has no effect on vanilla tools
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.10

**Steps to Reproduce:**
 1. Give yourself a golden shovel
 2. Enchant with efficiency 5
 3. Observe that mining dirt is not instant

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #1120 by replacing the short-circuting `if (true) return;` statement in `ItemStack#forEachModifier(EquipmentSlot, ...)` with an `if (false) { ... }` that encompasses the code replaced by the item stack extension method call, thus allowing the call to `EnchantmentHelper` to happen.

An explanatory comment was added (where none existed before) to assist future debugging of that patch, and for simple patch hygiene reasons.

Tested by obtaining a golden shovel with a max-level Efficiency enchantment through `/enchant`, and digging through dirt: mining dirt should be instant, with a block at even the quickest click. (It should also be possible to verify the attribute modifier's application manually through the `/attribute` command.)

---

Note that, as noted in my comment on the linked issue, this does not address the fact that the other `forEachModifier` method that takes in an `EquipmentSlotGroup` is left unmodified, and thus outside the reach of the `ItemAttributeModifiersEvent` (which is fired by that item stack extension method). I leave that work to another contributor, since it requires refactoring the event for both `EquipmentSlot` and `EquipmentSlotGroup`.

### CODE REVIEW

File: patches/net/minecraft/world/item/ItemStack.java.patch [hunk 1]
```diff
@@ -158,15 +158,23 @@
...
      }
-@@ -933,6 +_,8 @@
+@@ -933,12 +_,16 @@
      }
  
      public void forEachModifier(EquipmentSlot p_332001_, BiConsumer<Holder<Attribute>, AttributeModifier> p_330882_) {
++        // Neo: Use ItemStack extension method, which fires an event for mod-added attributes modifiers
 +        this.getAttributeModifiers(p_332001_).forEach(p_330882_);
-+        if (true) return;
++        if (false) {
```
Comment (Technici4n) [inline patches/net/minecraft/world/item/ItemStack.java.patch:172]: Thoughts on indenting the whole block to make sure that we won't miss changes here when updating?

File: patches/net/minecraft/world/item/ItemStack.java.patch [hunk 2]
```diff
@@ -158,15 +158,23 @@
...
          ItemAttributeModifiers itemattributemodifiers = this.getOrDefault(DataComponents.ATTRIBUTE_MODIFIERS, ItemAttributeModifiers.EMPTY);
```
Comment (Technici4n) [inline patches/net/minecraft/world/item/ItemStack.java.patch]: Shouldn't we just patch this to `getAttributeModifiers` instead?

File: patches/net/minecraft/world/item/ItemStack.java.patch (hunk 1 above)
Comment (sciwhiz12) [reply patches/net/minecraft/world/item/ItemStack.java.patch:172]: My personal preference when writing patches is to keep them small, contained, and commented, and indenting the block would make a lot of visual noise when looking at the patch itself.

It would, however, be effective I believe in ensuring changes to the block are always noticed during porting.

I'll do the change in my PR, but whoever works on the item attribute modifiers fixes next (as I described in my PR description) will need to do the same for the other `forEachModifier` method.

File: patches/net/minecraft/world/item/ItemStack.java.patch (hunk 2 above)
Comment (sciwhiz12) [reply patches/net/minecraft/world/item/ItemStack.java.patch]: What do you mean? The patch replaces the disabled portion of code with `IItemStackExtension#getAttributeModifiers`, since that extension method fires the appropriate item attribute modifiers event.

File: patches/net/minecraft/world/item/ItemStack.java.patch [hunk 3]
```diff
@@ -158,15 +158,27 @@
...
+-            itemattributemodifiers.forEach(p_332001_, p_330882_);
+-        } else {
+-            this.getItem().getDefaultAttributeModifiers().forEach(p_332001_, p_330882_);
++        // Neo: Use ItemStack extension method, which fires an event for mod-added attributes modifiers
 +        this.getAttributeModifiers(p_332001_).forEach(p_330882_);
-+        if (true) return;
-         ItemAttributeModifiers itemattributemodifiers = this.getOrDefault(DataComponents.ATTRIBUTE_MODIFIERS, ItemAttributeModifiers.EMPTY);
-         if (!itemattributemodifiers.modifiers().isEmpty()) {
-             itemattributemodifiers.forEach(p_332001_, p_330882_);
++        if (false) {
```
Comment (Technici4n) [inline patches/net/minecraft/world/item/ItemStack.java.patch:172]: Thoughts on outright deleting the code? 🤔
Otherwise this is also fine.

**Review by Technici4n — APPROVED** [review]
