### PR TITLE
Rebuild indexed feature list after biome modification

### LINKED ISSUE #868: [Bug] Game crashing on second run when used custom JSON feature/placement
**Minecraft Version:** 1.20.5

**NeoForge Version:** 20.5.5-beta

**Logs:** [Crash report + files](https://gist.github.com/yanny7/6e893498e1d7a7643dbd49cc936ffe2c)

**Steps to Reproduce:**
1. Use custom placement/feature for new world (attached to gist, just JSONs)
2. Restart game
3. Generate new chunks

**Description of issue:**
- Game crashes when generating new chunk

### PR DESCRIPTION
**Pull request by Technici4n**
To do so, rework the `Lazy` class to always be thread-safe, and support invalidation of the cached value. `NonNullLazy` was also removed in the process.

Fixes #868.

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/common/util/Lazy.java [hunk 1]
```diff
@@ -9,81 +9,47 @@
...
-                        this.lock = null;
-                    }
+    @Override
+    public T get() {
+        T ret = cachedValue;
+        if (ret == null) {
+            synchronized (this) {
+                ret = cachedValue;
+                if (ret == null) {
+                    cachedValue = ret = delegate.get();
```
Comment (embeddedt) [inline src/main/java/net/neoforged/neoforge/common/util/Lazy.java:49]: To prevent the supplier unexpectedly being called multiple times, should we wrap it in `Objects.requireNonNull` here?

**Review by embeddedt — APPROVED** [review]
