### PR TITLE
[1.21.11] Fix #2869 Separate the key modifiers for Command and Control keys on OSX

### LINKED ISSUE #2869: [1.21.11] Keys bound with the CMD modifier on mac cannot be triggered
**Minecraft Version:** `1.21.11`

**NeoForge Version:** `21.11.6-beta`

**Logs:** N/A

**Steps to Reproduce:**

`CTRL` binds as `CMD` but works normally:
 1. Try to bind a keybind to `CTRL + A`
 2. Observe that it binds to `CMD + A`
 3. Observe that it can be triggered by `CTRL + A`

`CMD` binds as `Left Win` and works normally
 1. Try to bind a keybind to `CMD`
 2. Observe that it binds to `Left Win`
 3. Observe that it can be triggered by `CMD`

`CMD` cannot be combined with other keys:
 1. Try to bind a keybind to `CMD + A`
 2. Observe that it does not work
 (This issue also impacts mods like JEI which create keybinds with `CMD + Key` by default. They cannot be triggered.)

**Description of issue:**
Mojang made some changes to key handling for Mac, specifically:
`Several uses of the cmd key on Mac have been rebound to ctrl`
([See here](https://www.minecraft.net/en-us/article/minecraft-java-edition-1-21-11) under the "Input" section)
This change makes some code very unclear, and has led to some problems in the NeoForge key modifiers system.

### PR DESCRIPTION
**Pull request by mezz**
# Issue Description

* https://github.com/neoforged/NeoForge/issues/2869

# Fix Description

This PR separates out the Command key modifier handling into its own modifier.
That allows most hotkeys to simply use Control across all platforms, to avoid conflicting with OSX global hotkeys, which is inline with Mojang's changes for 1.21.11.

# New Functionality

For special cases where Command is still wanted on OSX (copy, paste, text editing in general), the new modifier will allow it and still falls back to Control for other platforms.
For OSX players who want to bind hotkeys using Control or Command in any way they like, this is now supported.

# Breaking Changes

Since NeoForge 1.21.11 is in beta, this introduces breaking changes by adding a new enum variation, and also makes `codes` abstract as some minor breaking cleanup.

### CODE REVIEW

File: src/client/java/net/neoforged/neoforge/client/settings/KeyModifier.java [hunk 1]
```diff
@@ -16,6 +17,15 @@
...
+    /**
+     * Always matches the Control Key, even on OSX which normally uses the Command Key for hotkeys.
+     * Since 1.21.11, Mojang uses Control on OSX for hotkeys that conflict with OSX global system shortcuts.
+     * <p>
+     * For hotkeys that should use the Command key on OSX (like system hotkeys ⌘C for copy, ⌘P for paste, etc.),
+     * use {@link #CONTROL_OR_COMMAND} instead.
+     * For examples of places where Command should be used, see uses of
+     * `net.minecraft.client.input.InputWithModifiers#hasControlDownWithQuirk()`.
+     */
     CONTROL {
```
Comment (sciwhiz12) [inline src/client/java/net/neoforged/neoforge/client/settings/KeyModifier.java:29]: I half-wonder if we should rename this to `CONTROL_ONLY`, if only to make developers explicitly reckon with the change by way of a compiler error.

I'd welcome your thoughts on this, but we probably shouldn't do it. (The thought did cross my mind at least. 😆)

**Review by sciwhiz12 — APPROVED** [review]
Unfortunately, as I own exactly zero Apple hardware, I can't really test the added functionality. 😅 But it looks to be sane and it should run, and I'm sure you tested it beforehand.

**Review by Su5eD — APPROVED** [review]
Tested and confirmed to work on OSX

File: src/client/java/net/neoforged/neoforge/client/settings/KeyModifier.java (hunk 1 above)
Comment (mezz) [reply src/client/java/net/neoforged/neoforge/client/settings/KeyModifier.java:29]: I thought about this too. Naming it this way is intended to guide modders to use `CONTROL` by default unless they're really thinking hard about OSX and what might conflict, which seems to be the direction Mojang is taking. It also means existing hotkeys should "just work" without breaking changes that force modders to update.

Players will be able to set `CONTROL` or `COMMAND` in-game, and for them the enum name doesn't matter.

Comment (sciwhiz12) [reply src/client/java/net/neoforged/neoforge/client/settings/KeyModifier.java:29]: Alright then.
