### PR TITLE
[1.20.6] Add KnownPacks for mods

### LINKED ISSUE #846: All worlds have experimental settings with NeoForge
**NeoForge Version:** 20.5.0-beta

**Steps to Reproduce:**
1. Try to generate a new world without any experimental settings
2. The experimental settings message is displayed.

**Description of issue:**
All worlds have experimental settings with NeoForge

https://github.com/neoforged/NeoForge/assets/68275908/357e1e3f-fe04-4e41-8a66-67afc7a77ed4

### PR DESCRIPTION
**Pull request by lukebemish**
This adds `KnownPack`s for mod data packs, and allows packs added with `AddPackFindersEvent` with `KnownPack`s to actually be used. This has two benefits:
- large data pack entries do not need to be synced if they come from a known pack, and are recovered on the client from the packs present there
- Known packs are considered non-experimental (in most circumstances)

`KnownPack`s for mods are identified by the mod ID and version.

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java [hunk 1]
```diff
@@ -44,4 +46,11 @@ public void addRepositorySource(RepositorySource source) {
     public PackType getPackType() {
         return packType;
     }
+
+    /**
+     * {@return whether or not the pack repository being assembled is "trusted" to provide default KnownPacks}
+     */
+    public boolean isTrusted() {
+        return trusted;
+    }
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java]: What does being "trusted" entail here? When should a mod check this to do something differently?

File: tests/src/main/java/net/neoforged/neoforge/oldtest/world/LoginPacketSplitTest.java [hunk 2]
```diff
@@ -45,6 +45,7 @@
 import net.minecraft.server.packs.PackType;
 import net.minecraft.server.packs.metadata.MetadataSectionSerializer;
 import net.minecraft.server.packs.repository.BuiltInPackSource;
+import net.minecraft.server.packs.repository.KnownPack;
```
Comment (sciwhiz12) [inline tests/src/main/java/net/neoforged/neoforge/oldtest/world/LoginPacketSplitTest.java]: Spotless is erroring on this import, because it is unused.

File: src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java [hunk 3]
```diff
@@ -100,7 +101,7 @@ private static void packFinder(Map<IModFile, Pack.ResourcesSupplier> modResource
                         name,
                         Component.literal(packName.isEmpty() ? "[unnamed]" : packName),
                         PackSource.DEFAULT,
-                        Optional.empty());
+                        Optional.of(new KnownPack("neoforge", name, mod.getVersion().toString())));
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java]: Could you briefly explain why the namespace is `neoforge`, rather than the mod ID (and the pack ID being the pack name)?

File: patches/net/minecraft/server/network/config/SynchronizeRegistriesTask.java.patch [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+ 
+     public void handleResponse(List<KnownPack> p_326076_, Consumer<Packet<?>> p_326167_) {
+-        if (p_326076_.equals(this.requestedPacks)) {
+-            this.sendRegistries(p_326167_, Set.copyOf(this.requestedPacks));
+-        } else {
+-            this.sendRegistries(p_326167_, Set.of());
+-        }
++        Set<KnownPack> requested = new java.util.HashSet<>(this.requestedPacks);
++        requested.retainAll(p_326076_);
++        this.sendRegistries(p_326167_, requested);
```
Comment (sciwhiz12) [inline patches/net/minecraft/server/network/config/SynchronizeRegistriesTask.java.patch]: What motivated this change? (Should we add a comment here?)

**Review by sciwhiz12 — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java (hunk 1 above)
Comment (lukebemish) [reply src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java]: Basically: 9 times out of 10 modders can ignore this. It's here in case a modder, for some reason, wants to add a pack with a KnownPack that is not discovered by the client in sync - or, in general, wants to have different logic for the client-only pack being used to provide known packs than for the "normal" pack. The name comes from what vanilla calls it.

File: src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java (hunk 3 above)
Comment (lukebemish) [reply src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java]: Because neoforge is the one providing the pack, not the mod -- all the logic for the pack discovery and creation comes from neoforge. We'd be placing something into a mod's namespace without it doing anything if we did it the other way.

File: patches/net/minecraft/server/network/config/SynchronizeRegistriesTask.java.patch (hunk 4 above)
Comment (lukebemish) [reply patches/net/minecraft/server/network/config/SynchronizeRegistriesTask.java.patch]: Good point, I'll add a comment. Basically, beforehand, you needed an _exact_ match of all requested known packs being present on the client for _any_ to be used. With this, it'll use the ones that are present and sync the ones that are absent the normal way - which is necessary in the case of, say, datapacks-as-mods present only on the server, to avoid breaking KnownPack syncing entirely in that case

File: src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java (hunk 1 above)
Comment (lukebemish) [reply src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java]: Added some better docs

**Comment by lukebemish** [comment]
~~Turning this into a draft for now; there appears to be a cap on the number of known packs that can be synced C2S at present -- I need to poke removing that.~~ resolved

File: tests/src/main/java/net/neoforged/neoforge/debug/resources/BulkKnownPackTest.java [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+    }
+
+    public static class Listener implements TestListener {
+        @Override
+        public void onEnabled(TestFramework framework, Test test, @Nullable Entity changer) {
+            RegistryAccess access = changer.registryAccess();
+            var biomes = access.registry(Registries.BIOME).orElseThrow();
+            for (int i = 0; i < 128; i++) {
+                var id = new ResourceLocation(NAMESPACE, "entry_" + i);
+                biomes.getHolder(id).orElseThrow(() -> new IllegalStateException("Entry " + id + " that should be synced by KnownPack not found"));
```
Comment (Matyrobbrt) [inline tests/src/main/java/net/neoforged/neoforge/debug/resources/BulkKnownPackTest.java]: This should fail the test instead of throwing, and make it succeed at the end.

File: tests/src/main/java/net/neoforged/neoforge/debug/resources/BulkKnownPackTest.java [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+                            new PackSelectionConfig(true, Pack.Position.TOP, false))));
+                }
+            }
+        });
+    }
+
+    public static class Listener implements TestListener {
+        @Override
+        public void onEnabled(TestFramework framework, Test test, @Nullable Entity changer) {
+            RegistryAccess access = changer.registryAccess();
```
Comment (Matyrobbrt) [inline tests/src/main/java/net/neoforged/neoforge/debug/resources/BulkKnownPackTest.java]: `changer` can be null.

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

**Comment by lukebemish** [comment]
In order to guarantee sensible syncing of known packs, this PR now includes the mod IDs and versions of every mod in a mod file in the pack name and KnownPack for this file -- if we don't do this, we could end up with situations where, say, two mods are in the same file on one end and different files on another end and stuff gets synced via knownpack that is not discoverable via knownpack. I have also updated the system to add knownpacks to packs created by the utility TelepathicGrunt added to AddPackFindersEvent, which adds packs from subfolders of the mod.

File: patches/net/minecraft/client/multiplayer/KnownPacksManager.java.patch [hunk 7]
```diff
@@ -0,0 +1,20 @@
+--- a/net/minecraft/client/multiplayer/KnownPacksManager.java
++++ b/net/minecraft/client/multiplayer/KnownPacksManager.java
+@@ -44,9 +_,17 @@
+             }
+         }
+ 
++        if (list.size() > 1024) {
++            list = list.subList(0, 1024);
++            list1 = list1.subList(0, 1024);
++            LOGGER.warn("NeoForge: too many KnownPacks requested; only the first 1024 will be sent via KnownPack, the rest will be synced normally");
```
Comment (Matyrobbrt) [inline patches/net/minecraft/client/multiplayer/KnownPacksManager.java.patch]: How often will this get called? Inlining a `LogUtils.getLogger()` instead of patching in a field is probably fine.

File: src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java [hunk 8]
```diff
@@ -68,13 +71,22 @@ public void addPackFinders(ResourceLocation packLocation, PackType packType, Com
         if (getPackType() == packType) {
             var resourcePath = ModList.get().getModFileById(packLocation.getNamespace()).getFile().findResource(packLocation.getPath());
 
+            var version = ModList.get().getModContainerById(packLocation.getNamespace()).get().getModInfo().getVersion();
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java]: You can avoid two lookups by storing the container and getting its mod info (and file)

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

**Review by Matyrobbrt — APPROVED** [review]
