### PR TITLE
[1.21] Add support for the `c:register` channel registration payload

### LINKED ISSUE #1051: hasChannel not properly checking adhoc channels registered by another loader
**Minecraft Version:** 1.20.6

**NeoForge Version:**  20.6.99-beta

**Steps to Reproduce:**
 1. Launch a neo server
 2. Have a fabric client connect to the server
 3. Have the server check if the client has a custom network channel that was registered by fabric as an adhoc channel.

**Description of issue:**

When checking if a connection has a channel (at least on a server), it always returns false if the other end is providing it as an adhoc channel by means of the [`NetworkRegistry#onMinecraftRegister`](https://github.com/neoforged/NeoForge/blob/65e8748fc6ce6cf2b5b06b6e7943beabf269a247/src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java#L688). I believe this is because in `NetworkRegistry#initializeOtherConnection` we initialize [`ATTRIBUTE_PAYLOAD_SETUP` to `NetworkPayloadSetup.empty()`](https://github.com/neoforged/NeoForge/blob/65e8748fc6ce6cf2b5b06b6e7943beabf269a247/src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java#L392). And then when we end up querying `NetworkRegistry#hasChannel` we skip checking the adhoc channels because [`payloadSetup` is nonnull](https://github.com/neoforged/NeoForge/blob/65e8748fc6ce6cf2b5b06b6e7943beabf269a247/src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java#L600-L602)

### LINKED ISSUE #1394: Incorrect format string in NetworkRegistry#checkPacket leads to incorrect exception
See: <https://github.com/neoforged/NeoForge/blob/12f102053fbeea3800d91f8849170b6096e267d1/src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java#L442>

Here's an example of a broken exception message:
```
fail: net.minecraft.commands.Commands
      '/ganderdebug minecraft:acacia_button' threw an exception
      java.lang.UnsupportedOperationException: Payload {} may not be sent to the client!
```

This also applies in the other overload of checkPacket.

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
This PR adds support for the `c:register` payload, which allows declaring the play-phase channels during the configuration phase, as established by Fabric in https://github.com/FabricMC/fabric/pull/3244

To permit compatibility with fabric, the `c:version` payload is also here, though it is technically unsupported from our end. Fabric requires it be sent before sending `c:register`.  I don't _really_ see this version mechanism being useful atm and am aiming for a minimal implementation.

Aside from the explicit `c:register` support, this PR has a couple minor cleanup items:
1. Fixing the error messages in the exceptions thrown by `checkPacket` - some format strings are incorrectly using `{}` instead of `%s`.
2. Moves the channel attribute handling code to a new standalone class.
3. Fixes a couple style issues in `NetworkRegistry`.  At some point I should probably make braces on conditional statements required.

Closes #1051

### CODE REVIEW

File: patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch [hunk 1]
```diff
@@ -35,6 +35,16 @@
 +            return;
 +        }
 +
++        if (p_295727_.payload() instanceof net.neoforged.neoforge.network.payload.CommonVersionPayload) {
++            // no-op
```
Comment (sciwhiz12) [inline patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch]: Explain in this comment why the `c:version` payload is a no-op. (Alternatively, explain it in `CommonVersionPayload` and reference that from this comment.)

File: patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch [hunk 2]
```diff
@@ -35,6 +35,16 @@
 +            return;
 +        }
 +
++        if (p_294276_.payload() instanceof net.neoforged.neoforge.network.payload.CommonVersionPayload) {
++            // no-op
```
Comment (sciwhiz12) [inline patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch]: Explain in this comment why the `c:version` payload is a no-op. (Alternatively, explain it in `CommonVersionPayload` and reference that from this comment.)

File: src/main/java/net/neoforged/neoforge/network/payload/CommonRegisterPayload.java [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+
+    public static final ResourceLocation ID = ResourceLocation.fromNamespaceAndPath("c", "register");
+    public static final CustomPacketPayload.Type<CommonRegisterPayload> TYPE = new CustomPacketPayload.Type<>(ID);
+
+    public static final StreamCodec<FriendlyByteBuf, CommonRegisterPayload> STREAM_CODEC = StreamCodec.composite(
+            ByteBufCodecs.VAR_INT, CommonRegisterPayload::version,
+            ByteBufCodecs.STRING_UTF8.map(CommonRegisterPayload::protocolById, ConnectionProtocol::id), CommonRegisterPayload::protocol,
+            ByteBufCodecs.collection(HashSet::new, ResourceLocation.STREAM_CODEC), CommonRegisterPayload::channels,
+            CommonRegisterPayload::new);
+    @Override
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/network/payload/CommonRegisterPayload.java:36]: Please add a blank line between the field and the method.

File: src/main/java/net/neoforged/neoforge/network/payload/CommonRegisterPayload.java [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+import org.jetbrains.annotations.Nullable;
+
+/**
+ * Common Register, used to send play-phase channels during the configuration phase.
+ * 
+ * @param version  Declared version of all contained channels. Currently unused by NeoForge.
+ * @param protocol The {@link ConnectionProtocol} of the contained channels. One of "play" or "configuration". Currently NeoForge only expects and sends "play" channels via this payload.
+ * @param channels A list of all named channels available for the declared phase.
+ */
+public record CommonRegisterPayload(int version, ConnectionProtocol protocol, Set<ResourceLocation> channels) implements CustomPacketPayload {
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/network/payload/CommonRegisterPayload.java:27]: Mark this class as `@ApiStatus.Internal`.

File: src/main/java/net/neoforged/neoforge/network/payload/CommonVersionPayload.java [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+import net.minecraft.network.codec.ByteBufCodecs;
+import net.minecraft.network.codec.StreamCodec;
+import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
+import net.minecraft.resources.ResourceLocation;
+
+/**
+ * Unsupported common version payload. Must be sent to fabric to support their implementation of c:register.
+ * Only legal version is 1.
+ */
+public record CommonVersionPayload(List<Integer> versions) implements CustomPacketPayload {
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/network/payload/CommonVersionPayload.java:25]: Mark this class as `@ApiStatus.Internal`.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 6]
```diff
@@ -78,17 +78,11 @@
...
- * </p>
  */
 @ApiStatus.Internal
 public class NetworkRegistry {
     private static final Logger LOGGER = LogUtils.getLogger();
 
-    private static final AttributeKey<NetworkPayloadSetup> ATTRIBUTE_PAYLOAD_SETUP = AttributeKey.valueOf("neoforge:payload_setup");
-    private static final AttributeKey<Set<ResourceLocation>> ATTRIBUTE_ADHOC_CHANNELS = AttributeKey.valueOf("neoforge:adhoc_channels");
-    private static final AttributeKey<ConnectionType> ATTRIBUTE_CONNECTION_TYPE = AttributeKey.valueOf("neoforge:connection_type");
-    private static final AttributeKey<PacketFlow> ATTRIBUTE_FLOW = AttributeKey.valueOf("neoforge:flow");
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:91]: Why did you remove this channel attribute (and not mention it in the PR description as part of your cleanups)?

File: src/main/java/net/neoforged/neoforge/network/registration/ChannelAttributes.java [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+
+    /**
+     * Known ad-hoc channels from {@link MinecraftRegisterPayload}.
+     */
+    public static final AttributeKey<Set<ResourceLocation>> ADHOC_CHANNELS = AttributeKey.valueOf("neoforge:adhoc_channels");
+
+    /**
+     * Known common channels from {@link CommonRegisterPayload}.
+     */
+    public static final AttributeKey<Map<ConnectionProtocol, Set<ResourceLocation>>> COMMON_CHANNELS = AttributeKey.valueOf("neoforge:common_channels");
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/network/registration/ChannelAttributes.java:43]: Why not a `SetMultimap` from Guava?

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 8]
```diff
@@ -597,20 +579,24 @@ public static boolean hasChannel(ICommonPacketListener listener, ResourceLocatio
...
-        NetworkPayloadSetup payloadSetup = connection.channel().attr(ATTRIBUTE_PAYLOAD_SETUP).get();
-        if (payloadSetup == null) {
-            return getKnownAdHocChannelsOfOtherEnd(connection).contains(payloadId);
+        NetworkPayloadSetup payloadSetup = ChannelAttributes.getPayloadSetup(connection);
+        if (payloadSetup != null) {
+            // If a protocol is specified, only check against channels for that protocol
+            // Otherwise check against all protocols.
+            if (protocol != null && payloadSetup.getChannels(protocol).containsKey(payloadId)) {
+                return true;
+            } else if (protocol == null && payloadSetup.channels().values().stream().anyMatch(map -> map.containsKey(payloadId))) {
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:601]: Just a small fun comment: it took me looking at the code to realize why this looked strange to me -- `NetworkPayloadSetup` contains a map whose values are also maps. 😆

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 9]
```diff
@@ -622,7 +608,7 @@ public static boolean hasChannel(Connection connection, @Nullable ConnectionProt
      * @return The filtered packets.
      */
     public static <T extends PacketListener> List<Packet<?>> filterGameBundlePackets(ChannelHandlerContext context, Iterable<Packet<? super T>> packets) {
-        final NetworkPayloadSetup payloadSetup = context.channel().attr(ATTRIBUTE_PAYLOAD_SETUP).get();
+        NetworkPayloadSetup payloadSetup = context.channel().attr(ChannelAttributes.PAYLOAD_SETUP).get();
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:624]: Why not use the `ChannelAttributes#getPayloadSetup` method?

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java [hunk 10]
```diff
@@ -719,6 +704,39 @@ public static Set<ResourceLocation> getInitialServerUnregisterChannels() {
         return nowForgottenChannels.build();
     }
 
+    /**
+     * Replaces any existing common channels with the incoming ones from a {@link CommonRegisterPayload}.
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:739]: Is that the specified behavior of `c:register` on Fabric -- it _replaces_ all registrations with the registrations specified, instead of adding the new registrations? I would think it mimics `minecraft:register`, but I'd like to be sure just in case.

(@Technici4n, could you please advise on this?)

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Not tested, just a code review.

**Comment by Technici4n** [comment]
We had some discussion on Discord a few days ago. It's not clear that we need to support this. An alternative would be to allow sending unknown packets for `OTHER` connections, at least in the play phase.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 6 above)
Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:91]: Forgot to mention it.  This attribute was unused, so there was no point to keep it while refactoring.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 10 above)
Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:739]: I wasn't sure, and didn't see it formally specified anywhere.  Having the behavior of `minecraft:register` would be weird because there isn't a `c:unregister` payload to complement that behavior.

Comment (sciwhiz12) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:739]: We could check the implementation of the packet in Fabric API (and/or consult with @fabricmc maintainers) to see if it does a replacement or a simple addition.

**Comment by Shadows-of-Fire** [comment]
Just allowing any payload to be sent doesn't feel like the right solution, especially when this protocol exists and can be supported.  I don't want to have a situation where the contract of `hasChannel` is "check this, but the result might be invalid on an `OTHER` connection".

**Comment by Technici4n** [comment]
> I don't want to have a situation where the contract of hasChannel is "check this, but the result might be invalid on an OTHER connection".

You can perform the check during the configuration phase if you want to support `OTHER` connections reliably.

**Comment by Shadows-of-Fire** [comment]
Doing checks in the config phase only allows you to check for config channels, which isn't useful here.  There are only three effective solutions that might solve this problem:
1. Support `c:register` and allow the ecosystem to support it broadly so that channels are declared early in the config phase. (this solution)
2. Remove validation in `hasChannel`. Has the aforementioned side effect of creating a poor contract for the method, making code that has to interact with it awkward (the method would basically be invalid on `OTHER` connections, meaning consumers would need to always query the connection type _or_ hasChannel).
3. Provide an event that fires when `minecraft:register` is received (and channels are updated) so that consumers can fire login payloads as soon as the connection declares they're available.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 10 above)
Comment (Minecraftschurli) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:739]: > ... there isn't a c:unregister payload ...

there is a `minecraft:unregister` too

Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:739]: The `minecraft:` payloads do not interact with the channels supplied by the `c:` payload.  Thus I think the best implementation we can have is for `c:register` to replace the existing channels when it comes in, with the expectation that it be sent one time during configuration.

File: src/main/java/net/neoforged/neoforge/network/registration/ChannelAttributes.java (hunk 7 above)
Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/network/registration/ChannelAttributes.java:43]: Don't know, but my source attachment is busted for guava in neodev atm, so I shall be leaving it as-is.

File: src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java (hunk 9 above)
Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java:624]: Because those helpers work on `Connection` (to avoid unwrapping the `Channel` at most call sites), but this call site is unique in that we don't have a `Channel`, we have a `ChannelHandlerContext`.

And while true they both have a method with signature `public Channel channel()`, there isn't a common interface to retrieve it by.

**Comment by Shadows-of-Fire** [comment]
Updated to address Sci's review comments - I just implemented the correct payload handler for `c:version`, though given there's only one version it's mostly superfluous.

File: src/main/java/net/neoforged/neoforge/network/registration/ChannelAttributes.java (hunk 7 above)
Comment (sciwhiz12) [reply src/main/java/net/neoforged/neoforge/network/registration/ChannelAttributes.java:43]: Perhaps then, we should add a comment to consider moving it to SetMultimap in the future?

Comment (Shadows-of-Fire) [reply src/main/java/net/neoforged/neoforge/network/registration/ChannelAttributes.java:43]: Eh, probably not necessary.  If someone wants to move it they can do so with or without the todo.

**Review by sciwhiz12 — APPROVED** [review]
Looks fine to me, I believe.

@Technici4n, please review or leave a comment if you will not be leaving a review, thanks.

**Comment by Technici4n** [comment]
I'll have a look on Sunday latest.

**Review by Technici4n — APPROVED** [review]
