### PR TITLE
[1.21.3] Fix `ToolMaterial` and `ArmorMaterial` causing crashes when unique tags are used

### LINKED ISSUE #1631: [1.21.3] Crash when using custom ToolMaterial
**Minecraft Version:** 1.21.3

**NeoForge Version:** 21.3.3-beta

**Logs:** https://pastebin.com/ZVbGqum0

**Steps to Reproduce:**
 1. Run DataGen with Item using custom ToolMaterial
 2. Crash happens:
 
```
public static final DeferredItem<Item> SHARP_FLINT = ITEMS.registerItem("sharp_flint", (properties) -> knife(properties));

...

    public static Item knife(Properties properties) {
        ToolMaterial toolMaterial = new ToolMaterial(BlockTags.INCORRECT_FOR_STONE_TOOL, 160, 5.0F, 0.5F, 10, ItemTags.BEDS);
        properties = toolMaterial.applyCommonProperties(properties);
        properties = properties.component(DataComponents.TOOL, new Tool(List.of(), 1.0F, 1));
        properties = properties.attributes(toolMaterial.createToolAttributes(0.0F, 4.0F));
        return new ToolItem(properties);
    }

```

**Description of issue:**
Crash happens when creating item with custom ToolMaterial or ArmorMaterial

### PR DESCRIPTION
**Pull request by dhyces**
Closes #1631 

The fix for this issue was to call `MappedRegistry#bindAllTagsToEmpty` before refreezing registries. Vanilla calls this when they freeze registries, allowing them to use named `HolderSet`s in registry objects before they're available in-game (such as in `ToolMaterial`s and `ArmorMaterial`s). If this is not called, then tags are left unbound and `freeze` throws an exception. Vanilla's tags remained bound when NeoForge unfroze registries, however any new tags used were not bound on refreeze.

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/registries/GameData.java [hunk 1]
```diff
@@ -65,7 +65,10 @@ public static void unfreezeData() {
 
     public static void freezeData() {
         LOGGER.debug(REGISTRIES, "Freezing registries");
-        BuiltInRegistries.REGISTRY.stream().filter(r -> r instanceof MappedRegistry).forEach(r -> ((MappedRegistry<?>) r).freeze());
+        BuiltInRegistries.REGISTRY.stream().filter(r -> r instanceof MappedRegistry).forEach(r -> {
+            ((MappedRegistry<?>) r).bindAllTagsToEmpty();
```
Comment (Shadows-of-Fire) [inline src/main/java/net/neoforged/neoforge/registries/GameData.java:70]: Leave a comment here detailing why we call `bindAllTagsToEmpty` since it's non-obvious from the context.

**Review by Shadows-of-Fire — APPROVED** [review]
