### PR TITLE
[1.20.2] Fix blending issues caused by item decorators

### LINKED ISSUE #185: The scroll bar blinks with some resource packs that modify Minecraft GUI textures.
**Minecraft Version:** 1.20.1

**NeoForge Version:** 47.1.79

Vanilla:

https://github.com/neoforged/NeoForge/assets/68275908/d006a134-430a-46f9-b439-30fe148942ff

Neo:

https://github.com/neoforged/NeoForge/assets/68275908/c76b4311-51b1-4695-9602-cf1780144890

RP: https://modrinth.com/resourcepack/minimal
(It blinks at the same moment as the search bar cursor)

### PR DESCRIPTION
**Pull request by XFactHD**
This PR fixes blending issues in inventories by properly resetting the render state - disabling blending specifically - after the `ItemDecoratorHandler` has drawn all decorators. As far as I can tell, this doesn't cause any regressions in other places that call any of the two `GuiGraphics#renderItemDecorations()` overloads (i.e. recipe book ghost recipe, bundle tooltip, merchant list, etc.), but I would appreciate it if someone else would cross-check this.

Fixes #185

### CODE REVIEW

**Comment by Technici4n** [comment]
None of the item rendering in Vanilla seems to be touching the `RenderSystem` state anymore - do we still need to do this?

**Comment by XFactHD** [comment]
The decorator renderers might touch it though, so some kind of reseting is still a good idea in my opinion, considering that people are unlikely to notice this kind of issue (especially with the blending stuff as evidenced by the issue referenced by this PR) because it's not visible with vanilla assets.

**Comment by Technici4n** [comment]
What I would suggest instead is that we add a few Blaze3D patches to retrieve the current blend mode etc, and then use that to always reset to the correct state:

```patch
+ boolean depthTest = RenderSystem.isDepthTestEnabled();

  resetRenderState();
  for (IItemDecorator itemDecorator : itemDecorators) {
      if (itemDecorator.render(guiGraphics, font, stack, xOffset, yOffset))
          resetRenderState();
  }

+ if (!depthTest) RenderSystem.disableDepthTest();
```
and similar for the others. BlendFunc might be a bit tricky because it is defined by 4 integers, maybe we want to write that to a mutable struct.

This system will generalize nicely to fix other similar issues, and will ensure that we always reset to the correct render state. Might be worth giving this some thought because I expect that mods might want to use similar hooks. Maybe we want to make this more general for GUI state?

Something like `RenderSystem.captureGuiState(holderStruct)` and `RenderSystem.applyGuiState(holderStruct)`...

**Comment by XFactHD** [comment]
Yeah, I could see that backup and restore approach working quite well for this. I'll prototype something tomorrow.

**Comment by XFactHD** [comment]
I've implemented a simple way to backup and restore the GL state. Not my prettiest work, but it does the trick. To avoid confusion: I have intentionally not added the cull mode to the backup because it's currently never modified and I have also intentionally not added the shader colors stored in `RenderSystem` because they have to be handled through `GuiGraphics` due to the partial batching it does for untextured stuff and text.

File: patches/com/mojang/blaze3d/systems/RenderSystem.java.patch [hunk 1]
```diff
@@ -0,0 +1,23 @@
+--- a/com/mojang/blaze3d/systems/RenderSystem.java
++++ b/com/mojang/blaze3d/systems/RenderSystem.java
+@@ -1025,4 +1025,20 @@
+          void accept(it.unimi.dsi.fastutil.ints.IntConsumer p_157488_, int p_157489_);
+       }
+    }
++
++   public static void backupGlState(net.neoforged.neoforge.client.GlStateBackup state) {
++      if (!isOnRenderThread()) {
```
Comment (Technici4n) [inline patches/com/mojang/blaze3d/systems/RenderSystem.java.patch]: I think this should really be `assertOnRenderThread()` instead, otherwise the `state` will not be written correctly. And same for `restoreGlState`.

**Review by Technici4n — CHANGES_REQUESTED** [review]
OK that's a lot of state saving, but that should be fast enough (since it's just Java field reads and writes). I think we should restrict these methods to the render thread though.

File: patches/com/mojang/blaze3d/systems/RenderSystem.java.patch (hunk 1 above)
Comment (XFactHD) [reply patches/com/mojang/blaze3d/systems/RenderSystem.java.patch]: Yeah, that sounds reasonable in this case considering this would only be used in immediate-mode stuff like UIs anyway.

File: src/main/java/net/neoforged/neoforge/client/GlStateBackup.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
+package net.neoforged.neoforge.client;
+
+public final class GlStateBackup {
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/client/GlStateBackup.java:17]: Should this class have a bit of javadoc? Suggestion:

```
Backup of the OpenGL render state, for use in GUI rendering that needs to change the global render state temporarily
(for example by calling {@link RenderSystem#disableBlend}).

<p>Create a backup before changing the global render state with {@link RenderSystem#backupGlState},
and apply the backup with {@link RenderSystem#restoreGlState}.
```

Comment (Technici4n) [reply src/main/java/net/neoforged/neoforge/client/GlStateBackup.java:17]: (feel free to tweak as you see fit)

**Review by Technici4n — APPROVED** [review]
