### PR TITLE
[1.20.4] Make keybind menu have scrolling descriptions

### LINKED ISSUE #126: Keybind screen descriptions are cut-off
**Minecraft Version:** 1.20.1

**NeoForge Version:** 47.1.76

**Steps to Reproduce:**
 1. Change the language to lolcat or Bosanski
 2. Go to the keybinds menu
 3. Resize the window narrower than default, then wider than default

**Description of issue:**
Since https://github.com/neoforged/NeoForge/pull/48, keybind descriptions are set to a fixed max width, which doesn't fix the issue when resizing to narrow viewports and prevents the full string from being displayed in wider ones.

Top is NeoForge, bottom is Vanilla.
Narrow:
image

Wide:
wide

I'm not sure how this got past multiple reviewers...

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Resolves: https://github.com/neoforged/NeoForge/issues/126

What I did was undo this PR's work: https://github.com/neoforged/NeoForge/pull/48

I also then removed several Forge patched spacings that are no longer logical to have.

Then I AT the two static AbstractWidget.renderScrollingString methods so anyone can use them including me in this PR.

Then I made the text descriptions use that to do scrolling if the text is too long. The text is left aligned and is pushed away from center to the left based on largest string size. But once it hits the left side of the screen, the text will refuse to go beyond it and start the scrolling behavior for the remaining text that are still too large.

Yes there's some magic (tm) values here that was some trial and error but looks good in my testing. But please double check my work.

https://github.com/neoforged/NeoForge/assets/40846040/2df2d160-5bce-4b65-ac60-ac7a00918061

### CODE REVIEW

File: patches/net/minecraft/client/gui/screens/controls/KeyBindsList.java.patch [hunk 1]
```diff
@@ -45,29 +8,24 @@
...
-+            Component nameComponent = lines.size() > 1 ? Component.literal(lines.get(0).getString() + "...") : this.name;
-+            if(lines.size() > 1 && this.isMouseOver(p_282224_ + 95, p_282053_) && p_282224_ < p_281373_ - 90 + KeyBindsList.this.maxNameWidth) {
-+                KeyBindsList.this.keyBindsScreen.setTooltipForNextRenderPass(net.minecraft.locale.Language.getInstance().getVisualOrder(lines));
-+            }
-+            p_281805_.drawString(KeyBindsList.this.minecraft.font, nameComponent, k, p_282357_ + p_281932_ / 2 - 9 / 2, 16777215, false);
-+            this.resetButton.setX(p_281373_ + 190 + 20);
++            int textMaxWidth = p_281805_.guiWidth() / 2;
++            int k = p_281373_ + 90 - Math.min(KeyBindsList.this.maxNameWidth, textMaxWidth - 40);
++            net.minecraft.client.gui.components.AbstractWidget.renderScrollingString(p_281805_, KeyBindsList.this.minecraft.font, this.name, k, k, p_282357_ + p_281932_ / 2 - 9 / 2, textMaxWidth, p_282357_ + p_281932_ / 2 - 9 / 2 + 16, 16777215); // NEOFORGE: Makes descriptions start scrolling if too long
```
Comment (Matyrobbrt) [inline patches/net/minecraft/client/gui/screens/controls/KeyBindsList.java.patch]:
```suggestion
+            net.minecraft.client.gui.components.AbstractWidget.renderScrollingString(p_281805_, KeyBindsList.this.minecraft.font, this.name, k, k, p_282357_ + p_281932_ / 2 - 9 / 2, textMaxWidth, p_282357_ + p_281932_ / 2 - 9 / 2 + 16, 16777215); // Neo: Makes descriptions start scrolling if too long
```

File: patches/net/minecraft/client/gui/screens/controls/KeyBindsList.java.patch [hunk 2]
```diff
@@ -45,29 +8,24 @@
...
              this.resetButton.setY(p_282357_);
              this.resetButton.render(p_281805_, p_282224_, p_282053_, p_281432_);
-             this.changeButton.setX(p_281373_ + 105);
 @@ -218,7 +_,7 @@
              MutableComponent mutablecomponent = Component.empty();
              if (!this.key.isUnbound()) {
                  for(KeyMapping keymapping : KeyBindsList.this.minecraft.options.keyMappings) {
 -                    if (keymapping != this.key && this.key.same(keymapping)) {
-+                    if ((keymapping != this.key && this.key.same(keymapping)) || keymapping.hasKeyModifierConflict(this.key)) { // FORGE: gracefully handle conflicts like SHIFT vs SHIFT+G
++                    if ((keymapping != this.key && this.key.same(keymapping)) || keymapping.hasKeyModifierConflict(this.key)) { // NEOFORGE: gracefully handle conflicts like SHIFT vs SHIFT+G
```
Comment (Matyrobbrt) [inline patches/net/minecraft/client/gui/screens/controls/KeyBindsList.java.patch]:
```suggestion
+                    if ((keymapping != this.key && this.key.same(keymapping)) || keymapping.hasKeyModifierConflict(this.key)) { // Neo: gracefully handle conflicts like SHIFT vs SHIFT+G
```

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

**Review by Matyrobbrt — APPROVED** [review]
