### PR TITLE
[1.20.3] Fix render bounds of various BERs and add render bounds debug renderer

### LINKED ISSUE #317: Ender Dragon heads are invisible with certain camera angles
Ender Dragon heads are invisible with certain camera angles

https://github.com/neoforged/NeoForge/assets/68275908/93193f1e-ebfc-4348-9cb4-c456f255b209

### LINKED ISSUE #325: Banners are not correctly culled
https://github.com/neoforged/NeoForge/assets/68275908/88f807ab-216b-4c8a-8dc3-fb63da7a3088

### PR DESCRIPTION
**Pull request by XFactHD**
This PR fixes the render bounding box of various BE renderers which were previously missed or incorrectly fixed, adds a debug renderer for render bounding boxes (enabled via command) and removes the render BB getter in `IBlockEntityExtension` again which was accidentally reintroduced in the 1.20.3 update.

Fixes #317
Fixes #325

### CODE REVIEW

File: patches/net/minecraft/client/renderer/blockentity/BannerRenderer.java.patch [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
++++ b/net/minecraft/client/renderer/blockentity/BannerRenderer.java
+@@ -139,4 +_,10 @@
+                 );
+         }
+     }
++
++    @Override
++    public net.minecraft.world.phys.AABB getRenderBoundingBox(BannerBlockEntity blockEntity) {
++        net.minecraft.core.BlockPos pos = blockEntity.getBlockPos();
++        return net.minecraft.world.phys.AABB.encapsulatingFullBlocks(pos, pos.above());
```
Comment (KnightMiner) [inline patches/net/minecraft/client/renderer/blockentity/BannerRenderer.java.patch]: Don't banners go into the position below when they are on the wall? Or is that a separate renderer?

Comment (XFactHD) [reply patches/net/minecraft/client/renderer/blockentity/BannerRenderer.java.patch]: I was wondering why the reproduction case looked so weird and seemed to have the issue "the wrong way round" :D
I'll fix that shortly.

File: patches/net/minecraft/client/renderer/blockentity/SkullBlockRenderer.java.patch [hunk 2]
```diff
@@ -19,7 +19,7 @@
 +        SkullBlock.Type type = ((AbstractSkullBlock) blockEntity.getBlockState().getBlock()).getType();
 +        if (type == SkullBlock.Types.DRAGON) {
 +            net.minecraft.core.BlockPos pos = blockEntity.getBlockPos();
-+            return new net.minecraft.world.phys.AABB(pos.getX() - .5, pos.getY(), pos.getZ() - .5, pos.getX() + 1.5, pos.getY() + 1.5, pos.getZ() + 1.5);
++            return new net.minecraft.world.phys.AABB(pos.getX() - .625, pos.getY() - .3125, pos.getZ() - .625, pos.getX() + 1.62, pos.getY() + 1.0, pos.getZ() + 1.625);
```
Comment (Technici4n) [inline patches/net/minecraft/client/renderer/blockentity/SkullBlockRenderer.java.patch]: Why is xMax `1.62` and zMax `1.625`? If we are worried about potentially getting the numbers wrong I wouldn't mind rounding to full block coordinates just in case, BTW. Your call.

**Review by Technici4n — CHANGES_REQUESTED** [review]

**Review by Technici4n — APPROVED** [review]
LGTM
