### PR TITLE
Fix magic absorb not being applied to witch correctly

### LINKED ISSUE #2846: Witches lost magic resistance
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.216

**Steps to Reproduce:**
 1. Spawn a witch
 2. /damage <targeted_witch> 26 indirect_magic/magic/sonic_boom/thorns
 3. It dies

**Description of issue:**
Witches no longer have resistance against anything within #minecraft:witch_resistant_to

### PR DESCRIPTION
**Pull request by pynickle**
Fix #2846 

Available in all versions 1.21.1+

Need to backport to all versions 1.21.1+

### CODE REVIEW

**Comment by pynickle** [comment]
hh, why does the workflow fail? It succeed in my forked repo.

**Comment by sciwhiz12** [comment]
Huh, weird. Reran the failed job, and it now worked. I'm not going to look too deeply into that since it may just be a random fluke, but I'll keep it in mind if it happens again.

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
A simple fix indeed. 

On checking the calls to `getDamageAfterMagicAbsorb`, it seems there's a similar call site in `Player#actuallyHurt` which has the same issue. Please also fix that in the same manner.

**Review by sciwhiz12 — COMMENTED** [review]
I've thought about this more and looked at the code deeper (while checking that test change), and I think I misunderstood what the damage absorption code does.

If we look at `LivingEntity#getDamageAfterMagicAbsorb`, it applies the reductions to the damage container itself through `DamageContainer#setReduction` (which modifies the `newDamage`). That way, the damage container can control the reduction through any applied modifiers.

I think the correct fix here would be to modify `Witch#getDamageAfterMagicAbsorb` such that it uses `DamageContainer.Reduction`s to negate or reduce the damage to the Witch entity. Thus, the damage container itself would be responsible for the reduction changing the damage, rather than being applied externally.

This probably means a new value for `DamageContainer.Reduction`, since I think it doesn't fall under any of the existing ones.

I've asked @Caltinor, as the original implementor of the entity damage API, to review this as well.

**Comment by Caltinor** [comment]
I would still use `Reduction.ENCHANTMENTS` to match how things like protection are captured.  Logically it makes sense to add a kind of "natural resistance" value to this enum for the witch, but i'm not sure it's practical for any other context.  It would be an extra dimension of reductions that i'm unsure would have wider use outside of the witch.  that's just my concern though, it does make sense logically to have the distinction.

**Comment by sciwhiz12** [comment]
Sure, we can use `Reduction.ENCHANTMENTS` for now and re-assess in the future if it seems that it would be better to have a separate reduction type for an entity's natural resistance to certain types of damage.

**Comment by pynickle** [comment]
Modified the code in Witch.java. I hope this is okay.

File: patches/net/minecraft/world/entity/monster/Witch.java.patch [hunk 1]
```diff
@@ -0,0 +1,15 @@
+--- a/net/minecraft/world/entity/monster/Witch.java
++++ b/net/minecraft/world/entity/monster/Witch.java
+@@ -207,10 +_,11 @@
+     protected float getDamageAfterMagicAbsorb(DamageSource p_34149_, float p_34150_) {
+         p_34150_ = super.getDamageAfterMagicAbsorb(p_34149_, p_34150_);
+         if (p_34149_.getEntity() == this) {
+-            p_34150_ = 0.0F;
++            return 0.0F;
```
Comment (sciwhiz12) [inline patches/net/minecraft/world/entity/monster/Witch.java.patch]: Why is this simply a `return`? Wouldn't this mean the witch can damage itself, since the return value of this method is not used (which is why we need the `DamageContainer#setReduction` call below)?

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
I've been thinking about this PR a bit, and I think we have another potential issue to address that affects this fix.

`DamageContainer#setReduction` both stores the reduction value (in a map) and applies the value to the `newDamage` by way of subtraction. That immediate subtraction implies to me that the method is intended to be called _at most once_ for each `DamageContainer.Reduction` enum value. 

Otherwise, if there are multiple call sites, only the last call would have its value stored but all calls' values would be applied against `newDamage`. This would be very confusing in terms of the API, of "ghost" reductions to the damage.

Because of this, I believe we're forced to create a new `DamageContainer.Reduction` enum value for this purpose since we can't overload `ENCHANTMENTS` to avoid a potential doube-call for that.

So, this would mean:
- Creating a new `DamageContainer.Reduction` value (`INNATE_RESISTANCE` maybe?).
- Modifying `Witch#getDamageAfterMagicAbsorb` to call `setReduction` only once with the final value. Simplest modification here is to join the two `if`s with an `else` (since if the first one runs, the second one does nothing.)

@Caltinor, if you had the time, I'd appreciate your input on this again. If it is true that `setReduction` is intended to be called at most once, we should probably add a comment to that method to that effect.

---
The patch for `Witch` could be modified as follows:
```patch
diff --git i/patches/net/minecraft/world/entity/monster/Witch.java.patch w/patches/net/minecraft/world/entity/monster/Witch.java.patch
index 231e0de8f..5018061be 100644
--- i/patches/net/minecraft/world/entity/monster/Witch.java.patch
+++ w/patches/net/minecraft/world/entity/monster/Witch.java.patch
@@ -1,15 +1,16 @@
 --- a/net/minecraft/world/entity/monster/Witch.java
 +++ b/net/minecraft/world/entity/monster/Witch.java
-@@ -207,10 +_,12 @@
+@@ -207,10 +_,13 @@
      protected float getDamageAfterMagicAbsorb(DamageSource p_34149_, float p_34150_) {
          p_34150_ = super.getDamageAfterMagicAbsorb(p_34149_, p_34150_);
          if (p_34149_.getEntity() == this) {
-+            this.damageContainers.peek().setReduction(net.neoforged.neoforge.common.damagesource.DamageContainer.Reduction.ENCHANTMENTS, p_34150_);
++            this.damageContainers.peek().setReduction(net.neoforged.neoforge.common.damagesource.DamageContainer.Reduction.INNATE_RESISTANCE, p_34150_);
              p_34150_ = 0.0F;
          }
++        else // Neo: Join the two ifs; if the first one runs (reducing damage to 0), the second one (reducing damage by 15%) effectively does nothing
  
          if (p_34149_.is(DamageTypeTags.WITCH_RESISTANT_TO)) {
-+            this.damageContainers.peek().setReduction(net.neoforged.neoforge.common.damagesource.DamageContainer.Reduction.ENCHANTMENTS, p_34150_ * 0.85F);
++            this.damageContainers.peek().setReduction(net.neoforged.neoforge.common.damagesource.DamageContainer.Reduction.INNATE_RESISTANCE, p_34150_ * 0.85F);
              p_34150_ *= 0.15F;
          }
  
```

**Comment by Caltinor** [comment]
@sciwhiz12 your assessment on the intended behavior of `setReduction` is correct. So, I agree that we do want a new enum value to capture this.

**Comment by pynickle** [comment]
So, is the name INNATE_RESISTANCE confirmed for use, or will it be another name?

**Comment by sciwhiz12** [comment]
I can't think of a better name than `INNATE_RESISTANCE`. I originally thought of `NATURAL_RESISTANCE`, but "innate" is more specific as to the source of the resistance (coming from the mob themselves) rather than "natural". And of course, it has to be "resistance" rather than "immunity" because the latter implies a full reduction, while the former can be both full or partial damage reduction.

I've put out a small call on the Discord server for ideas, but let's go forward with that name for now and change it if necessary.

**Review by sciwhiz12 — APPROVED** [review]
Looks good to me. Tested by summoning a Witch, throwing a splash potion of harming, and checking its health through `/data get entity @n[type=witch] Health` (before the witch heals itself). The health goes down to `24.2f` from `26f`, the same as vanilla.
