### PR TITLE
Have TranslatableContents throw when fed improper arguments in dev

### LINKED ISSUE #703: Component.translatable crashes for non component/number/string objects.
Orion told me to open it as a ticket.

Atm a Component.translatable crashes with most objects that are neither components nor basic primitives.

I do agree that people shouldn't put random objects in there and instead either do .toString themselves or use the translatableEscape method.

But, I believe a lot of mods don't even know about this and the crashes are also in a way that makes it very hard to find the origin code.

Request is: Don't crash but throw a warning with stracktrace.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Closes https://github.com/neoforged/NeoForge/issues/703

The dev exception will look like this which is a bit more clearer than vanilla's error. And by having the throw in the constructor for TranslatableContent, it makes it easy to find the code that is the source of the problem.
image

Also fixed several spots in NeoForge where we were passing bad arguments as well.

Note: the track command's crash from bad argument passed to Translatable will be fixed in this PR: https://github.com/neoforged/NeoForge/pull/915

### CODE REVIEW

File: patches/net/minecraft/network/chat/contents/TranslatableContents.java.patch [hunk 1]
```diff
@@ -1,14 +1,28 @@
...
-                 j = l;
-             }
+@@ -81,6 +_,13 @@
+         this.key = p_265775_;
+         this.fallback = p_265204_;
+         this.args = p_265752_;
++        if (!net.neoforged.fml.loading.FMLEnvironment.production) {
++            for (Object arg : this.args) {
++                if (!(arg instanceof Component) && !isAllowedPrimitiveArgument(arg)) {
++                    throw new IllegalArgumentException("TranslatableContents's arguments must be a Component, Number, Boolean, or String. Was given " + arg + " for " + this.key);
```
Comment (Matyrobbrt) [inline patches/net/minecraft/network/chat/contents/TranslatableContents.java.patch]:
```suggestion
+                    throw new IllegalArgumentException("TranslatableContents' arguments must be either a Component, Number, Boolean, or a String. Was given " + arg + " for " + this.key);
```

**Review by Matyrobbrt — APPROVED** [review]

**Review by marchermans — APPROVED** [review]
