### PR TITLE
[1.20.4] Snapshot ModelDataManager in RenderChunkRegion instead of exposing original ModelDataManager owned by ClientLevel

### LINKED ISSUE #321: ModelData is not snapshotted during chunk build tasks
Chunks are built/meshed on worker threads, however, the return value of `ModelDataManager#getAt` is used in the [`SectionRenderDispatcher`](https://github.com/neoforged/NeoForge/blob/3156629503564a7a77c2321e2b0a081d08daef86/patches/net/minecraft/client/renderer/chunk/SectionRenderDispatcher.java.patch#L60-L64) patch as-is, without a copy being made of the map. Because `ModelDataManager` uses thread-safe maps, this won't cause a crash, but can lead to the data becoming out of sync with the task's copy of block data if the map is updated later by another `getAt` call.

The proper solution here is to make a copy of the map and store that in the task, to be consistent with other accesses to the client world.

On a related note: the implementation of `getModelDataManager()` on `RenderChunkRegion` simply delegates to the client level, which is again inconsistent as the model data retrieved via this code path could be more up-to-date than the copy of the block data made within the region.

### PR DESCRIPTION
**Pull request by XFactHD**
This PR reworks the `ModelDataManager` to separate it into an "active" manager which is owned by a `ClientLevel` and can have its data refreshed at the request of a `BlockEntity` and a "snapshot" manager which is owned by a `RenderChunkRegion` and is immutable. The snapshot is created from the active manager when a compile task for a section is created (happens on the main client thread) and contains the data from the section being compiled plus the surrounding sections provided as context for neighbor-sensitive operations (i.e. vanilla's face culling, connected textures systems, etc.), which covers a volume of 48<sup>3</sup> blocks in the current vanilla implementation. This mostly matches the strategy of how vanilla copies blockstates except that it doesn't copy the entire chunk height and instead only covers the y levels required as context.

The rational behind these changes is threefold:

1. The model data captured by `SectionRenderDispatcher.RenderSection.RebuildTask` as well as the data used by other model data consumers on meshing threads can go out of sync with the snapshoted `BlockState`s when a BE in the related chunk requests an update after the data is captured and another model data consumer (i.e. an implementor of the appearance API) then retrieves data from the `ModelDataManager`, causing an automatic refresh. The desync in `SectionRenderDispatcher.RenderSection.RebuildTask` could technically be fixed by just creating a copy of the model data map backing the manager but the desync for other consumers can only be fixed with snapshoting
2. If an update of the model data happens as described above, then the entire refresh happens off-thread which is inherently unsafe as mods are effectively free to do any computation they want in `IBlockEntityExtension#getModelData()`
3. The current implementation has the potential for a fatal race condition between `ModelDataManager#requestRefresh()` and `ModelDataManager#refreshAt()` due to the iterator of `Collections#synchronizedSet()` not providing any synchronization (which is documented on said method). If the main thread retrieves a set of BEs from the `needModelDataRefresh` map in `requestRefresh()`, a worker then removes the same set from said map and starts iterating it in `refreshAt()` (i.e. due to a mod using model data in the appearance API) and the main thread then adds the new BE position to the set, then a CME is thrown by the iterator used implicitly by the foreach loop in `refreshAt()`.

The proposed changes are currently largely untested outside of checking that chunk rendering still works at all in vanilla NeoForge. I will be throwing this at FramedBlocks in the coming days to test the changes more thoroughly as it makes heavy use of model data in all scenarios mentioned above. I would welcome any additional testing from anyone who has a mod with comparable needs.

Fixes #321

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java [hunk 1]
```diff
@@ -32,49 +33,125 @@
...
-    private final Level level;
-    private final Map<ChunkPos, Set<BlockPos>> needModelDataRefresh = new ConcurrentHashMap<>();
-    private final Map<ChunkPos, Map<BlockPos, ModelData>> modelDataCache = new ConcurrentHashMap<>();
+public abstract sealed class ModelDataManager permits ModelDataManager.Active, ModelDataManager.Snapshot {
+    ModelDataManager() {}
 
-    public ModelDataManager(Level level) {
-        this.level = level;
-    }
+    public abstract void requestRefresh(BlockEntity blockEntity);
```
Comment (embeddedt) [inline src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java]: How about making this a public method on `Active` since it's useless to call on a snapshot?

**Review by embeddedt — COMMENTED** [review]
Should the `getModelDataManager` override in `ClientLevel` be widened to return `Active` rather than a generic `ModelDataManager`?

File: src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java [hunk 2]
```diff
@@ -32,49 +32,122 @@
...
+            this.level = level;
+        }
+
+        public void requestRefresh(BlockEntity blockEntity) {
+            if (isOtherThread()) {
+                throw new UnsupportedOperationException("Cannot request ModelData refresh outside the owning thread: " + owningThread);
+            }
+
+            Preconditions.checkNotNull(blockEntity, "Block entity must not be null");
+            needModelDataRefresh.computeIfAbsent(SectionPos.asLong(blockEntity.getBlockPos()), $ -> new HashSet<>())
```
Comment (embeddedt) [inline src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java:85]: Maybe assert that the block entity belongs to this level too.

**Review by embeddedt — DISMISSED** [review]
Implementation seems solid to me, might be nice to have some Javadoc but it's not critical for an internal API, in my opinion. `getAt[orEmpty]` is fairly self-explanatory.

File: src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java [hunk 3]
```diff
@@ -32,49 +32,123 @@
...
+        }
+
+        @Override
+        public ModelData getAtOrEmpty(BlockPos pos) {
+            return Objects.requireNonNullElse(getAt(pos), ModelData.EMPTY);
+        }
+
+        @Override
+        public ModelDataManager.Snapshot snapshotSectionRegion(int sectionMinX, int sectionMinY, int sectionMinZ, int sectionMaxX, int sectionMaxY, int sectionMaxZ) {
+            return new ModelDataManager.Snapshot(this, sectionMinX, sectionMinY, sectionMinZ, sectionMaxX, sectionMaxY, sectionMaxZ);
```
Comment (embeddedt) [inline src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java:108]: I think this should throw if you call it off the main thread. I just did it by accident while porting Embeddium locally.

**Comment by XFactHD** [comment]
> might be nice to have some Javadoc but it's not critical for an internal API

I'll add some javadocs tomorrow with a fresh mind, since this is technically API surface (I'm considering moving the annotation to the actual implementation classes) for consumption around things like the appearance API.

File: src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java [hunk 4]
```diff
@@ -109,6 +129,11 @@ private boolean isOtherThread() {
         }
     }
 
+    /**
+     * A snapshot of the state of the active manager at the point in time when a chunk section was prepared for re-rendering.
```
Comment (embeddedt) [inline src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java]: Should probably clarify that it's not a snapshot of the *entire* active manager (although I should hope most people can figure this out from a cursory code read).

**Review by embeddedt — DISMISSED** [review]

**Review by embeddedt — DISMISSED** [review]

File: patches/net/minecraft/world/level/Level.java.patch [hunk 5]
```diff
@@ -235,6 +235,11 @@
 +        if (value > maxEntityRadius)
 +            maxEntityRadius = value;
 +        return maxEntityRadius;
++    }
++
++    @Override
++    public net.neoforged.neoforge.client.model.data.ModelDataManager.Active getModelDataManager() {
```
Comment (Technici4n) [inline patches/net/minecraft/world/level/Level.java.patch:242]: Technically this should be annotated with nullable, else you are saying that the method does not return null. (Since `T` is a subtype of `@Nullable T`).

File: src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java [hunk 6]
```diff
@@ -22,59 +23,166 @@
...
+            this.modelDataCache = cache.isEmpty() ? Long2ObjectMaps.emptyMap() : cache;
+        }
+
+        private Snapshot() {
+            this.sectionMin = this.sectionMax = SectionPos.asLong(0, 0, 0);
+            this.modelDataCache = Long2ObjectMaps.emptyMap();
+        }
+
+        @Override
+        public ModelData getAt(BlockPos pos) {
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java:172]: should be nullable for the same reason

**Review by Technici4n — CHANGES_REQUESTED** [review]
Looks very nice, just two nullability nitpicks.

**Review by Technici4n — APPROVED** [review]
