### PR TITLE
[1.20.2] Band-aid fix connections between Neo and vanilla

### LINKED ISSUE #205: [1.20.2] Connection between Neoforge and Vanilla Server/Client broken
**Minecraft Version:** 1.20.2

**NeoForge Version:** 20.2.4-beta (probably with 20.2.3 and 20.2.5 too, haven't tested yet)

**Logs:** 
Client's debug log when connecting to a vanilla server:
[neoforge client's debug.log](https://github.com/neoforged/NeoForge/files/13210280/debug.log)
Server's debug log when a vanilla client tries to connect to the server
[neoforge server's debug.log](https://github.com/neoforged/NeoForge/files/13210286/debug.log)

**Steps to Reproduce:**
 1. Either start Neoforge or Minecraft Vanilla Server
 2. Either start Vanilla or Neoforge Client
 3. Try to connect

**Description of issue:**
When trying to connect to a Neoforge server with a vanilla client you'll get an "Incompatible Version" Error (as seen in the next image)
image
You'll get the same error when running a vanilla server and try to connect with a neoforge client (as seen in the next image)
image

### PR DESCRIPTION
**Pull request by XFactHD**
This PR implements a band-aid fix for the connection issue between Neo clients and vanilla servers and vice-versa.
This serves as a holdover until it's fixed properly in the networking refactor and to make sure Neo<->vanilla connections work fine in 1.20.2 in case the networking refactor is retargeted to 1.20.3.

Fixes #205

### CODE REVIEW

File: patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch [hunk 1]
```diff
@@ -19,18 +26,17 @@
...
++      this(p_179801_.readVarInt(), p_179801_.readUtf(255), p_179801_.readUnsignedShort(), ClientIntent.byId(p_179801_.readVarInt()), null);
     }
  
     @Override
-@@ -25,6 +_,7 @@
-       p_134737_.writeUtf(this.hostName);
+    public void write(FriendlyByteBuf p_134737_) {
+       p_134737_.writeVarInt(this.protocolVersion);
+-      p_134737_.writeUtf(this.hostName);
++      p_134737_.writeUtf(this.hostName + "\0" + this.fmlVersion + "\0");
```
Comment (Matyrobbrt) [inline patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch]: Why does this have two null chars?

Comment (XFactHD) [reply patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch]: This was taken almost directly from the previous implementation: https://github.com/neoforged/NeoForge/blob/55133ebdb40c8e83d8d816b5bdf06c0683c48116/patches/minecraft/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch#L26. You'd probably have to ask cpw what the intention was with the trailing null char.

Comment (pupnewfster) [reply patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch]: I believe it might have been to easier extract our block of data in case another server (such as some bukkit one) decided to append data and didn't bother with their own separator

Comment (XFactHD) [reply patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch]: Sounds like a reasonable explanation. Would you still consider that relevant enough to keep the trailing null char?

**Review by sciwhiz12 — APPROVED** [review]
Tested, and it works. :shipit:
