### PR TITLE
Truncate tags command clipboard text within 32k string limit

### LINKED ISSUE #1543: Running command /neoforge tags <registry> list could kick player when there are too many tags
**Minecraft Version:** {Minecraft version}

1.21.1

**NeoForge Version:** {NeoForge version. *Version number, not latest/rb*}

21.1.47

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

https://gist.github.com/YocyCraft/29d218b2409db9cf5d9d09cb48736635

**Steps to Reproduce:**

 1. Open ATM10 Modpack
 2. Run command /neoforge tags minecraft:items list
 3. Kicked off from the game

**Description of issue:**

There are too many tags of registry so the message returned from command is too long
屏幕截图 2024-09-15 220113

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #1543 by truncating the number of lines in the copy-to-clipboard text of the `/neoforge tags` command to as much entries as can fit within the (artificial) limit of 32.6k characters for elements (plus some allowance for the explanatory text for the truncation).

Tested by modifying the `list` subcommand temporarily to have 30,000+ dummy entries (adding to the count and using `Stream.concat`), and it works.

A previous version of this PR artifically constrained the number of entries to 1,000 entries (approximately the number of 32-character-long entries that fits into 32,767--the limit of strings in `FriendlyByteBuf`--and rounded down the nearest hundreds). At @Technici4n's prompting (in Discord), I've changed the strategy to instead fit as much of the entries as possible by counting their lengths as they're added to the text, and cutting off when the text is about to reach a limit, which is current 32,600 characters. That leaves about ~167 characters room for the explanatory note for the truncation, which should be plenty.

---

We could perhaps consider adding a new subcommand to `/neoforge dump` which exports the list of tags for registries (or elements in a tag, or tags of an element). Should that be added, we may also remove the functionality of the copy-on-clipboard for `/neoforge tags`, and perhaps even have it instead give the appropriate `/neoforge dump` command to the user with arguments filled in.

### CODE REVIEW

**Comment by HenryLoenwind** [comment]
One thought: Does this really need to run as a server command? Those registries are synced to the client, aren't they?

**Comment by lukebemish** [comment]
Not _necessarily_ -- afaik that command dumps tags for any registry, including server only ones? Registries can have tags and not be synced.

**Comment by sciwhiz12** [comment]
Updated to use a new truncation strategy that fits as much text as possible into the clipboard text, rather than constraining the amount of elements based on a precalculated heuristic on element lengths. See updated PR description for details.

File: src/main/java/net/neoforged/neoforge/server/command/TagsCommand.java [hunk 1]
```diff
@@ -171,16 +175,45 @@ private static MutableComponent createMessage(final MutableComponent header,
...
+                countedLines++;
+            }
+            // Remove the trailing newline if present
+            if (!clipboardTextBuilder.isEmpty()) {
+                clipboardTextBuilder.deleteCharAt(clipboardTextBuilder.length() - 1);
+            }
+
+            if (reachedLimit) {
+                // Almost went over the limit; add additional info to clipboard text
+                clipboardText = "(Too many entries to fit in clipboard, showing only first " + countedLines + " entries...)" + '\n'
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/server/command/TagsCommand.java:207]: Shouldn't there be a `\n` at the beginning since you remove it just above?

Comment (sciwhiz12) [reply src/main/java/net/neoforged/neoforge/server/command/TagsCommand.java:207]: What do you mean? The clipboard text builder will contain a string that doesn't end in a newline, and in the case of the limit being reached, the starting truncation notice and the ending truncation notice are both separated by a newline from the main (elements) text.

Comment (Technici4n) [reply src/main/java/net/neoforged/neoforge/server/command/TagsCommand.java:207]: Ah right this looks correct.

**Review by Technici4n — APPROVED** [review]

**Review by XFactHD — APPROVED** [review]
