### PR TITLE
Fix `ParametrizedGameTestSequence` swallowing exceptions

### LINKED ISSUE #1998: ParametrizedGameTestSequence swallows exception messages
**Minecraft Version:** 1.21.1
**NeoForge Version:** 21.1.123

**Logs:**
> Tests: [03Mar2025 11:14:55] [TestFramework mekanismtests:tests]: Test 'testWrongErrorMessage' has been enabled.
[11:14:55] [Server thread/ERROR] [minecraft/LogTestReporter]: testWrongErrorMessage failed at 12556713, -60, 11028596! Expected value to be non-null!

**Steps to Reproduce:**
```java
@GameTest
@EmptyTemplate
@TestHolder(description = "Shows the wrong error message is displayed.")
public static void testWrongErrorMessage(final ExtendedGameTestHelper helper) {
    helper.startSequence().thenMap(() -> {
        helper.fail("This error message does not display");
        return "unused return value";
    }).thenMap(Function.identity()).thenSucceed();
}
```

**Description of issue:**

When throwing game test assert exceptions from within a `ParametrizedGameTestSequence`, it causes the wrong exception message to be displayed. It will always display `Expected value to be non-null!` as the atomic reference never gets a value set due to the exception that occurred. This can lead to confusing error messages in tests as instead of receiving the expected failure message, one about null values is printed instead.

Having anything attempt to use the value of the `thenMap` that failed, causes the `Expected value to be non-null` message to be printed anything

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #1998 by making `ParametrizedGameTestSequence` rethrow the exception from the previous value supplier (which may be a `ParametrizedGameTestSequence`) before throwing its own exception about the value being `null`.

When a previous `ParametrizedGameTestSequence` throws an exception, its returned value will be `null`, causing a succeeding `ParametrizedGameTestSequence` to throw its own error about the value being `null`, hiding the original exception as `GameTestInfo` only stores a single failure exception.

To avoid this, `ParametrizedGameTestSequence` now stores the exception thrown from the previous step and rethrows it, so the `GameTestInfo` will always have the original exception. This also has the side-effect that further steps of `thenMap(Function)` (in unbroken continuity with the first erroring one) will not execute but instead rethrow the original exception.

---

You can test this behavior through this adapted case from the issue:

```java
@GameTest
@EmptyTemplate
@TestHolder(description = "Shows the original error message is displayed.")
public static void testOriginalErrorMessage(final ExtendedGameTestHelper helper) {
    helper.startSequence()
            .thenMap(() -> {
                helper.fail("This error message should display");
                return "unused return value";
            })
            .thenMap(Function.identity())
            .thenMap(Function.identity())
            .thenMap(value -> {
                helper.fail("This error message should NOT display");
                return "unused return value";
            })
            .thenMap(Function.identity())
            .thenMap(Function.identity())
            .thenSucceed();
}
```

The first error message should be displayed, and not the second one. 

Note that a `thenMap` call with a `Supplier` provided will 'reset' the trace, and will always execute regardless of the previous step (and thus future sequence steps will also execute). However, that will not reset the status of the game test -- the failure will persist until something else calls the appropriate methods on the game test helper. 

You can test this by changing the second substantial `thenMap` call to provide a `Supplier` (`value ->` becomes `() ->`): the second error message will always display in that case. If the second `helper.fail` is also removed with that change to `Supplier` still in effect, then the first error message will be displayed, but the rest of the steps after that second substantial `thenMap` will still execute.

### CODE REVIEW

File: testframework/src/main/java/net/neoforged/testframework/gametest/ParametrizedGameTestSequence.java [hunk 1]
```diff
@@ -24,11 +24,25 @@ public ParametrizedGameTestSequence(GameTestInfo info, ExtendedSequence sequence
         this.info = info;
         this.sequence = sequence;
 
+        final AtomicReference<RuntimeException> capturedException = new AtomicReference<>();
```
Comment (Matyrobbrt) [inline testframework/src/main/java/net/neoforged/testframework/gametest/ParametrizedGameTestSequence.java]: This should catch any `Throwable`.

**Review by Matyrobbrt — CHANGES_REQUESTED** [review]

File: testframework/src/main/java/net/neoforged/testframework/gametest/ParametrizedGameTestSequence.java (hunk 1 above)
Comment (sciwhiz12) [reply testframework/src/main/java/net/neoforged/testframework/gametest/ParametrizedGameTestSequence.java]: How do you want me to rethrow the `Throwable`? Guava's `Throwables.throwIfUnchecked` and a fallback `new RuntimeException(ex)` for checked exceptions?

Comment (sciwhiz12) [reply testframework/src/main/java/net/neoforged/testframework/gametest/ParametrizedGameTestSequence.java]: Done. Used the good ol' sneaky throw tactic.

**Review by Matyrobbrt — APPROVED** [review]

**Comment by sciwhiz12** [comment]
@neoforged/bots backport 1.21.1
