### PR TITLE
Fix issues with binding function keys on Mac systems

### LINKED ISSUE #1683: Function keys do not work properly with certain keyboards on macOS
**Minecraft Version:** 1.20.1, 1.20.4, 1.21.1

**NeoForge Version:** 47.1.106, 20.4.237, 21.1.77

**Logs:** 1.21.1: https://gist.github.com/unilock/a699a9ebba05e3da37dbb5759e381f16

**Steps to Reproduce:**
 1. Install Minecraft 1.21.1 + NeoForge on macOS
 2. Attempt to bind a key to a function key (F1, F2, F3, ...)
 3. The key is bound as "Not Bound" instead

**Description of issue:**
The function keys (F1 thru F12) can't be used with keybinds (they always end up as "Not Bound"), and the debug keybinds (F3+x) just bring up the debug overlay instead of... debugging.

I assume this is because "F3" on macOS is technically "fn+F3" ("fn" being a separate key). I guess NeoForge detects the "fn" instead of (or before) the "F3", and treats it as an unknown key - thus "Not Bound".

Interestingly, editing `options.txt` to bind a function key results in that keybind working fine in-game.

All of this works without issue on both vanilla and Fabric.

Image

### PR DESCRIPTION
**Pull request by Matyrobbrt**
With the help of @codexadrian I was able to find the cause of this issue. With the following simple listeners added to a mod
```java
@SubscribeEvent
static void onPress(ScreenEvent.KeyPressed.Pre event) {
	if (event.getScreen() instanceof KeyBindsScreen) {
		var key = InputConstants.getKey(event.getKeyCode(), event.getScanCode());
		Ihatekeybinds.LOGGER.error("Pressed key {} with code {}, modifiers {}, scan code {}", key, event.getKeyCode(), event.getModifiers(), event.getScanCode());
	}
}

@SubscribeEvent
static void onRelease(ScreenEvent.KeyReleased.Pre event) {
	if (event.getScreen() instanceof KeyBindsScreen) {
		var key = InputConstants.getKey(event.getKeyCode(), event.getScanCode());
		Ihatekeybinds.LOGGER.error("Released key {} with code {}, modifiers {}, scan code {}", key, event.getKeyCode(), event.getModifiers(), event.getScanCode());
	}
}
```
we can notice that attempting to press `Fn` + any function key when the option to `Use F keys as standard function keys` is turned off will cause the following log lines to be printed
```
[10Jul2025 17:25:41.591] [Render thread/ERROR] [com.matyrobbrt.keybinds.Ihatekeybinds/]: Released key scancode.63 with code -1, modifiers 0, scan code 63
[10Jul2025 17:25:42.116] [Render thread/ERROR] [com.matyrobbrt.keybinds.Ihatekeybinds/]: Pressed key key.keyboard.f1 with code 290, modifiers 0, scan code 122
[10Jul2025 17:25:42.196] [Render thread/ERROR] [com.matyrobbrt.keybinds.Ihatekeybinds/]: Released key key.keyboard.f1 with code 290, modifiers 0, scan code 122
[10Jul2025 17:25:42.274] [Render thread/ERROR] [com.matyrobbrt.keybinds.Ihatekeybinds/]: Released key scancode.63 with code -1, modifiers 0, scan code 63
```
As it would seem, Mac systems fire the `RELEASE` event for a special key with the scan code 63 before pressing the function key, and after releasing it. For this issue, only the first part is relevant. By firing a `RELEASE` event before even pressing the function key, our patch in `KeyBindsScreen` detects the `keyReleased` event, sets the `selectedKey`'s value to `UNKNOWN` (as this key event has the code -1) and then sets the `selectedKey` to null, resetting the keybind and preventing the game from further picking up the press/release combination of the real function key.  
The fix is rather naive but unfortunately I was not able to come up with something better than simply hardcoding the patch to ignore scancode 63 events.

Fixes #1683

P.S.: this does not affect vanilla as they only listen for `keyPressed` which as we have determined above does not fire for the special `Fn` key

~~**PENDING TESTING**~~ Testing has confirmed the issue to no longer be present with this PR.

### CODE REVIEW

File: patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch [hunk 1]
```diff
@@ -40,10 +40,13 @@
...
 +
-+    // Neo: This method is override to more easily handle modifier keys
++    // Neo: This method is overridden to more easily handle modifier keys
 +    @Override
 +    public boolean keyReleased(int p_94715_, int p_94716_, int p_94717_) {
-+        if (this.selectedKey != null) {
++        // We ignore events from keys with the scan code 63 as they're emitted
++        // (only as RELEASE, not PRESS) by Mac systems to indicate that "Fn" is being pressed
++        // See https://github.com/neoforged/NeoForge/issues/1683
++        if (this.selectedKey != null && (net.minecraft.Util.getPlatform() != net.minecraft.Util.OS.OSX || p_94716_ != 63)) {
```
Comment (XFactHD) [inline patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch]:
```suggestion
+        if (this.selectedKey != null && (!net.minecraft.client.Minecraft.ON_OSX || p_94716_ != 63)) {
```

Comment (Matyrobbrt) [reply patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch]: Great, so that's the 3rd way I've found to check whether you're on a Mac in Minecraft code

File: patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch [hunk 2]
```diff
@@ -40,10 +40,13 @@
 +        }
 +    }
 +
-+    // Neo: This method is override to more easily handle modifier keys
++    // Neo: This method is overridden to more easily handle modifier keys
 +    @Override
 +    public boolean keyReleased(int p_94715_, int p_94716_, int p_94717_) {
-+        if (this.selectedKey != null) {
++        // We ignore events from keys with the scan code 63 as they're emitted
```
Comment (Technici4n) [inline patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch:46]: Is there no LWJGL constant for the scan code 63?

Comment (Matyrobbrt) [reply patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch:46]: No but that aside, why would there be? Scan codes are platform-specific and GLFW only provides constants for the general key codes.

Comment (Technici4n) [reply patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch:46]: Ok

**Review by Technici4n — APPROVED** [review]

**Review by XFactHD — APPROVED** [review]
