### PR TITLE
Run CapabilityHooks::registerVanillaProviders at LOW priority

### LINKED ISSUE #1288: CapabilityHooks#registerVanillaProviders overwrites Mod-registered Capabilities in some Scenarios
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.86-beta (but reproduces as early as .65-beta and probably all the way before too on 1.21

**Logs:** No logs but a related bug report https://github.com/klikli-dev/occultism/issues/1148

**Steps to Reproduce:**
 It reproduces consistently with this mod combination: https://github.com/klikli-dev/occultism/issues/1148#issuecomment-2223467526 but ONLY in production, e.g. on a curseforge profile, not if I have the same mods via cursemaven in the MDK.
However, I believe that to be only a happy accident, because the underlying issue seems to be the event registration order. If a 1:1 repro is needed anyway I can provide a curseforge pack defintion and a video.

**Description of issue:**
CapabilityHooks#registerVanillaProviders is added as listener with EventPriority.NORMAL.
Most mods will also add their listeners with this priority, especially for capabilities.

It seems the order of events with the same priority depends on factors that are not entirely deterministic from a modder's perspective (e.g. other mods present impact that?). 

As a result I had the situation that in the MDK, my item capability handler for my custom entity was added before the vanilla provider, which resulted in everything working.
In *some* modpacks, however (such as the above combination) my custom handler was added after the vanilla provider. Because the vanilla provider returns a capability for every living entity, my own handler is never returned (See EntityCapability#getCapability which returns on the first non-null cap) 

This can be solved by registering my handler with a higher priority, however I believe that that is not desired behaviour. The vanilla providers should likely be registered with a lower priority than normal, to avoid this "undetermined" behaviour if modders use the default priority.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Closes https://github.com/neoforged/NeoForge/issues/1288

Having it at NORMAL was causing hard-to-diagnosis issues in prod where a mod's cap is overwritten by neo or not depending on load order. Putting it at LOW allows mods to work out of the box without needing to dig into priorities

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java [hunk 1]
```diff
@@ -616,7 +617,7 @@ public NeoForgeMod(IEventBus modEventBus, Dist dist, ModContainer container) {
         DualStackUtils.initialise();
         TagConventionLogWarning.init();
 
-        modEventBus.addListener(CapabilityHooks::registerVanillaProviders);
+        modEventBus.addListener(EventPriority.LOW, CapabilityHooks::registerVanillaProviders);
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java]: Only the fallback providers should be registered using `LOW`. (i.e. the ones that might target mod content)

**Review by Technici4n — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java (hunk 1 above)
Comment (TelepathicGrunt) [reply src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java]: Ok I think I got it this time. Thank you for the heads up!

File: src/main/java/net/neoforged/neoforge/capabilities/CapabilityHooks.java [hunk 2]
```diff
@@ -112,6 +112,28 @@ public static void registerVanillaProviders(RegisterCapabilitiesEvent event) {
             event.registerEntity(Capabilities.ItemHandler.ENTITY_AUTOMATION, entityType, (entity, ctx) -> new InvWrapper(entity));
         }
         event.registerEntity(Capabilities.ItemHandler.ENTITY, EntityType.PLAYER, (player, ctx) -> new PlayerInvWrapper(player.getInventory()));
+
+        event.registerItem(Capabilities.ItemHandler.ITEM, (stack, ctx) -> new ComponentItemHandler(stack, DataComponents.CONTAINER, 27),
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/capabilities/CapabilityHooks.java:117]: nitpick: You could have moved `// Items` up here.

**Review by Technici4n — APPROVED** [review]
