### PR TITLE
Fix BiomeSpecialEffectsBuilder to copy backgroundMusicVolume

### LINKED ISSUE #1733: [1.21.4]If you enter the Pale garden in 1.21.4. not music fade out
**Minecraft Version:** 1.21.4
**NeoForge Version:** 21.4.2-beta

**Description of issue:**

The background music that should fade out in Pale Garden doesn't fade out.

mayby ```net.minecraft.client.Minecraft#getSituationalMusic``` is not support fade out?

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #1733 by also copying `backgroundMusicVolume` in the copy factory for `BiomeSpecialEffectsBuilder`. Tested by checking that walking into a pale garden biome with background music playing causes the music to slowly fade out, and then fade back in when walking outside of the pale garden biome. See also https://github.com/neoforged/NeoForge/pull/1766#issuecomment-2559770847 for a bit more information.

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/common/world/BiomeSpecialEffectsBuilder.java [hunk 1]
```diff
@@ -30,6 +30,7 @@ public static BiomeSpecialEffectsBuilder copyOf(BiomeSpecialEffects baseEffects)
         baseEffects.getAmbientMoodSettings().ifPresent(builder::ambientMoodSound);
         baseEffects.getAmbientAdditionsSettings().ifPresent(builder::ambientAdditionsSound);
         baseEffects.getBackgroundMusic().ifPresent(builder::backgroundMusic);
+        builder.backgroundMusicVolume = baseEffects.getBackgroundMusicVolume();
```
Comment (embeddedt) [inline src/main/java/net/neoforged/neoforge/common/world/BiomeSpecialEffectsBuilder.java:33]: I would avoid setting the field directly in case vanilla adds side effects later.

```suggestion
        builder.backgroundMusicVolume(baseEffects.getBackgroundMusicVolume());
```

**Review by embeddedt — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/common/world/BiomeSpecialEffectsBuilder.java (hunk 1 above)
Comment (Technici4n) [reply src/main/java/net/neoforged/neoforge/common/world/BiomeSpecialEffectsBuilder.java:33]: Well, the PR is consistent with how `grassColorModifier` is set above.

Comment (embeddedt) [reply src/main/java/net/neoforged/neoforge/common/world/BiomeSpecialEffectsBuilder.java:33]: Oh, true.

**Review by embeddedt — APPROVED** [review]

**Review by Technici4n — APPROVED** [review]
