### PR TITLE
[1.20.2] Use map backing the atlas instead of the atlas itself for liquid texture lookups

### LINKED ISSUE #200: Minecraft crashes when resources are reloaded near an ocean
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.79

log: https://gist.github.com/Lolothepro/492ec28746b1971da65b9c7fba5bc672
crash report: https://gist.github.com/Lolothepro/53ef8b98fdd51161e235075a1858a564
log + crash: https://mclo.gs/fEVrWeH

**Description of issue:**

4471952105434132996
`/execute in minecraft:overworld run tp @s -197.87 63.00 656.28 -149.26 18.15`

https://github.com/neoforged/NeoForge/assets/68275908/5dfb7a33-a79d-4d21-96c2-3a65e9fa5bc9

video log: https://mclo.gs/exRV1je

### PR DESCRIPTION
**Pull request by XFactHD**
This PR changes the liquid texture lookups in `LiquidBlockRenderer` to directly use the map backing the texture atlas instead of going through the atlas in order to prevent crashes when a chunk is re-batched while reloading resources.

I would appreciate testing by others who can reproduce the initial issue as I am completely unable to reproduce it.

Fixes #200

### CODE REVIEW

**Comment by Lolothepro** [comment]
I can confirm that it's fixed

File: src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+import net.minecraft.client.renderer.texture.MissingTextureAtlasSprite;
+import net.minecraft.client.renderer.texture.TextureAtlas;
+import net.minecraft.client.renderer.texture.TextureAtlasSprite;
+import net.minecraft.core.BlockPos;
+import net.minecraft.resources.ResourceLocation;
+import net.minecraft.world.level.BlockAndTintGetter;
+import net.minecraft.world.level.material.FluidState;
+import net.neoforged.neoforge.client.extensions.common.IClientFluidTypeExtensions;
+
+public final class FluidSpriteCache {
```
Comment (Matyrobbrt) [inline src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java:25]: Should this class be marked as `@ApiStatus.Internal`, or at the very least the `reload` method?

Comment (XFactHD) [reply src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java:25]: I intentionally didn't mark the class as internal because I can see mods making use of this as well. Marking `reload()` as internal seems reasonable though, I'll change that shortly.

**Review by sciwhiz12 — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+
+        return new TextureAtlasSprite[] {
+                textures.getOrDefault(props.getStillTexture(fluid, level, pos), missingSprite),
+                textures.getOrDefault(props.getFlowingTexture(fluid, level, pos), missingSprite),
+                overlay == null ? null : textures.getOrDefault(overlay, missingSprite),
+        };
+    }
+
+    @ApiStatus.Internal
+    @SuppressWarnings("deprecation")
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java:46]: You can get the sprite from some menu if you want to remove the deprecation. :P

File: src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+import net.minecraft.client.renderer.texture.TextureAtlas;
+import net.minecraft.client.renderer.texture.TextureAtlasSprite;
+import net.minecraft.core.BlockPos;
+import net.minecraft.resources.ResourceLocation;
+import net.minecraft.world.level.BlockAndTintGetter;
+import net.minecraft.world.level.material.FluidState;
+import net.neoforged.neoforge.client.extensions.common.IClientFluidTypeExtensions;
+import org.jetbrains.annotations.ApiStatus;
+
+public final class FluidSpriteCache {
```
Comment (Technici4n) [inline src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java:25]: Can you add javadoc to this class as well as to `getFluidSprites`? Ideally explaining why this should be used (i.e. off-thread sprite access).

**Review by Technici4n — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java (hunk 3 above)
Comment (XFactHD) [reply src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java:25]: I've added some simple docs. I can't think of anything better right now, so if you have suggestions for anything better, then I'm all ears.

File: src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java (hunk 2 above)
Comment (XFactHD) [reply src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java:46]: Accessing the atlas location via `InventoryMenu.BLOCK_ATLAS` seems like an anti-pattern to me, I'd rather suppress the deprecation warning instead.

**Review by Technici4n — APPROVED** [review]
