### PR TITLE
Hide demo timer when debug overlay is open

### LINKED ISSUE #863: Text in demo mode is not rendered correctly
**NeoForge Version:** 20.5.5-beta

Explanation:

In Minecraft 1.20.4, [this PR](https://github.com/neoforged/NeoForge/pull/357) causes demo mode text to be rendered if the F3 menu is closed as Minecraft Vanilla, and if the F3 menu is opened as part of the F3 menu.

This no longer works in NeoForge 1.20.5, because the Minecraft GUI system has changed.

Reproduction steps:
1.Launch Minecraft Demo
2.Generate a world
3.Press F3

Screenshot:

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR fixes #863 by hiding the demo timer (on the player HUD) when the (F3) debug overlay is visible, to avoid overlap between the demo timer and the debug overlay.

The demo timer is visible as the first line on the right side of the debug overlay (as added by #357), so the information is always available to the user.

### CODE REVIEW

**Review by embeddedt — DISMISSED** [review]

File: patches/net/minecraft/client/gui/Gui.java.patch [hunk 1]
```diff
@@ -237,6 +237,15 @@
              }
          }
  
+@@ -664,7 +_,7 @@
+     }
+ 
+     private void renderDemoOverlay(GuiGraphics p_281825_, float p_316211_) {
+-        if (this.minecraft.isDemo()) {
++        if (this.minecraft.isDemo() && !this.getDebugOverlay().showDebugScreen()) { // NEO: Hide demo timer when F3 debug overlay is open
```
Comment (XFactHD) [inline patches/net/minecraft/client/gui/Gui.java.patch]: Please add a reference to the Mojira issue: https://bugs.mojang.com/browse/MC-271166

**Review by embeddedt — APPROVED** [review]

**Review by XFactHD — APPROVED** [review]
