### PR TITLE
Fix MC-219981 by healing leader zombie health relative to new max health

### LINKED ISSUE #2095: [1.21.1] (MC-219981) Leader zombies with max health bonus does not spawn with new max health
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.141

**Logs:** 

**Steps to Reproduce:**
This includes the entire process of discovering the issue.
https://github.com/DragonSurvivalTeam/DragonSurvival/issues/786

**Description of issue:**
I noticed the mechanism that generates super monsters based on Local difficulty probability, but it seems that while setting the maximum health cap, the current health value was not set.

### PR DESCRIPTION
**Pull request by Matyrobbrt**
[MC-219981](https://bugs.mojang.com/browse/MC/issues/MC-219981) is a confirmed vanilla bug which makes leader zombies not heal relative to their max health after becoming a leader (either by natural spawning or conversion to husk or drowned). To fix it, we re-set the health of the zombie after turning into a leader, but we do so taking into consideration both its new max health and the amount of damage it had previously taken. Therefore a 20/20 zombie turning into a leader with a max health of 48 will have 48 health while a 15/20 zombie turning into a leader with a max health of 60 will have 55/60 health. Fixes #2095

### CODE REVIEW

File: patches/net/minecraft/world/entity/monster/Zombie.java.patch [hunk 1]
```diff
@@ -37,3 +37,19 @@
              if (p_219160_.getDifficulty() != Difficulty.HARD && this.random.nextBoolean()) {
                  return flag;
              }
+@@ -565,10 +_,15 @@
+                 .addOrReplacePermanentModifier(
+                     new AttributeModifier(LEADER_ZOMBIE_BONUS_ID, this.random.nextDouble() * 0.25 + 0.5, AttributeModifier.Operation.ADD_VALUE)
+                 );
++
```
Comment (sciwhiz12) [inline patches/net/minecraft/world/entity/monster/Zombie.java.patch]: Why add an empty line?

**Review by sciwhiz12 — COMMENTED** [review]
I've not yet tested this, but it looks good from just reading the code.

File: patches/net/minecraft/world/entity/monster/Zombie.java.patch (hunk 1 above)
Comment (Matyrobbrt) [reply patches/net/minecraft/world/entity/monster/Zombie.java.patch]: For absolutely no reason, whoops

**Review by TelepathicGrunt — APPROVED** [review]
