### PR TITLE
[1.21] Fix angles set in ViewportEvent.ComputeCameraAngles not taking effect

### LINKED ISSUE #1123: [1.21] Changes to `ViewportEvent.ComputeCameraAngles` `pitch` and `yaw` aren't applied to rotation.
**Minecraft Version:** `1.21`

**NeoForge Version:** `21.0.10-beta`

**Description of issue:**
Changes to rotation made in the `ComputeCameraAngles` event aren't applied to the overall camera rotation. There doesn't appear to be any visual change.

Potential findings: 

- It looks like `setAnglesInternal` updates the `yRot` and `xRot` fields of the Camera. However, when actually applying the rotations, the `rotation` field is referenced instead.

- Only the `pitch` and `yaw` aren't applied because `roll` is applied separately, on a different line.

### PR DESCRIPTION
**Pull request by XFactHD**
This PR moves the dispatch of `ViewportEvent.ComputeCameraAngles` to `Camera#setup()` to fix the modified angles not affecting the three camera vectors (forward, up, left) and modifications to pitch and yaw in the event not taking effect at all.

Fixes #1123

### CODE REVIEW

**Review by embeddedt — DISMISSED** [review]

File: src/main/java/net/neoforged/neoforge/client/ClientHooks.java [hunk 1]
```diff
@@ -435,8 +435,8 @@ public static void onFogRender(FogRenderer.FogMode mode, FogType type, Camera ca
         }
     }
 
-    public static ViewportEvent.ComputeCameraAngles onCameraSetup(GameRenderer renderer, Camera camera, float partial) {
-        ViewportEvent.ComputeCameraAngles event = new ViewportEvent.ComputeCameraAngles(renderer, camera, partial, camera.getYRot(), camera.getXRot(), 0);
+    public static ViewportEvent.ComputeCameraAngles onCameraSetup(Camera camera, float yaw, float pitch, float partial) {
+        ViewportEvent.ComputeCameraAngles event = new ViewportEvent.ComputeCameraAngles(Minecraft.getInstance().gameRenderer, camera, partial, yaw, pitch, 0);
         NeoForge.EVENT_BUS.post(event);
         return event;
     }
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/client/ClientHooks.java]: Should we consider inlining this method into the patch? Since what this method does can be replaced with a `var event = NeoForge.EVENT_BUS.post(new ViewportEvent.ComputeCameraAngles(...))` line, and the method is called only once.

Comment (XFactHD) [reply src/main/java/net/neoforged/neoforge/client/ClientHooks.java]: ~~I'm not a fan of inlining this into the patch because it makes the resulting line extremely long, about 275 characters to be exact, even with `var` instead of writing out the event type for the variable.~~
Nevermind, I can just add some line breaks 🤦‍♂️.

**Review by sciwhiz12 — APPROVED** [review]

**Review by embeddedt — APPROVED** [review]
