### PR TITLE
[1.20.4] Fix GUI far plane calculation to match vanilla

### LINKED ISSUE #445: VanillaTweaks "No Spyglass Overlay" is incompatible with NeoForge
**NeoForge Version:** 20.4.65-beta

**Steps to Reproduce:**
 1. Download and install the "No Spyglass Overlay" resource pack from the [VanillaTweaks website](https://vanillatweaks.net/picker/resource-packs/) (in Unobtrusive)
 2. Use the spyglass
 3. The black borders are still present in NeoForge, unlike in Minecraft Vanilla

**Description of issue:**

NeoForge:

Vanilla:

### PR DESCRIPTION
**Pull request by XFactHD**
This PR fixes the screen-layer-aware GUI far plane calculation to fully match the vanilla GUI far plane again and adjusts the layer rendering the actually make use of the increased per-layer depth.

This fixes the VanillaTweaks "No Spyglass Overlay" resource pack not working on NeoForge.
It is worth noting though that, while it fixes this RP in an almost-vanilla environment (i.e. only NeoForge installed), there's no guarantee that it will work when other mods are involved as they can trivially insert a custom HUD component under the spy glass overlay and offset its depth such that the shader's detection doesn't work anymore or even breaks other HUD components. There is nothing NeoForge can do about this other than entirely removing a very valuable feature, which is not a viable solution, especially considering mods can achieve the RP's effect in a trivial and clean way as well.

The test mod used to test screen layering was also adjusted to match how screens are now supposed to be drawn and was used to test that layering to absurd levels still works fine.

Fixes #445

### CODE REVIEW

**Review by marchermans — APPROVED** [review]

File: patches/net/minecraft/client/renderer/GameRenderer.java.patch [hunk 1]
```diff
@@ -74,7 +74,7 @@
              posestack.pushPose();
              posestack.setIdentity();
 -            posestack.translate(0.0F, 0.0F, -11000.0F);
-+            posestack.translate(0.0D, 0.0D, 1000F - net.neoforged.neoforge.client.ClientHooks.getGuiFarPlane());
++            posestack.translate(0.0D, 0.0D, 10000F - net.neoforged.neoforge.client.ClientHooks.getGuiFarPlane());
```
Comment (TheCurle) [inline patches/net/minecraft/client/renderer/GameRenderer.java.patch:77]: It's bizarre how we were a factor of 10 off, huh?

**Review by TheCurle — APPROVED** [review]
Seems good. Verified the original value, and yeah. We just had it wrong. Weird.

**Review by Technici4n — APPROVED** [review]
