### PR TITLE
Fix chunk force ticking

### LINKED ISSUE #1702: [1.21.3] forceTicks in addRegionTicket isn't working correctly
**Minecraft Version:** 1.21.3

**NeoForge Version:** tested on 21.3.31-beta

**Logs:** (This crash is not the only problem, so please read the description below!) Crash on world join from the lack of a null check in `ServerChunkCache.collectTickingChunks`. The `shouldForceTicks` call returning true bypasses the vanilla null check. 
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.LevelChunk.getPos()" because "levelchunk" is null
	at TRANSFORMER/minecraft@1.21.3/net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:417) ~[neoforge-21.3.31-beta.jar%23215!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.3/net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:363) ~[neoforge-21.3.31-beta.jar%23215!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.3/net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:338) ~[neoforge-21.3.31-beta.jar%23215!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.3/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:373) ~[neoforge-21.3.31-beta.jar%23215!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking}
	at TRANSFORMER/minecraft@1.21.3/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1090) ~[neoforge-21.3.31-beta.jar%23215!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass}
	at TRANSFORMER/minecraft@1.21.3/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:963) ~[neoforge-21.3.31-beta.jar%23215!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass}
	at TRANSFORMER/minecraft@1.21.3/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:108) ~[neoforge-21.3.31-beta.jar%23215!/:?] {re:classloading,xf:fml:openpartiesandclaims:xaero_pac_integratedserver_tickpaused,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.3/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:723) ~[neoforge-21.3.31-beta.jar%23215!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass}
	at TRANSFORMER/minecraft@1.21.3/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:278) ~[neoforge-21.3.31-beta.jar%23215!/:?]
```

**Steps to Reproduce:**
 1. Add a ticket with `ServerChunkCache.addRegionTicket(TicketType<T> p_8388_, ChunkPos p_8389_, int p_8390_, T p_8391_, boolean forceTicks)` with forceTicks set to true.
 2. Plant some wheat seeds in the forceloaded chunk.
 3. Fly far away and set random tick speed to 3000, then wait for 30 seconds.
 4. Set random tick speed back to 3.
 5. Return to the forceloaded chunk.
 6. **(First issue)** The wheat has not grown.
 7. Relog.
 8. **(Second issue)** If the ticket persists, so it's readded on world join, you'll crash with a NPE. Not sure if it's guaranteed but seems to happen every time for me when standing in the forceloaded chunk.

**Description of issue:**

Forceload tickets with `forceTicks` set to true don't force random block ticks and cause a crash when joining a world.

### PR DESCRIPTION
**Pull request by Matyrobbrt**
In 1.21.2, Mojang changed the previous chunk ticking code. Instead of iterating all known chunks and checking if each one should be ticked, it now uses a chunk manager that's constantly based on the location of players.

This means that our previous code which simply adds a check on the ticking candidates is no longer feasible, as chunks situated far out from players will not even be considered candidates to begin with. The new method adds each force ticked chunk to the list of final candidates manually, checking if the chunk is already in the list.

Fixes #1702

### CODE REVIEW

File: patches/net/minecraft/server/level/ChunkMap.java.patch [hunk 1]
```diff
@@ -48,6 +48,27 @@
...
+     }
+ 
++    void collectForceTickingChunks(List<LevelChunk> list) {
++        var itr = distanceManager.forcedTickets.long2ObjectEntrySet().fastIterator();
++        while (itr.hasNext()) {
++            var entry = itr.next();
++            ChunkHolder holder = this.visibleChunkMap.get(entry.getLongKey());
++            if (holder != null && !entry.getValue().isEmpty()) {
++                var chunk = holder.getTickingChunk();
++                if (chunk != null && !list.contains(chunk)) {
```
Comment (embeddedt) [inline patches/net/minecraft/server/level/ChunkMap.java.patch]: O(n) `List.contains` performance will almost certainly become a problem as soon as there are enough forceloaded chunks.

**Review by embeddedt — CHANGES_REQUESTED** [review]

**Review by embeddedt — APPROVED** [review]
Looks good now
