### PR TITLE
Restore modded fluid swimming functionality

### LINKED ISSUE #2573: Movement in water-based Fluids is weighty/heavy
**Minecraft Version:** 1.21.8

**NeoForge Version:** 21.8.27

**Steps to Reproduce:**
 1. Create a custom Fluid, making sure that the fluid mimics Water's behaviour by tagging it was Water.
 2. Move through the fluid.

**Description of issue:**
This is a similar issue to #2320 but it was closed in error, likely due to a lack of response for two months. I'm forced to duplicate this ticket.

The logic for processing movement in fluids that behave like water is not properly done. There are two places this can be seen.

In `Entity#updateFluidHeightAndDoFluidPushing`, the Deprecated vanilla method calls the NeoForge method, but then returns the method as true only when the FluidTag is `WATER` and the FluidType is `WATER_TYPE`, or if the FluidTag is `LAVA` and the FluidType is `LAVA_TYPE`. Otherwise, for all custom fluids, this returns false. As the only method being used is the Deprecated method, field `wasTouchingWater` is never true, nor is fall distance reset. This affects any logic that checks if an Entity is in water.

In `LivingEntity#travelInFluid`, the Deprecated method calls the NeoForge method, except the FluidState that is passed is always Empty. Again, the only usage of these two methods is the Deprecated one as this used in `LivingEntity#travel`. This means all FluidStates are Empty, meaning that `isInFluidType` will always be false as the FluidState is unable to be checked, and same applies for `moveInFluid`. The only other check in place is `isInWater`, but as `wasTouchingWater` is never set to true, this ends up false, and both cases fail. As such, no water-based movement in LivingEntity is run for custom fluids, either.

At present, the only way to fix this is through transforming, but this is not a viable solution. I am aware that #2435 exists, but this is currently in Draft, and this bug needs to be fixed in the interim at the very least so that mods with custom fluids are not seen as a buggy.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Not thrilled with this code but it'll be removed once https://github.com/neoforged/NeoForge/pull/2435 is done.

For now, this attempts to restore some modded fluid pushing, sinking, and swimming behavior on the player. Fluid pushing in updateInWaterStateAndDoWaterCurrentPushing will try to check for if entity is in any fluid that has isWaterLike returning true. travelInFluid now will check the current fluid type the player's eye is in for some in-fluid movement logic to work. And lastly, player now checks if player is in any fluid with canSwim returning true in updateIsUnderwater to allow swimming to work.

isWaterLike is a new fluid type property added with the following javadoc:

```java
        /**
         * Sets whether the fluid does the following:
         * <pre>
         * - Triggers splash effects when entering
         * - Crouching in fluid causes player to sink
         * - Reduces fall damage and resets fall distance when touching fluid
         * - Triggers water swim sounds
         * - Trigger the swim game event
         * - Allows various mobs to move, breath, or perform other water-based behavior properly
         * - makes wolves/dogs shake when exiting fluid
         * - Damages entities that are sensitive to water
         * - Prevents sun-burning mobs from being set on fire in sunlight *(Note: {@link #canExtinguish} must be false as well for fire to persist)*
         * - Allows fire arrows to be extinguished. *(Note: {@link #canExtinguish} also can extinguish the fire independently)*
         * - Allows Riptide Tridents to activate
         * - Allows Conduit block to function
         * - Underwater music can play when player is submerged in the fluid
         * - Muffles Minecart moving sounds and reduces their speed
         * </pre>
         * @param isWaterLike whether the fluid is water-like
         * @return the property holder instance
         */
```

Closes https://github.com/neoforged/NeoForge/issues/2573

### CODE REVIEW

File: patches/net/minecraft/world/entity/Entity.java.patch [hunk 1]
```diff
@@ -326,6 +333,22 @@
...
++
++        if (this.forgeFluidTypeHeight.isEmpty()) {
++            return false;
++        }
++
++        for (net.neoforged.neoforge.fluids.FluidType fluidType : this.forgeFluidTypeHeight.keySet()) {
++            if (fluidType.canPushEntity(this) && this.isInFluidType(fluidType)) {
++                return true;
++            }
++        }
```
Comment (ChampionAsh5357) [inline patches/net/minecraft/world/entity/Entity.java.patch]: I think this causes unintended effects for lava as `canPushEntity` returns true for all fluids as all fluids can push the entity. We would be treating lava like water in some situations here.

File: patches/net/minecraft/world/entity/Entity.java.patch [hunk 2]
```diff
@@ -118,6 +118,13 @@
      }
  
      void updateInWaterStateAndDoWaterCurrentPushing() {
+         if (this.getVehicle() instanceof AbstractBoat abstractboat && !abstractboat.isUnderWater()) {
+             this.wasTouchingWater = false;
+-        } else if (this.updateFluidHeightAndDoFluidPushing(FluidTags.WATER, 0.014)) {
++        } else if (this.updateFluidHeightAndDoCanPushEntityFluidPushing()) {
```
Comment (ChampionAsh5357) [inline patches/net/minecraft/world/entity/Entity.java.patch]: Since this is run in multiple situations, we should probably be clear the fluid maps in this method. In the case of checking fall damage, the update code is ran again, but it doesn't clear the map, which causes fluids that aren't updated to stick around. It should also remove the need for the `isInFluidType` below.

File: patches/net/minecraft/world/entity/LivingEntity.java.patch [hunk 3]
```diff
@@ -530,7 +530,7 @@
          double d0 = this.getY();
          double d1 = this.getEffectiveGravity();
 -        if (this.isInWater()) {
-+        if (this.isInWater() || (this.isInFluidType(fluidState) && !this.moveInFluid(fluidState, p_365480_, d1))) {
++        if (this.isInWater() || (this.isInFluidType(this.getEyeInFluidType()) && !this.moveInFluid(this.level().getFluidState(BlockPos.containing(this.getEyePosition())), p_365480_, d1))) {
```
Comment (ChampionAsh5357) [inline patches/net/minecraft/world/entity/LivingEntity.java.patch:534]: Probably a comment here mentioning that we are using the eye height instead of the fluidstate provided as it's always empty.

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]
I don't particularly mind this as a patch, but I'm not sure whether we want to assume all fluids are water-like. It may just be easier to add a quick field to fluid type that says `isWaterLike` and then check those in this scenario.

File: patches/net/minecraft/world/entity/Entity.java.patch (hunk 2 above)
Comment (TelepathicGrunt) [reply patches/net/minecraft/world/entity/Entity.java.patch]: Took me a bit of rereading to get what you were saying. Done now

File: patches/net/minecraft/world/entity/Entity.java.patch (hunk 1 above)
Comment (TelepathicGrunt) [reply patches/net/minecraft/world/entity/Entity.java.patch]: Added isWaterLike but only for this spot

File: patches/net/minecraft/world/entity/LivingEntity.java.patch (hunk 3 above)
Comment (TelepathicGrunt) [reply patches/net/minecraft/world/entity/LivingEntity.java.patch:534]: Comment added

File: patches/net/minecraft/world/entity/Entity.java.patch [hunk 4]
```diff
@@ -326,6 +338,26 @@
 +        else return false;
 +    }
 +
++    public boolean updateFluidHeightAndDoCanPushEntityFluidPushing(boolean performFluidPushing) {
++        this.forgeFluidTypeHeight.clear();
```
Comment (ChampionAsh5357) [inline patches/net/minecraft/world/entity/Entity.java.patch]: This should be fine, though I can't ever think of a situation where we don't check for fluids and clear the map anyway.

File: src/main/java/net/neoforged/neoforge/fluids/FluidType.java [hunk 5]
```diff
@@ -868,6 +879,7 @@ public static final class Properties {
         private Rarity rarity = Rarity.COMMON;
         @Nullable
         private DripstoneDripInfo dripInfo;
+        private boolean isWaterLike = true;
```
Comment (ChampionAsh5357) [inline src/main/java/net/neoforged/neoforge/fluids/FluidType.java]: This should default to false as otherwise we would be introducing a breaking change to other fluids that aren't supposed to be water like.

**Review by ChampionAsh5357 — CHANGES_REQUESTED** [review]

File: src/main/java/net/neoforged/neoforge/fluids/FluidType.java (hunk 5 above)
Comment (TelepathicGrunt) [reply src/main/java/net/neoforged/neoforge/fluids/FluidType.java]: Most of the properties we have for water stuff are true default so i matched that. But I'll reverse this one

File: patches/net/minecraft/world/entity/Entity.java.patch (hunk 4 above)
Comment (TelepathicGrunt) [reply patches/net/minecraft/world/entity/Entity.java.patch]: Moved it into the performFluidPushing if statement

**Review by ChampionAsh5357 — APPROVED** [review]
I don't notice any difference in behavior, so it should be good.

**Comment by TelepathicGrunt** [comment]
@Andromander would you like to try this PR snapshot in your dev environment to see if this solves your issue for your fluid? You need to set waterlike in the fluidtype to true as well

**Comment by Andromander** [comment]
Can confirm the `isWaterLike` property does work.
