### PR TITLE
Make Biome and Structure Modifiers not crash when attempted to be re-applied

### LINKED ISSUE #431: Neoforge Biome/Structure Modifiers crashes on recycled Frozen Registries
o/ A Interesting crash with server registry recycling happens. (I technically have it fixed with mixins but i still should report it)

When you create a custom server using the world creation screens information, that works just fine.
But the moment you try to do that a second time the server will simply crash, because the registries haven't been reset 100%

This leads to the following crash:

<details>
<summary>Crashlog</summary>
<p>

```
java.lang.IllegalStateException: Biome Reference{ResourceKey[minecraft:worldgen/biome / minecraft:badlands]=net.minecraft.world.level.biome.Biome@504521ae} already modified
	at net.neoforged.neoforge.common.world.ModifiableBiomeInfo.applyBiomeModifiers(ModifiableBiomeInfo.java:76) ~[neoforge-20.4.49-beta.jar%23196%23203!/:?] {re:mixin,re:classloading,pl:mixin:APP:chunkpregen.mixins.json:common.forge.BiomeModifierRemoverMixin,pl:mixin:A}
	at net.neoforged.neoforge.server.ServerLifecycleHooks.lambda$runModifiers$1(ServerLifecycleHooks.java:200) ~[neoforge-20.4.49-beta.jar%23196%23203!/:?] {re:classloading}
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at net.neoforged.neoforge.server.ServerLifecycleHooks.runModifiers(ServerLifecycleHooks.java:199) ~[neoforge-20.4.49-beta.jar%23196%23203!/:?] {re:classloading}
	at net.neoforged.neoforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:90) ~[neoforge-20.4.49-beta.jar%23196%23203!/:?] {re:classloading}
	at net.minecraft.client.server.IntegratedServer.initServer(IntegratedServer.java:72) ~[neoforge-20.4.49-beta.jar%23197!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:663) ~[neoforge-20.4.49-beta.jar%23197!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:255) ~[neoforge-20.4.49-beta.jar%23197!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerSeedMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

</p>
</details>

And sadly there is no API to actually reset the biome/structure modifiers.
So a mixin is required to fix this.

To explain why I ran into this problem.
I simply implemented a quick seed switch option where you can cycle through seeds a lot more quickly then normally.
And when you recycle the registries that have already been picked (you can't change them after the fact) changing the seed has barely any effects on registries themselves.
The issue is always appearing, unless you do a 100% registries recreation, which is kinda overkill.
That issue exists since 1.19.0

So yeah.

Some infos about neo version:
I was using: Neoforge 20.4.49-beta

Edit:
This is the code to fix this crash.

<details>
<summary>Code</summary>
<p>

```java
private void resetRegistries(MinecraftServer server) {
	final RegistryAccess registries = server.registryAccess();

	registries.registryOrThrow(Registries.BIOME).holders().forEach(biomeHolder -> {
		((BiomeModifierRemoverMixin)biomeHolder.value().modifiableBiomeInfo()).clearModifiers(null);
	});
	registries.registryOrThrow(Registries.STRUCTURE).holders().forEach(structureHolder -> {
		((StructureModifierRemoverMixin)structureHolder.value().modifiableStructureInfo()).clearModifiers(null);
	});
}
```
It just resets the modifier cache so the modifiers can be reapplied on the next attempt.

</p>
</details>

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Basically, the modifiers already know if a biome or structure was modified and ideally should just no-op instead. It doesn't make sense to throw an exception when the exception isn't really helping anyone or preventing any error. Even Commoble, when asked, said there wasn't any strong reason for the exception either
image

So let's just remove the exception and the modifier do nothing if object was already modified. Basically cleanup. Might allow for more niche use case for the modifiers but they have other issues to deal with on their own when recycling registries. Just NeoForge should be one less roadblock

Closes https://github.com/neoforged/NeoForge/issues/431

### CODE REVIEW

File: src/main/java/net/neoforged/neoforge/common/world/ModifiableBiomeInfo.java [hunk 1]
```diff
@@ -80,7 +79,7 @@ public BiomeInfo getModifiedBiomeInfo() {
     @ApiStatus.Internal
     public boolean applyBiomeModifiers(final Holder<Biome> biome, final List<BiomeModifier> biomeModifiers, RegistryAccess registryAccess) {
         if (this.modifiedBiomeInfo != null)
-            throw new IllegalStateException(String.format(Locale.ENGLISH, "Biome %s already modified", biome));
+            return true;
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/common/world/ModifiableBiomeInfo.java:80]: Adjust the javadoc of this method to match how this method now operates. (It no longer throws an exception, and the biome is only modified on the first invocation of this method.)

File: src/main/java/net/neoforged/neoforge/common/world/ModifiableStructureInfo.java [hunk 2]
```diff
@@ -66,7 +65,7 @@ public StructureInfo getModifiedStructureInfo() {
     @ApiStatus.Internal
     public void applyStructureModifiers(final Holder<Structure> structure, final List<StructureModifier> structureModifiers) {
         if (this.modifiedStructureInfo != null)
-            throw new IllegalStateException(String.format(Locale.ENGLISH, "Structure %s already modified", structure));
+            return;
```
Comment (sciwhiz12) [inline src/main/java/net/neoforged/neoforge/common/world/ModifiableStructureInfo.java:66]: Adjust the javadoc of this method to match how this method now operates. (It no longer throws an exception, and the biome is only modified on the first invocation of this method.)

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]

**Review by sciwhiz12 — APPROVED** [review]

**Comment by TelepathicGrunt** [comment]
Time to yolo it
