### PR TITLE
Fix crash when rendering corrupted level summaries

### LINKED ISSUE #683: Crashes on world screen when rendering corrupted level summaries
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.190

**Logs:** https://gist.github.com/tmvkrpxl0/fb3f5c025697253ba8dd25b41ee49fc4

**Steps to Reproduce:**
 1. Add this world
[World1.zip](https://github.com/neoforged/NeoForge/files/14477850/World1.zip)
 2. Load world screen
 3. crash

**Description of issue:**
Method `LevelSummary#isLifecycleExperimental` added by https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/level/storage/LevelSummary.java.patch does not take account that `this.settings` can be null.
If the level is corrupted or it's symlink then `settings` is set to null.

### LINKED ISSUE #838: NeoForge crashes when I scroll in the World Select.
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.232

**Logs:** The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.LevelSettings.getLifecycle()" because "this.settings" is null

**Steps to Reproduce:**
 1. Load NeoForge
 2. Click Singleplayer
 3. Scroll down

### PR DESCRIPTION
**Pull request by embeddedt**
`CorruptedLevelSummary` and `SymlinkLevelSummary` initialize the settings field to null, which causes a crash in our patched-in `isLifecycleExperimental` method. Since we have no way of knowing if the world is actually experimental in that case, we can just null-check the field and return `false` if it's null.

This will fix #838 and #683.

### CODE REVIEW

File: patches/net/minecraft/world/level/storage/LevelSummary.java.patch [hunk 1]
```diff
@@ -5,7 +5,7 @@
      }
  
 +    public boolean isLifecycleExperimental() {
-+        return this.settings.getLifecycle().equals(com.mojang.serialization.Lifecycle.experimental());
++        return this.settings != null && this.settings.getLifecycle().equals(com.mojang.serialization.Lifecycle.experimental());
 +    }
```
Comment (sciwhiz12) [inline patches/net/minecraft/world/level/storage/LevelSummary.java.patch]: Since the `LevelSettings` is now accessible through `LevelSummary#getSettings()`, should we remove this patched-in method and inline that in the one place it's used (in `WorldSelectionList.WorldListEntry`).

**Review by sciwhiz12 — APPROVED** [review]
Tested with the example world from #683.
