### PR TITLE
Make all removal entries optional at runtime

### LINKED ISSUE #2319: [Bug] entries in the remove list of a worldgen tag have to be present in the registry
This is the result of a [conversation on discord](https://discord.com/channels/313125603924639766/852298000042164244/1381231990958850109). I'm opening this so it is not forgotten.

**Minecraft Version:** observed on 1.21.4+

**NeoForge Version:** 21.4.136

**Logs:**
```
[21:36:39] [Render thread/ERROR] [minecraft/RegistryDataLoader]: Registry loading errors:
> Errors in registry minecraft:root:
>> Errors in element minecraft:worldgen/biome:
java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/biome]: [non-existent:tag]
    at TRANSFORMER/minecraft@1.21.5/net.minecraft.core.MappedRegistry.freeze(MappedRegistry.java:306)
    at TRANSFORMER/minecraft@1.21.5/net.minecraft.resources.RegistryDataLoader.lambda$load$8(RegistryDataLoader.java:199)
    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
    at TRANSFORMER/minecraft@1.21.5/net.minecraft.resources.RegistryDataLoader.load(RegistryDataLoader.java:195)
    at TRANSFORMER/minecraft@1.21.5/net.minecraft.resources.RegistryDataLoader.load(RegistryDataLoader.java:157)
    at TRANSFORMER/minecraft@1.21.5/net.minecraft.server.WorldLoader.load(WorldLoader.java:44)
    at TRANSFORMER/minecraft@1.21.5/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.loadWorldDataBlocking(WorldOpenFlows.java:205)
    at TRANSFORMER/minecraft@1.21.5/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.loadWorldStem(WorldOpenFlows.java:143)
```

**Steps to Reproduce:**
 1. remove a non existent entry from a biome (probably any world gen) tag
 2. try to start the game
 3. won't load

**Description of issue:**
it seems like the tag loader requires all entries in remove lists of world gen related tags to be present in the registry, which is unnecessary. this does not happen for other tags. XFactHD assumed there is a separate tag loader that is missing some patches. sciwhiz12 reproduced the issue

Workaround:
marking the entry in the remove list as optional
`.getInternalBuilder().remove(TagEntry.optionalElement(...))`

### PR DESCRIPTION
**Pull request by Matyrobbrt**
The issue detailed in #2319 is caused by reloadable registries using a different method in `TagLoader`: `loadTagsForRegistry`, which is operated on writable registries. This method uses a `ElementLookup#fromWritableRegistry` element lookup, which uses either the registry directly if the tag entry is not marked as required or, if the tag entry is marked as required, it uses the `WritableRegistry#createRegistrationLookup` - and this lookup always uses `getOrCreateHolderOrThrow`, creating pending intrusive holders for all looked-up required elements.

The fix I implemented is to create copies of all `TagEntry`s used for removal that have the `required` flag always set to `false`. I also removed the patched-in removal check in `tryBuildTag` as it is no longer necessary if all removal entries are optional.

Fixes #2319

### CODE REVIEW

**Comment by BarionLP** [comment]
seems fine, can't reproduce the problem on your branch

File: patches/net/minecraft/tags/TagLoader.java.patch [hunk 1]
```diff
@@ -4,17 +4,16 @@
  
                      String s = resource.sourcePackId();
                      tagfile.entries().forEach(p_215997_ -> list.add(new TagLoader.EntryWithSource(p_215997_, s)));
-+                    tagfile.remove().forEach(e -> list.add(new TagLoader.EntryWithSource(e, s, true)));
++                    tagfile.remove().forEach(e -> list.add(new TagLoader.EntryWithSource(e.withRequired(false), s, true))); // Make all removal entries optional at runtime to avoid them creating intrusive holders - see NeoForge#2319
```
Comment (XFactHD) [inline patches/net/minecraft/tags/TagLoader.java.patch]: Please move the comment above the existing line

**Review by XFactHD — APPROVED** [review]
